export const AppData = {
  collection: 'campaign',
  batches: [
    {
      number: '1',
      rows: [
        {
          id: 'COPA1919',
          data: {
            name: 'Final Tournament',
            tournament_id: 'COPA1919',
            description: 'Copa America 1919',
            order: 9,
            stages: [
              {
                name: 'Final Round',
                type: 'roundrobin',
                eliminate_count: 2,
                next_round: 'Final Playoff',
                advancement: {
                  auto: [1, 2],
                  eliminated: [3, 4],
                  text: "The winner would've won the Copa America. As Brazil and Uruguay finished tied on points in the final round, a playoff match was played between Brazil and Uruguay to determine the champion. Brazil eventually won the Final Playoff.",
                },
                groups: [
                  {
                    name: 'Final Round',
                    teams: [{ id: 'BRA' }, { id: 'CHI' }, { id: 'ARG' }, { id: 'URU' }],
                    matches: [
                      {
                        home_team: { id: 'BRA' },
                        away_team: { id: 'CHI' },
                        home_score: 6,
                        away_score: 0,
                        date: '1919-05-11',
                        time: '12:00',
                        stadium: 'Estádio das Laranjeiras',
                        city: 'Rio de Janeiro',
                      },
                      {
                        home_team: { id: 'ARG' },
                        away_team: { id: 'URU' },
                        home_score: 2,
                        away_score: 3,
                        date: '1919-05-13',
                        time: '12:00',
                        stadium: 'Estádio das Laranjeiras',
                        city: 'Rio de Janeiro',
                      },
                    ],
                  },
                ],
              },
              {
                name: 'Final Playoff',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Final Playoff',
                    matches: [
                      {
                        home_team: { id: 'BRA' },
                        away_team: { id: 'URU' },
                        home_score: 0,
                        away_score: 0,
                        home_extra_score: 1,
                        away_extra_score: 0,
                        date: '1919-05-29',
                        time: '12:00',
                        stadium: 'Estádio das Laranjeiras',
                        city: 'Rio de Janeiro',
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
      ],
    },
    {
      number: '2',
      rows: [
        {
          id: 'WC2022_ALLQ',
          data: {
            name: 'Overall Qualification',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 Overall Qualification',
            order: 1,
            details: {
              logo_filename: '640px-FIFA_logo_without_slogan.svg.png',
              start_date: '2019-06-06',
              end_date: '2022-06-14',
              color: '#cc0000',
              team_count: 207,
              confed_count: 6,
            },
            statistics: { total_matches: 765, total_goals: 2197, attendance: 6789008 },
            awards: {
              golden_boot: [{ name: 'Ali Mabkhout', team: { id: 'UAE' }, goals: 14 }],
            },
          },
        },
        {
          id: 'WC2022_AFCQ',
          data: {
            name: 'AFC Asian Qualifiers',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 AFC Asian Qualifiers',
            order: 2,
            details: {
              logo_filename: 'AFC_Asian_Qualifiers.png',
              start_date: '2019-06-06',
              end_date: '2022-06-01',
              color: '#e5cf1d',
              team_count: 46,
              confed_count: 1,
            },
            statistics: { total_matches: 204, total_goals: 626, attendance: 1940722 },
            awards: {
              golden_boot: [{ name: 'Ali Mabkhout', team: { id: 'UAE' }, goals: 14 }],
            },
            stages: [
              {
                name: 'First Round',
                type: 'knockout',
                hide_bracket: true,
                rounds: [
                  {
                    name: 'First Round',
                    short_name: '1stR',
                    next_round: 'Second Round',
                    matches: [
                      {
                        multiple_legs: true,
                        home_team: { id: 'MAC' },
                        away_team: { id: 'SRI' },
                        home_score: 1,
                        away_score: 0,
                        date: '2019-06-06',
                        time: '19:30',
                        stadium: 'Zhuhai Sports Center Stadium',
                        city: 'Zhuhai (China)',
                        leg2_home_team: { id: 'SRI' },
                        leg2_away_team: { id: 'MAC' },
                        leg2_home_awarded_score: 3,
                        leg2_away_awarded_score: 0,
                        leg2_awarded_match: true,
                        leg2_awarded_text:
                          'Awarded: Macau did not send their team for the second leg due to safety reasons following the 2019 Sri Lanka Easter bombings. FIFA announced on June 27, 2019 that the match was declared a 3–0 forfeit victory to Sri Lanka, and consequently qualifying Sri Lanka to the second round.',
                        leg2_date: '2019-06-11',
                        leg2_time: '15:30',
                        leg2_stadium: 'Sugathadasa Stadium',
                        leg2_city: 'Colombo',
                      },
                    ],
                  },
                ],
              },
              {
                name: 'Second Round',
                type: 'roundrobin',
              },
              {
                name: 'Third Round',
              },
              {
                name: 'Fourth Round',
              },
              { name: 'Inter-confederation play-offs' },
            ],
          },
        },
        {
          id: 'WC2022_CAFQ',
          data: {
            name: 'CAF Qualification',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 CAF Qualification',
            order: 3,
            details: {
              logo_filename: 'Confederation_of_African_Football_logo.png',
              start_date: '2019-09-04',
              end_date: '2022-03-01',
              color: '#000000',
              team_count: 54,
              confed_count: 1,
            },
            statistics: { total_matches: 148, total_goals: 345, attendance: 769510 },
            awards: {
              golden_boot: [{ name: 'Islam Slimani', team: { id: 'ALG' }, goals: 7 }],
            },
          },
        },
        {
          id: 'WC2022_CONCACAFQ',
          data: {
            name: 'CONCACAF Qualifiers',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 CONCACAF Qualifiers',
            order: 4,
            details: {
              logo_filename: 'CONCACAF_qualifiers_-_Road_to_Qatar_-_Logo_480x494.png',
              start_date: '2021-03-24',
              end_date: '2022-03-30',
              color: '#cc0000',
              team_count: 34,
              confed_count: 1,
            },
            statistics: { total_matches: 94, total_goals: 295, attendance: 698674 },
            awards: {
              golden_boot: [{ name: 'Cyle Larin', team: { id: 'CAN' }, goals: 11 }],
            },
          },
        },
        {
          id: 'WC2022_CONMEBOLQ',
          data: {
            name: 'CONMEBOL Qualification',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 CONMEBOL Qualification',
            order: 5,
            details: {
              logo_filename: 'CONMEBOL_logo_(2017).png',
              start_date: '2020-10-08',
              end_date: '2022-03-29',
              color: '#cc0000',
              team_count: 10,
              confed_count: 1,
            },
            statistics: { total_matches: 69, total_goals: 168, attendance: 689954 },
            awards: {
              golden_boot: [{ name: 'Marcelo Moreno', team: { id: 'BOL' }, goals: 9 }],
            },
          },
        },
        {
          id: 'WC2022_OFCQ',
          data: {
            name: 'OFC Qualification',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 OFC Qualification',
            order: 6,
            details: {
              host: [{ id: 'QAT' }],
              logo_filename: 'Oceania_Football_Confederation_logo.png',
              start_date: '2022-03-13',
              end_date: '2022-03-30',
              color: '#cc0000',
              team_count: 9,
              confed_count: 1,
            },
          },
        },
        {
          id: 'WC2022_UEFAQ',
          data: {
            name: 'European Qualifiers',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 European Qualifiers',
            order: 7,
            details: {
              logo_filename: 'UEFA_Euro_2016_qualifying.png',
              start_date: '2021-03-24',
              end_date: '2022-03-29',
              color: '#cc0000',
              team_count: 55,
              confed_count: 1,
            },
            statistics: { total_matches: 250, total_goals: 763, attendance: 2690148 },
            awards: {
              golden_boot: [
                { name: 'Harry Kane', team: { id: 'ENG' }, goals: 12 },
                { name: 'Memphis Depay', team: { id: 'NED' }, goals: 12 },
              ],
            },
          },
        },
        {
          id: 'WC2022_ICPO',
          data: {
            name: 'Inter-confederation play-offs',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 Inter-confederation play-offs',
            order: 8,
            details: {
              host: [{ id: 'QAT' }],
              logo_filename: '640px-FIFA_logo_without_slogan.svg.png',
              start_date: '2022-06-13',
              end_date: '2022-06-14',
              color: '#cc0000',
              team_count: 4,
              confed_count: 4,
            },
          },
        },
        {
          id: 'WC2022',
          data: {
            name: 'Final Tournament',
            tournament_id: 'WC2022',
            description: 'World Cup 2022 Final Tournament',
            order: 9,
            stages: [{ name: 'Group Stage' }, { name: 'Knockout Stage' }],
          },
        },
        {
          id: 'WC2018_AFCQ',
          data: {
            name: 'AFC Asian Qualifiers',
            tournament_id: 'WC2018',
            description: 'World Cup 2018 AFC Asian Qualifiers',
            order: 1,
            details: { logo_filename: 'AFC_Asian_Qualifiers.png' },
          },
        },
        {
          id: 'WC2018',
          data: {
            name: 'Final Tournament',
            tournament_id: 'WC2018',
            description: 'World Cup 2018 Final Tournament',
            order: 9,
            stages: [
              {
                name: 'Group Stage',
                type: 'roundrobin',
                eliminate_count: 16,
                next_round: 'Round of 16',
                advancement: { auto: [1, 2], eliminated: [3, 4] },
                groups: [
                  {
                    name: 'Group A',
                    teams: [{ id: 'RUS' }, { id: 'URU' }, { id: 'EGY' }, { id: 'KSA' }],
                    matches: [
                      {
                        home_team: { id: 'RUS' },
                        away_team: { id: 'KSA' },
                        home_score: 5,
                        away_score: 0,
                        date: '2018-06-14',
                        time: '18:00',
                        stadium: 'Luzhniki Stadium',
                        city: 'Moscow',
                      },
                      {
                        home_team: { id: 'EGY' },
                        away_team: { id: 'URU' },
                        home_score: 0,
                        away_score: 1,
                        date: '2018-06-15',
                        time: '17:00',
                        stadium: 'Ekaterinburg Arena',
                        city: 'Ekaterinburg',
                      },
                      {
                        home_team: { id: 'RUS' },
                        away_team: { id: 'EGY' },
                        home_score: 3,
                        away_score: 1,
                        date: '2018-06-19',
                        time: '21:00',
                        stadium: 'Saint Petersburg Stadium',
                        city: 'St. Petersburg',
                      },
                    ],
                  },
                  {
                    name: 'Group B',
                    teams: [{ id: 'POR' }, { id: 'ESP' }, { id: 'IRN' }, { id: 'MAR' }],
                    matches: [
                      {
                        home_team: { id: 'MAR' },
                        away_team: { id: 'IRN' },
                        home_score: 0,
                        away_score: 1,
                        date: '2018-06-15',
                        time: '18:00',
                        stadium: 'Saint Petersburg Stadium',
                        city: 'St. Petersburg',
                      },
                    ],
                  },
                  {
                    name: 'Group C',
                    teams: [{ id: 'FRA' }, { id: 'DEN' }, { id: 'PER' }, { id: 'AUS' }],
                    matches: [
                      {
                        home_team: { id: 'FRA' },
                        away_team: { id: 'AUS' },
                        home_score: 2,
                        away_score: 1,
                        date: '2018-06-16',
                        time: '13:00',
                        stadium: 'Kazan Arena',
                        city: 'Kazan',
                      },
                    ],
                  },
                  {
                    name: 'Group D',
                    teams: [{ id: 'CRO' }, { id: 'ARG' }, { id: 'NGA' }, { id: 'ISL' }],
                    matches: [
                      {
                        home_team: { id: 'ARG' },
                        away_team: { id: 'ISL' },
                        home_score: 1,
                        away_score: 1,
                        date: '2018-06-16',
                        time: '16:00',
                        stadium: 'Spartak Stadium',
                        city: 'Moscow',
                      },
                      {
                        home_team: { id: 'CRO' },
                        away_team: { id: 'NGA' },
                        home_score: 2,
                        away_score: 0,
                        date: '2018-06-16',
                        time: '21:00',
                        stadium: 'Kaliningrad Stadium',
                        city: 'Kaliningrad',
                      },
                    ],
                  },
                  {
                    name: 'Group E',
                    teams: [{ id: 'BRA' }, { id: 'SUI' }, { id: 'SRB' }, { id: 'CRC' }],
                    matches: [],
                  },
                  {
                    name: 'Group F',
                    teams: [{ id: 'GER' }, { id: 'MEX' }, { id: 'SWE' }, { id: 'KOR' }],
                    matches: [
                      {
                        home_team: { id: 'GER' },
                        away_team: { id: 'MEX' },
                        home_score: 0,
                        away_score: 1,
                        date: '2018-06-17',
                        time: '18:00',
                        stadium: 'Luzhniki Stadium',
                        city: 'Moscow',
                      },
                    ],
                  },
                  {
                    name: 'Group G',
                    teams: [{ id: 'BEL' }, { id: 'ENG' }, { id: 'TUN' }, { id: 'PAN' }],
                    matches: [
                      {
                        home_team: { id: 'BEL' },
                        away_team: { id: 'PAN' },
                        home_score: 3,
                        away_score: 0,
                        date: '2018-06-18',
                        time: '18:00',
                        stadium: 'Fisht Stadium',
                        city: 'Sochi',
                      },
                    ],
                  },
                  {
                    name: 'Group H',
                    teams: [{ id: 'POL' }, { id: 'COL' }, { id: 'SEN' }, { id: 'JPN' }],
                    matches: [],
                  },
                ],
              },
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Round of 16',
                    short_name: '1/8',
                    eliminate_count: 8,
                    next_round: 'Quarter-finals',
                    matches: [
                      {
                        home_team: { id: 'FRA' },
                        away_team: { id: 'ARG' },
                        home_score: 4,
                        away_score: 3,
                        date: '2018-06-30',
                        time: '17:00',
                        stadium: 'Kazan Arena',
                        city: 'Kazan',
                        bracket_order: 2,
                      },
                      {
                        home_team: { id: 'URU' },
                        away_team: { id: 'POR' },
                        home_score: 2,
                        away_score: 1,
                        date: '2018-06-30',
                        time: '21:00',
                        stadium: 'Fisht Stadium',
                        city: 'Sochi',
                        bracket_order: 1,
                      },
                      {
                        home_team: { id: 'ESP' },
                        away_team: { id: 'RUS' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        home_penalty_score: 3,
                        away_penalty_score: 4,
                        date: '2018-07-01',
                        time: '17:00',
                        stadium: 'Luzhniki Stadium',
                        city: 'Moscow',
                        bracket_order: 5,
                      },
                      {
                        home_team: { id: 'CRO' },
                        away_team: { id: 'DEN' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        home_penalty_score: 3,
                        away_penalty_score: 2,
                        date: '2018-07-01',
                        time: '21:00',
                        stadium: 'Nizhny Novgorod Stadium',
                        city: 'Nizhny Novgorod',
                        bracket_order: 6,
                      },
                      {
                        home_team: { id: 'BRA' },
                        away_team: { id: 'MEX' },
                        home_score: 2,
                        away_score: 0,
                        date: '2018-07-02',
                        time: '18:00',
                        stadium: 'Samara Arena',
                        city: 'Samara',
                        bracket_order: 3,
                      },
                      {
                        home_team: { id: 'BEL' },
                        away_team: { id: 'JPN' },
                        home_score: 3,
                        away_score: 2,
                        date: '2018-07-02',
                        time: '21:00',
                        stadium: 'Rostov Arena',
                        city: 'Rostov-On-Don',
                        bracket_order: 4,
                      },
                      {
                        home_team: { id: 'SWE' },
                        away_team: { id: 'SUI' },
                        home_score: 1,
                        away_score: 0,
                        date: '2018-07-03',
                        time: '17:00',
                        stadium: 'Saint Petersburg Stadium',
                        city: 'St. Petersburg',
                        bracket_order: 7,
                      },
                      {
                        home_team: { id: 'COL' },
                        away_team: { id: 'ENG' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        home_penalty_score: 3,
                        away_penalty_score: 4,
                        date: '2018-07-03',
                        time: '21:00',
                        stadium: 'Spartak Stadium',
                        city: 'Moscow',
                        bracket_order: 8,
                      },
                    ],
                  },
                  {
                    name: 'Quarter-finals',
                    short_name: '1/4',
                    eliminate_count: 4,
                    next_round: 'Semi-finals',
                    matches: [
                      {
                        home_team: { id: 'URU' },
                        away_team: { id: 'FRA' },
                        home_score: 0,
                        away_score: 2,
                        date: '2018-07-06',
                        time: '17:00',
                        stadium: 'Nizhny Novgorod Stadium',
                        city: 'Nizhny Novgorod',
                        bracket_order: 1,
                      },
                      {
                        home_team: { id: 'BRA' },
                        away_team: { id: 'BEL' },
                        home_score: 1,
                        away_score: 2,
                        date: '2018-07-06',
                        time: '21:00',
                        stadium: 'Kazan Arena',
                        city: 'Kazan',
                        bracket_order: 2,
                      },
                      {
                        home_team: { id: 'SWE' },
                        away_team: { id: 'ENG' },
                        home_score: 0,
                        away_score: 2,
                        date: '2018-07-07',
                        time: '18:00',
                        stadium: 'Samara Arena',
                        city: 'Samara',
                        bracket_order: 4,
                      },
                      {
                        home_team: { id: 'RUS' },
                        away_team: { id: 'CRO' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 1,
                        away_extra_score: 1,
                        home_penalty_score: 3,
                        away_penalty_score: 4,
                        date: '2018-07-07',
                        time: '21:00',
                        stadium: 'Fisht Stadium',
                        city: 'Sochi',
                        bracket_order: 3,
                      },
                    ],
                  },
                  {
                    name: 'Semi-finals',
                    short_name: '1/2',
                    eliminate_count: 2,
                    next_round: 'Final',
                    matches: [
                      {
                        home_team: { id: 'FRA' },
                        away_team: { id: 'BEL' },
                        home_score: 1,
                        away_score: 0,
                        date: '2018-07-10',
                        time: '21:00',
                        stadium: 'Saint Petersburg Stadium',
                        city: 'St. Petersburg',
                        bracket_order: 1,
                      },
                      {
                        home_team: { id: 'CRO' },
                        away_team: { id: 'ENG' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 1,
                        away_extra_score: 0,
                        date: '2018-07-11',
                        time: '21:00',
                        stadium: 'Luzhniki Stadium',
                        city: 'Moscow',
                        bracket_order: 2,
                      },
                    ],
                  },
                  {
                    name: 'Third-place',
                    short_name: '3rd',
                    matches: [
                      {
                        home_team: { id: 'BEL' },
                        away_team: { id: 'ENG' },
                        home_score: 2,
                        away_score: 0,
                        date: '2018-07-14',
                        time: '17:00',
                        stadium: 'Saint Petersburg Stadium',
                        city: 'St. Petersburg',
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [
                      {
                        home_team: { id: 'FRA' },
                        away_team: { id: 'CRO' },
                        home_score: 4,
                        away_score: 2,
                        date: '2018-07-15',
                        time: '18:00',
                        stadium: 'Luzhniki Stadium',
                        city: 'Moscow',
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'WC2014',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC2014',
            description: 'World Cup 2014 Final Tournament',
            order: 9,
            stages: [{ name: 'Group Stage' }],
          },
        },
        {
          id: 'WC2010',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC2010',
            description: 'World Cup 2010 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC2006',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC2006',
            description: 'World Cup 2006 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC2002',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC2002',
            description: 'World Cup 2002 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1998',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1998',
            description: 'World Cup 1998 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1994',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1994',
            description: 'World Cup 1994 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1990',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1990',
            description: 'World Cup 1990 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1986',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1986',
            description: 'World Cup 1986 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1982',
          data: {
            name: 'Final Tournament',
            tournament_id: 'WC1982',
            description: 'World Cup 1982 Final Tournament',
            order: 9,
            stages: [
              {
                name: 'First Group Stage',
                type: 'roundrobin',
                eliminate_count: 12,
                next_round: 'Second Group Stage',
                advancement: { auto: [1, 2], eliminated: [3, 4], text: 'The top 2 teams would advance to the second round.' },
                groups: [
                  {
                    name: 'Group 1',
                    teams: [{ id: 'ITA' }, { id: 'POL' }, { id: 'PER' }, { id: 'CMR' }],
                    matches: [
                      {
                        home_team: { id: 'POL' },
                        away_team: { id: 'PER' },
                        home_score: 5,
                        away_score: 1,
                        date: '1982-06-22',
                        time: '17:15',
                        stadium: 'Estadio de Riazor',
                        city: 'A Coruña',
                      },
                    ],
                  },
                  {
                    name: 'Group 2',
                    teams: [],
                    matches: [],
                  },
                ],
              },
              {
                name: 'Second Group Stage',
                type: 'roundrobin',
                eliminate_count: 4,
                next_round: 'Semi-finals',
                tiebreakers: ['team', 'firstroundfirstsecond', 'lot'],
                advancement: { auto: [1], eliminated: [2, 3], text: 'The winners advance to the semi-finals round.' },
                groups: [
                  {
                    name: 'Group A',
                    teams: [],
                    matches: [],
                  },
                  {
                    name: 'Group B',
                    teams: [],
                    matches: [],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'WC1978',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1978',
            description: 'World Cup 1978 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1974',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1974',
            description: 'World Cup 1974 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1970',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1970',
            description: 'World Cup 1970 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1966',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1966',
            description: 'World Cup 1966 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1962',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1962',
            description: 'World Cup 1962 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1958',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1958',
            description: 'World Cup 1958 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1954',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1954',
            description: 'World Cup 1954 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1950',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1950',
            description: 'World Cup 1950 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'WC1938',
          data: {
            name: 'Tournament',
            tournament_id: 'WC1938',
            description: 'World Cup 1938 Final Tournament',
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Round of 16',
                    short_name: '1/8',
                    eliminate_count: 8,
                    next_round: 'Quarter-finals',
                    teams: [
                      { id: 'SUI' },
                      { id: 'GER-1935-1945' },
                      { id: 'HUN-1919-1946' },
                      { id: 'INH' },
                      { id: 'SWE' },
                      { id: 'AUT' },
                      { id: 'CUB' },
                      { id: 'ROU' },
                      { id: 'FRA' },
                      { id: 'BEL' },
                      { id: 'ITA-1861-1946' },
                      { id: 'NOR' },
                      { id: 'BRA' },
                      { id: 'POL' },
                      { id: 'TCH' },
                      { id: 'NED' },
                    ],
                    matches: [
                      {
                        home_team: { id: 'SUI' },
                        away_team: { id: 'GER-1935-1945' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1938-06-04',
                        time: '17:00',
                        stadium: 'Parc des Princes',
                        city: 'Paris',
                        bracket_order: 6,
                        replay_home_team: { id: 'SUI' },
                        replay_away_team: { id: 'GER-1935-1945' },
                        replay_home_score: 4,
                        replay_away_score: 2,
                        replay_date: '1938-06-09',
                        replay_time: '18:00',
                        replay_stadium: 'Parc des Princes',
                        replay_city: 'Paris',
                        replay_match: true,
                      },
                      {
                        home_team: { id: 'SWE' },
                        away_team: { id: 'AUT' },
                        walkover_match: true,
                        home_walkover: true,
                        away_withdrew: true,
                        walkover_text: 'Sweden advanced by walkover as Austria were unable to compete.',
                        date: '1938-06-05',
                        time: '17:00',
                        stadium: 'Stade Gerland',
                        city: 'Lyon',
                        bracket_order: 7,
                      },
                      {
                        home_team: { id: 'CUB' },
                        away_team: { id: 'ROU' },
                        home_score: 2,
                        away_score: 2,
                        home_extra_score: 1,
                        away_extra_score: 1,
                        date: '1938-06-05',
                        time: '17:00',
                        stadium: 'Stade du T.O.E.C.',
                        city: 'Toulouse',
                        bracket_order: 8,
                        replay_home_team: { id: 'CUB' },
                        replay_away_team: { id: 'ROU' },
                        replay_home_score: 2,
                        replay_away_score: 1,
                        replay_date: '1938-06-09',
                        replay_time: '18:00',
                        replay_stadium: 'Stade du T.O.E.C.',
                        replay_city: 'Toulouse',
                        replay_match: true,
                      },
                    ],
                  },
                  {
                    name: 'Quarter-finals',
                    short_name: '1/4',
                    eliminate_count: 4,
                    next_round: 'Semi-finals',
                    matches: [
                      {
                        home_team: { id: 'BRA' },
                        away_team: { id: 'TCH' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1938-06-12',
                        time: '17:00',
                        stadium: 'Parc Lescure',
                        city: 'Bordeaux',
                        bracket_order: 2,
                        replay_home_team: { id: 'BRA' },
                        replay_away_team: { id: 'TCH' },
                        replay_home_score: 2,
                        replay_away_score: 1,
                        replay_date: '1938-06-14',
                        replay_time: '18:00',
                        replay_stadium: 'Parc Lescure',
                        replay_city: 'Bordeaux',
                        replay_match: true,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'WC1934',
          data: {
            name: 'Tournament',
            tournament_id: 'WC1934',
            description: 'World Cup 1934 Final Tournament',
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Quarter-finals',
                    short_name: '1/4',
                    eliminate_count: 4,
                    next_round: 'Semi-finals',
                    matches: [
                      {
                        home_team: { id: 'ITA-1861-1946' },
                        away_team: { id: 'ESP-1931-1936' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1934-05-31',
                        time: '16:30',
                        stadium: 'Stadio Giovanni Berta',
                        city: 'Florence',
                        bracket_order: 1,
                        replay_home_team: { id: 'ITA-1861-1946' },
                        replay_away_team: { id: 'ESP-1931-1936' },
                        replay_home_score: 1,
                        replay_away_score: 0,
                        replay_date: '1934-06-01',
                        replay_time: '16:30',
                        replay_stadium: 'Stadio Giovanni Berta',
                        replay_city: 'Florence',
                        replay_match: true,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'WC1930',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WC1930',
            description: 'World Cup 1930 Final Tournament',
            order: 9,
          },
        },
      ],
    },
    {
      number: '3',
      rows: [
        {
          id: 'WWC2019',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC2019',
            description: "Women's World Cup 2019 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WWC2015',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC2015',
            description: "Women's World Cup 2015 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WWC2011',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC2011',
            description: "Women's World Cup 2011 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WWC2007',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC2007',
            description: "Women's World Cup 2007 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WWC2003',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC2003',
            description: "Women's World Cup 2003 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WWC1999',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC1999',
            description: "Women's World Cup 1999 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WWC1995',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC1995',
            description: "Women's World Cup 1995 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WWC1991',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WWC1991',
            description: "Women's World Cup 1991 Final Tournament",
            order: 9,
          },
        },
      ],
    },
    {
      number: '4',
      rows: [
        {
          id: 'MOFT2020',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT2020',
            description: "Men's Olympic 2020 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT2016',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT2016',
            description: "Men's Olympic 2016 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT2012',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT2012',
            description: "Men's Olympic 2012 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT2008',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT2008',
            description: "Men's Olympic 2008 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT2004',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT2004',
            description: "Men's Olympic 2004 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT2000',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT2000',
            description: "Men's Olympic 2000 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1996',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1996',
            description: "Men's Olympic 1996 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1992',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1992',
            description: "Men's Olympic 1992 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1988',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1988',
            description: "Men's Olympic 1988 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1984',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1984',
            description: "Men's Olympic 1984 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1980',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1980',
            description: "Men's Olympic 1980 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1976',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1976',
            description: "Men's Olympic 1976 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1972',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1972',
            description: "Men's Olympic 1972 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1968',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1968',
            description: "Men's Olympic 1968 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1964',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1964',
            description: "Men's Olympic 1964 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1960',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1960',
            description: "Men's Olympic 1960 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1956',
          data: {
            name: 'Tournament',
            tournament_id: 'MOFT1956',
            description: "Men's Olympic 1956 Final Tournament",
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'First Round',
                    short_name: '1/8',
                    eliminate_count: 8,
                    next_round: 'Quarter-finals',
                    teams: [
                      { id: 'URS_U23MNT' },
                      { id: 'GER-1956-1968_U23MNT' },
                      { id: 'GBR_U23MNT' },
                      { id: 'THA_U23MNT' },
                      { id: 'AUS_U23MNT' },
                      { id: 'JPN_U23MNT' },
                      { id: 'YUG-1945-1963_U23MNT' },
                      { id: 'USA_U23MNT' },
                      { id: 'IDN_U23MNT' },
                      { id: 'BUL-1948-1967_U23MNT' },
                      { id: 'IND_U23MNT' },
                    ],
                    matches: [
                      {
                        home_team: { id: 'BUL-1948-1967_U23MNT' },
                        away_team: { id: 'EGY-1953-1958_U23MNT' },
                        bye_match: true,
                        bye_text: 'Opponent withdrew',
                        away_withdrew: true,
                        date: '1956-11-23',
                        bracket_order: 7,
                      },
                      {
                        home_team: { id: 'IND_U23MNT' },
                        away_team: { id: 'HUN-1949-1956_U23MNT' },
                        bye_match: true,
                        bye_notes: 'Opponent withdrew',
                        away_withdrew: true,
                        date: '1956-11-23',
                        bracket_order: 4,
                      },
                      {
                        home_team: { id: 'IDN_U23MNT' },
                        away_team: { id: 'VSO_U23MNT' },
                        bye_match: true,
                        bye_notes: 'Opponent withdrew',
                        away_withdrew: true,
                        date: '1956-11-23',
                        bracket_order: 5,
                      },
                      {
                        home_team: { id: 'CHN_U23MNT' },
                        away_team: { id: 'TUR_U23MNT' },
                        cancelled_match: true,
                        home_withdrew: true,
                        away_withdrew: true,
                        date: '1956-11-23',
                        bracket_order: 2,
                      },
                      {
                        home_team: { id: 'YUG-1945-1963_U23MNT' },
                        away_team: { id: 'USA_U23MNT' },
                        postponed_match: true,
                        postponed_text: 'to the quarter-finals',
                        date: '1956-11-23',
                        bracket_order: 1,
                      },
                    ],
                  },
                  {
                    name: 'Quarter-finals',
                    short_name: '1/4',
                    eliminate_count: 4,
                    next_round: 'Semi-finals',
                    matches: [
                      {
                        home_team: { id: 'IDN_U23MNT' },
                        away_team: { id: 'URS_U23MNT' },
                        home_score: 0,
                        away_score: 0,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1956-11-29',
                        time: '12:00',
                        stadium: 'Olympic Park Stadium',
                        city: 'Melbourne',
                        bracket_order: 3,
                        replay_home_team: { id: 'IDN_U23MNT' },
                        replay_away_team: { id: 'URS_U23MNT' },
                        replay_home_score: 0,
                        replay_away_score: 4,
                        replay_date: '1956-12-01',
                        replay_time: '12:00',
                        replay_stadium: 'Olympic Park Stadium',
                        replay_city: 'Melbourne',
                        replay_match: true,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'MOFT1952',
          data: {
            name: 'Tournament',
            tournament_id: 'MOFT1952',
            description: "Men's Olympic 1952 Final Tournament",
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'First Round',
                    short_name: '1/8',
                    eliminate_count: 8,
                    next_round: 'Quarter-finals',
                    matches: [
                      {
                        home_team: { id: 'YUG-1945-1963_U23MNT' },
                        away_team: { id: 'URS_U23MNT' },
                        home_score: 5,
                        away_score: 5,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1952-07-20',
                        time: '19:00',
                        stadium: 'Ratina Stadion',
                        city: 'Tampere',
                        bracket_order: 6,
                        replay_home_team: { id: 'YUG-1945-1963_U23MNT' },
                        replay_away_team: { id: 'URS_U23MNT' },
                        replay_home_score: 3,
                        replay_away_score: 1,
                        replay_date: '1952-07-22',
                        replay_time: '19:00',
                        replay_stadium: 'Ratina Stadion',
                        replay_city: 'Tampere',
                        replay_match: true,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'MOFT1948',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1948',
            description: "Men's Olympic 1948 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1936',
          data: {
            name: 'Tournament',
            tournament_id: 'MOFT1936',
            description: "Men's Olympic 1936 Final Tournament",
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Quarter-finals',
                    short_name: '1/4',
                    eliminate_count: 4,
                    next_round: 'Semi-finals',
                    matches: [
                      {
                        home_team: { id: 'PER_U23MNT' },
                        away_team: { id: 'AUT_U23MNT' },
                        home_score: 2,
                        away_score: 2,
                        home_extra_score: 2,
                        away_extra_score: 0,
                        void_match: true,
                        void_text:
                          'Due to a pitch invasion, the match was declared null and void, and ordered to be replayed. Peru objected to the replay decision and withdrew from the tournament.',
                        home_withdrew: true,
                        date: '1936-08-08',
                        time: '17:30',
                        stadium: 'Hertha-BSC-Platz',
                        city: 'Berlin',
                        bracket_order: 3,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'MOFT1928',
          data: {
            name: 'Tournament',
            tournament_id: 'MOFT1928',
            description: "Men's Olympic 1928 Final Tournament",
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Quarter-finals',
                    short_name: '1/4',
                    eliminate_count: 4,
                    next_round: 'Semi-finals',
                    matches: [
                      {
                        home_team: { id: 'ITA-1861-1946_U23MNT' },
                        away_team: { id: 'ESP-1875-1931_U23MNT' },
                        home_score: 1,
                        away_score: 1,
                        date: '1928-06-01',
                        time: '19:00',
                        stadium: 'Olympic Stadium',
                        city: 'Amsterdam',
                        bracket_order: 2,
                        replay_home_team: { id: 'ITA-1861-1946_U23MNT' },
                        replay_away_team: { id: 'ESP-1875-1931_U23MNT' },
                        replay_home_score: 7,
                        replay_away_score: 1,
                        replay_date: '1928-06-04',
                        replay_time: '14:00',
                        replay_stadium: 'Olympic Stadium',
                        replay_city: 'Amsterdam',
                        replay_match: true,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [
                      {
                        home_team: { id: 'URU_U23MNT' },
                        away_team: { id: 'ARG_U23MNT' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1928-06-10',
                        time: '16:00',
                        stadium: 'Olympic Stadium',
                        city: 'Amsterdam',
                        replay_home_team: { id: 'URU_U23MNT' },
                        replay_away_team: { id: 'ARG_U23MNT' },
                        replay_home_score: 2,
                        replay_away_score: 1,
                        replay_date: '1928-06-13',
                        replay_time: '19:00',
                        replay_stadium: 'Olympic Stadium',
                        replay_city: 'Amsterdam',
                        replay_match: true,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'MOFT1924',
          data: {
            name: 'Tournament',
            tournament_id: 'MOFT1924',
            description: "Men's Olympic 1924 Final Tournament",
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Second Round',
                    short_name: '1/8',
                    eliminate_count: 8,
                    next_round: 'Quarter-finals',
                    matches: [
                      {
                        home_team: { id: 'SUI_U23MNT' },
                        away_team: { id: 'TCH_U23MNT' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1924-05-28',
                        time: '17:00',
                        stadium: 'Stade Bergeyre',
                        city: 'Paris',
                        bracket_order: 5,
                        replay_home_team: { id: 'SUI_U23MNT' },
                        replay_away_team: { id: 'TCH_U23MNT' },
                        replay_home_score: 1,
                        replay_away_score: 0,
                        replay_date: '1924-05-30',
                        replay_time: '17:00',
                        replay_stadium: 'Stade Bergeyre',
                        replay_city: 'Paris',
                        replay_match: true,
                      },
                    ],
                  },
                  {
                    name: 'Third-place',
                    short_name: '3rd',
                    matches: [
                      {
                        home_team: { id: 'NED_U23MNT' },
                        away_team: { id: 'SWE_U23MNT' },
                        home_score: 1,
                        away_score: 1,
                        date: '1924-06-08',
                        time: '16:00',
                        stadium: 'Stade Olympique',
                        city: 'Colombes',
                        replay_home_team: { id: 'NED_U23MNT' },
                        replay_away_team: { id: 'SWE_U23MNT' },
                        replay_home_score: 1,
                        replay_away_score: 3,
                        replay_date: '1924-06-09',
                        replay_time: '14:30',
                        replay_stadium: 'Stade Olympique',
                        replay_city: 'Colombes',
                        replay_match: true,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'MOFT1920',
          data: {
            name: 'Tournament',
            tournament_id: 'MOFT1920',
            description: "Men's Olympic 1920 Final Tournament",
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'First Round',
                    short_name: '1/8',
                    eliminate_count: 7,
                    next_round: 'Quarter-finals',
                    teams: [
                      { id: 'TCH_U23MNT' },
                      { id: 'YUG-1918-1929_U23MNT' },
                      { id: 'ESP-1875-1931_U23MNT' },
                      { id: 'DEN_U23MNT' },
                      { id: 'ITA-1861-1946_U23MNT' },
                      { id: 'EGY-1914-1922_U23MNT' },
                      { id: 'NOR_U23MNT' },
                      { id: 'GBR_U23MNT' },
                      { id: 'NED_U23MNT' },
                      { id: 'LUX_U23MNT' },
                      { id: 'SWE_U23MNT' },
                      { id: 'GRE_U23MNT' },
                      { id: 'BEL_U23MNT' },
                      { id: 'SUI_U23MNT' },
                      { id: 'FRA_U23MNT' },
                    ],
                    bye_teams: [{ id: 'FRA_U23MNT' }, { id: 'BEL_U23MNT' }],
                    matches: [
                      {
                        home_team: { id: 'BEL_U23MNT' },
                        bye_match: true,
                        date: '1920-08-28',
                        bracket_order: 1,
                      },
                      {
                        home_team: { id: 'FRA_U23MNT' },
                        away_team: { id: 'SUI_U23MNT' },
                        home_awarded_score: 2,
                        away_awarded_score: 0,
                        awarded_score_ignored: true,
                        awarded_match: true,
                        away_withdrew: true,
                        awarded_text: 'Switzerland withdrew on the morning before the first round due to internal dissent.',
                        date: '1920-08-28',
                        bracket_order: 7,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [
                      {
                        home_team: { id: 'BEL_U23MNT' },
                        away_team: { id: 'TCH_U23MNT' },
                        home_score: 2,
                        away_score: 0,
                        disqualified_match: true,
                        away_disqualified: true,
                        disqualified_text: 'Czechoslovakia walked off the field in the 40th minute to protest the officiating',
                        date: '1920-09-02',
                        time: '17:30',
                        stadium: 'Olympic Stadium',
                        city: 'Antwerp',
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'MOFT1912',
          data: {
            name: 'Tournamnt',
            tournament_id: 'MOFT1912',
            description: "Men's Olympic 1912 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'MOFT1908',
          data: {
            name: 'Tournament',
            tournament_id: 'MOFT1908',
            description: "Men's Olympic 1908 Final Tournament",
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'First Round',
                    short_name: '1/4',
                    eliminate_count: 4,
                    next_round: 'Semi-finals',
                    teams: [
                      { id: 'DEN_U23MNT' },
                      { id: 'FRA-B_U23MNT' },
                      { id: 'GBR_U23MNT' },
                      { id: 'SWE_U23MNT' },
                      { id: 'NED_U23MNT' },
                      { id: 'FRA_U23MNT' },
                      { id: 'HUN-1867-1918_U23MNT' },
                      { id: 'BOH_U23MNT' },
                    ],
                    matches: [
                      {
                        home_team: { id: 'NED_U23MNT' },
                        away_team: { id: 'HUN-1867-1918_U23MNT' },
                        bye_match: true,
                        bye_text: 'Hungary withdrew due to the Bosnian crisis',
                        away_withdrew: true,
                        date: '1908-10-18',
                        bracket_order: 2,
                      },
                      {
                        home_team: { id: 'FRA_U23MNT' },
                        away_team: { id: 'BOH_U23MNT' },
                        bye_match: true,
                        bye_text: 'Bohemia withdrew after losing their FIFA membershi',
                        away_withdrew: true,
                        date: '1908-10-18',
                        bracket_order: 4,
                      },
                    ],
                  },
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [],
                  },
                ],
              },
            ],
          },
        },
      ],
    },
    {
      number: '5',
      rows: [
        {
          id: 'WOFT2020',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WOFT2020',
            description: "Women's Olympic 2020 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WOFT2016',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WOFT2016',
            description: "Women's Olympic 2016 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WOFT2012',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WOFT2012',
            description: "Women's Olympic 2012 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WOFT2008',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WOFT2008',
            description: "Women's Olympic 2008 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WOFT2004',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WOFT2004',
            description: "Women's Olympic 2004 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WOFT2000',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WOFT2000',
            description: "Women's Olympic 2000 Final Tournament",
            order: 9,
          },
        },
        {
          id: 'WOFT1996',
          data: {
            name: 'Tournamnt',
            tournament_id: 'WOFT1996',
            description: "Women's Olympic 1996 Final Tournament",
            order: 9,
          },
        },
      ],
    },
    {
      number: '6',
      rows: [
        {
          id: 'CONFEDC2017',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC2017',
            description: 'Confederations Cup 2017',
            order: 9,
          },
        },
        {
          id: 'CONFEDC2013',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC2013',
            description: 'Confederations Cup 2013',
            order: 9,
          },
        },
        {
          id: 'CONFEDC2009',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC2009',
            description: 'Confederations Cup 2009',
            order: 9,
          },
        },
        {
          id: 'CONFEDC2005',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC2005',
            description: 'Confederations Cup 2005',
            order: 9,
          },
        },
        {
          id: 'CONFEDC2003',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC2003',
            description: 'Confederations Cup 2003',
            order: 9,
          },
        },
        {
          id: 'CONFEDC2001',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC2001',
            description: 'Confederations Cup 2001',
            order: 9,
          },
        },
        {
          id: 'CONFEDC1999',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC1999',
            description: 'Confederations Cup 1999',
            order: 9,
          },
        },
        {
          id: 'CONFEDC1997',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC1997',
            description: 'Confederations Cup 1997',
            order: 9,
          },
        },
        {
          id: 'CONFEDC1995',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC1995',
            description: 'Confederations Cup 1995',
            order: 9,
          },
        },
        {
          id: 'CONFEDC1992',
          data: {
            name: 'Tournamnt',
            tournament_id: 'CONFEDC1992',
            description: 'Confederations Cup 1992',
            order: 9,
          },
        },
      ],
    },
  ],
}
