export const AppData = {
  collection: 'campaign',
  batches: [
    {
      number: '7',
      rows: [
        {
          id: 'EURO2020',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO2020',
            description: 'Euro 2020 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO2016',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO2016',
            description: 'Euro 2016 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO2012',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO2012',
            description: 'Euro 2012 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO2008',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO2008',
            description: 'Euro 2008 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO2004',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO2004',
            description: 'Euro 2004 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO2000',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO2000',
            description: 'Euro 2000 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1996',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1996',
            description: 'Euro 1996 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1992',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1992',
            description: 'Euro 1992 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1988',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1988',
            description: 'Euro 1988 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1984',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1984',
            description: 'Euro 1984 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1980',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1980',
            description: 'Euro 1980 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1976',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1976',
            description: 'Euro 1976 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1972',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1972',
            description: 'Euro 1972 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1968',
          data: {
            name: 'Tournament',
            tournament_id: 'EURO1968',
            description: 'Euro 1968 Final Tournament',
            order: 9,
            stages: [
              {
                name: 'Knockout Stage',
                type: 'knockout',
                rounds: [
                  {
                    name: 'Final',
                    short_name: '1st',
                    matches: [
                      {
                        home_team: { id: 'ITA' },
                        away_team: { id: 'YUG-1963-1992' },
                        home_score: 1,
                        away_score: 1,
                        home_extra_score: 0,
                        away_extra_score: 0,
                        date: '1968-06-08',
                        time: '21:15',
                        stadium: 'Stadio Olimpico',
                        city: 'Rome',
                        replay_home_team: { id: 'ITA' },
                        replay_away_team: { id: 'YUG-1963-1992' },
                        replay_home_score: 2,
                        replay_away_score: 0,
                        replay_date: '1968-06-10',
                        replay_time: '21:15',
                        replay_stadium: 'Stadio Olimpico',
                        replay_city: 'Rome',
                        replay_match: true,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        {
          id: 'EURO1964',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1964',
            description: 'Euro 1964 Final Tournament',
            order: 9,
          },
        },
        {
          id: 'EURO1960',
          data: {
            name: 'Tournamnt',
            tournament_id: 'EURO1960',
            description: 'Euro 1960 Final Tournament',
            order: 9,
          },
        },
      ],
    },
    {
      number: '8',
      rows: [
        {
          id: 'UCL202021',
          data: {
            name: 'Tournament',
            tournament_id: 'UCL202021',
            description: 'UEFA Champions League 2020-21',
            order: 9,
            stages: [
              { name: 'Preliminary Round', type: 'knockout' },
              {
                name: 'Qualifying Rounds',
                type: 'knockout',
                hide_bracket: true,
                rounds: [
                  {
                    name: 'First Qualifying Round',
                    next_round: 'Second Qualifying Round',
                    eliminate_count: 59,
                    bye_teams: [
                      { id: 'DZA' },
                      { id: 'YBO' },
                      { id: 'FCM' },
                      { id: 'AZA' },
                      { id: 'VPL' },
                      { id: 'PAO' },
                      { id: 'BES' },
                      { id: 'LZA' },
                      { id: 'RAV' },
                    ],
                    matches: [
                      {
                        home_team: { id: 'KIK' },
                        away_team: { id: 'SKS' },
                        home_awarded_score: 3,
                        away_awarded_score: 0,
                        date: '2020-08-21',
                        time: '18:00',
                        stadium: 'Við Djúpumýrar',
                        city: 'Klaksvík',
                        awarded_match: true,
                        awarded_text:
                          'Awarded: The KÍ v Slovan Bratislava match was postponed to 21 August 2020 due to one staff member from Slovan Bratislava testing positive for SARS-2 coronavirus and the whole team being put into quarantine by the Faroese authorities. On 21 August, the match could not be played due to one player from Slovan Bratislava testing positive for SARS-2 coronavirus and the whole second team being put into quarantine by the Faroese authorities. KÍ were subsequently awarded a technical 3–0 victory by UEFA according to the regulations related to COVID-19.',
                      },
                    ],
                  },
                  {
                    name: 'Second Qualifying Round',
                    next_round: 'Third Qualifying Round',
                    eliminate_count: 46,
                    bye_teams: [{ id: 'SLB' }, { id: 'DYK' }, { id: 'GNT' }],
                    multiple_paths: true,
                    paths: [
                      {
                        name: 'Champions',
                        matches: [
                          {
                            home_team: { id: 'CFR' },
                            away_team: { id: 'DZA' },
                            home_score: 2,
                            away_score: 2,
                            home_extra_score: 0,
                            away_extra_score: 0,
                            home_penalty_score: 5,
                            away_penalty_score: 6,
                            date: '2020-08-26',
                            time: '20:00',
                            stadium: 'Stadionul Dr. Constantin Rădulescu',
                            city: 'Cluj-Napoca',
                          },
                          {
                            home_team: { id: 'SMA' },
                            away_team: { id: 'MTA' },
                            home_score: 0,
                            away_score: 3,
                            date: '2020-08-26',
                            time: '18:00',
                            stadium: 'Sūduva Stadium',
                            city: 'Marijampolė',
                          },
                          {
                            home_team: { id: 'KFT' },
                            away_team: { id: 'RSB' },
                            home_score: 0,
                            away_score: 1,
                            date: '2020-08-25',
                            time: '20:00',
                            stadium: 'Arena Kombëtare',
                            city: 'Tirana',
                          },
                        ],
                      },
                      {
                        name: 'League',
                        matches: [
                          {
                            home_team: { id: 'AZA' },
                            away_team: { id: 'VPL' },
                            home_score: 1,
                            away_score: 1,
                            home_extra_score: 2,
                            away_extra_score: 0,
                            date: '2020-08-26',
                            time: '16:30',
                            stadium: 'AFAS Stadion',
                            city: 'Alkmaar',
                          },
                          {
                            home_team: { id: 'PAO' },
                            away_team: { id: 'BES' },
                            home_score: 3,
                            away_score: 1,
                            date: '2020-08-25',
                            time: '20:00',
                            stadium: 'Toumba Stadium',
                            city: 'Thessaloniki',
                          },
                          {
                            home_team: { id: 'LZA' },
                            away_team: { id: 'RAV' },
                            home_score: 0,
                            away_score: 1,
                            date: '2020-08-26',
                            time: '19:00',
                            stadium: 'Stadion Kranjčevićeva',
                            city: 'Zagreb',
                          },
                        ],
                      },
                    ],
                  },
                  { name: 'Third Qualifying Round' },
                ],
              },
              {
                name: 'Play-off Round',
                type: 'knockout',
                hide_bracket: true,
                rounds: [{ name: 'Play-off Round', paths: [{ name: 'Champions' }, { name: 'League' }] }],
              },
              {
                name: 'Group Stage',
                type: 'roundrobin',
                multiple_matchdays: true,
                eliminate_count: 16,
                home_and_away: true,
                next_round: 'Round of 16',
                advancement: {
                  auto: [1, 2],
                  transferred: [3],
                  eliminated: [4],
                  text: 'The top 2 teams would advance to the Round of 16. The third-placed teams would transfer to the Europa League Round of 32.',
                },
                groups: [
                  {
                    name: 'Group A',
                    teams: [{ id: 'RBS' }, { id: 'LMO' }, { id: 'BAY' }, { id: 'ATM' }],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [
                          {
                            home_team: { id: 'RBS' },
                            away_team: { id: 'LMO' },
                            home_score: 2,
                            away_score: 2,
                            date: '2020-10-21',
                            time: '18:55',
                            stadium: 'Stadion Wals-Siezenheim',
                            city: 'Wals-Siezenheim',
                          },
                          {
                            home_team: { id: 'BAY' },
                            away_team: { id: 'ATM' },
                            home_score: 4,
                            away_score: 0,
                            date: '2020-10-21',
                            time: '21:00',
                            stadium: 'Allianz Arena',
                            city: 'Munich',
                          },
                        ],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [
                          {
                            home_team: { id: 'LMO' },
                            away_team: { id: 'BAY' },
                            home_score: 1,
                            away_score: 2,
                            date: '2020-10-27',
                            time: '18:55',
                            stadium: 'RZD Arena',
                            city: 'Moscow',
                          },
                        ],
                      },
                    ],
                  },
                  {
                    name: 'Group B',
                    teams: [{ id: 'RMA' }, { id: 'SHK' }, { id: 'INT' }, { id: 'BMG' }],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [
                          {
                            home_team: { id: 'RMA' },
                            away_team: { id: 'SHK' },
                            home_score: 2,
                            away_score: 3,
                            date: '2020-10-21',
                            time: '18:55',
                            stadium: 'Alfredo di Stéfano',
                            city: 'Madrid',
                          },
                        ],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [
                          {
                            home_team: { id: 'SHK' },
                            away_team: { id: 'INT' },
                            home_score: 0,
                            away_score: 0,
                            date: '2020-10-27',
                            time: '18:55',
                            stadium: 'NSC Olimpiyskiy Stadium',
                            city: 'Kyiv',
                          },
                        ],
                      },
                      {
                        name: 'Matchday 3',
                        matches: [
                          {
                            home_team: { id: 'SHK' },
                            away_team: { id: 'BMG' },
                            home_score: 0,
                            away_score: 6,
                            date: '2020-11-03',
                            time: '18:55',
                            stadium: 'NSC Olimpiyskiy Stadium',
                            city: 'Kyiv',
                          },
                        ],
                      },
                    ],
                  },
                  {
                    name: 'Group E',
                    teams: [{ id: 'CHE' }, { id: 'SEV' }, { id: 'REN' }, { id: 'KRA' }],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [
                          {
                            home_team: { id: 'CHE' },
                            away_team: { id: 'SEV' },
                            home_score: 0,
                            away_score: 0,
                            date: '2020-10-20',
                            time: '21:00',
                            stadium: 'Stamford Bridge',
                            city: 'London',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              { name: 'Knockout Stage', type: 'knockout' },
            ],
          },
        },
        {
          id: 'UCL201920',
          data: {
            name: 'Tournament',
            tournament_id: 'UCL201920',
            description: 'UEFA Champions League 2019-20',
            order: 9,
            stages: [
              { name: 'Preliminary Round', type: 'knockout' },
              {
                name: 'Qualifying Rounds',
                type: 'knockout',
                hide_bracket: true,
                rounds: [
                  {
                    name: 'First Qualifying Round',
                    next_round: 'Second Qualifying Round',
                    eliminate_count: 60,
                    bye_teams: [{ id: 'MTA' }, { id: 'COP' }, { id: 'DZA' }, { id: 'APO' }, { id: 'VPL' }, { id: 'OLY' }, { id: 'PSV' }, { id: 'BAS' }],
                    matches: [
                      {
                        multiple_legs: true,
                        home_team: { id: 'NOM' },
                        away_team: { id: 'KFS' },
                        home_score: 0,
                        away_score: 1,
                        date: '2019-07-09',
                        time: '18:00',
                        stadium: 'Kadriorg Stadium',
                        city: 'Tallinn',
                        leg2_home_team: { id: 'KFS' },
                        leg2_away_team: { id: 'NOM' },
                        leg2_home_score: 1,
                        leg2_away_score: 2,
                        leg2_date: '2019-07-16',
                        leg2_time: '17:00',
                        leg2_stadium: 'Toše Proeski Arena',
                        leg2_city: 'Skopje',
                      },
                      {
                        multiple_legs: true,
                        home_team: { id: 'SMA' },
                        away_team: { id: 'RSB' },
                        home_score: 0,
                        away_score: 0,
                        date: '2019-07-09',
                        time: '20:00',
                        stadium: 'Sūduva Stadium',
                        city: 'Marijampolė',
                        leg2_home_team: { id: 'RSB' },
                        leg2_away_team: { id: 'SMA' },
                        leg2_home_score: 2,
                        leg2_away_score: 1,
                        leg2_date: '2019-07-16',
                        leg2_time: '20:45',
                        leg2_stadium: 'Red Star Stadium',
                        leg2_city: 'Belgrade',
                      },
                      {
                        multiple_legs: true,
                        home_team: { id: 'FER' },
                        away_team: { id: 'LUD' },
                        home_score: 2,
                        away_score: 1,
                        date: '2019-07-10',
                        time: '20:00',
                        stadium: 'Groupama Arena',
                        city: 'Budapest',
                        leg2_home_team: { id: 'LUD' },
                        leg2_away_team: { id: 'FER' },
                        leg2_home_score: 2,
                        leg2_away_score: 3,
                        leg2_date: '2019-07-17',
                        leg2_time: '19:30',
                        leg2_stadium: 'Ludogorets Arena',
                        leg2_city: 'Razgrad',
                      },
                      {
                        multiple_legs: true,
                        home_team: { id: 'F91' },
                        away_team: { id: 'VFC' },
                        home_score: 2,
                        away_score: 2,
                        date: '2019-07-09',
                        time: '20:00',
                        stadium: 'Stade Josy Barthel',
                        city: 'Luxembourg City',
                        leg2_home_team: { id: 'VFC' },
                        leg2_away_team: { id: 'F91' },
                        leg2_home_score: 1,
                        leg2_away_score: 1,
                        leg2_date: '2019-07-16',
                        leg2_time: '20:00',
                        leg2_stadium: 'Centenary Stadium',
                        leg2_city: "Ta' Qali",
                      },
                      {
                        multiple_legs: true,
                        home_team: { id: 'DUN' },
                        away_team: { id: 'RIG' },
                        home_score: 0,
                        away_score: 0,
                        date: '2019-07-10',
                        time: '20:45',
                        stadium: 'Oriel Park',
                        city: 'Dundalk',
                        leg2_home_team: { id: 'RIG' },
                        leg2_away_team: { id: 'DUN' },
                        leg2_home_score: 0,
                        leg2_away_score: 0,
                        leg2_home_extra_score: 0,
                        leg2_away_extra_score: 0,
                        leg2_home_penalty_score: 4,
                        leg2_away_penalty_score: 5,
                        leg2_date: '2019-07-17',
                        leg2_time: '18:30',
                        leg2_stadium: 'Skonto Stadium',
                        leg2_city: 'Riga',
                      },
                    ],
                  },
                  {
                    name: 'Second Qualifying Round',
                    next_round: 'Third Qualifying Round',
                    eliminate_count: 48,
                    bye_teams: [{ id: 'PAO' }, { id: 'AJA' }, { id: 'IBA' }, { id: 'KRA' }, { id: 'PTO' }, { id: 'BRG' }, { id: 'DYK' }, { id: 'LIN' }],
                    multiple_paths: true,
                    paths: [
                      {
                        name: 'Champions',
                        matches: [
                          {
                            multiple_legs: true,
                            home_team: { id: 'CFR' },
                            away_team: { id: 'MTA' },
                            home_score: 1,
                            away_score: 0,
                            date: '2019-07-24',
                            time: '20:00',
                            stadium: 'Stadionul Dr. Constantin Rădulescu',
                            city: 'Cluj-Napoca',
                            leg2_home_team: { id: 'MTA' },
                            leg2_away_team: { id: 'CFR' },
                            leg2_home_score: 2,
                            leg2_away_score: 2,
                            leg2_date: '2019-07-30',
                            leg2_time: '19:00',
                            leg2_stadium: 'Netanya Stadium',
                            leg2_city: 'Netanya',
                          },
                          {
                            multiple_legs: true,
                            home_team: { id: 'BBO' },
                            away_team: { id: 'RBK' },
                            home_score: 2,
                            away_score: 1,
                            date: '2019-07-24',
                            time: '19:00',
                            stadium: 'Borisov Arena',
                            city: 'Barysaw',
                            leg2_home_team: { id: 'RBK' },
                            leg2_away_team: { id: 'BBO' },
                            leg2_home_score: 2,
                            leg2_away_score: 0,
                            leg2_date: '2019-07-31',
                            leg2_time: '19:00',
                            leg2_stadium: 'Lerkendal Stadion',
                            leg2_city: 'Trondheima',
                          },
                          {
                            multiple_legs: true,
                            home_team: { id: 'MRB' },
                            away_team: { id: 'AIK' },
                            home_score: 2,
                            away_score: 1,
                            date: '2019-07-24',
                            time: '20:15',
                            stadium: 'Ljudski vrt',
                            city: 'Maribor',
                            leg2_home_team: { id: 'AIK' },
                            leg2_away_team: { id: 'MRB' },
                            leg2_home_score: 2,
                            leg2_away_score: 1,
                            leg2_home_extra_score: 1,
                            leg2_away_extra_score: 1,
                            leg2_date: '2019-07-31',
                            leg2_time: '19:00',
                            leg2_stadium: 'Friends Arena',
                            leg2_city: 'Solna',
                          },
                        ],
                      },
                      {
                        name: 'League',
                        matches: [
                          {
                            multiple_legs: true,
                            home_team: { id: 'PSV' },
                            away_team: { id: 'BAS' },
                            home_score: 3,
                            away_score: 2,
                            date: '2019-07-23',
                            time: '20:00',
                            stadium: 'Philips Stadion',
                            city: 'Eindhoven',
                            leg2_home_team: { id: 'BAS' },
                            leg2_away_team: { id: 'PSV' },
                            leg2_home_score: 2,
                            leg2_away_score: 1,
                            leg2_date: '2019-07-30',
                            leg2_time: '20:00',
                            leg2_stadium: 'St. Jakob-Park',
                            leg2_city: 'Basel',
                          },
                        ],
                      },
                    ],
                  },
                  {
                    name: 'Third Qualifying Round',
                    next_round: 'Play-off Round',
                    eliminate_count: 38,
                    bye_teams: [{ id: 'SLP' }, { id: 'YBO' }],
                    multiple_paths: true,
                    paths: [
                      {
                        name: 'Champions',
                        matches: [
                          {
                            multiple_legs: true,
                            home_team: { id: 'RSB' },
                            away_team: { id: 'COP' },
                            home_score: 1,
                            away_score: 1,
                            date: '2019-08-06',
                            time: '20:45',
                            stadium: 'Red Star Stadium',
                            city: 'Belgrade',
                            leg2_home_team: { id: 'COP' },
                            leg2_away_team: { id: 'RSB' },
                            leg2_home_score: 1,
                            leg2_away_score: 1,
                            leg2_home_extra_score: 0,
                            leg2_away_extra_score: 0,
                            leg2_home_penalty_score: 6,
                            leg2_away_penalty_score: 7,
                            leg2_date: '2019-08-13',
                            leg2_time: '20:00',
                            leg2_stadium: 'Parken Stadium',
                            leg2_city: 'Copenhagen',
                          },
                        ],
                      },
                      {
                        name: 'League',
                        matches: [],
                      },
                    ],
                  },
                ],
              },
              {
                name: 'Play-off Round',
                type: 'knockout',
                hide_bracket: true,
                rounds: [{ name: 'Play-off Round', paths: [{ name: 'Champions' }, { name: 'League' }] }],
              },
              {
                name: 'Group Stage',
                type: 'roundrobin',
                multiple_matchdays: true,
                eliminate_count: 16,
                home_and_away: true,
                next_round: 'Round of 16',
                advancement: {
                  auto: [1, 2],
                  transferred: [3],
                  eliminated: [4],
                  text: 'The top 2 teams would advance to the Round of 16. The third-placed teams would transfer to the Europa League Round of 32.',
                },
                groups: [
                  {
                    name: 'Group A',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [],
                      },
                    ],
                  },
                  {
                    name: 'Group B',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [],
                      },
                      {
                        name: 'Matchday 3',
                        matches: [],
                      },
                    ],
                  },
                  {
                    name: 'Group E',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                    ],
                  },
                ],
              },
              { name: 'Knockout Stage', type: 'knockout' },
            ],
          },
        },
        {
          id: 'UCL201819',
          data: {
            name: 'Tournamnt',
            tournament_id: 'UCL201819',
            description: 'UEFA Champions League 2018-19',
            order: 9,
          },
        },
      ],
    },
    {
      number: '9',
      rows: [
        {
          id: 'UEL202021',
          data: {
            name: 'Tournament',
            tournament_id: 'UEL202021',
            description: 'UEFA Europa League 2020-21',
            order: 9,
            stages: [
              {
                name: 'Preliminary Round',
                type: 'knockout',
                hide_bracket: true,
                rounds: [
                  {
                    name: 'Preliminary Round',
                    next_round: 'First Qualifying Round',
                    eliminate_count: 205,
                    teams: [
                      { id: 'TRP' },
                      { id: 'GJI' },
                      { id: 'LRI' },
                      { id: 'PRI' },
                      { id: 'SAC' },
                      { id: 'ISK' },
                      { id: 'UEE' },
                      { id: 'ZET' },
                      { id: 'GLN' },
                      { id: 'HBT' },
                      { id: 'SJF' },
                      { id: 'B36' },
                      { id: 'CFC' },
                      { id: 'LFI' },
                      { id: 'RUN' },
                      { id: 'BTU' },
                    ],
                    bye_teams: [
                      { id: 'MRB' },
                      { id: 'LJU' },
                      { id: 'VKR' },
                      { id: 'LET' },
                      { id: 'RIT' },
                      { id: 'DER' },
                      { id: 'ZAL' },
                      { id: 'PAI' },
                      { id: 'BUH' },
                      { id: 'ITU' },
                      { id: 'ZRI' },
                      { id: 'D03' },
                      { id: 'VFC' },
                      { id: 'BLA' },
                      { id: 'UTP' },
                      { id: 'RBK' },
                      { id: 'UBK' },
                      { id: 'ABE' },
                      { id: 'MOT' },
                      { id: 'HAM' },
                      { id: 'PUS' },
                      { id: 'MAL' },
                      { id: 'CRA' },
                      { id: 'KUK' },
                      { id: 'SOF' },
                      { id: 'VES' },
                      { id: 'DAT' },
                      { id: 'SSO' },
                      { id: 'SFI' },
                      { id: 'DMI' },
                      { id: 'GLI' },
                      { id: 'AGF' },
                      { id: 'HOK' },
                      { id: 'SHR' },
                      { id: 'ILV' },
                      { id: 'FHA' },
                      { id: 'DAC-2021' },
                      { id: 'TNS' },
                      { id: 'ZIL' },
                      { id: 'VAD' },
                      { id: 'HBN' },
                      { id: 'SER' },
                      { id: 'RUZ' },
                      { id: 'BAK' },
                      { id: 'FKS' },
                      { id: 'KES' },
                      { id: 'LAC' },
                      { id: 'HBS' },
                      { id: 'BAT' },
                      { id: 'NOM' },
                      { id: 'MUR' },
                      { id: 'BOD' },
                      { id: 'KZA' },
                      { id: 'VID' },
                      { id: 'BOH' },
                      { id: 'APL' },
                      { id: 'SAB' },
                      { id: 'MHA' },
                      { id: 'ZEL' },
                      { id: 'ASH' },
                      { id: 'KFR' },
                      { id: 'PBE' },
                      { id: 'RFS' },
                      { id: 'POZ-2021' },
                      { id: 'VLM' },
                      { id: 'ORD' },
                      { id: 'BTO' },
                      { id: 'SBU' },
                      { id: 'SGS' },
                      { id: 'PRO' },
                      { id: 'CSO' },
                      { id: 'SRE' },
                      { id: 'HIN' },
                      { id: 'TSC' },
                      { id: 'SUM' },
                      { id: 'KFS' },
                      { id: 'KAI' },
                      { id: 'NOA' },
                      { id: 'LTB' },
                      { id: 'UNC' },
                      { id: 'TEU' },
                      { id: 'BEJ' },
                      { id: 'BBL' },
                      { id: 'SUJ' },
                      { id: 'PLO' },
                      { id: 'APO' },
                    ],
                    matches: [
                      {
                        home_team: { id: 'LRI' },
                        away_team: { id: 'PRI' },
                        home_awarded_score: 3,
                        away_awarded_score: 0,
                        date: '2020-08-22',
                        time: '18:00',
                        stadium: 'Victoria Stadium',
                        city: 'Gibraltar',
                        awarded_match: true,
                        awarded_text:
                          'Awarded: The match could not be played due to eight players from Prishtina testing positive for Coronavirus and the whole second team being put into quarantine by the Gibraltarian authorities. Lincoln Red Imps were subsequently awarded a technical 3–0 victory by UEFA.',
                      },
                    ],
                  },
                ],
              },
              {
                name: 'Qualifying Rounds',
                type: 'knockout',
                hide_bracket: true,
                rounds: [
                  {
                    name: 'First Qualifying Round',
                    next_round: 'Second Qualifying Round',
                    bye_teams: [],
                    matches: [
                      {
                        home_team: { id: 'KIK' },
                        away_team: { id: 'SKS' },
                        home_awarded_score: 3,
                        away_awarded_score: 0,
                        date: '2020-08-21',
                        time: '18:00',
                        stadium: 'Við Djúpumýrar',
                        city: 'Klaksvík',
                        awarded_match: true,
                        awarded_text:
                          'Awarded: The KÍ v Slovan Bratislava match was postponed to 21 August 2020 due to one staff member from Slovan Bratislava testing positive for SARS-2 coronavirus and the whole team being put into quarantine by the Faroese authorities. On 21 August, the match could not be played due to one player from Slovan Bratislava testing positive for SARS-2 coronavirus and the whole second team being put into quarantine by the Faroese authorities. KÍ were subsequently awarded a technical 3–0 victory by UEFA according to the regulations related to COVID-19.',
                      },
                    ],
                  },
                  {
                    name: 'Second Qualifying Round',
                    next_round: 'Third Qualifying Round',
                    bye_teams: [],
                    multiple_paths: true,
                    paths: [
                      {
                        name: 'Champions',
                        matches: [],
                      },
                      {
                        name: 'Main',
                        matches: [],
                      },
                    ],
                  },
                  { name: 'Third Qualifying Round' },
                ],
              },
              {
                name: 'Play-off Round',
                type: 'knockout',
                hide_bracket: true,
                rounds: [{ name: 'Play-off Round', paths: [{ name: 'Champions' }, { name: 'Main' }] }],
              },
              {
                name: 'Group Stage',
                type: 'roundrobin',
                multiple_matchdays: true,
                eliminate_count: 32,
                home_and_away: true,
                next_round: 'Round of 32',
                bye_teams: [{ id: 'DYK' }, { id: 'BRG' }, { id: 'MUN' }, { id: 'RBS' }, { id: 'KRA' }, { id: 'SHK' }, { id: 'AJA' }, { id: 'OLY' }],
                advancement: {
                  auto: [1, 2],
                  eliminated: [3, 4],
                  text: 'The top 2 teams would advance to the Round of 32, joined by 8 third-placed teams from UCL.',
                },
                groups: [
                  {
                    name: 'Group A',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [],
                      },
                    ],
                  },
                  {
                    name: 'Group B',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [],
                      },
                      {
                        name: 'Matchday 3',
                        matches: [],
                      },
                    ],
                  },
                  {
                    name: 'Group E',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                    ],
                  },
                  {
                    name: 'Group I',
                    teams: [{ id: 'VIL' }, { id: 'SIV' }, { id: 'MTA' }, { id: 'QAR' }],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                      {
                        name: 'Matchday 6',
                        matches: [
                          {
                            home_team: { id: 'VIL' },
                            away_team: { id: 'QAR' },
                            home_awarded_score: 3,
                            away_awarded_score: 0,
                            date: '2020-12-10',
                            time: '21:00',
                            stadium: 'Estadio de la Cerámica',
                            city: 'Villarreal',
                            awarded_match: true,
                            awarded_text:
                              'Awarded: The Villarreal v Qarabag match was cancelled and awarded as a 3–0 win to Villarreal after several players of the Qarabağ squad tested positive for the SARS-CoV-2.',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              { name: 'Knockout Stage', type: 'knockout' },
            ],
          },
        },
        {
          id: 'UEL201920',
          data: {
            name: 'Tournament',
            tournament_id: 'UEL201920',
            description: 'UEFA Europa League 2019-20',
            order: 9,
            stages: [
              { name: 'Preliminary Round', type: 'knockout' },
              {
                name: 'Qualifying Rounds',
                type: 'knockout',
                hide_bracket: true,
                rounds: [
                  {
                    name: 'First Qualifying Round',
                    next_round: 'Second Qualifying Round',
                    eliminate_count: 159,
                    bye_teams: [
                      { id: 'TRP' },
                      { id: 'SMA' },
                      { id: 'GLI' },
                      { id: 'RIG' },
                      { id: 'TIR' },
                      { id: 'SHE' },
                      { id: 'ARA' },
                      { id: 'LRI' },
                      { id: 'VRE' },
                      { id: 'LUD' },
                      { id: 'SKS' },
                      { id: 'FRN' },
                      { id: 'SAC' },
                      { id: 'AST' },
                      { id: 'HBT' },
                      { id: 'LNF' },
                      { id: 'KFS' },
                      { id: 'F91' },
                      { id: 'FCA' },
                      { id: 'EPN' },
                      { id: 'ATS' },
                      { id: 'SGR' },
                      { id: 'UTR' },
                      { id: 'JAB' },
                      { id: 'LEG' },
                      { id: 'GBL' },
                      { id: 'YMA' },
                      { id: 'SGE' },
                      { id: 'GNT' },
                      { id: 'VCO' },
                      { id: 'ZLH' },
                      { id: 'OSI' },
                      { id: 'TOR' },
                      { id: 'LUZ' },
                      { id: 'STR' },
                      { id: 'MBO' },
                      { id: 'AZA' },
                      { id: 'HAC' },
                      { id: 'PLO' },
                      { id: 'WLV' },
                      { id: 'ART' },
                      { id: 'AEL' },
                      { id: 'VDG' },
                      { id: 'ESB' },
                      { id: 'PBE' },
                    ],
                    matches: [
                      {
                        multiple_legs: true,
                        home_team: { id: 'RBI' },
                        away_team: { id: 'SPT' },
                        home_score: 2,
                        away_score: 0,
                        date: '2019-07-11',
                        time: '19:00',
                        stadium: 'Banja Luka City Stadium',
                        city: 'Banja Luka',
                        leg2_home_team: { id: 'SPT' },
                        leg2_away_team: { id: 'RBI' },
                        leg2_home_score: 2,
                        leg2_away_score: 0,
                        leg2_home_extra_score: 0,
                        leg2_away_extra_score: 0,
                        leg2_home_penalty_score: 3,
                        leg2_away_penalty_score: 2,
                        leg2_date: '2019-07-18',
                        leg2_time: '20:45',
                        leg2_stadium: 'Anton Malatinský Stadium',
                        leg2_city: 'Trnava',
                      },
                      {
                        multiple_legs: true,
                        home_team: { id: 'DAC-2021' },
                        away_team: { id: 'CRA' },
                        home_score: 1,
                        away_score: 1,
                        date: '2019-07-11',
                        time: '20:30',
                        stadium: 'MOL Aréna',
                        city: 'Dunajská Streda',
                        leg2_home_team: { id: 'CRA' },
                        leg2_away_team: { id: 'DAC-2021' },
                        leg2_home_score: 1,
                        leg2_away_score: 1,
                        leg2_home_extra_score: 1,
                        leg2_away_extra_score: 1,
                        leg2_date: '2019-07-18',
                        leg2_time: '19:00',
                        leg2_stadium: 'Marshal Józef Piłsudski Stadium',
                        leg2_city: 'Kraków',
                      },
                    ],
                  },
                  {
                    name: 'Second Qualifying Round',
                    next_round: 'Third Qualifying Round',
                    eliminate_count: 113,
                    bye_teams: [],
                    multiple_paths: true,
                    paths: [
                      {
                        name: 'Champions',
                        matches: [],
                      },
                      {
                        name: 'Main',
                        matches: [],
                      },
                    ],
                  },
                  { name: 'Third Qualifying Round' },
                ],
              },
              {
                name: 'Play-off Round',
                type: 'knockout',
                hide_bracket: true,
                rounds: [{ name: 'Play-off Round', paths: [{ name: 'Champions' }, { name: 'Main' }] }],
              },
              {
                name: 'Group Stage',
                type: 'roundrobin',
                multiple_matchdays: true,
                eliminate_count: 32,
                home_and_away: true,
                next_round: 'Round of 32',
                bye_teams: [],
                advancement: {
                  auto: [1, 2],
                  eliminated: [3, 4],
                  text: 'The top 2 teams would advance to the Round of 32, joined by 8 third-placed teams from UCL.',
                },
                groups: [
                  {
                    name: 'Group A',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [],
                      },
                    ],
                  },
                  {
                    name: 'Group B',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                      {
                        name: 'Matchday 2',
                        matches: [],
                      },
                      {
                        name: 'Matchday 3',
                        matches: [],
                      },
                    ],
                  },
                  {
                    name: 'Group E',
                    teams: [],
                    matchdays: [
                      {
                        name: 'Matchday 1',
                        matches: [],
                      },
                    ],
                  },
                ],
              },
              { name: 'Knockout Stage', type: 'knockout' },
            ],
          },
        },
        {
          id: 'UEL201819',
          data: {
            name: 'Tournamnt',
            tournament_id: 'UEL201819',
            description: 'UEFA Europa League 2018-19',
            order: 9,
          },
        },
      ],
    },
    {
      number: '10',
      rows: [
        {
          id: 'UECL202122',
          data: {
            name: 'Tournamnt',
            tournament_id: 'UECL202122',
            description: 'UEFA Europa Conference League 2021-22',
            order: 9,
          },
        },
      ],
    },
    {
      number: '11',
      rows: [
        {
          id: 'UNL202021',
          data: {
            name: 'Tournament',
            tournament_id: 'UNL202021',
            multiple_leagues: true,
            description: 'UEFA Nations League 2020-21',
            order: 9,
            leagues: [
              {
                name: 'League A',
                default: true,
                default_matchday: 'Matchday 1',
                standing_count: 0,
                stages: [
                  {
                    name: 'Group Stage',
                    type: 'roundrobin',
                    home_and_away: true,
                    multiple_matchdays: true,
                    advancement: {
                      auto: [1],
                      eliminated: [2, 3],
                      relegated: [4],
                      text: 'The top teams in League A would advance to the Nations League Finals. The top teams in leagues B, C and D would be promoted to the higher league. The last-placed teams in leagues A and B would be relegated to the lower league. The last-placed teams in league C would play in relegation play-outs to determine 2 to be relegated to league D.',
                    },
                    groups: [
                      {
                        name: 'Group 1',
                        teams: [{ id: 'ITA' }, { id: 'BIH' }, { id: 'NED' }, { id: 'POL' }],
                        matchdays: [
                          {
                            name: 'Matchday 1',
                            matches: [
                              {
                                home_team: { id: 'ITA' },
                                away_team: { id: 'BIH' },
                                home_score: 1,
                                away_score: 1,
                                date: '2020-09-04',
                                time: '20:45',
                                stadium: 'Stadio Artemio Franchi',
                                city: 'Florence',
                              },
                              {
                                home_team: { id: 'NED' },
                                away_team: { id: 'POL' },
                                home_score: 1,
                                away_score: 0,
                                date: '2020-09-04',
                                time: '20:45',
                                stadium: 'Johan Cruyff Arena',
                                city: 'Amsterdam',
                              },
                            ],
                          },
                          {
                            name: 'Matchday 2',
                            matches: [
                              {
                                home_team: { id: 'BIH' },
                                away_team: { id: 'POL' },
                                home_score: 1,
                                away_score: 2,
                                date: '2020-09-07',
                                time: '20:45',
                                stadium: 'Bilino Polje',
                                city: 'Zenica',
                              },
                            ],
                          },
                        ],
                      },
                      {
                        name: 'Group 2',
                        teams: [{ id: 'ISL' }, { id: 'ENG' }, { id: 'DEN' }, { id: 'BEL' }],
                        matchdays: [
                          {
                            name: 'Matchday 1',
                            matches: [
                              {
                                home_team: { id: 'ISL' },
                                away_team: { id: 'ENG' },
                                home_score: 0,
                                away_score: 1,
                                date: '2020-09-05',
                                time: '18:00',
                                stadium: 'Laugardalsvöllur',
                                city: 'Reykjavík',
                              },
                            ],
                          },
                          {
                            name: 'Matchday 3',
                            matches: [
                              {
                                home_team: { id: 'ENG' },
                                away_team: { id: 'BEL' },
                                home_score: 2,
                                away_score: 1,
                                date: '2020-10-11',
                                time: '18:00',
                                stadium: 'Wembley Stadium',
                                city: 'London',
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    name: 'Finals',
                    type: 'knockout',
                    rounds: [],
                  },
                ],
              },
              {
                name: 'League B',
                standing_count: 16,
                stages: [
                  {
                    name: 'Group Stage',
                    type: 'roundrobin',
                    home_and_away: true,
                    multiple_matchdays: true,
                    advancement: {
                      auto: [1],
                      eliminated: [2, 3],
                      relegated: [4],
                      text: 'The top teams in League A would advance to the Nations League Finals. The top teams in leagues B, C and D would be promoted to the higher league. The last-placed teams in leagues A and B would be relegated to the lower league. The last-placed teams in league C would play in relegation play-outs to determine 2 to be relegated to league D.',
                    },
                    groups: [
                      {
                        name: 'Group 1',
                        teams: [{ id: 'NOR' }, { id: 'AUT' }, { id: 'ROU' }, { id: 'NIR' }],
                        matchdays: [
                          {
                            name: 'Matchday 1',
                            matches: [
                              {
                                home_team: { id: 'NOR' },
                                away_team: { id: 'AUT' },
                                home_score: 1,
                                away_score: 2,
                                date: '2020-09-04',
                                time: '20:45',
                                stadium: 'Ullevaal Stadion',
                                city: 'Oslo',
                              },
                            ],
                          },
                          {
                            name: 'Matchday 2',
                            matches: [],
                          },
                        ],
                      },
                      {
                        name: 'Group 2',
                        teams: [{ id: 'SCO' }, { id: 'ISR' }, { id: 'SVK' }, { id: 'CZE' }],
                        matchdays: [
                          {
                            name: 'Matchday 1',
                            matches: [],
                          },
                          {
                            name: 'Matchday 3',
                            matches: [],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              { name: 'League C', standing_count: 32, stages: [] },
              { name: 'League D', standing_count: 48, stages: [] },
            ],
          },
        },
        {
          id: 'UNL201819',
          data: {
            name: 'Tournamnt',
            tournament_id: 'UNL201819',
            description: 'UEFA Nations League 2018-19',
            order: 9,
          },
        },
      ],
    },
  ],
}
