export const AppData = {
  collection: 'nation',
  batches: [
    {
      number: '1',
      rows: [
        {
          id: 'AFG',
          data: {
            name: 'Afghanistan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Afghanistan.png',
            start_date: '1973-07-16',
            end_date: '',
          },
        },
        {
          id: 'AFG-1931-1973',
          data: {
            name: 'Afghanistan',
            official_name: 'Kingdom of Afghanistan',
            parent_nation_id: 'AFG',
            nation_type_id: 'NATN',
            flag_filename: 'Afghanistan_1931_1973.png',
            code: 'AFG',
            start_date: '1930-03-27',
            end_date: '1973-07-16',
          },
        },
        {
          id: 'ALB',
          data: {
            name: 'Albania',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Albania.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ALG',
          data: {
            name: 'Algeria',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Algeria.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ASA',
          data: {
            name: 'American Samoa',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'American_Samoa.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AND',
          data: {
            name: 'Andorra',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Andorra.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ANG',
          data: {
            name: 'Angola',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Angola.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AIA',
          data: {
            name: 'Anguilla',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Anguilla.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ATG',
          data: {
            name: 'Antigua and Barbuda',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Antigua_and_Barbuda.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ARG',
          data: {
            name: 'Argentina',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'arg.svg',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ARM',
          data: {
            name: 'Armenia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Armenia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ARU',
          data: {
            name: 'Aruba',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Aruba.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AUS',
          data: {
            name: 'Australia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Australia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AUT',
          data: {
            name: 'Austria',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Austria.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AUTHM',
          data: {
            name: 'Austria',
            official_name: 'Habsburg Monarchy',
            parent_nation_id: 'AUT',
            nation_type_id: 'NATN',
            flag_filename: 'Austrian_Habsburg_Monarchy.png',
            code: 'AUT',
            start_date: '',
            end_date: '1918-01-01',
          },
        },
        {
          id: 'AZE',
          data: {
            name: 'Azerbaijan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Azerbaijan.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '2',
      rows: [
        {
          id: 'BAH',
          data: {
            name: 'Bahamas',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bahamas.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BHR',
          data: {
            name: 'Bahrain',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bahrain.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BAN',
          data: {
            name: 'Bangladesh',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bangladesh.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BRB',
          data: {
            name: 'Barbados',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Barbados.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BLR',
          data: {
            name: 'Belarus',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Belarus.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BEL',
          data: {
            name: 'Belgium',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Belgium.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BLZ',
          data: {
            name: 'Belize',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Belize.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BEN',
          data: {
            name: 'Benin',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Benin.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BER',
          data: {
            name: 'Bermuda',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bermuda.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BHU',
          data: {
            name: 'Bhutan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bhutan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BOL',
          data: {
            name: 'Bolivia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bolivia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BIH',
          data: {
            name: 'Bosnia and Herzegovina',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bosnia_and_Herzegovina.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BOT',
          data: {
            name: 'Botswana',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Botswana.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BRA',
          data: {
            name: 'Brazil',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Brazil.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VGB',
          data: {
            name: 'British Virgin Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'British_Virgin_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BRU',
          data: {
            name: 'Brunei Darussalam',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Brunei_Darussalam.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BUL',
          data: {
            name: 'Bulgaria',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Bulgaria.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BUL-1946-1948',
          data: {
            name: 'Bulgaria',
            official_name: 'People\'s Republic of Bulgaria',
            parent_nation_id: 'BUL',
            nation_type_id: 'NATN',
            flag_filename: 'Bulgaria_1946_1948.png',
            code: 'BUL',
            start_date: '1946-09-15',
            end_date: '1948-01-27',
          },
        },
        {
          id: 'BUL-1948-1967',
          data: {
            name: 'Bulgaria',
            official_name: 'People\'s Republic of Bulgaria',
            parent_nation_id: 'BUL',
            nation_type_id: 'NATN',
            flag_filename: 'Bulgaria_1948_1967.png',
            code: 'BUL',
            start_date: '1948-01-27',
            end_date: '1967-06-14',
          },
        },
        {
          id: 'BUL-1967-1971',
          data: {
            name: 'Bulgaria',
            official_name: 'People\'s Republic of Bulgaria',
            parent_nation_id: 'BUL',
            nation_type_id: 'NATN',
            flag_filename: 'Bulgaria_1967_1971.png',
            code: 'BUL',
            start_date: '1967-06-14',
            end_date: '1971-05-21',
          },
        },
        {
          id: 'BUL-1971-1990',
          data: {
            name: 'Bulgaria',
            official_name: 'People\'s Republic of Bulgaria',
            parent_nation_id: 'BUL',
            nation_type_id: 'NATN',
            flag_filename: 'Bulgaria_1971_1990.png',
            code: 'BUL',
            start_date: '1971-05-21',
            end_date: '1990-11-15',
          },
        },
        {
          id: 'BFA',
          data: {
            name: 'Burkina Faso',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Burkina_Faso.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'UPV',
          data: {
            name: 'Upper Volta',
            official_name: '',
            parent_nation_id: 'BFA',
            nation_type_id: 'NATN',
            flag_filename: 'Upper_Volta.png',
            code: 'UPV',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BUR',
          data: {
            name: 'Burma',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Burma.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BDI',
          data: {
            name: 'Burundi',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Burundi.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '3',
      rows: [
        {
          id: 'CAM',
          data: {
            name: 'Cambodia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Cambodia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CMR',
          data: {
            name: 'Cameroon',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Cameroon.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CMR-1961-1975',
          data: {
            name: 'Cameroon',
            official_name: 'Federal Republic of Cameroon',
            parent_nation_id: 'CMR',
            nation_type_id: 'NATN',
            flag_filename: 'Cameroon_1961_1975.png',
            code: 'CMR',
            start_date: '1961-10-01',
            end_date: '1975-05-20',
          },
        },
        {
          id: 'CAN',
          data: {
            name: 'Canada',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Canada.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CPV',
          data: {
            name: 'Cape Verde Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Cape_Verde_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CAY',
          data: {
            name: 'Cayman Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Cayman_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CTA',
          data: {
            name: 'Central African Republic',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Central_African_Republic.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CHA',
          data: {
            name: 'Chad',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Chad.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CHI',
          data: {
            name: 'Chile',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Chile.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CHN',
          data: {
            name: 'China PR',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'China_PR.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TPE',
          data: {
            name: 'Chinese Taipei',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Chinese_Taipei.png',
            start_date: '2006-01-01',
            end_date: '',
          },
        },
        {
          id: 'TPE-1924-1949',
          data: {
            name: 'China',
            official_name: 'China',
            parent_nation_id: 'TPE',
            nation_type_id: 'NATN',
            flag_filename: 'Taiwan.png',
            code: 'CHN',
            start_date: '1924-01-01',
            end_date: '1949-01-01',
          },
        },
        {
          id: 'TPE-1949-1960',
          data: {
            name: 'Taiwan',
            official_name: 'Taiwan',
            parent_nation_id: 'TPE',
            nation_type_id: 'NATN',
            flag_filename: 'Taiwan.png',
            code: 'TAI',
            start_date: '1949-01-01',
            end_date: '1960-01-01',
          },
        },
        {
          id: 'TPE-1960-1979',
          data: {
            name: 'Republic of China',
            official_name: '',
            parent_nation_id: 'TPE',
            nation_type_id: 'NATN',
            flag_filename: 'Republic_of_China.png',
            code: 'ROC',
            start_date: '1960-01-01',
            end_date: '1979-01-01',
          },
        },
        {
          id: 'TPE-1979-2006',
          data: {
            name: 'Chinese Taipei',
            official_name: 'Chinese Taipei',
            parent_nation_id: 'TPE',
            nation_type_id: 'NATN',
            flag_filename: 'Chinese_Taipei_2006.png',
            code: 'TPE',
            start_date: '1979-01-01',
            end_date: '2006-01-01',
          },
        },
        {
          id: 'RUS',
          data: {
            name: 'Russia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Russia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CIS',
          data: {
            name: 'CIS',
            official_name: 'Commonwealth of Independent States',
            parent_nation_id: 'RUS',
            nation_type_id: 'NATN',
            flag_filename: 'CIS.png',
            code: 'CIS',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'URS',
          data: {
            name: 'Soviet Union',
            official_name: '',
            parent_nation_id: 'RUS',
            nation_type_id: 'NATN',
            flag_filename: 'urs.png',
            code: 'URS',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'COL',
          data: {
            name: 'Colombia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Colombia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'COM',
          data: {
            name: 'Comoros',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Comoros.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CGO',
          data: {
            name: 'Congo',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Congo.png',
            start_date: '1991-06-09',
            end_date: '',
          },
        },
        {
          id: 'CGO-1970-1991',
          data: {
            name: 'Congo',
            official_name: 'People\'s Republic of the Congo',
            parent_nation_id: 'CGO',
            nation_type_id: 'NATN',
            flag_filename: 'Congo_1970_1991.png',
            code: 'CGO',
            start_date: '1970-01-02',
            end_date: '1991-06-09',
          },
        },
        {
          id: 'COD',
          data: {
            name: 'Congo DR',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Congo_DR.png',
            start_date: '2006-02-18',
            end_date: '',
          },
        },
        {
          id: 'COD-1964-1966',
          data: {
            name: 'Congo-Léopoldville',
            official_name: 'Congo-Léopoldville',
            parent_nation_id: 'COD',
            nation_type_id: 'NATN',
            flag_filename: 'Congo_Leopoldville_1964_1966.png',
            code: 'COD',
            start_date: '1964-08-01',
            end_date: '1966-06-01',
          },
        },
        {
          id: 'COD-1966-1971',
          data: {
            name: 'Congo-Kinshasa',
            official_name: 'Congo-Kinshasa',
            parent_nation_id: 'COD',
            nation_type_id: 'NATN',
            flag_filename: 'Congo_Kinshasa_1966_1971.png',
            code: 'COD',
            start_date: '1966-06-01',
            end_date: '1971-10-27',
          },
        },
        {
          id: 'COD-1971-1997',
          data: {
            name: 'Zaire',
            official_name: '',
            parent_nation_id: 'COD',
            nation_type_id: 'NATN',
            flag_filename: 'zai.png',
            code: 'ZAI',
            start_date: '1971-10-27',
            end_date: '1997-05-17',
          },
        },
        {
          id: 'COD-1997-2003',
          data: {
            name: 'Congo DR',
            official_name: 'Democratic Republic of the Congo',
            parent_nation_id: 'COD',
            nation_type_id: 'NATN',
            flag_filename: 'Congo_DR_1997_2003.png',
            code: 'COD',
            start_date: '1997-05-17',
            end_date: '2003-01-01',
          },
        },
        {
          id: 'COD-2003-2006',
          data: {
            name: 'Congo DR',
            official_name: 'Democratic Republic of the Congo',
            parent_nation_id: 'COD',
            nation_type_id: 'NATN',
            flag_filename: 'Congo_DR_2003_2006.png',
            code: 'COD',
            start_date: '2003-01-01',
            end_date: '2006-02-18',
          },
        },
        {
          id: 'COK',
          data: {
            name: 'Cook Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Cook_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CRC',
          data: {
            name: 'Costa Rica',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Costa_Rica.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CRC-1964-1998',
          data: {
            name: 'Costa Rica',
            official_name: 'Costa Rica',
            parent_nation_id: 'CRC',
            nation_type_id: 'NATN',
            flag_filename: 'Costa_Rica_1964_1998.png',
            code: 'CRC',
            start_date: '1964-01-01',
            end_date: '1998-01-01',
          },
        },
        {
          id: 'CRO',
          data: {
            name: 'Croatia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Croatia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CUB',
          data: {
            name: 'Cuba',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Cuba.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CUW',
          data: {
            name: 'Curaçao',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Curacao.png',
            start_date: '2010-10-10',
            end_date: '',
          },
        },
        {
          id: 'CYP',
          data: {
            name: 'Cyprus',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Cyprus.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CZE',
          data: {
            name: 'Czech Republic',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Czech_Republic.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TCH',
          data: {
            name: 'Czechoslovakia',
            official_name: '',
            parent_nation_id: 'CZE',
            nation_type_id: 'NATN',
            flag_filename: 'tch.png',
            code: 'TCH',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '4',
      rows: [
        {
          id: 'DEN',
          data: {
            name: 'Denmark',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Denmark.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'DJI',
          data: {
            name: 'Djibouti',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Djibouti.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'DMA',
          data: {
            name: 'Dominica',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Dominica.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'DOM',
          data: {
            name: 'Dominican Republic',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Dominican_Republic.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'INH',
          data: {
            name: 'Dutch East Indies',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'inh.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
  ],
}
