export const AppData = {
  collection: 'nation',
  batches: [
    {
      number: '5',
      rows: [
        {
          id: 'GDR',
          data: {
            name: 'East Germany',
            official_name: 'German Democratic Republic',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_East_Germany_2-3.png',
            start_date: '1949-10-07',
            end_date: '1990-10-03',
          },
        },
        {
          id: 'ECU',
          data: {
            name: 'Ecuador',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONMEBOL',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Ecuador.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'EGY',
          data: {
            name: 'Egypt',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Egypt.svg.png',
            start_date: '1984-10-04',
            end_date: '',
          },
        },
        {
          id: 'EGY-1972-1984',
          data: {
            name: 'Egypt',
            official_name: 'Federation of Arab Republics',
            parent_nation_id: 'EGY',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Egypt_(1972–1984).svg.png',
            code: 'EGY',
            start_date: '1972-01-01',
            end_date: '1984-10-04',
          },
        },
        {
          id: 'UAR',
          data: {
            name: 'United Arab Republic',
            official_name: '',
            parent_nation_id: 'EGY',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_United_Arab_Republic_(1958–1971).svg.png',
            code: 'UAR',
            start_date: '1958-02-22',
            end_date: '1971-09-11',
          },
        },
        {
          id: 'EGY-1953-1958',
          data: {
            name: 'Egypt',
            official_name: 'Republic of Egypt',
            parent_nation_id: 'EGY',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Egypt_(1953–1958).svg.png',
            code: 'EGY',
            start_date: '1953-06-18',
            end_date: '1958-02-22',
          },
        },
        {
          id: 'EGY-1922-1953',
          data: {
            name: 'Egypt',
            official_name: 'Kingdom of Egypt',
            parent_nation_id: 'EGY',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Egypt_(1922–1953).svg.png',
            code: 'EGY',
            start_date: '1922-02-28',
            end_date: '1953-06-18',
          },
        },
        {
          id: 'EGY-1914-1922',
          data: {
            name: 'Egypt',
            official_name: 'Sultanate of Egypt',
            parent_nation_id: 'EGY',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Egypt_(1882-1922)_2-3.png',
            code: 'EGY',
            start_date: '1914-11-05',
            end_date: '1922-02-28',
          },
        },
        {
          id: 'SLV',
          data: {
            name: 'El Salvador',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_El_Salvador_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ENG',
          data: {
            name: 'England',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_England_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'EQG',
          data: {
            name: 'Equatorial Guinea',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Equatorial_Guinea.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ERI',
          data: {
            name: 'Eritrea',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Eritrea_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'EST',
          data: {
            name: 'Estonia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Estonia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SWZ',
          data: {
            name: 'Eswatini',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Eswatini.svg.png',
            start_date: '2018-04-19',
            end_date: '',
          },
        },
        {
          id: 'SWZ-2018',
          data: {
            name: 'Swaziland',
            official_name: '',
            parent_nation_id: 'SWZ',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Eswatini.svg.png',
            start_date: '',
            end_date: '2018-04-19',
          },
        },
        {
          id: 'ETH',
          data: {
            name: 'Ethiopia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Ethiopia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ETH-1975-1987',
          data: {
            name: 'Ethiopia',
            official_name: 'Provisional Military Government of Socialist Ethiopia',
            parent_nation_id: 'ETH',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Ethiopia_(1975–1987).svg.png',
            code: 'ETH',
            start_date: '1975-03-21',
            end_date: '1987-02-22',
          },
        },
        {
          id: 'ETH-1941-1974',
          data: {
            name: 'Ethiopia',
            official_name: 'Italian Ethiopia',
            parent_nation_id: 'ETH',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Ethiopia_(1897-1936;_1941-1974).svg.png',
            code: 'ETH',
            start_date: '1941-01-01',
            end_date: '1974-09-12',
          },
        },
      ],
    },
    {
      number: '6',
      rows: [
        {
          id: 'FRO',
          data: {
            name: 'Faroe Islands',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Faroe_Islands_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'FIJ',
          data: {
            name: 'Fiji',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Fiji_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'FIN',
          data: {
            name: 'Finland',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Finland_2-3.png',
            start_date: '1917-12-06',
            end_date: '',
          },
        },
        {
          id: 'FIN-1809-1917',
          data: {
            name: 'Finland',
            official_name: 'Grand Duchy of Finland',
            parent_nation_id: 'FIN',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Russia.svg.png',
            code: 'FIN',
            start_date: '1809-03-29',
            end_date: '1917-12-06',
          },
        },
        {
          id: 'FRA',
          data: {
            name: 'France',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_France.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUF',
          data: {
            name: 'French Guiana',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: '640px-Flag_of_French_Guiana.svg.png',
            start_date: '2010-01-29',
            end_date: '2016-01-01',
          },
        },
      ],
    },
    {
      number: '7',
      rows: [
        {
          id: 'GAB',
          data: {
            name: 'Gabon',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Gabon_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GAM',
          data: {
            name: 'Gambia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_The_Gambia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GEO',
          data: {
            name: 'Georgia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Georgia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GER',
          data: {
            name: 'Germany',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Germany_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GER-1949-1990',
          data: {
            name: 'West Germany',
            official_name: 'Federal Republic of Germany',
            parent_nation_id: 'GER',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Germany_2-3.png',
            code: 'FRG',
            start_date: '1949-05-23',
            end_date: '1990-10-03',
          },
        },
        {
          id: 'GER-1956-1968',
          data: {
            name: 'Germany',
            official_name: 'Germany',
            parent_nation_id: 'GER',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'German_Olympic_flag_(1959-1968)_2-3.png',
            code: 'GER',
            start_date: '1956-01-01',
            end_date: '1968-01-01',
          },
        },
        {
          id: 'GER-1935-1945',
          data: {
            name: 'Germany',
            official_name: 'Germany',
            parent_nation_id: 'GER',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Germany_(1935–1945)_2-3.png',
            code: 'GER',
            start_date: '1935-09-15',
            end_date: '1945-05-08',
          },
        },
        {
          id: 'GER-1933-1935',
          data: {
            name: 'Germany',
            official_name: 'Germany',
            parent_nation_id: 'GER',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Germany_(1867–1918).svg.png',
            code: 'GER',
            start_date: '1933-01-30',
            end_date: '1935-09-15',
          },
        },
        {
          id: 'GER-1918-1933',
          data: {
            name: 'Germany',
            official_name: 'Weimar Republic',
            parent_nation_id: 'GER',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Germany_2-3.png',
            code: 'GER',
            start_date: '1918-11-11',
            end_date: '1933-01-30',
          },
        },
        {
          id: 'GER-1866-1918',
          data: {
            name: 'Germany',
            official_name: 'German Empire',
            parent_nation_id: 'GER',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Germany_(1867–1918).svg.png',
            code: 'GER',
            start_date: '1866-01-01',
            end_date: '1918-11-11',
          },
        },
        {
          id: 'GHA',
          data: {
            name: 'Ghana',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Ghana.svg.png',
            start_date: '1966-02-24',
            end_date: '',
          },
        },
        {
          id: 'GHA-1964-1966',
          data: {
            name: 'Ghana',
            official_name: 'Ghana',
            parent_nation_id: 'GHA',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Ghana_(1964–1966).svg.png',
            code: 'GHA',
            start_date: '1964-01-01',
            end_date: '1966-02-24',
          },
        },
        {
          id: 'GIB',
          data: {
            name: 'Gibraltar',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_Gibraltar_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GBR',
          data: {
            name: 'Great Britain',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_United_Kingdom_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GRE',
          data: {
            name: 'Greece',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Greece_2-3.png',
            flag_max_width: '115%',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GRN',
          data: {
            name: 'Grenada',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Grenada_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GLP',
          data: {
            name: 'Guadeloupe',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: 'Unofficial_flag_of_Guadeloupe_(local)_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUM',
          data: {
            name: 'Guam',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Guam_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUA',
          data: {
            name: 'Guatemala',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Guatemala_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUI',
          data: {
            name: 'Guinea',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Guinea.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GNB',
          data: {
            name: 'Guinea-Bissau',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Guinea-Bissau_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUY',
          data: {
            name: 'Guyana',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Guyana_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '8',
      rows: [
        {
          id: 'HAI',
          data: {
            name: 'Haiti',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Haiti_2-3.png',
            start_date: '1986-02-26',
            end_date: '',
          },
        },
        {
          id: 'HAI-1964-1986',
          data: {
            name: 'Haiti',
            official_name: 'Haiti',
            parent_nation_id: 'HAI',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Haiti_(1964–1986)_2-3.png',
            code: 'HAI',
            start_date: '1964-01-01',
            end_date: '1986-02-26',
          },
        },
        {
          id: 'HON',
          data: {
            name: 'Honduras',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Honduras_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'HKG',
          data: {
            name: 'Hong Kong',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'TER',
            flag_filename: '640px-Flag_of_Hong_Kong.svg.png',
            start_date: '1997-07-01',
            end_date: '',
          },
        },
        {
          id: 'HKG-1959-1997',
          data: {
            name: 'Hong Kong',
            official_name: 'Hong Kong',
            parent_nation_id: 'HKG',
            confederation_id: 'AFC',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_Hong_Kong_(1959–1997)_2-3.png',
            code: 'HKG',
            start_date: '1959-01-01',
            end_date: '1997-01-01',
          },
        },
        {
          id: 'HKG-1955-1959',
          data: {
            name: 'Hong Kong',
            official_name: 'Hong Kong',
            parent_nation_id: 'HKG',
            confederation_id: 'AFC',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_Hong_Kong_(1955–1959)_2-3.png',
            code: 'HKG',
            start_date: '1955-01-01',
            end_date: '1959-01-01',
          },
        },
        {
          id: 'HUN',
          data: {
            name: 'Hungary',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Hungary_2-3.png',
            start_date: '1989-10-23',
            end_date: '',
          },
        },
        {
          id: 'HUN-1957-1989',
          data: {
            name: 'Hungary',
            official_name: "Hungarian People's Republic",
            parent_nation_id: 'HUN',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Hungary_2-3.png',
            code: 'HUN',
            start_date: '1957-05-23',
            end_date: '1989-10-23',
          },
        },
        {
          id: 'HUN-1949-1956',
          data: {
            name: 'Hungary',
            official_name: "Hungarian People's Republic",
            parent_nation_id: 'HUN',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Hungary_(1949-1956)_2-3.png',
            code: 'HUN',
            start_date: '1949-08-20',
            end_date: '1956-10-23',
          },
        },
        {
          id: 'HUN-1946-1949',
          data: {
            name: 'Hungary',
            official_name: 'Second Hungarian Republic',
            parent_nation_id: 'HUN',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Hungary_(1946-1949,_1956-1957)_2-3.png',
            code: 'HUN',
            start_date: '1946-02-01',
            end_date: '1949-08-20',
          },
        },
        {
          id: 'HUN-1919-1946',
          data: {
            name: 'Hungary',
            official_name: 'Kingdom of Hungary',
            parent_nation_id: 'HUN',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Hungary_(1915-1918,_1919-1946)_2-3.png',
            code: 'HUN',
            start_date: '1920-02-29',
            end_date: '1946-02-01',
          },
        },
        {
          id: 'HUN-1867-1918',
          data: {
            name: 'Hungary',
            official_name: 'Lands of the Crown of Saint Stephen',
            parent_nation_id: 'HUN',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Hungary_(1915-1918;_angels)_2-3.png',
            code: 'HUN',
            start_date: '1867-03-30',
            end_date: '1918-11-16',
          },
        },
      ],
    },
    {
      number: '9',
      rows: [
        {
          id: 'ISL',
          data: {
            name: 'Iceland',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Iceland_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'IND',
          data: {
            name: 'India',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_India.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'IDN',
          data: {
            name: 'Indonesia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Indonesia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'INH',
          data: {
            name: 'Dutch East Indies',
            official_name: '',
            parent_nation_id: 'IDN',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Netherlands.svg.png',
            start_date: '1800-01-01',
            end_date: '1949-12-27',
          },
        },
        {
          id: 'IRN',
          data: {
            name: 'Iran',
            official_name: 'Islamic Republic of Iran',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Iran_2-3.png',
            start_date: '1980-01-01',
            end_date: '',
          },
        },
        {
          id: 'IRN-1964-1980',
          data: {
            name: 'Iran',
            official_name: 'Iran',
            parent_nation_id: 'IRN',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'State_flag_of_Iran_(1964–1980)_2-3.png',
            code: 'IRN',
            start_date: '1964-01-01',
            end_date: '1980-01-01',
          },
        },
        {
          id: 'IRQ',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Iraq.svg.png',
            start_date: '2008-01-22',
            end_date: '',
          },
        },
        {
          id: 'IRQ-2004-2008',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: 'IRQ',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Iraq_(2004–2008).svg.png',
            code: 'IRQ',
            start_date: '2004-08-05',
            end_date: '2008-01-22',
          },
        },
        {
          id: 'IRQ-1991-2004',
          data: {
            name: 'Iraq',
            official_name: '',
            parent_nation_id: 'IRQ',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Iraq_(1991–2004).svg.png',
            code: 'IRQ',
            start_date: '1991-04-01',
            end_date: '2004-08-05',
          },
        },
        {
          id: 'IRQ-1963-1991',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: 'IRQ',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Iraq_(1963–1991).svg.png',
            code: 'IRQ',
            start_date: '1963-10-31',
            end_date: '1991-04-01',
          },
        },
        {
          id: 'IRQ-1959-1963',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: 'IRQ',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Iraq_(1959–1963)_2-3.png',
            code: 'IRQ',
            start_date: '1959-01-11',
            end_date: '1963-10-31',
          },
        },
        {
          id: 'IRQ-1921-1959',
          data: {
            name: 'Iraq',
            official_name: 'Kingdom of Iraq',
            parent_nation_id: 'IRQ',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Iraq_(1924–1959)_2-3.png',
            code: 'IRQ',
            start_date: '1921-04-23',
            end_date: '1959-01-11',
          },
        },
        {
          id: 'ISR',
          data: {
            name: 'Israel',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Israel_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ITA',
          data: {
            name: 'Italy',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Italy.svg.png',
            start_date: '1946-06-02',
            end_date: '',
          },
        },
        {
          id: 'ITA-1861-1946',
          data: {
            name: 'Italy',
            official_name: 'Kingdom of Italy',
            parent_nation_id: 'ITA',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Italy_(1861–1946).svg.png',
            code: 'ITA',
            start_date: '1861-03-17',
            end_date: '1946-06-02',
          },
        },
        {
          id: 'CIV',
          data: {
            name: 'Ivory Coast',
            official_name: "Côte d'Ivoire",
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: "640px-Flag_of_Cote_d'Ivoire.svg.png",
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '10',
      rows: [
        {
          id: 'JAM',
          data: {
            name: 'Jamaica',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Jamaica_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'JPN',
          data: {
            name: 'Japan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Japan.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'JOR',
          data: {
            name: 'Jordan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Jordan_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '11',
      rows: [
        {
          id: 'KAZ',
          data: {
            name: 'Kazakhstan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Kazakhstan_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KEN',
          data: {
            name: 'Kenya',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Kenya.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KIR',
          data: {
            name: 'Kiribati',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Kiribati_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PRK',
          data: {
            name: 'Korea DPR',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_North_Korea_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KOR',
          data: {
            name: 'Korea Republic',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_South_Korea.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KVX',
          data: {
            name: 'Kosovo',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_Kosovo_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KUW',
          data: {
            name: 'Kuwait',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Kuwait_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KGZ',
          data: {
            name: 'Kyrgyzstan',
            official_name: 'Kyrgyz Republic',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Kyrgyzstan_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
  ],
}
