export const AppData = {
  collection: 'nation',
  batches: [
    {
      number: '18',
      rows: [
        {
          id: 'TAH',
          data: {
            name: 'Tahiti',
            official_name: 'French Polynesia',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'French_Polynesia.png',
            start_date: '1984-12-04',
            end_date: '',
          },
        },
        {
          id: 'TAH-1794-1984',
          data: {
            name: 'Tahiti',
            official_name: 'French Polynesia',
            parent_nation_id: 'TAH',
            nation_type_id: 'NATN',
            flag_filename: 'French_Polynesia_1794_1984.png',
            code: 'TAH',
            start_date: '1794-02-15',
            end_date: '1984-12-04',
          },
        },
        {
          id: 'TJK',
          data: {
            name: 'Tajikistann',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Tajikistan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TAN',
          data: {
            name: 'Tanzania',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Tanzania.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'THA',
          data: {
            name: 'Thailand',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Thailand.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TLS',
          data: {
            name: 'Timor-Leste',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Timor-Leste.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TOG',
          data: {
            name: 'Togo',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Togo.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TGA',
          data: {
            name: 'Tonga',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Tonga.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TRI',
          data: {
            name: 'Trinidad and Tobago',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Trinidad_and_Tobago.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TUN',
          data: {
            name: 'Tunisia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Tunisia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TUR',
          data: {
            name: 'Turkey',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Turkey.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TKM',
          data: {
            name: 'Turkmenistan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Turkmenistan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TCA',
          data: {
            name: 'Turks and Caicos Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Turks_and_Caicos_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '19',
      rows: [
        {
          id: 'UGA',
          data: {
            name: 'Uganda',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Uganda.png',
            start_date: '1973-07-16',
            end_date: '',
          },
        },
        {
          id: 'UGA-1914-1962',
          data: {
            name: 'Uganda',
            official_name: 'Uganda Protectorate',
            parent_nation_id: 'UGA',
            nation_type_id: 'NATN',
            flag_filename: 'Uganda_1914_1962.png',
            code: 'UGA',
            start_date: '1914-01-01',
            end_date: '1962-10-09',
          },
        },
        {
          id: 'UKR',
          data: {
            name: 'Ukraine',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Ukraine.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'UAE',
          data: {
            name: 'United Arab Emirates',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'United_Arab_Emirates.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'URU',
          data: {
            name: 'Uruguay',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Uruguay.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VIR',
          data: {
            name: 'US Virgin Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'US_Virgin_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'USA',
          data: {
            name: 'USA',
            official_name: 'United States of America',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'USA.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'UZB',
          data: {
            name: 'Uzbekistan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Uzbekistan.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '20',
      rows: [
        {
          id: 'VEN',
          data: {
            name: 'Venezuela',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Venezuela.png',
            start_date: '2006-03-12',
            end_date: '',
          },
        },
        {
          id: 'VEN-1930-1954',
          data: {
            name: 'Venezuela',
            official_name: 'Venezuela',
            parent_nation_id: 'VEN',
            nation_type_id: 'NATN',
            flag_filename: 'Venezuela_1930_1954.png',
            code: 'VEN',
            start_date: '1930-01-01',
            end_date: '1954-01-01',
          },
        },
        {
          id: 'VEN-1954-2006',
          data: {
            name: 'Venezuela',
            official_name: 'Venezuela',
            parent_nation_id: 'VEN',
            nation_type_id: 'NATN',
            flag_filename: 'Venezuela_1954_2006.png',
            code: 'VEN',
            start_date: '1954-01-01',
            end_date: '2006-03-12',
          },
        },
        {
          id: 'WAL',
          data: {
            name: 'Wales',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Wales.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'WAL-1953-1959',
          data: {
            name: 'Wales',
            official_name: 'Wales',
            parent_nation_id: 'WAL',
            nation_type_id: 'NATN',
            flag_filename: 'Wales_1953_1959.png',
            code: 'WAL',
            start_date: '1953-03-11',
            end_date: '1959-01-01',
          },
        },
        {
          id: 'YEM',
          data: {
            name: 'Yemen',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Yemen.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ZAM',
          data: {
            name: 'Zambia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Zambia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ZIM',
          data: {
            name: 'Zimbabwe',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Zimbabwe.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '100',
      rows: [
        {
          id: 'AFG',
          data: {
            name: 'Afghanistan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Afghanistan.png',
            start_date: '1973-07-16',
            end_date: '',
          },
        },
        {
          id: 'AFG-1931-1973',
          data: {
            name: 'Afghanistan',
            official_name: 'Kingdom of Afghanistan',
            parent_nation_id: 'AFG',
            nation_type_id: 'NATN',
            flag_filename: 'Afghanistan_1931_1973.png',
            start_date: '1930-03-27',
            end_date: '1973-07-16',
          },
        },
      ],
    },
  ],
}
