export const AppData = {
  collection: 'nation',
  batches: [
    {
      number: '18',
      rows: [
        {
          id: 'TAH',
          data: {
            name: 'Tahiti',
            official_name: 'French Polynesia',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_French_Polynesia_2-3.png',
            start_date: '1984-12-04',
            end_date: '',
          },
        },
        {
          id: 'TAH-1794-1984',
          data: {
            name: 'Tahiti',
            official_name: 'French Polynesia',
            parent_nation_id: 'TAH',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_France.svg.png',
            code: 'TAH',
            start_date: '1794-02-15',
            end_date: '1984-12-04',
          },
        },
        {
          id: 'TJK',
          data: {
            name: 'Tajikistan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Tajikistan_2-3.pngg',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TAN',
          data: {
            name: 'Tanzania',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Tanzania.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'THA',
          data: {
            name: 'Thailand',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Thailand.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TLS',
          data: {
            name: 'Timor-Leste',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_East_Timor_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TOG',
          data: {
            name: 'Togo',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Togo_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TGA',
          data: {
            name: 'Tonga',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Tonga_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TRI',
          data: {
            name: 'Trinidad and Tobago',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Trinidad_and_Tobago_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TUN',
          data: {
            name: 'Tunisia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Tunisia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TUR',
          data: {
            name: 'Turkey',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Turkey.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TKM',
          data: {
            name: 'Turkmenistan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Turkmenistan.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TCA',
          data: {
            name: 'Turks and Caicos Islands',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_the_Turks_and_Caicos_Islands_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TUV',
          data: {
            name: 'Tuvalu',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Tuvalu_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '19',
      rows: [
        {
          id: 'UGA',
          data: {
            name: 'Uganda',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Uganda.svg.png',
            start_date: '1973-07-16',
            end_date: '',
          },
        },
        {
          id: 'UGA-1914-1962',
          data: {
            name: 'Uganda',
            official_name: 'Uganda Protectorate',
            parent_nation_id: 'UGA',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Uganda_Protectorate_2-3.png',
            code: 'UGA',
            start_date: '1914-01-01',
            end_date: '1962-10-09',
          },
        },
        {
          id: 'UKR',
          data: {
            name: 'Ukraine',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Ukraine_(pantone_colors).svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'UAE',
          data: {
            name: 'United Arab Emirates',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_United_Arab_Emirates_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'URU',
          data: {
            name: 'Uruguay',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONMEBOL',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Uruguay.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VIR',
          data: {
            name: 'US Virgin Islands',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: '640px-Flag_of_the_United_States_Virgin_Islands.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'USA',
          data: {
            name: 'United States',
            official_name: 'United States of America',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_United_States_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'UZB',
          data: {
            name: 'Uzbekistan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Uzbekistan_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '20',
      rows: [
        {
          id: 'VAN',
          data: {
            name: 'Vanuatu',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Vanuatu_(official)_2-3.png',
            start_date: '1980-07-30',
            end_date: '',
          },
        },
        {
          id: 'VAN-1980',
          data: {
            name: 'New Hebrides',
            official_name: 'New Hebrides',
            parent_nation_id: 'VAN',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Vanuatu_(official)_2-3.png',
            code: 'HEB',
            start_date: '1980-07-30',
            end_date: '',
          },
        },
        {
          id: 'VAN-1953-1980',
          data: {
            name: 'New Hebrides',
            official_name: '',
            parent_nation_id: 'VAN',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_British_New_Hebrides_(1952–1980)_2-3.png',
            code: 'HEB',
            start_date: '1953-01-01',
            end_date: '1980-07-30',
          },
        },
        {
          id: 'VEN',
          data: {
            name: 'Venezuela',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONMEBOL',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Venezuela_(state).png',
            start_date: '2006-03-12',
            end_date: '',
          },
        },
        {
          id: 'VEN-1954-2006',
          data: {
            name: 'Venezuela',
            official_name: 'Venezuela',
            parent_nation_id: 'VEN',
            confederation_id: 'CONMEBOL',
            nation_type_id: 'NATN',
            flag_filename: '640px-State_flag_of_Venezuela_(1954–2006).svg.png',
            code: 'VEN',
            start_date: '1954-01-01',
            end_date: '2006-03-12',
          },
        },
        {
          id: 'VEN-1930-1954',
          data: {
            name: 'Venezuela',
            official_name: 'Venezuela',
            parent_nation_id: 'VEN',
            confederation_id: 'CONMEBOL',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Venezuela_(1930–2006).svg.png',
            code: 'VEN',
            start_date: '1930-01-01',
            end_date: '1954-01-01',
          },
        },
        {
          id: 'VIE',
          data: {
            name: 'Vietnam',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Vietnam.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VSO',
          data: {
            name: 'South Vietnam',
            official_name: '',
            parent_nation_id: 'VIE',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_South_Vietnam.svg.png',
            code: 'VSO',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'WAL',
          data: {
            name: 'Wales',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Wales_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'WAL-1953-1959',
          data: {
            name: 'Wales',
            official_name: 'Wales',
            parent_nation_id: 'WAL',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Wales_(1953–1959)_2-3.png',
            code: 'WAL',
            start_date: '1953-03-11',
            end_date: '1959-01-01',
          },
        },
        {
          id: 'YEM',
          data: {
            name: 'Yemen',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Yemen.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ZAM',
          data: {
            name: 'Zambia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Zambia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ZAN',
          data: {
            name: 'Zanzibar',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'TER',
            flag_filename: '640px-Flag_of_Zanzibar.svg.png',
            flag_max_width: '115%',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ZIM',
          data: {
            name: 'Zimbabwe',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Zimbabwe_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '100',
      rows: [
        {
          id: 'AFG',
          data: {
            name: 'Afghanistan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Afghanistan.png',
            start_date: '1973-07-16',
            end_date: '',
          },
        },
        {
          id: 'AFG-1931-1973',
          data: {
            name: 'Afghanistan',
            official_name: 'Kingdom of Afghanistan',
            parent_nation_id: 'AFG',
            nation_type_id: 'NATN',
            flag_filename: 'Afghanistan_1931_1973.png',
            start_date: '1930-03-27',
            end_date: '1973-07-16',
          },
        },
      ],
    },
  ],
}
