export const AppData = {
  collection: "nation",
  batches: [   
    {
      number: '5',
      rows: [
        {
          id: 'GDR',
          data: {
            name: 'East Germany',
            official_name: 'German Democratic Republic',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'gdr.png',
            start_date: '1949-10-07',
            end_date: '1990-10-03',
          },
        },
        {
          id: 'ECU',
          data: {
            name: 'Ecuador',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Ecuador.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'EGY',
          data: {
            name: 'Egypt',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Egypt.png',
            start_date: '1984-10-04',
            end_date: '',
          },
        },
        {
          id: 'EGY-1914-1922',
          data: {
            name: 'Egypt',
            official_name: 'Sultanate of Egypt',
            parent_nation_id: 'EGY',
            nation_type_id: 'NATN',
            flag_filename: 'Egypt_1882_1922.png',
            code: 'EGY',
            start_date: '1914-11-05',
            end_date: '1922-02-28',
          },
        },
        {
          id: 'EGY-1922-1953',
          data: {
            name: 'Egypt',
            official_name: 'Kingdom of Egypt',
            parent_nation_id: 'EGY',
            nation_type_id: 'NATN',
            flag_filename: 'Kingdom_of_Egypt.png',
            code: 'EGY',
            start_date: '1922-02-28',
            end_date: '1953-06-18',
          },
        },
        {
          id: 'EGY-1953-1958',
          data: {
            name: 'Egypt',
            official_name: 'Republic of Egypt',
            parent_nation_id: 'EGY',
            nation_type_id: 'NATN',
            flag_filename: 'Republic_of_Egypt.png',
            code: 'EGY',
            start_date: '1953-06-18',
            end_date: '1958-02-22',
          },
        },
        {
          id: 'EGY-1958-1971',
          data: {
            name: 'United Arab Republic',
            official_name: '',
            parent_nation_id: 'EGY',
            nation_type_id: 'NATN',
            flag_filename: 'United_Arab_Republic.png',
            code: 'UAR',
            start_date: '1958-02-22',
            end_date: '1971-09-11',
          },
        },
        {
          id: 'EGY-1972-1984',
          data: {
            name: 'Egypt',
            official_name: 'Federation of Arab Republics',
            parent_nation_id: 'EGY',
            nation_type_id: 'NATN',
            flag_filename: 'Federation_of_Arab_Republics.png',
            code: 'EGY',
            start_date: '1972-01-01',
            end_date: '1984-10-04',
          },
        },
        {
          id: 'SLV',
          data: {
            name: 'El Salvador',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'El_Salvador.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ENG',
          data: {
            name: 'England',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'England.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'EQG',
          data: {
            name: 'Equatorial Guinea',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Equatorial_Guinea.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ERI',
          data: {
            name: 'Eritrea',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Eritrea.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'EST',
          data: {
            name: 'Estonia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Estonia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ETH',
          data: {
            name: 'Ethiopia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Ethiopia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ETH-1941-1974',
          data: {
            name: 'Ethiopia',
            official_name: 'Italian Ethiopia',
            parent_nation_id: 'ETH',
            nation_type_id: 'NATN',
            flag_filename: 'Ethiopia_1941_1974.png',
            code: 'ETH',
            start_date: '1941-01-01',
            end_date: '1974-09-12',
          },
        },
        {
          id: 'ETH-1975-1987',
          data: {
            name: 'Ethiopia',
            official_name: 'Provisional Military Government of Socialist Ethiopia',
            parent_nation_id: 'ETH',
            nation_type_id: 'NATN',
            flag_filename: 'Ethiopia_1975_1987.png',
            code: 'ETH',
            start_date: '1975-03-21',
            end_date: '1987-02-22',
          },
        },
      ],
    },
    {
      number: '6',
      rows: [
        {
          id: 'FRO',
          data: {
            name: 'Faroe Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Faroe_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'FIJ',
          data: {
            name: 'Fiji',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Fiji.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'FIN',
          data: {
            name: 'Finland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Finland.png',
            start_date: '1917-12-06',
            end_date: '',
          },
        },
        {
          id: 'FIN-1809-1917',
          data: {
            name: 'Finland',
            official_name: 'Grand Duchy of Finland',
            parent_nation_id: 'FIN',
            nation_type_id: 'NATN',
            flag_filename: 'Grand_Duchy_of_Finland.png',
            code: 'FIN',
            start_date: '1809-03-29',
            end_date: '1917-12-06',
          },
        },
        {
          id: 'FRA',
          data: {
            name: 'France',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'France.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUF',
          data: {
            name: 'French Guiana',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'French_Guiana.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MKD',
          data: {
            name: 'FYR Macedonia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'FYR_Macedonia.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '7',
      rows: [
        {
          id: 'GAB',
          data: {
            name: 'Gabon',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Gabon.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GAM',
          data: {
            name: 'Gambia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Gambia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GEO',
          data: {
            name: 'Georgia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Georgia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GER',
          data: {
            name: 'Germany',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Germany.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GER-1866-1918',
          data: {
            name: 'Germany',
            official_name: 'German Empire',
            parent_nation_id: 'GER',
            nation_type_id: 'NATN',
            flag_filename: 'German_Empire.png',
            code: 'GER',
            start_date: '1866-01-01',
            end_date: '1918-11-11',
          },
        },
        {
          id: 'GER-1918-1933',
          data: {
            name: 'Germany',
            official_name: 'Weimar Republic',
            parent_nation_id: 'GER',
            nation_type_id: 'NATN',
            flag_filename: 'Germany.png',
            code: 'GER',
            start_date: '1918-11-11',
            end_date: '1933-01-30',
          },
        },
        {
          id: 'GER-1933-1935',
          data: {
            name: 'Germany',
            official_name: 'Germany',
            parent_nation_id: 'GER',
            nation_type_id: 'NATN',
            flag_filename: 'Germany_1933_1935.png',
            code: 'GER',
            start_date: '1933-01-30',
            end_date: '1935-09-15',
          },
        },
        {
          id: 'GER-1935-1945',
          data: {
            name: 'Germany',
            official_name: 'Germany',
            parent_nation_id: 'GER',
            nation_type_id: 'NATN',
            flag_filename: 'Germany_1935_1945.png',
            code: 'GER',
            start_date: '1935-09-15',
            end_date: '1945-05-08',
          },
        },
        {
          id: 'GER-1956-1968',
          data: {
            name: 'Germany',
            official_name: 'Germany',
            parent_nation_id: 'GER',
            nation_type_id: 'NATN',
            flag_filename: 'German_Olympic_1956_1968.png',
            code: 'GER',
            start_date: '1956-01-01',
            end_date: '1968-01-01',
          },
        },
        {
          id: 'GER-1949-1990',
          data: {
            name: 'West Germany',
            official_name: 'Federal Republic of Germany',
            parent_nation_id: 'GER',
            nation_type_id: 'NATN',
            flag_filename: 'Germany.png',
            code: 'FRG',
            start_date: '1949-05-23',
            end_date: '1990-10-03',
          },
        },
        {
          id: 'GHA',
          data: {
            name: 'Ghana',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Ghana.png',
            start_date: '1966-02-24',
            end_date: '',
          },
        },
        {
          id: 'GHA-1964-1966',
          data: {
            name: 'Ghana',
            official_name: 'Ghana',
            parent_nation_id: 'GHA',
            nation_type_id: 'NATN',
            flag_filename: 'Ghana_1964_1966.png',
            code: 'GHA',
            start_date: '1964-01-01',
            end_date: '1966-02-24',
          },
        },
        {
          id: 'GIB',
          data: {
            name: 'Gibraltar',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Gibraltar.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GBR',
          data: {
            name: 'Great Britain',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Great_Britain.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GRE',
          data: {
            name: 'Greece',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Greece.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GRN',
          data: {
            name: 'Grenada',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Grenada.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GLP',
          data: {
            name: 'Guadeloupe',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Guadeloupe.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUM',
          data: {
            name: 'Guam',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Guam.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUA',
          data: {
            name: 'Guatemala',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Guatemala.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUI',
          data: {
            name: 'Guinea',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Guinea.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GNB',
          data: {
            name: 'Guinea-Bissau',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Guinea_Bissau.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'GUY',
          data: {
            name: 'Guyana',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Guyana.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '8',
      rows: [
        {
          id: 'HAI',
          data: {
            name: 'Haiti',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Haiti.png',
            start_date: '1986-02-26',
            end_date: '',
          },
        },
        {
          id: 'HAI-1964-1986',
          data: {
            name: 'Haiti',
            official_name: 'Haiti',
            parent_nation_id: 'HAI',
            nation_type_id: 'NATN',
            flag_filename: 'Haiti_1964_1986.png',
            code: 'HAI',
            start_date: '1964-01-01',
            end_date: '1986-02-26',
          },
        },
        {
          id: 'HON',
          data: {
            name: 'Honduras',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Honduras.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'HKG',
          data: {
            name: 'Hong Kong',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Hong_Kong.png',
            start_date: '1997-07-01',
            end_date: '',
          },
        },
        {
          id: 'HKG-1955-1959',
          data: {
            name: 'Hong Kong',
            official_name: 'Hong Kong',
            parent_nation_id: 'HKG',
            nation_type_id: 'TER',
            flag_filename: 'Hong_Kong_1955_1959.png',
            code: 'HKG',
            start_date: '1955-01-01',
            end_date: '1959-01-01',
          },
        },
        {
          id: 'HKG-1959-1997',
          data: {
            name: 'Hong Kong',
            official_name: 'Hong Kong',
            parent_nation_id: 'HKG',
            nation_type_id: 'TER',
            flag_filename: 'Hong_Kong_1959_1997.png',
            code: 'HKG',
            start_date: '1959-01-01',
            end_date: '1997-01-01',
          },
        },
        {
          id: 'HUN',
          data: {
            name: 'Hungary',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Hungary.png',
            start_date: '1989-10-23',
            end_date: '',
          },
        },
        {
          id: 'HUN-1915-1918',
          data: {
            name: 'Hungary',
            official_name: 'Lands of the Crown of Saint Stephen',
            parent_nation_id: 'HUN',
            nation_type_id: 'NATN',
            flag_filename: 'Hungary_1915_1918.png',
            code: 'HUN',
            start_date: '1867-03-30',
            end_date: '1918-11-16',
          },
        },
        {
          id: 'HUN-1920-1946',
          data: {
            name: 'Hungary',
            official_name: 'Kingdom of Hungary',
            parent_nation_id: 'HUN',
            nation_type_id: 'NATN',
            flag_filename: 'Kingdom_of_Hungary.png',
            code: 'HUN',
            start_date: '1920-02-29',
            end_date: '1946-02-01',
          },
        },
        {
          id: 'HUN-1946-1949',
          data: {
            name: 'Hungary',
            official_name: 'Second Hungarian Republic',
            parent_nation_id: 'HUN',
            nation_type_id: 'NATN',
            flag_filename: 'Second_Hungarian_Republic.png',
            code: 'HUN',
            start_date: '1946-02-01',
            end_date: '1949-08-20',
          },
        },
        {
          id: 'HUN-1949-1956',
          data: {
            name: 'Hungary',
            official_name: 'Hungarian People\'s Republic',
            parent_nation_id: 'HUN',
            nation_type_id: 'NATN',
            flag_filename: 'Hungarian_People_Republic.png',
            code: 'HUN',
            start_date: '1949-08-20',
            end_date: '1956-10-23',
          },
        },
        {
          id: 'HUN-1957-1989',
          data: {
            name: 'Hungary',
            official_name: 'Hungarian People\'s Republic',
            parent_nation_id: 'HUN',
            nation_type_id: 'NATN',
            flag_filename: 'Hungary.png',
            code: 'HUN',
            start_date: '1957-05-23',
            end_date: '1989-10-23',
          },
        },
      ],
    },
    {
      number: '9',
      rows: [
        {
          id: 'ISL',
          data: {
            name: 'Iceland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Iceland.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'IND',
          data: {
            name: 'India',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'India.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'IDN',
          data: {
            name: 'Indonesia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Indonesia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'IRN',
          data: {
            name: 'Iran',
            official_name: 'Islamic Republic of Iran',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Iran.png',
            start_date: '1980-01-01',
            end_date: '',
          },
        },
        {
          id: 'IRN-1964-1980',
          data: {
            name: 'Iran',
            official_name: 'Iran',
            parent_nation_id: 'IRN',
            nation_type_id: 'NATN',
            flag_filename: 'Iran_1964_1980.png',
            code: 'IRN',
            start_date: '1964-01-01',
            end_date: '1980-01-01',
          },
        },
        {
          id: 'IRQ',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Iraq.png',
            start_date: '2008-01-22',
            end_date: '',
          },
        },
        {
          id: 'IRQ-1921-1959',
          data: {
            name: 'Iraq',
            official_name: 'Kingdom of Iraq',
            parent_nation_id: 'IRQ',
            nation_type_id: 'NATN',
            flag_filename: 'Kingdom_of_Iraq.png',
            code: 'IRQ',
            start_date: '1921-04-23',
            end_date: '1959-01-11',
          },
        },
        {
          id: 'IRQ-1959-1963',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: 'IRQ',
            nation_type_id: 'NATN',
            flag_filename: 'Iraq_1959_1963.png',
            code: 'IRQ',
            start_date: '1959-01-11',
            end_date: '1963-10-31',
          },
        },
        {
          id: 'IRQ-1963-1991',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: 'IRQ',
            nation_type_id: 'NATN',
            flag_filename: 'Iraq_1963_1991.png',
            code: 'IRQ',
            start_date: '1963-10-31',
            end_date: '1991-04-01',
          },
        },
        {
          id: 'IRQ-1991-2004',
          data: {
            name: 'Iraq',
            official_name: '',
            parent_nation_id: 'IRQ',
            nation_type_id: 'NATN',
            flag_filename: 'Iraq_1991_2004.png',
            code: 'IRQ',
            start_date: '1991-04-01',
            end_date: '2004-08-05',
          },
        },
        {
          id: 'IRQ-2004-2008',
          data: {
            name: 'Iraq',
            official_name: 'Iraq',
            parent_nation_id: 'IRQ',
            nation_type_id: 'NATN',
            flag_filename: 'Iraq_2004_2008.png',
            code: 'IRQ',
            start_date: '2004-08-05',
            end_date: '2008-01-22',
          },
        },
        {
          id: 'ISR',
          data: {
            name: 'Israel',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Israel.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ITA',
          data: {
            name: 'Italy',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Italy.png',
            start_date: '1946-06-02',
            end_date: '',
          },
        },
        {
          id: 'ITA-1861-1946',
          data: {
            name: 'Italy',
            official_name: 'Kingdom of Italy',
            parent_nation_id: 'ITA',
            nation_type_id: 'NATN',
            flag_filename: 'Kingdom_of_Italy.png',
            code: 'ITA',
            start_date: '1861-03-17',
            end_date: '1946-06-02',
          },
        },
        {
          id: 'CIV',
          data: {
            name: 'Ivory Coast',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Ivory_Coast.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '10',
      rows: [
        {
          id: 'JAM',
          data: {
            name: 'Jamaica',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Jamaica.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'JPN',
          data: {
            name: 'Japan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Japan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'JOR',
          data: {
            name: 'Jordan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Jordan.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '11',
      rows: [
        {
          id: 'KAZ',
          data: {
            name: 'Kazakhstan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Kazakhstan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KEN',
          data: {
            name: 'Kenya',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Kenya.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PRK',
          data: {
            name: 'Korea DPR',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Korea_DPR.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KOR',
          data: {
            name: 'Korea Republic',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Korea_Republic.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KVX',
          data: {
            name: 'Kosovo',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Kosovo.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KUW',
          data: {
            name: 'Kuwait',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Kuwait.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KGZ',
          data: {
            name: 'Kyrgyzstan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Kyrgyz_Republic.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
  ]
};
