export const AppData = {
  collection: 'nation',
  batches: [
    {
      number: '1',
      rows: [
        {
          id: 'AFG',
          data: {
            name: 'Afghanistan',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Afghanistan_(2013–2021).svg.png',
            start_date: '2013-08-19',
            end_date: '2021-08-15',
          },
        },
        {
          id: 'AFG-1931-1973',
          data: {
            name: 'Afghanistan',
            official_name: 'Kingdom of Afghanistan',
            parent_nation: { id: 'AFG' },
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Afghanistan_(1931–1973).svg.png',
            code: 'AFG',
            start_date: '1930-03-27',
            end_date: '1973-07-16',
          },
        },
        {
          id: 'ALB',
          data: {
            name: 'Albania',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Albania_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ALG',
          data: {
            name: 'Algeria',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Algeria.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ASA',
          data: {
            name: 'American Samoa',
            official_name: '',
            confederation: { id: 'OFC' },
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_American_Samoa_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AND',
          data: {
            name: 'Andorra',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Andorra_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ANG',
          data: {
            name: 'Angola',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Angola.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AIA',
          data: {
            name: 'Anguilla',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_Anguilla_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ATG',
          data: {
            name: 'Antigua and Barbuda',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Antigua_and_Barbuda.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ARG',
          data: {
            name: 'Argentina',
            official_name: '',
            confederation: { id: 'CONMEBOL' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Argentina_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ARM',
          data: {
            name: 'Armenia',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Armenia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ARU',
          data: {
            name: 'Aruba',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Aruba.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AUS',
          data: {
            name: 'Australia',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Australia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AUT',
          data: {
            name: 'Austria',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Austria.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'AUT-1918',
          data: {
            name: 'Austria',
            official_name: 'Habsburg Monarchy',
            parent_nation: { id: 'AUT' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Habsburg_Monarchy.svg.png',
            code: 'AUT',
            start_date: '',
            end_date: '1918-01-01',
          },
        },
        {
          id: 'AZE',
          data: {
            name: 'Azerbaijan',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Azerbaijan_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '2',
      rows: [
        {
          id: 'BAH',
          data: {
            name: 'Bahamas',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Bahamas_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BHR',
          data: {
            name: 'Bahrain',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bahrain_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BAN',
          data: {
            name: 'Bangladesh',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bangladesh_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BRB',
          data: {
            name: 'Barbados',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Barbados.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BLR',
          data: {
            name: 'Belarus',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Belarus_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BEL',
          data: {
            name: 'Belgium',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Belgium_(civil).svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BLZ',
          data: {
            name: 'Belize',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Belize_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BEN',
          data: {
            name: 'Benin',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Benin.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BER',
          data: {
            name: 'Bermuda',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bermuda_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BHU',
          data: {
            name: 'Bhutan',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Bhutan.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BOL',
          data: {
            name: 'Bolivia',
            official_name: '',
            confederation: { id: 'CONMEBOL' },
            nation_type_id: 'NATN',
            flag_filename: 'Bandera_de_Bolivia_(Estado)_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BOE',
          data: {
            name: 'Bonaire',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_Bonaire_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BIH',
          data: {
            name: 'Bosnia and Herzegovina',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bosnia_and_Herzegovina_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BOT',
          data: {
            name: 'Botswana',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Botswana.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BRA',
          data: {
            name: 'Brazil',
            official_name: '',
            confederation: { id: 'CONMEBOL' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Brazil_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VGB',
          data: {
            name: 'British Virgin Islands',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_the_British_Virgin_Islands_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BRU',
          data: {
            name: 'Brunei Darussalam',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Brunei_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BUL',
          data: {
            name: 'Bulgaria',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bulgaria_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'BUL-1971-1990',
          data: {
            name: 'Bulgaria',
            official_name: "People's Republic of Bulgaria",
            parent_nation: { id: 'BUL' },
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: "Flag_of_People's_Republic_of_Bulgaria_2-3.png",
            code: 'BUL',
            start_date: '1971-05-21',
            end_date: '1990-11-15',
          },
        },
        {
          id: 'BUL-1967-1971',
          data: {
            name: 'Bulgaria',
            official_name: "People's Republic of Bulgaria",
            parent_nation: { id: 'BUL' },
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bulgaria_(1967-1971)_2-3.png',
            code: 'BUL',
            start_date: '1967-06-14',
            end_date: '1971-05-21',
          },
        },
        {
          id: 'BUL-1948-1967',
          data: {
            name: 'Bulgaria',
            official_name: "People's Republic of Bulgaria",
            parent_nation: { id: 'BUL' },
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bulgaria_(1948-1967)_2-3.png',
            code: 'BUL',
            start_date: '1948-01-27',
            end_date: '1967-06-14',
          },
        },
        {
          id: 'BUL-1946-1948',
          data: {
            name: 'Bulgaria',
            official_name: "People's Republic of Bulgaria",
            parent_nation: { id: 'BUL' },
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Bulgaria_(1946-1948)_2-3.png',
            code: 'BUL',
            start_date: '1946-09-15',
            end_date: '1948-01-27',
          },
        },
        {
          id: 'BFA',
          data: {
            name: 'Burkina Faso',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Burkina_Faso.svg.png',
            start_date: '1984-08-04',
            end_date: '',
          },
        },
        {
          id: 'UPV',
          data: {
            name: 'Upper Volta',
            official_name: '',
            parent_nation: { id: 'BFA' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Upper_Volta.svg.png',
            code: 'UPV',
            start_date: '',
            end_date: '1984-08-04',
          },
        },
        {
          id: 'BDI',
          data: {
            name: 'Burundi',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Burundi_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '3',
      rows: [
        {
          id: 'CAM',
          data: {
            name: 'Cambodia',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Cambodia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CAM-1970-1975',
          data: {
            name: 'Khmer Republic',
            official_name: '',
            parent_nation: { id: 'CAM' },
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Khmer_Republic.svg.png',
            start_date: '1970-01-01',
            end_date: '1975-01-01',
          },
        },
        {
          id: 'CMR',
          data: {
            name: 'Cameroon',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Cameroon.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CMR-1961-1975',
          data: {
            name: 'Cameroon',
            official_name: 'Federal Republic of Cameroon',
            parent_nation: { id: 'CMR' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Cameroon_(1961-1975).svg.png',
            code: 'CMR',
            start_date: '1961-10-01',
            end_date: '1975-05-20',
          },
        },
        {
          id: 'CAN',
          data: {
            name: 'Canada',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Canada_(Pantone)_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CPV',
          data: {
            name: 'Cape Verde',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Cape_Verde_(2-3_ratio).svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CAY',
          data: {
            name: 'Cayman Islands',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_the_Cayman_Islands_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CTA',
          data: {
            name: 'Central African Republic',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Central_African_Republic.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CHA',
          data: {
            name: 'Chad',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Chad.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CHI',
          data: {
            name: 'Chile',
            official_name: '',
            confederation: { id: 'CONMEBOL' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Chile.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CHN',
          data: {
            name: 'China PR',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: "640px-Flag_of_the_People's_Republic_of_China.svg.png",
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'TPE',
          data: {
            name: 'Chinese Taipei',
            official_name: '',
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Chinese_Taipei_for_Olympic_games.svg.png',
            start_date: '2006-01-01',
            end_date: '',
          },
        },
        {
          id: 'TPE-1979-2006',
          data: {
            name: 'Chinese Taipei',
            official_name: 'Chinese Taipei',
            parent_nation: { id: 'TPE' },
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Former_Chinese_Taipei_Football_Flag.svg.png',
            code: 'TPE',
            start_date: '1979-01-01',
            end_date: '2006-01-01',
          },
        },
        {
          id: 'TPE-1960-1979',
          data: {
            name: 'Republic of China',
            official_name: '',
            parent_nation: { id: 'TPE' },
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Republic_of_China.svg.png',
            code: 'ROC',
            start_date: '1960-01-01',
            end_date: '1979-01-01',
          },
        },
        {
          id: 'TPE-1960',
          data: {
            name: 'Formosa',
            official_name: 'Republic of China',
            parent_nation: { id: 'TPE' },
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Republic_of_China.svg.png',
            code: 'ROC',
            start_date: '1960-01-01',
            end_date: '1960-01-01',
          },
        },
        {
          id: 'TPE-1949-1960',
          data: {
            name: 'Taiwan',
            official_name: 'Taiwan',
            parent_nation: { id: 'TPE' },
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Republic_of_China.svg.png',
            code: 'TAI',
            start_date: '1949-01-01',
            end_date: '1960-01-01',
          },
        },
        {
          id: 'TPE-1924-1949',
          data: {
            name: 'China',
            official_name: 'China',
            parent_nation: { id: 'TPE' },
            confederation: { id: 'AFC' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Republic_of_China.svg.png',
            code: 'CHN',
            start_date: '1924-01-01',
            end_date: '1949-01-01',
          },
        },
        {
          id: 'COL',
          data: {
            name: 'Colombia',
            official_name: '',
            confederation: { id: 'CONMEBOL' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Colombia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'COM',
          data: {
            name: 'Comoros',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Comoros_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CGO',
          data: {
            name: 'Congo',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Republic_of_the_Congo.svg.png',
            start_date: '1991-06-09',
            end_date: '',
          },
        },
        {
          id: 'CGO-1970-1991',
          data: {
            name: 'Congo',
            official_name: "People's Republic of the Congo",
            parent_nation: { id: 'CGO' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: "640px-Flag_of_the_People's_Republic_of_the_Congo.svg.png",
            code: 'CGO',
            start_date: '1970-01-02',
            end_date: '1991-06-09',
          },
        },
        {
          id: 'CGO-1959-1970',
          data: {
            name: 'Congo-Brazzaville',
            official_name: '',
            parent_nation: { id: 'CGO' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Republic_of_the_Congo.svg.png',
            code: 'CGO',
            start_date: '1959-09-15',
            end_date: '1970-01-02',
          },
        },
        {
          id: 'COD',
          data: {
            name: 'Congo DR',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Democratic_Republic_of_the_Congo_2-3.png',
            start_date: '2006-02-18',
            end_date: '',
          },
        },
        {
          id: 'COD-2003-2006',
          data: {
            name: 'Congo DR',
            official_name: 'Democratic Republic of the Congo',
            parent_nation: { id: 'COD' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Democratic_Republic_of_the_Congo_(2003–2006).svg.png',
            code: 'COD',
            start_date: '2003-01-01',
            end_date: '2006-02-18',
          },
        },
        {
          id: 'COD-1997-2003',
          data: {
            name: 'Congo DR',
            official_name: 'Democratic Republic of the Congo',
            parent_nation: { id: 'COD' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Democratic_Republic_of_the_Congo_(1997–2003).svg.png',
            code: 'COD',
            start_date: '1997-05-17',
            end_date: '2003-01-01',
          },
        },
        {
          id: 'ZAI',
          data: {
            name: 'Zaire',
            official_name: '',
            parent_nation: { id: 'COD' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Zaire_(1971–1997).svg.png',
            code: 'ZAI',
            start_date: '1971-10-27',
            end_date: '1997-05-17',
          },
        },
        {
          id: 'COD-1966-1971',
          data: {
            name: 'Congo-Kinshasa',
            official_name: 'Congo-Kinshasa',
            parent_nation: { id: 'COD' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Democratic_Republic_of_the_Congo_(1966–1971).svg.png',
            code: 'COD',
            start_date: '1966-06-01',
            end_date: '1971-10-27',
          },
        },
        {
          id: 'COD-1964-1966',
          data: {
            name: 'Congo-Léopoldville',
            official_name: 'Congo-Léopoldville',
            parent_nation: { id: 'COD' },
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Democratic_Republic_of_the_Congo_(1964–1966).svg.png',
            code: 'COD',
            start_date: '1964-08-01',
            end_date: '1966-06-01',
          },
        },
        {
          id: 'COK',
          data: {
            name: 'Cook Islands',
            official_name: '',
            confederation: { id: 'OFC' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Cook_Islands_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CRC',
          data: {
            name: 'Costa Rica',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Costa_Rica_(state)_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CRC-1964-1998',
          data: {
            name: 'Costa Rica',
            official_name: 'Costa Rica',
            parent_nation: { id: 'CRC' },
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'State_Flag_of_Costa_Rica_(1964-1998)_2-3.png',
            code: 'CRC',
            start_date: '1964-01-01',
            end_date: '1998-01-01',
          },
        },
        {
          id: 'CRO',
          data: {
            name: 'Croatia',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Croatia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CUB',
          data: {
            name: 'Cuba',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Cuba_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CUW',
          data: {
            name: 'Curaçao',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Curacao.svg.png',
            start_date: '2010-10-10',
            end_date: '',
          },
        },
        {
          id: 'ANT',
          data: {
            name: 'Netherlands Antilles',
            official_name: '',
            parent_nation: { id: 'CUW' },
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Netherlands_Antilles_(1986–2010).svg.png',
            code: 'ANT',
            start_date: '1986-01-01',
            end_date: '2010-01-01',
          },
        },
        {
          id: 'ANT-1959-1986',
          data: {
            name: 'Netherlands Antilles',
            official_name: 'Netherlands Antilles',
            parent_nation: { id: 'CUW' },
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Netherlands_Antilles_(1959–1986).svg.png',
            code: 'ANT',
            start_date: '1959-01-01',
            end_date: '1986-01-01',
          },
        },
        {
          id: 'CYP',
          data: {
            name: 'Cyprus',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Cyprus.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CZE',
          data: {
            name: 'Czech Republic',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Czech_Republic.svg.png',
            start_date: '1993-01-01',
            end_date: '',
          },
        },
        {
          id: 'TCH',
          data: {
            name: 'Czechoslovakia',
            official_name: '',
            parent_nation: { id: 'CZE' },
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Czech_Republic.svg.png',
            code: 'TCH',
            start_date: '1918-10-01',
            end_date: '1993-01-01',
          },
        },
        {
          id: 'BOH',
          data: {
            name: 'Bohemia',
            official_name: '',
            parent_nation: { id: 'CZE' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Bohemia.svg.png',
            code: 'BOH',
            start_date: '1903-04-05',
            end_date: '1918-10-01',
          },
        },
      ],
    },
    {
      number: '4',
      rows: [
        {
          id: 'DEN',
          data: {
            name: 'Denmark',
            official_name: '',
            confederation: { id: 'UEFA' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Denmark_2-3.png',
            flag_max_width: '105%',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'DJI',
          data: {
            name: 'Djibouti',
            official_name: '',
            confederation: { id: 'CAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Djibouti.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'DMA',
          data: {
            name: 'Dominica',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Dominica_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'DOM',
          data: {
            name: 'Dominican Republic',
            official_name: '',
            confederation: { id: 'CONCACAF' },
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Dominican_Republic.svg.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
  ],
}
