export const AppData = {
  collection: "nation",
  batches: [
    {
      number: '12',
      rows: [
        {
          id: 'LAO',
          data: {
            name: 'Laos',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Laos.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LVA',
          data: {
            name: 'Latvia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Latvia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LIB',
          data: {
            name: 'Lebanon',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Lebanon.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LES',
          data: {
            name: 'Lesotho',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Lesotho.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LBR',
          data: {
            name: 'Liberia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Liberia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LBY',
          data: {
            name: 'Libya',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Libya.png',
            start_date: '2011-02-17',
            end_date: '',
          },
        },
        {
          id: 'LBY-1977-2011',
          data: {
            name: 'Libya',
            official_name: 'Great Socialist People\'s Libyan Arab Jamahiriya',
            parent_nation_id: 'LBY',
            nation_type_id: 'NATN',
            flag_filename: 'Libya_1977_2011.png',
            code: 'LBY',
            start_date: '1977-11-11',
            end_date: '2011-02-17',
          },
        },
        {
          id: 'LIE',
          data: {
            name: 'Liechtenstein',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Liechtenstein.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LTU',
          data: {
            name: 'Lithuania',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Lithuania.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LUX',
          data: {
            name: 'Luxembourg',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Luxembourg.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '13',
      rows: [
        {
          id: 'MAC',
          data: {
            name: 'Macau',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Macau.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MAD',
          data: {
            name: 'Madagascar',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Madagascar.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MWI',
          data: {
            name: 'Malawi',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Malawi.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MAS',
          data: {
            name: 'Malaysia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Malaysia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MDV',
          data: {
            name: 'Maldives',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Maldives.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MLI',
          data: {
            name: 'Mali',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Mali.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MLT',
          data: {
            name: 'Malta',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Malta.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MTQ',
          data: {
            name: 'Martinique',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Martinique.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MTN',
          data: {
            name: 'Mauritania',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Mauritania.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MRI',
          data: {
            name: 'Mauritius',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Mauritius.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MEX',
          data: {
            name: 'Mexico',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Mexico.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MDA',
          data: {
            name: 'Moldova',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Moldova.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MNG',
          data: {
            name: 'Mongolia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Mongolia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MNE',
          data: {
            name: 'Montenegro',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Montenegro.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MSR',
          data: {
            name: 'Montserrat',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'Montserrat.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MAR',
          data: {
            name: 'Morocco',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Morocco.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MOZ',
          data: {
            name: 'Mozambique',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Mozambique.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MYA',
          data: {
            name: 'Myanmar',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Myanmar.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '14',
      rows: [
        {
          id: 'NAM',
          data: {
            name: 'Namibia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Namibia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NEP',
          data: {
            name: 'Nepal',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Nepal.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NED',
          data: {
            name: 'Netherlands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Netherlands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CUW-1959-1986',
          data: {
            name: 'Netherlands Antilles',
            official_name: 'Netherlands Antilles',
            parent_nation_id: 'CUW',
            nation_type_id: 'NATN',
            flag_filename: 'Netherlands_Antilles_1959_1986.png',
            code: 'ANT',
            start_date: '1959-01-01',
            end_date: '1986-01-01',
          },
        },
        {
          id: 'CUW-1986-2010',
          data: {
            name: 'Netherlands_Antilles',
            official_name: '',
            parent_nation_id: 'CUW',
            nation_type_id: 'NATN',
            flag_filename: 'Netherlands_Antilles.png',
            code: 'ANT',
            start_date: '1986-01-01',
            end_date: '2010-01-01',
          },
        },
        {
          id: 'NCL',
          data: {
            name: 'New Caledonia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'TER',
            flag_filename: 'New_Caledonia.png',
            start_date: '2008-01-01',
            end_date: '',
          },
        },
        {
          id: 'NCL-1973-2008',
          data: {
            name: 'New Caledonia',
            official_name: 'New Caledonia',
            parent_nation_id: 'NCL',
            nation_type_id: 'TER',
            flag_filename: 'France.png',
            code: 'NCL',
            start_date: '1973-01-01',
            end_date: '2008-01-01',
          },
        },
        {
          id: 'VAN',
          data: {
            name: 'Vanuatu',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Vanuatu.png',
            start_date: '1980-07-30',
            end_date: '',
          },
        },
        {
          id: 'VAN-1953-1980',
          data: {
            name: 'New Hebrides',
            official_name: '',
            parent_nation_id: 'VAN',
            nation_type_id: 'NATN',
            flag_filename: 'New_Hebrides.png',
            code: 'HEB',
            start_date: '1953-01-01',
            end_date: '1980-07-30',
          },
        },
        {
          id: 'VAN-1980',
          data: {
            name: 'New Hebrides',
            official_name: 'New Hebrides',
            parent_nation_id: 'VAN',
            nation_type_id: 'NATN',
            flag_filename: 'Vanuatu.png',
            code: 'HEB',
            start_date: '1980-07-30',
            end_date: '',
          },
        },
        {
          id: 'NZL',
          data: {
            name: 'New Zealand',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'New_Zealand.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NCA',
          data: {
            name: 'Nicaragua',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Nicaragua.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NIG',
          data: {
            name: 'Niger',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Niger.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NGA',
          data: {
            name: 'Nigeria',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Nigeria.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NIR',
          data: {
            name: 'Northern Ireland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Northern_Ireland.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NOR',
          data: {
            name: 'Norway',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Norway.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'OMA',
          data: {
            name: 'Oman',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Oman.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '15',
      rows: [
        {
          id: 'PAK',
          data: {
            name: 'Pakistan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Pakistan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PLE',
          data: {
            name: 'Palestine',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Palestine.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PAN',
          data: {
            name: 'Panama',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Panama.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PNG',
          data: {
            name: 'Papua New Guinea',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Papua_New_Guinea.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PAR',
          data: {
            name: 'Paraguay',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Paraguay.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PER',
          data: {
            name: 'Peru',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Peru.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PHI',
          data: {
            name: 'Philippines',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Philippines.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'POL',
          data: {
            name: 'Poland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Poland.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'POR',
          data: {
            name: 'Portugal',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Portugal.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PUR',
          data: {
            name: 'Puerto Rico',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Puerto_Rico.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'QAT',
          data: {
            name: 'Qatar',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Qatar.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '16',
      rows: [
        {
          id: 'IRL',
          data: {
            name: 'Republic of Ireland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Republic_of_Ireland.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ROU',
          data: {
            name: 'Romania',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Romania.png',
            start_date: '1989-12-22',
            end_date: '',
          },
        },
        {
          id: 'ROU-1947-1948',
          data: {
            name: 'Romania',
            official_name: 'Romanian People\'s Republic',
            parent_nation_id: 'ROU',
            nation_type_id: 'NATN',
            flag_filename: 'Romania_1947_1948.png',
            code: 'ROU',
            start_date: '1947-12-30',
            end_date: '1948-04-13',
          },
        },
        {
          id: 'ROU-1948-1952',
          data: {
            name: 'Romania',
            official_name: 'Romanian People\'s Republic',
            parent_nation_id: 'ROU',
            nation_type_id: 'NATN',
            flag_filename: 'Romania_1948_1952.png',
            code: 'ROU',
            start_date: '1948-04-13',
            end_date: '1952-09-24',
          },
        },
        {
          id: 'ROU-1952-1965',
          data: {
            name: 'Romania',
            official_name: 'Romanian People\'s Republic',
            parent_nation_id: 'ROU',
            nation_type_id: 'NATN',
            flag_filename: 'Romania_1952_1965.png',
            code: 'ROU',
            start_date: '1952-09-24',
            end_date: '1965-08-21',
          },
        },
        {
          id: 'ROU-1965-1989',
          data: {
            name: 'Romania',
            official_name: 'Socialist Republic of Romania',
            parent_nation_id: 'ROU',
            nation_type_id: 'NATN',
            flag_filename: 'Romania_1965_1989.png',
            code: 'ROU',
            start_date: '1965-08-21',
            end_date: '1989-12-22',
          },
        },
        {
          id: 'RWA',
          data: {
            name: 'Rwanda',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Rwanda.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '17',
      rows: [
        {
          id: 'SAM',
          data: {
            name: 'Samoa',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Samoa.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SMR',
          data: {
            name: 'San Marino',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'San_Marino.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'STP',
          data: {
            name: 'São Tomé e Príncipe',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'São_Tomé_e_Príncipe.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KSA',
          data: {
            name: 'Saudi Arabia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Saudi_Arabia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SCO',
          data: {
            name: 'Scotland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Scotland.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SEN',
          data: {
            name: 'Senegal',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Senegal.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SRB',
          data: {
            name: 'Serbia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Serbia.png',
            start_date: '2006-06-05',
            end_date: '',
          },
        },
        {
          id: 'SRB-2003-2006',
          data: {
            name: 'Serbia and Montenegro',
            official_name: 'State Union of Serbia and Montenegro',
            parent_nation_id: 'SRB',
            nation_type_id: 'NATN',
            flag_filename: 'Serbia_and_Montenegro.svg',
            code: 'SCG',
            start_date: '2003-02-04',
            end_date: '2006-06-03',
          },
        },
        {
          id: 'YUG',
          data: {
            name: 'Yugoslavia',
            official_name: 'Federal Republic of Yugoslavia',
            parent_nation_id: 'SRB',
            nation_type_id: 'NATN',
            flag_filename: 'Serbia_and_Montenegro.svg',
            code: 'YUG',
            start_date: '1992-04-27',
            end_date: '2003-02-04',
          },
        },
        {
          id: 'YUG-1918-1929',
          data: {
            name: 'Yugoslavia',
            official_name: 'Kingdom of Serbs, Croats and Slovenes',
            parent_nation_id: 'SRB',
            nation_type_id: 'NATN',
            flag_filename: 'Kingdom_of_Yugoslavia.png',
            code: 'YUG',
            start_date: '1918-01-01',
            end_date: '1929-10-03',
          },
        },
        {
          id: 'YUG-1929-1943',
          data: {
            name: 'Yugoslavia',
            official_name: 'Kingdom of Yugoslavia',
            parent_nation_id: 'SRB',
            nation_type_id: 'NATN',
            flag_filename: 'Kingdom_of_Yugoslavia.png',
            code: 'YUG',
            start_date: '1929-10-03',
            end_date: '1943-11-29',
          },
        },
        {
          id: 'YUG-1943-1945',
          data: {
            name: 'Yugoslavia',
            official_name: 'Democratic Federal Yugoslavia',
            parent_nation_id: 'SRB',
            nation_type_id: 'NATN',
            flag_filename: 'yug.png',
            code: 'YUG',
            start_date: '1943-11-29',
            end_date: '1945-11-29',
          },
        },
        {
          id: 'YUG-1945-1963',
          data: {
            name: 'Yugoslavia',
            official_name: 'Federal People\'s Republic of Yugoslavia',
            parent_nation_id: 'SRB',
            nation_type_id: 'NATN',
            flag_filename: 'yug.png',
            code: 'YUG',
            start_date: '1945-11-29',
            end_date: '1963-04-07',
          },
        },
        {
          id: 'YUG-1945-1992',
          data: {
            name: 'Yugoslavia',
            official_name: 'Socialist Federal Republic of Yugoslavia',
            parent_nation_id: 'SRB',
            nation_type_id: 'NATN',
            flag_filename: 'yug.png',
            code: 'YUG',
            start_date: '1945-11-29',
            end_date: '1992-04-27',
          },
        },
        {
          id: 'SEY',
          data: {
            name: 'Seychelles',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Seychelles.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SLE',
          data: {
            name: 'Sierra Leone',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Sierra_Leone.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SIN',
          data: {
            name: 'Singapore',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Singapore.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SVK',
          data: {
            name: 'Slovakia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Slovakia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SVN',
          data: {
            name: 'Slovenia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Slovenia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SOL',
          data: {
            name: 'Solomon Islands',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Solomon_Islands.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SOM',
          data: {
            name: 'Somalia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Somalia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'RSA',
          data: {
            name: 'South Africa',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'South_Africa.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SSD',
          data: {
            name: 'South Sudan',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'South_Sudan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VSO',
          data: {
            name: 'South Vietnam',
            official_name: '',
            parent_nation_id: 'VIE',
            nation_type_id: 'NATN',
            flag_filename: 'South_Vietnam.png',
            code: 'VSO',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VIE',
          data: {
            name: 'Vietnam',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Vietnam.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SYE',
          data: {
            name: 'South Yemen',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'South_Yemen.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ESP',
          data: {
            name: 'Spain',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Spain.png',
            start_date: '1981-10-05',
            end_date: '',
          },
        },
        {
          id: 'ESP-1875-1931',
          data: {
            name: 'Spain',
            official_name: 'Spain',
            parent_nation_id: 'ESP',
            nation_type_id: 'NATN',
            flag_filename: 'Spain_1875_1931.png',
            code: 'ESP',
            start_date: '1875-01-01',
            end_date: '1931-04-27',
          },
        },
        {
          id: 'ESP-1931-1939',
          data: {
            name: 'Spain',
            official_name: 'Second Spanish Republic',
            parent_nation_id: 'ESP',
            nation_type_id: 'NATN',
            flag_filename: 'Spain_1931_1939.png',
            code: 'ESP',
            start_date: '1931-04-27',
            end_date: '1939-04-01',
          },
        },
        {
          id: 'ESP-1939-1977',
          data: {
            name: 'Spain',
            official_name: 'Spanish State',
            parent_nation_id: 'ESP',
            nation_type_id: 'NATN',
            flag_filename: 'Spanish_State.png',
            code: 'ESP',
            start_date: '1939-04-01',
            end_date: '1977-01-21',
          },
        },
        {
          id: 'ESP-1977-1981',
          data: {
            name: 'Spain',
            official_name: 'Spain',
            parent_nation_id: 'ESP',
            nation_type_id: 'NATN',
            flag_filename: 'Spain_1977_1981.png',
            code: 'ESP',
            start_date: '1977-01-21',
            end_date: '1981-10-05',
          },
        },
        {
          id: 'IOC',
          data: {
            name: 'Spain',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Olympic.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SRI',
          data: {
            name: 'Sri Lanka',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Sri_Lanka.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SKN',
          data: {
            name: 'St. Kitts and Nevis',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'St._Kitts_and_Nevis.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LCA',
          data: {
            name: 'St. Lucia',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'St._Lucia.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VIN',
          data: {
            name: 'St. Vincent and the Grenadines',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'St._Vincent_and_the_Grenadines.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SDN',
          data: {
            name: 'Samoa',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Sudan.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SDN-1956-1970',
          data: {
            name: 'Sudan',
            official_name: 'Republic of Sudan',
            parent_nation_id: 'SDN',
            nation_type_id: 'NATN',
            flag_filename: 'Sudan_1956_1970.png',
            code: 'SDN',
            start_date: '1956-01-01',
            end_date: '1970-05-20',
          },
        },
        {
          id: 'SUR',
          data: {
            name: 'Suriname',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Suriname.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SWZ',
          data: {
            name: 'Swaziland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Swaziland.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SWE',
          data: {
            name: 'Sweden',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Sweden.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SUI',
          data: {
            name: 'Switzerland',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'sui.svg',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SYR',
          data: {
            name: 'Syria',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Syria.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
  ]
};
