export const AppData = {
  collection: 'nation',
  batches: [
    {
      number: '12',
      rows: [
        {
          id: 'LAO',
          data: {
            name: 'Laos',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Laos.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LVA',
          data: {
            name: 'Latvia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Latvia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LBN',
          data: {
            name: 'Lebanon',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Lebanon.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LES',
          data: {
            name: 'Lesotho',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Lesotho.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LBR',
          data: {
            name: 'Liberia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Liberia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LBY',
          data: {
            name: 'Libya',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Libya_2-3.png',
            start_date: '2011-02-17',
            end_date: '',
          },
        },
        {
          id: 'LBY-1977-2011',
          data: {
            name: 'Libya',
            official_name: "Great Socialist People's Libyan Arab Jamahiriya",
            parent_nation_id: 'LBY',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Libya_(1977–2011,_3-2).svg.png',
            code: 'LBY',
            start_date: '1977-11-11',
            end_date: '2011-02-17',
          },
        },
        {
          id: 'LIE',
          data: {
            name: 'Liechtenstein',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Liechtenstein_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LTU',
          data: {
            name: 'Lithuania',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Lithuania_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LUX',
          data: {
            name: 'Luxembourg',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Luxembourg_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '13',
      rows: [
        {
          id: 'MAC',
          data: {
            name: 'Macau',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Macau.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MAD',
          data: {
            name: 'Madagascar',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Madagascar.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MWI',
          data: {
            name: 'Malawi',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Malawi.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MAS',
          data: {
            name: 'Malaysia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Malaysia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MDV',
          data: {
            name: 'Maldives',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Maldives.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MLI',
          data: {
            name: 'Mali',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Mali.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MLT',
          data: {
            name: 'Malta',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Malta.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MTQ',
          data: {
            name: 'Martinique',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_the_Territorial_Collectivity_of_Martinique_2-3.png',
            start_date: '2019-05-10',
            end_date: '',
          },
        },
        {
          id: 'MTQ-2019',
          data: {
            name: 'Martinique',
            official_name: '',
            parent_nation_id: 'MTQ',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: '640px-Snake_Flag_of_Martinique.svg.png',
            start_date: '1766-08-04',
            end_date: '2019-05-10',
          },
        },
        {
          id: 'MTN',
          data: {
            name: 'Mauritania',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Mauritania.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MRI',
          data: {
            name: 'Mauritius',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Mauritius.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MEX',
          data: {
            name: 'Mexico',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Mexico_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MEX-1916-1934',
          data: {
            name: 'Mexico',
            official_name: '',
            parent_nation_id: 'MEX',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Mexico_(1916-1934)_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MDA',
          data: {
            name: 'Moldova',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Moldova_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MNG',
          data: {
            name: 'Mongolia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Mongolia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MNE',
          data: {
            name: 'Montenegro',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Montenegro_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MSR',
          data: {
            name: 'Montserrat',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_Montserrat_2-3.pngg',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MAR',
          data: {
            name: 'Morocco',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Morocco.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MOZ',
          data: {
            name: 'Mozambique',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Mozambique.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MYA',
          data: {
            name: 'Myanmar',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Myanmar.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MYA-1988-2010',
          data: {
            name: 'Myanmar',
            official_name: 'Union of Myanmar',
            parent_nation_id: 'MYA',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Myanmar_(1974–2010)_2-3.png',
            start_date: '1988-09-18',
            end_date: '2010-10-21',
          },
        },
        {
          id: 'BUR-1974-1988',
          data: {
            name: 'Burma',
            official_name: 'Socialist Republic of the Union of Burma',
            parent_nation_id: 'MYA',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Myanmar_(1974–2010)_2-3.png',
            start_date: '1974-01-03',
            end_date: '1988-09-18',
          },
        },
        {
          id: 'BUR-1948-1974',
          data: {
            name: 'Burma',
            official_name: 'Union of Burma',
            parent_nation_id: 'MYA',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Burma_(1948–1974)_2-3.png',
            start_date: '1948-01-04',
            end_date: '1974-01-03',
          },
        },
      ],
    },
    {
      number: '14',
      rows: [
        {
          id: 'NAM',
          data: {
            name: 'Namibia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Namibia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NEP',
          data: {
            name: 'Nepal',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Nepal_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NED',
          data: {
            name: 'Netherlands',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_Netherlands.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NCL',
          data: {
            name: 'New Caledonia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'TER',
            flag_filename: '640px-New_Caledonia_flags_merged_(2017).svg.png',
            start_date: '2008-01-01',
            end_date: '',
          },
        },
        {
          id: 'NCL-1973-2008',
          data: {
            name: 'New Caledonia',
            official_name: 'New Caledonia',
            parent_nation_id: 'NCL',
            confederation_id: 'OFC',
            nation_type_id: 'TER',
            flag_filename: '640px-Flag_of_France.svg.png',
            code: 'NCL',
            start_date: '1973-01-01',
            end_date: '2008-01-01',
          },
        },
        {
          id: 'NZL',
          data: {
            name: 'New Zealand',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_New_Zealand_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NCA',
          data: {
            name: 'Nicaragua',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Nicaragua_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NIG',
          data: {
            name: 'Niger',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Niger_(3-2).svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NGA',
          data: {
            name: 'Nigeria',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Nigeria_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'MKD',
          data: {
            name: 'North Macedonia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_North_Macedonia_2-3.png',
            start_date: '2019-02-12',
            end_date: '',
          },
        },
        {
          id: 'MKD-2019',
          data: {
            name: 'Macedonia',
            official_name: 'FYR Macedonia',
            parent_nation_id: 'MKD',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_North_Macedonia_2-3.png',
            start_date: '',
            end_date: '2019-02-12',
          },
        },
        {
          id: 'NIR',
          data: {
            name: 'Northern Ireland',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Northern_Ireland_(1953–1972)_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NMI',
          data: {
            name: 'Northern Mariana Islands',
            official_name: 'Commonwealth of the Northern Mariana Islands',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'TER',
            flag_filename: 'Flag_of_the_Northern_Mariana_Islands_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'NOR',
          data: {
            name: 'Norway',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Norway_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'OMA',
          data: {
            name: 'Oman',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Oman_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '15',
      rows: [
        {
          id: 'PAK',
          data: {
            name: 'Pakistan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Pakistan.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PLE',
          data: {
            name: 'Palestine',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Palestine_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PAN',
          data: {
            name: 'Panama',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Panama.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PNG',
          data: {
            name: 'Papua New Guinea',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Papua_New_Guinea_2-3.png',
            flag_max_width: '105%',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PAR',
          data: {
            name: 'Paraguay',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONMEBOL',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Paraguay_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PER',
          data: {
            name: 'Peru',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONMEBOL',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Peru_(state).svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PHI',
          data: {
            name: 'Philippines',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Philippines_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'POL',
          data: {
            name: 'Poland',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Poland_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'POR',
          data: {
            name: 'Portugal',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Portugal_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'PUR',
          data: {
            name: 'Puerto Rico',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Puerto_Rico.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'QAT',
          data: {
            name: 'Qatar',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Qatar_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '16',
      rows: [
        {
          id: 'IRL',
          data: {
            name: 'Republic of Ireland',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Ireland_2-3.png',
            start_date: '1953-01-01',
            end_date: '',
          },
        },
        {
          id: 'IRL-1936-1950',
          data: {
            name: 'Ireland',
            official_name: '',
            parent_nation_id: 'IRL',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Ireland_2-3.png',
            code: 'EIR',
            start_date: '1936-01-01',
            end_date: '1950-01-01',
          },
        },
        {
          id: 'IRL-1924-1936',
          data: {
            name: 'Irish Free State',
            official_name: '',
            parent_nation_id: 'IRL',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Ireland_2-3.png',
            code: 'IFS',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'REU',
          data: {
            name: 'Réunion',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'TER',
            flag_filename: '640px-Proposed_flag_of_Reunion_(VAR).svg.png',
            flag_max_width: '115%',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ROU',
          data: {
            name: 'Romania',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Romania_2-3.png',
            flag_max_width: '115%',
            start_date: '1989-12-22',
            end_date: '',
          },
        },
        {
          id: 'ROU-1965-1989',
          data: {
            name: 'Romania',
            official_name: 'Socialist Republic of Romania',
            parent_nation_id: 'ROU',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Romania_(1965–1989).svg.png',
            code: 'ROU',
            start_date: '1965-08-21',
            end_date: '1989-12-22',
          },
        },
        {
          id: 'ROU-1952-1965',
          data: {
            name: 'Romania',
            official_name: "Romanian People's Republic",
            parent_nation_id: 'ROU',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Romania_(1952–1965).svg.png',
            code: 'ROU',
            start_date: '1952-09-24',
            end_date: '1965-08-21',
          },
        },
        {
          id: 'ROU-1948-1952',
          data: {
            name: 'Romania',
            official_name: "Romanian People's Republic",
            parent_nation_id: 'ROU',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Romania_(1948–1952).svg.png',
            code: 'ROU',
            start_date: '1948-04-13',
            end_date: '1952-09-24',
          },
        },
        {
          id: 'ROU-1947-1948',
          data: {
            name: 'Romania',
            official_name: "Romanian People's Republic",
            parent_nation_id: 'ROU',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Romania_(January-March_1948).svg.png',
            code: 'ROU',
            start_date: '1947-12-30',
            end_date: '1948-04-13',
          },
        },
        {
          id: 'RUS',
          data: {
            name: 'Russia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Russia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'CIS',
          data: {
            name: 'CIS',
            official_name: 'Commonwealth of Independent States',
            parent_nation_id: 'RUS',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_the_CIS_(UEFA_Euro_1992).svg.png',
            code: 'CIS',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'URS',
          data: {
            name: 'Soviet Union',
            official_name: '',
            parent_nation_id: 'RUS',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Soviet_Union_2-3.png',
            code: 'URS',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'RWA',
          data: {
            name: 'Rwanda',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Rwanda.svg.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
    {
      number: '17',
      rows: [
        {
          id: 'SAM',
          data: {
            name: 'Samoa',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Samoa_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SMR',
          data: {
            name: 'San Marino',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_San_Marino_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'STP',
          data: {
            name: 'São Tomé and Príncipe',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Sao_Tome_and_Principe_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'KSA',
          data: {
            name: 'Saudi Arabia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Saudi_Arabia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SCO',
          data: {
            name: 'Scotland',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Scotland_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SEN',
          data: {
            name: 'Senegal',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Senegal.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SRB',
          data: {
            name: 'Serbia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Serbia.svg.png',
            start_date: '2006-06-05',
            end_date: '',
          },
        },
        {
          id: 'SRB-2003-2006',
          data: {
            name: 'Serbia and Montenegro',
            official_name: 'State Union of Serbia and Montenegro',
            parent_nation_id: 'SRB',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Yugoslavia_(1992–2003);_Flag_of_Serbia_and_Montenegro_(2003–2006)_2-3.png',
            code: 'SCG',
            start_date: '2003-02-04',
            end_date: '2006-06-03',
          },
        },
        {
          id: 'YUG-1992-2003',
          data: {
            name: 'Yugoslavia',
            official_name: 'Federal Republic of Yugoslavia',
            parent_nation_id: 'SRB',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Yugoslavia_(1992–2003);_Flag_of_Serbia_and_Montenegro_(2003–2006)_2-3.png',
            code: 'YUG',
            start_date: '1992-04-27',
            end_date: '2003-02-04',
          },
        },
        {
          id: 'YUG-1963-1992',
          data: {
            name: 'Yugoslavia',
            official_name: 'Socialist Federal Republic of Yugoslavia',
            parent_nation_id: 'SRB',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Yugoslavia_(1946-1992)_2-3.png',
            code: 'YUG',
            start_date: '1945-11-29',
            end_date: '1992-04-27',
          },
        },
        {
          id: 'YUG-1945-1963',
          data: {
            name: 'Yugoslavia',
            official_name: "Federal People's Republic of Yugoslavia",
            parent_nation_id: 'SRB',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Yugoslavia_(1946-1992)_2-3.png',
            code: 'YUG',
            start_date: '1945-11-29',
            end_date: '1963-04-07',
          },
        },
        {
          id: 'YUG-1943-1945',
          data: {
            name: 'Yugoslavia',
            official_name: 'Democratic Federal Yugoslavia',
            parent_nation_id: 'SRB',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Yugoslavia_(1943–1946)_2-3.png',
            code: 'YUG',
            start_date: '1943-11-29',
            end_date: '1945-11-29',
          },
        },
        {
          id: 'YUG-1929-1943',
          data: {
            name: 'Yugoslavia',
            official_name: 'Kingdom of Yugoslavia',
            parent_nation_id: 'SRB',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Yugoslavia_(1918–1941).svg.png',
            code: 'YUG',
            start_date: '1929-10-03',
            end_date: '1943-11-29',
          },
        },
        {
          id: 'YUG-1918-1929',
          data: {
            name: 'Yugoslavia',
            official_name: 'Kingdom of Serbs, Croats and Slovenes',
            parent_nation_id: 'SRB',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Yugoslavia_(1918–1941).svg.png',
            code: 'YUG',
            start_date: '1918-12-01',
            end_date: '1929-10-03',
          },
        },
        {
          id: 'SEY',
          data: {
            name: 'Seychelles',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Seychelles_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SLE',
          data: {
            name: 'Sierra Leone',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Sierra_Leone.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SIN',
          data: {
            name: 'Singapore',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Singapore.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SVK',
          data: {
            name: 'Slovakia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Slovakia_2-3.png',
            flag_max_width: '115%',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SVN',
          data: {
            name: 'Slovenia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Slovenia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SOL',
          data: {
            name: 'Solomon Islands',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'OFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_the_Solomon_Islands_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SOM',
          data: {
            name: 'Somalia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Somalia.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'RSA',
          data: {
            name: 'South Africa',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_South_Africa.svg.png',
            start_date: '1957-01-01',
            end_date: '',
          },
        },
        {
          id: 'RSA-1928-1994',
          data: {
            name: 'South Africa',
            official_name: '',
            parent_nation_id: 'RSA',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_South_Africa_(1928–1994).svg.png',
            start_date: '1928-05-31',
            end_date: '1994-04-26',
          },
        },
        {
          id: 'SSD',
          data: {
            name: 'South Sudan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_South_Sudan_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'YMD',
          data: {
            name: 'South Yemen',
            official_name: '',
            parent_nation_id: '',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_South_Yemen.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ESP',
          data: {
            name: 'Spain',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Spain.svg.png',
            start_date: '1981-10-05',
            end_date: '',
          },
        },
        {
          id: 'IOC-ESP',
          data: {
            name: 'Spain',
            official_name: '',
            parent_nation_id: '',
            confederation_id: '',
            nation_type_id: 'NATN',
            flag_filename: '640px-Spain_Olympic_Flag_1980.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'ESP-1977-1981',
          data: {
            name: 'Spain',
            official_name: 'Spain',
            parent_nation_id: 'ESP',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Spain_(1977–1981).svg.png',
            code: 'ESP',
            start_date: '1977-01-21',
            end_date: '1981-10-05',
          },
        },
        {
          id: 'ESP-1945-1977',
          data: {
            name: 'Spain',
            official_name: 'Spanish State',
            parent_nation_id: 'ESP',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Spain_(1945–1977).svg.png',
            code: 'ESP',
            start_date: '1945-07-26',
            end_date: '1977-01-21',
          },
        },
        {
          id: 'ESP-1938-1945',
          data: {
            name: 'Spain',
            official_name: 'Spanish State',
            parent_nation_id: 'ESP',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Spain_(1938–1945).svg.png',
            code: 'ESP',
            start_date: '1938-01-01',
            end_date: '1945-07-26',
          },
        },
        {
          id: 'ESP-1936-1938',
          data: {
            name: 'Spain',
            official_name: 'Spanish State',
            parent_nation_id: 'ESP',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Bandera_del_bando_nacional_1936-1938.svg.png',
            code: 'ESP',
            start_date: '1936-08-29',
            end_date: '1938-01-11',
          },
        },
        {
          id: 'ESP-1931-1936',
          data: {
            name: 'Spain',
            official_name: 'Second Spanish Republic',
            parent_nation_id: 'ESP',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Spain_(1931–1939)_2-3.png',
            code: 'ESP',
            start_date: '1931-04-27',
            end_date: '1936-08-29',
          },
        },
        {
          id: 'ESP-1875-1931',
          data: {
            name: 'Spain',
            official_name: 'Spain',
            parent_nation_id: 'ESP',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Spain_(1785–1873,_1875–1931).svg.png',
            code: 'ESP',
            start_date: '1875-01-01',
            end_date: '1931-04-27',
          },
        },
        {
          id: 'SRI',
          data: {
            name: 'Sri Lanka',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Sri_Lanka_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SKN',
          data: {
            name: 'Saint Kitts and Nevis',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Saint_Kitts_and_Nevis.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'LCA',
          data: {
            name: 'Saint Lucia',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Saint_Lucia_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SMN',
          data: {
            name: 'Saint Martin',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: '640px-Flag_of_France.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'VIN',
          data: {
            name: 'Saint Vincent and the Grenadines',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SMA',
          data: {
            name: 'Sint Maarten',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'TER',
            flag_filename: '640px-Flag_of_Sint_Maarten.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SDN',
          data: {
            name: 'Sudan',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Sudan_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SDN-1956-1970',
          data: {
            name: 'Sudan',
            official_name: 'Republic of Sudan',
            parent_nation_id: 'SDN',
            confederation_id: 'CAF',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Sudan_(1956–1970)_2-3.png',
            code: 'SDN',
            start_date: '1956-01-01',
            end_date: '1970-05-20',
          },
        },
        {
          id: 'SUR',
          data: {
            name: 'Suriname',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'CONCACAF',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Suriname.svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SWE',
          data: {
            name: 'Sweden',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: 'Flag_of_Sweden_2-3.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SUI',
          data: {
            name: 'Switzerland',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'UEFA',
            nation_type_id: 'NATN',
            flag_filename: '640px-Civil_Ensign_of_Switzerland_(Pantone).svg.png',
            start_date: '',
            end_date: '',
          },
        },
        {
          id: 'SYR',
          data: {
            name: 'Syria',
            official_name: '',
            parent_nation_id: '',
            confederation_id: 'AFC',
            nation_type_id: 'NATN',
            flag_filename: '640px-Flag_of_Syria.svg.png',
            start_date: '',
            end_date: '',
          },
        },
      ],
    },
  ],
}
