export const AppData = {
  collection: 'tournament',
  batches: [
    {
      number: '10',
      rows: [
        {
          id: 'AAC2019',
          data: {
            year: '2019',
            name: 'AFC Asian Cup United Arab Emirates 2019',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'head2headreapply', 'goaldifferenceandgoalscored', 'penalty', 'fairplaylight', 'lot'],
            no_third_place: true,
            details: {
              host: ['UAE'],
              logo_filename: '2019_AFC_Asian_Cup_logo_480x514.png',
              mascot_filename: 'mascot_UAE_2019_Athletic-Pride.jpg',
              start_date: '2019-01-05',
              end_date: '2019-02-01',
              color: '#ff0000',
              team_count: 24,
              venue_count: 8,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '640px-Qatar_-_Japan,_AFC_Asian_Cup_2019_56.jpg',
                text: 'Qatar',
              },
            ],
            final_standings: { champions: 'QAT', runners_up: 'JPN', semi_finalist1: 'IRN', semi_finalist2: 'UAE' },
            statistics: { total_matches: 51, total_goals: 130, attendance: 644307 },
            awards: {
              golden_boot: [{ name: 'Almoez Ali', team: 'QAT', goals: 9 }],
              golden_ball: [{ name: 'Almoez Ali', team: 'QAT' }],
              golden_glove: [{ name: 'Saad Al Sheeb', team: 'QAT' }],
              fair_play_team: ['JPN'],
            },
          },
        },
        {
          id: 'AAC2015',
          data: {
            year: '2015',
            name: 'AFC Asian Cup Australia 2015',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'penalty', 'fairplaylight', 'lot'],
            details: {
              host: ['AUS'],
              logo_filename: '2015_AFC_Asian_Cup_logo_480x590.png',
              mascot_filename: 'mascot_Australia_2015.jpg',
              start_date: '2015-01-09',
              end_date: '2015-01-31',
              color: '#00008b',
              team_count: 16,
              venue_count: 5,
              city_count: 5,
            },
            hero_images: [
              {
                name: 'Final',
                filename: '640px-2015_Asian_Cup_Final.jpg',
                text: '2015 AFC Asian Cup Final',
              },
            ],
            final_standings: { champions: 'AUS', runners_up: 'KOR', third_place: ['UAE'], fourth_place: 'IRQ' },
            statistics: { total_matches: 32, total_goals: 85, attendance: 705705 },
            awards: {
              golden_boot: [{ name: 'Ali Mabkhout', team: 'UAE', goals: 5 }],
              golden_ball: [{ name: 'Massimo Luongo', team: 'AUS' }],
              golden_glove: [{ name: 'Mathew Ryan', team: 'AUS' }],
              fair_play_team: ['AUS'],
            },
          },
        },
        {
          id: 'AAC2011',
          data: {
            year: '2011',
            short_year: '2011',
            name: 'AFC Asian Cup Qatar 2011',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'penalty', 'fairplaylight', 'lot'],
            details: {
              host: ['QAT'],
              logo_filename: '2011_AFC_Asian_Cup_full_logo_480x533.png',
              start_date: '2011-01-07',
              end_date: '2011-01-29',
              color: '#79003c',
              team_count: 16,
              venue_count: 5,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Khalifa International Stadium, Doha',
                filename: '640px-Khalifa_Stadium,_Doha,_Brazil_vs_Argentina_(2010).jpg',
                text: 'The Khalifa International Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'JPN', runners_up: 'AUS', third_place: ['KOR'], fourth_place: 'UZB' },
            statistics: { total_matches: 32, total_goals: 90, attendance: 405361 },
            awards: {
              golden_boot: [{ name: 'Koo Ja-cheol', team: 'KOR', goals: 5 }],
              golden_ball: [{ name: 'Keisuke Honda', team: 'JPN' }],
              fair_play_team: ['KOR'],
            },
          },
        },
        {
          id: 'AAC2007',
          data: {
            year: '2007',
            short_year: '2007',
            name: 'AFC Asian Cup Indonesia-Malaysia-Thailand-Vietnam 2007',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['IDN', 'MAS', 'THA', 'VIE'],
              logo_filename: '2007_Asian_Cup_Logo_480x401.png',
              start_date: '2007-07-07',
              end_date: '2007-07-29',
              color: '#105f49',
              team_count: 16,
              venue_count: 8,
              city_count: 7,
            },
            hero_images: [
              {
                name: 'Group A',
                filename: '640px-Asian_Cup_2007-Australia-Oman.jpg',
                text: 'Players from Oman and Australia line up during the national anthems.',
              },
            ],
            final_standings: { champions: 'IRQ-2004-2008', runners_up: 'KSA', third_place: ['KOR'], fourth_place: 'JPN' },
            statistics: { total_matches: 32, total_goals: 84, attendance: 724222 },
            awards: {
              golden_boot: [
                { name: 'Younis Mahmoud', team: 'IRQ-2004-2008', goals: 4 },
                { name: 'Naohiro Takahara', team: 'JPN', goals: 4 },
                { name: 'Yasser Al-Qahtani', team: 'KSA', goals: 4 },
              ],
              golden_ball: [{ name: 'Younis Mahmoud', team: 'IRQ-2004-2008' }],
              golden_glove: [{ name: 'Noor Sabri', team: 'IRQ-2004-2008' }],
              best_defender: [{ name: 'Bassim Abbas', team: 'IRQ-2004-2008' }],
              fair_play_team: ['JPN'],
            },
          },
        },
        {
          id: 'AAC2004',
          data: {
            year: '2004',
            short_year: '2004',
            name: 'AFC Asian Cup China 2004',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['CHN'],
              logo_filename: '2004_AFC_Asian_Cup_full_logo_480x616.png',
              start_date: '2004-07-17',
              end_date: '2004-08-07',
              color: '#ee2c29',
              team_count: 16,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Workers Stadium, Beijing',
                filename: '640px-Workers_stadium_internal_field.jpeg',
                text: 'The Workers Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'JPN', runners_up: 'CHN', third_place: ['IRN'], fourth_place: 'BHR' },
            statistics: { total_matches: 32, total_goals: 96, attendance: 937650 },
            awards: {
              golden_boot: [
                { name: "A'ala Hubail", team: 'BHR', goals: 5 },
                { name: 'Ali Karimi', team: 'IRN', goals: 5 },
              ],
              golden_ball: [{ name: 'Shunsuke Nakamura', team: 'JPN' }],
              fair_play_team: ['CHN'],
            },
          },
        },
        {
          id: 'AAC2000',
          data: {
            year: '2000',
            name: 'AFC Asian Cup Lebanon 2000',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['LBN'],
              logo_filename: '2000_AFC_Asian_Cup_logo_480x358.png',
              start_date: '2000-10-12',
              end_date: '2000-10-29',
              color: '#149552',
              team_count: 12,
              venue_count: 3,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Sports City Stadium, Beirut',
                filename: '640px-Camille_Chamoun_Sports_City_Stadium_2018_-_Beirut_derby_(Nejmeh_fans).png',
                text: 'The Sports City Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'JPN', runners_up: 'KSA', third_place: ['KOR'], fourth_place: 'CHN' },
            statistics: { total_matches: 26, total_goals: 77, attendance: 276488 },
            awards: {
              golden_boot: [{ name: 'Lee Dong-Gook', team: 'KOR', goals: 6 }],
              golden_ball: [{ name: 'Hiroshi Nanami', team: 'JPN' }],
              golden_glove: [{ name: 'Jiang Jin', team: 'CHN' }],
              best_defender: [{ name: 'Ryuzo Morioka', team: 'JPN' }],
              fair_play_team: ['KSA'],
            },
          },
        },
        {
          id: 'AAC1996',
          data: {
            year: '1996',
            name: 'AFC Asian Cup United Arab Emirates 1996',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['UAE'],
              logo_filename: '1996_AFC_Asian_Cup_logo_480x536.png',
              start_date: '1996-12-04',
              end_date: '1996-12-21',
              color: '#ff0000',
              team_count: 12,
              venue_count: 3,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Sheikh Zayed Stadium, Abu Dhabi',
                filename: '640px-Gulf_Cup_(36).jpg',
                text: 'The Sheikh Zayed Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'KSA', runners_up: 'UAE', third_place: ['IRN'], fourth_place: 'KUW' },
            statistics: { total_matches: 26, total_goals: 80, attendance: 448000 },
            awards: {
              golden_boot: [{ name: 'Ali Daei', team: 'IRN', goals: 8 }],
              golden_ball: [{ name: 'Khodadad Azizi', team: 'IRN' }],
              golden_glove: [{ name: 'Mohamed Al-Deayea', team: 'KSA' }],
              fair_play_team: ['IRN'],
            },
          },
        },
        {
          id: 'AAC1992',
          data: {
            year: '1992',
            short_year: '1992',
            name: 'AFC Asian Cup Japan 1992',
            short_name: 'Japan 1992',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['JPN'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1992-10-29',
              end_date: '1992-11-08',
              color: '#fa2200',
              team_count: 8,
              venue_count: 3,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Hiroshima Big Arch, Hiroshima',
                filename: '640px-Bigarch050423.jpg',
                text: 'The Hiroshima Big Arch hosted the final.',
              },
            ],
            final_standings: { champions: 'JPN', runners_up: 'KSA', third_place: ['CHN'], fourth_place: 'UAE' },
            statistics: { total_matches: 16, total_goals: 31, attendance: 316496 },
            awards: {
              golden_boot: [{ name: 'Fahad Al-Bishi', team: 'KSA', goals: 3 }],
              golden_ball: [{ name: 'Kazuyoshi Miura', team: 'JPN' }],
            },
          },
        },
        {
          id: 'AAC1988',
          data: {
            year: '1988',
            short_year: '1988',
            name: 'AFC Asian Cup Qatar 1988',
            short_name: 'Qatar 1988',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['QAT'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1988-12-02',
              end_date: '1988-12-18',
              color: '#671637',
              team_count: 10,
              venue_count: 2,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Qatar SC Stadium, Doha',
                filename: '640px-Interior_view_of_Suheim_Bin_Hamad_Stadium_in_2020.jpg',
                text: 'Qatar SC Stadium, Doha',
              },
            ],
            final_standings: { champions: 'KSA', runners_up: 'KOR', third_place: ['IRN'], fourth_place: 'CHN' },
            statistics: { total_matches: 24, total_goals: 40 },
            awards: {
              golden_boot: [{ name: 'Lee Tae-Ho', team: 'KOR', goals: 3 }],
              golden_ball: [{ name: 'Kim Joo-Sung', team: 'KOR' }],
              golden_glove: [{ name: 'Zhang Huikang', team: 'CHN' }],
              best_forward: [{ name: 'Lee Tae-ho', team: 'KOR' }],
            },
          },
        },
        {
          id: 'AAC1984',
          data: {
            year: '1984',
            short_year: '1984',
            name: 'AFC Asian Cup Singapore 1984',
            short_name: 'Singapore 1984',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['SIN'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1984-12-01',
              end_date: '1984-12-16',
              color: '#f93127',
              team_count: 10,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'National Stadium, Kallang',
                filename: '640px-NationalStadium.jpg',
                text: 'The National Stadium hosted all the matches.',
              },
            ],
            final_standings: { champions: 'KSA', runners_up: 'CHN', third_place: ['KUW'], fourth_place: 'IRN' },
            statistics: { total_matches: 24, total_goals: 44 },
            awards: {
              golden_boot: [
                { name: 'Shahrokh Bayani', team: 'IRN', goals: 3 },
                { name: 'Nasser Mohammadkhani', team: 'IRN', goals: 3 },
                { name: 'Jia Xiuquan', team: 'CHN', goals: 3 },
              ],
              golden_ball: [{ name: 'Jia Xiuquan', team: 'CHN' }],
              golden_glove: [{ name: 'Abdullah Al-Deayea', team: 'KSA' }],
              fair_play_team: ['CHN'],
            },
          },
        },
        {
          id: 'AAC1980',
          data: {
            year: '1980',
            short_year: '1980',
            name: 'AFC Asian Cup Kuwait 1980',
            short_name: 'Kuwait 1980',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['KUW'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1980-09-15',
              end_date: '1980-09-30',
              color: '#4fb24a',
              team_count: 10,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Sabah Al-Salem Stadium, Kuwait City',
                filename: '640px-ArabiStagium.jpg',
                text: 'The Sabah Al-Salem Stadium hosted all the matches.',
              },
            ],
            final_standings: { champions: 'KUW', runners_up: 'KOR', third_place: ['IRN'], fourth_place: 'PRK' },
            statistics: { total_matches: 24, total_goals: 76 },
            awards: {
              golden_boot: [
                { name: 'Behtash Fariba', team: 'IRN', goals: 7 },
                { name: 'Choi Soon-ho', team: 'KOR', goals: 7 },
              ],
            },
          },
        },
        {
          id: 'AAC1976',
          data: {
            year: '1976',
            short_year: '1976',
            name: 'AFC Asian Cup Iran 1976',
            short_name: 'Iran 1976',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['IRN-1964-1980'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1976-06-03',
              end_date: '1976-06-13',
              color: '#089748',
              team_count: 6,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Aryamehr Stadium, Tehran',
                filename: '640px-Azadi_Stadium_ACL_2018.jpg',
                text: 'The Aryamehr Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'IRN-1964-1980', runners_up: 'KUW', third_place: ['CHN'], fourth_place: 'IRQ-1963-1991' },
            statistics: { total_matches: 10, total_goals: 25 },
            awards: {
              golden_boot: [
                { name: 'Fathi Kamel', team: 'KUW', goals: 3 },
                { name: 'Gholam Hossein Mazloumi', team: 'IRN-1964-1980', goals: 3 },
                { name: 'Nasser Nouraei', team: 'IRN-1964-1980', goals: 3 },
              ],
              golden_ball: [{ name: 'Ali Parvin', team: 'IRN-1964-1980' }],
            },
          },
        },
        {
          id: 'AAC1972',
          data: {
            year: '1972',
            short_year: '1972',
            name: 'AFC Asian Cup Thailand 1972',
            short_name: 'Thailand 1972',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['THA'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1972-05-07',
              end_date: '1972-05-19',
              color: '#2251a2',
              team_count: 6,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'National Stadium, Bangkok',
                filename: '640px-Suphachalasai_3116.jpeg',
                text: 'The National Stadium hosted all the matches.',
              },
            ],
            final_standings: { champions: 'IRN-1964-1980', runners_up: 'KOR', third_place: ['THA'], fourth_place: 'CAM-1970-1975' },
            statistics: { total_matches: 13, total_goals: 38 },
            awards: {
              golden_boot: [{ name: 'Hossein Kalani', team: 'IRN-1964-1980', goals: 5 }],
              golden_ball: [{ name: 'Ebrahim Ashtiani', team: 'IRN-1964-1980' }],
            },
          },
        },
        {
          id: 'AAC1968',
          data: {
            year: '1968',
            short_year: '1968',
            name: 'AFC Asian Cup Iran 1968',
            short_name: 'Iran 1968',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['IRN-1964-1980'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1968-05-10',
              end_date: '1968-05-19',
              color: '#089748',
              team_count: 5,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Amjadieh Stadium, Tehran',
                filename: '640px-Amjadieh_Stadium.jpg',
                text: 'The Amjadieh Stadium hosted all the matches.',
              },
            ],
            final_standings: { champions: 'IRN-1964-1980', runners_up: 'BUR-1948-1974', third_place: ['ISR'], fourth_place: 'TPE-1960-1979' },
            statistics: { total_matches: 10, total_goals: 32 },
            awards: {
              golden_boot: [
                { name: 'Homayoun Behzadi', team: 'IRN-1964-1980', goals: 4 },
                { name: 'Moshe Romano', team: 'ISR', goals: 4 },
                { name: 'Giora Spiegel', team: 'ISR', goals: 4 },
              ],
            },
          },
        },
        {
          id: 'AAC1964',
          data: {
            year: '1964',
            short_year: '1964',
            name: 'AFC Asian Cup Israel 1964',
            short_name: 'Israel 1964',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['ISR'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1964-05-26',
              end_date: '1964-06-03',
              color: '#15296d',
              team_count: 4,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '640px-Flickr_-_Government_Press_Office_(GPO)_-_The_Asian_Cup.jpg',
                text: 'The Israeli soccer team holds the Asian Cup after its victory over South Korea at Ramat Gan stadium.',
              },
            ],
            final_standings: { champions: 'ISR', runners_up: 'IND', third_place: ['KOR'], fourth_place: 'HKG-1959-1997' },
            statistics: { total_matches: 6, total_goals: 13, attendance: 99000 },
            awards: {
              golden_boot: [
                { name: 'Inder Singh', team: 'IND', goals: 2 },
                { name: 'Mordechai Spiegler', team: 'ISR', goals: 2 },
              ],
            },
          },
        },
        {
          id: 'AAC1960',
          data: {
            year: '1960',
            short_year: '1960',
            name: 'AFC Asian Cup Korea Republic 1960',
            short_name: 'Korea Republic 1960',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['KOR'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1960-10-14',
              end_date: '1960-10-23',
              color: '#fa2200',
              team_count: 4,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Hyochang Stadium, Seoul',
                filename: '640px-Hyochang_Stadium.jpeg',
                text: 'The Hyochang Stadium hosted a group match.',
              },
            ],
            final_standings: { champions: 'KOR', runners_up: 'ISR', third_place: ['TPE-1960-1979'], fourth_place: 'VSO' },
            statistics: { total_matches: 6, total_goals: 19 },
            awards: {
              golden_boot: [{ name: 'Cho Yoon-ok', team: 'KOR', goals: 4 }],
            },
          },
        },
        {
          id: 'AAC1956',
          data: {
            year: '1956',
            short_year: '1956',
            name: 'AFC Asian Cup Hong Kong 1956',
            short_name: 'Hong Kong 1956',
            competition_id: 'AAC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['HKG-1955-1959'],
              logo_filename: 'AFC_Asian_Cup.png',
              start_date: '1956-09-01',
              end_date: '1956-09-15',
              color: '#fa300f',
              team_count: 4,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Government Stadium, Hong Kong',
                filename: '640px-Hong_Kong_Stadium-1.jpg',
                text: 'The Government Stadium hosted all matches.',
              },
            ],
            final_standings: { champions: 'KOR', runners_up: 'ISR', third_place: ['HKG-1955-1959'], fourth_place: 'VSO' },
            statistics: { total_matches: 6, total_goals: 27, attendance: 136000 },
            awards: {
              golden_boot: [{ name: 'Nahum Stelmach', team: 'ISR', goals: 4 }],
            },
          },
        },
      ],
    },
    {
      number: '11',
      rows: [
        {
          id: 'ONC2016',
          data: {
            year: '2016',
            short_year: '2016',
            name: 'OFC Nations Cup Papua New Guinea 2016',
            short_name: 'Papua New Guinea 2016',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'head2headawaygoals', 'fairplay', 'lot'],
            no_third_place: true,
            details: {
              host: ['PNG'],
              logo_filename: 'OFCcup.png',
              start_date: '2016-05-28',
              end_date: '2016-06-11',
              color: '#e1151e',
              team_count: 8,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Sir John Guise Stadium, Port Moresby',
                filename: 'Sir._John_Guise_Stadium.jpg',
                text: 'The Sir John Guise Stadium hosted all the matches.',
              },
            ],
            final_standings: { champions: 'NZL', runners_up: 'PNG', semi_finalist1: 'NCL', semi_finalist2: 'SOL' },
            statistics: { total_matches: 15, total_goals: 48, attendance: 41996 },
            awards: {
              golden_boot: [{ name: 'Raymond Gunemba', team: 'PNG', goals: 5 }],
              golden_ball: [{ name: 'David Muta', team: 'PNG' }],
              golden_glove: [{ name: 'Stefan Marinovic', team: 'NZL' }],
              fair_play_team: ['NCL'],
            },
          },
        },
        {
          id: 'ONC2012',
          data: {
            year: '2012',
            short_year: '2012',
            name: 'OFC Nations Cup Solomon Islands 2012',
            short_name: 'Solomon Islands 2012',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['SOL'],
              logo_filename: 'OFCcup.png',
              start_date: '2012-06-01',
              end_date: '2012-06-10',
              color: '#086349',
              team_count: 8,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Lawson Tama Stadium, Honiaray',
                filename: 'Lawson_Tama_Stadium.jpg',
                text: 'The national stadium of Solomon Islands, during the Olympics Torch Relay',
              },
            ],
            final_standings: { champions: 'TAH', runners_up: 'NCL', third_place: ['NZL'], fourth_place: 'SOL' },
            statistics: { total_matches: 16, total_goals: 64, attendance: 133700 },
            awards: {
              golden_boot: [{ name: 'Jacques Haeko', team: 'NCL', goals: 6 }],
              golden_ball: [{ name: 'Nicolas Vallar', team: 'TAH' }],
              golden_glove: [{ name: 'Rocky Nyikeine', team: 'NCL' }],
              fair_play_team: ['SOL'],
            },
          },
        },
        {
          id: 'ONC2008',
          data: {
            year: '2008',
            short_year: '2008',
            name: 'OFC Nations Cup 2008',
            short_name: '2008',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            show_match_year: true,
            tiebreakers: ['team'],
            details: {
              logo_filename: 'OFCcup.png',
              start_date: '2007-10-17',
              end_date: '2008-11-19',
              color: '#192e71',
              team_count: 4,
              venue_count: 5,
              city_count: 5,
            },
            hero_images: [
              {
                name: 'Westpac Stadium, Wellington',
                filename: '640px-All_Whites_v_Peru_11_November_2017.jpg',
                text: 'Westpac Stadium, Wellington',
              },
            ],
            final_standings: { champions: 'NZL', runners_up: 'NCL-1973-2008', third_place: ['FIJ'], fourth_place: 'VAN' },
            statistics: { total_matches: 12, total_goals: 39 },
            awards: {
              golden_boot: [{ name: 'Shane Smeltz', team: 'NZL', goals: 8 }],
            },
          },
        },
        {
          id: 'ONC2004',
          data: {
            year: '2004',
            short_year: '2004',
            name: 'OFC Nations Cup Australia 2004',
            short_name: 'Australia 2004',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['AUS'],
              logo_filename: 'OFCcup.png',
              start_date: '2004-05-29',
              end_date: '2004-10-12',
              color: '#178338',
              team_count: 6,
              venue_count: 4,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Sydney Football Stadium, Sydney',
                filename: '640px-Allianz_Stadium_-_13_October_2012.jpg',
                text: 'The Sydney Football Stadium hosted the 2nd-leg final.',
              },
            ],
            final_standings: { champions: 'AUS', runners_up: 'SOL', third_place: ['NZL'], fourth_place: 'FIJ' },
            statistics: { total_matches: 17, total_goals: 69 },
            awards: {
              golden_boot: [
                { name: 'Tim Cahill', team: 'AUS', goals: 6 },
                { name: 'Vaughan Coveny', team: 'NZL', goals: 6 },
              ],
            },
          },
        },
        {
          id: 'ONC2002',
          data: {
            year: '2002',
            short_year: '2002',
            name: 'OFC Nations Cup New Zealand 2002',
            short_name: 'New Zealand 2002',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['NZL'],
              logo_filename: 'OFCcup.png',
              mascot_filename: 'OFC3-copy-2002.jpeg',
              start_date: '2002-07-05',
              end_date: '2002-07-14',
              color: '#1d368a',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Ericsson Stadium, Auckland',
                filename: '640px-EricssonStadium00.jpg',
                text: 'The Ericsson Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'NZL', runners_up: 'AUS', third_place: ['TAH'], fourth_place: 'VAN' },
            statistics: { total_matches: 16, total_goals: 64 },
            awards: {
              golden_boot: [
                { name: 'Bobby Despotovski', team: 'AUS', goals: 5 },
                { name: 'Joel Porter', team: 'AUS', goals: 5 },
                { name: 'Chris Killen', team: 'NZL', goals: 5 },
                { name: 'Jeff Campbell', team: 'NZL', goals: 5 },
              ],
            },
          },
        },
        {
          id: 'ONC2000',
          data: {
            year: '2000',
            short_year: '2000',
            name: 'OFC Nations Cup Tahiti 2000',
            short_name: 'Tahiti 2000',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['TAH'],
              logo_filename: 'OFCcup.png',
              start_date: '2000-06-19',
              end_date: '2000-06-28',
              color: '#fe0000',
              team_count: 6,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Papeete, Tahiti',
                filename: '640px-FP-papeete-hafen-1.jpg',
                text: "Papeete's city center and marina",
              },
            ],
            final_standings: { champions: 'AUS', runners_up: 'NZL', third_place: ['SOL'], fourth_place: 'VAN' },
            statistics: { total_matches: 10, total_goals: 48 },
            awards: {
              golden_boot: [
                { name: 'Craig Foster', team: 'AUS', goals: 5 },
                { name: 'Clayton Zane', team: 'AUS', goals: 5 },
              ],
            },
          },
        },
        {
          id: 'ONC1998',
          data: {
            year: '1998',
            short_year: '1998',
            name: 'OFC Nations Cup Australia 1998',
            short_name: 'Australia 1998',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['AUS'],
              logo_filename: 'OFCcup.png',
              start_date: '1998-09-25',
              end_date: '1998-10-04',
              color: '#178338',
              team_count: 6,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Lang Park, Brisbane',
                filename: '640px-Suncorp_Stadium_22_April_2012_(cropped).jpg',
                text: 'The Lang Park hosted all the matches of the tournament.',
              },
            ],
            final_standings: { champions: 'NZL', runners_up: 'AUS', third_place: ['FIJ'], fourth_place: 'TAH' },
            statistics: { total_matches: 10, total_goals: 52 },
            awards: {
              golden_boot: [{ name: 'Damian Mori', team: 'AUS', goals: 10 }],
            },
          },
        },
        {
          id: 'ONC1996',
          data: {
            year: '1996',
            short_year: '1996',
            name: 'OFC Nations Cup 1996',
            short_name: '1996',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            no_third_place: true,
            show_match_year: true,
            details: { logo_filename: 'OFCcup.png', start_date: '1995-11-10', end_date: '1996-11-01', color: '#192e71', team_count: 4 },
            hero_images: [
              {
                name: 'Queen Elizabeth II Park, Christchurch',
                filename: 'QEII2.jpeg',
                text: 'The Queen Elizabeth II Park hosted the 1st-leg of the semi-final New Zealand vs Australia.',
              },
            ],
            final_standings: { champions: 'AUS', runners_up: 'TAH', semi_finalist1: 'NZL', semi_finalist2: 'SOL' },
            statistics: { total_matches: 6, total_goals: 18 },
            awards: {
              golden_boot: [{ name: 'Kris Trajanovski', team: 'AUS', goals: 7 }],
            },
          },
        },
        {
          id: 'ONC1980',
          data: {
            year: '1980',
            short_year: '1980',
            name: 'Oceania Nations Cup New Caledonia 1980',
            short_name: 'New Caledonia 1980',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['NCL-1973-2008'],
              logo_filename: 'OFCcup.png',
              start_date: '1980-02-24',
              end_date: '1980-03-01',
              color: '#009543',
              team_count: 8,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Nouméa, New Caledonia',
                filename: '640px-Noumea_centre_1402561139_375c811796_o.jpg',
                text: 'City centre and Nouméa Cathedral',
              },
            ],
            final_standings: { champions: 'AUS', runners_up: 'TAH-1794-1984', third_place: ['NCL-1973-2008'], fourth_place: 'FIJ' },
            statistics: { total_matches: 14, total_goals: 94 },
            awards: {
              golden_boot: [
                { name: 'Ian Hunter', team: 'AUS', goals: 5 },
                { name: 'Eddie Krncevic', team: 'AUS', goals: 5 },
              ],
            },
          },
        },
        {
          id: 'ONC1973',
          data: {
            year: '1973',
            short_year: '1973',
            name: 'Oceania Nations Cup New Zealand 1973',
            short_name: 'New Zealand 1973',
            competition_id: 'ONC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['NZL'],
              logo_filename: 'OFCcup.png',
              start_date: '1973-02-17',
              end_date: '1973-02-24',
              color: '#1d368a',
              team_count: 5,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Auckland, New Zealand',
                filename: 'Auckland,_Albert_Park.jpg',
                text: 'Albert Park in Auckland',
              },
            ],
            final_standings: { champions: 'NZL', runners_up: 'TAH-1794-1984', third_place: ['NCL-1973-2008'], fourth_place: 'VAN-1953-1980' },
            statistics: { total_matches: 12, total_goals: 37 },
            awards: {
              golden_boot: [
                { name: 'Segin Wayewol (NCL)', team: 'NCL-1973-2008', goals: 3 },
                { name: 'Alan Marley', team: 'NZL', goals: 3 },
                { name: 'Erroll Bennett (TAH)', team: 'TAH-1794-1984', goals: 3 },
              ],
            },
          },
        },
      ],
    },
    {
      number: '12',
      rows: [
        {
          id: 'CONFEDC2017',
          data: {
            year: '2017',
            name: 'FIFA Confederations Cup Russia 2017',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'fairplay', 'lot'],
            details: {
              host: ['RUS'],
              logo_filename: '2017_FIFA_Confederations_Cup_480x530.png',
              start_date: '2017-06-17',
              end_date: '2017-07-02',
              color: '#930c10',
              team_count: 8,
              confed_count: 6,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '640px-Chile_-_Germany_(3).jpg',
                text: 'Germany lineup',
              },
            ],
            final_standings: { champions: 'GER', runners_up: 'CHI', third_place: ['POR'], fourth_place: 'MEX' },
            statistics: { total_matches: 16, total_goals: 43, attendance: 628304 },
            awards: {
              golden_boot: [{ name: 'Timo Werner', team: 'GER', goals: 3, assists: 2 }],
              silver_boot: [{ name: 'Leon Goretzka', team: 'GER', goals: 3, assists: 0 }],
              bronze_boot: [{ name: 'Lars Stindl', team: 'GER', goals: 3, assists: 0 }],
              golden_ball: [
                { name: 'Julian Draxler', team: 'GER' },
                { name: 'Alexis Sánchez', team: 'CHI' },
                { name: 'Leon Goretzka', team: 'GER' },
              ],
              golden_glove: [{ name: 'Claudio Bravo', team: 'CHI' }],
              fair_play_team: ['GER'],
            },
          },
        },
        {
          id: 'CONFEDC2013',
          data: {
            year: '2013',
            name: 'FIFA Confederations Cup Brazil 2013',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['BRA'],
              logo_filename: '2013_FIFA_Confederations_Cup_394x417.png',
              start_date: '2013-06-15',
              end_date: '2013-06-30',
              color: '#477c16',
              team_count: 8,
              confed_count: 6,
              venue_count: 6,
              city_count: 6,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '640px-Confed.Cup2013Champions.jpg',
                text: 'Brazil won the competition after beating Spain 3–0 in the final.',
              },
            ],
            final_standings: { champions: 'BRA', runners_up: 'ESP', third_place: ['ITA'], fourth_place: 'URU' },
            statistics: { total_matches: 16, total_goals: 68, attendance: 804659 },
            awards: {
              golden_boot: [{ name: 'Fernando Torres', team: 'ESP', goals: 5, assists: 1, minutes: 273 }],
              silver_boot: [{ name: 'Fred', team: 'BRA', goals: 5, assists: 1, minutes: 423 }],
              bronze_boot: [{ name: 'Neymar', team: 'BRA', goals: 4 }],
              golden_ball: [
                { name: 'Neymar', team: 'BRA' },
                { name: 'Andrés Iniesta', team: 'ESP' },
                { name: 'Paulinho', team: 'BRA' },
              ],
              golden_glove: [{ name: 'Júlio César', team: 'BRA' }],
              fair_play_team: ['ESP'],
            },
          },
        },
        {
          id: 'CONFEDC2009',
          data: {
            year: '2009',
            name: 'FIFA Confederations Cup South Africa 2009',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['RSA'],
              logo_filename: '2009_FIFA_Confederations_Cup_480x527.png',
              start_date: '2009-06-14',
              end_date: '2009-06-28',
              color: '#0c733b',
              team_count: 8,
              confed_count: 6,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Ellis Park Stadium, Johannesburg',
                filename: '640px-Ellis_Park_Stadium.jpg',
                text: 'The Ellis Park Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'BRA', runners_up: 'USA', third_place: ['ESP'], fourth_place: 'RSA' },
            statistics: { total_matches: 16, total_goals: 44, attendance: 584894 },
            awards: {
              golden_boot: [{ name: 'Luís Fabiano', team: 'BRA', goals: 5 }],
              silver_boot: [{ name: 'Fernando Torres', team: 'ESP', goals: 3 }],
              bronze_boot: [{ name: 'David Villa', team: 'ESP', goals: 3 }],
              golden_ball: [
                { name: 'Kaká', team: 'BRA' },
                { name: 'Luís Fabiano', team: 'ESP' },
                { name: 'Clint Dempsey', team: 'USA' },
              ],
              golden_glove: [{ name: 'Tim Howard', team: 'USA' }],
              fair_play_team: ['BRA'],
            },
          },
        },
        {
          id: 'CONFEDC2005',
          data: {
            year: '2005',
            short_year: '2005',
            name: 'FIFA Confederations Cup Germany 2005',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['GER'],
              logo_filename: 'cc_2005.jpg',
              start_date: '2005-06-15',
              end_date: '2005-06-29',
              color: '#281e1d',
              team_count: 8,
              confed_count: 6,
              venue_count: 5,
              city_count: 5,
            },
            hero_images: [
              {
                name: 'Final',
                filename: '640px-Confed-Cup_Finale.jpeg',
                text: 'Brazil vs Argentina',
              },
            ],
            final_standings: { champions: 'BRA', runners_up: 'ARG', third_place: ['GER'], fourth_place: 'MEX' },
            statistics: { total_matches: 16, total_goals: 56, attendance: 603106 },
            awards: {
              golden_boot: [{ name: 'Adriano', team: 'BRA', goals: 5 }],
              silver_boot: [{ name: 'Michael Ballack', team: 'GER', goals: 4 }],
              bronze_boot: [{ name: 'John Aloisi', team: 'AUS', goals: 4 }],
              golden_ball: [
                { name: 'Adriano', team: 'BRA' },
                { name: 'Riquelme', team: 'ARG' },
                { name: 'Ronaldinho', team: 'BRA' },
              ],
              golden_glove: [{ name: 'Oswaldo Sánchez', team: 'MEX' }],
              fair_play_team: ['GRE'],
            },
          },
        },
        {
          id: 'CONFEDC2003',
          data: {
            year: '2003',
            short_year: '2003',
            name: 'FIFA Confederations Cup France 2003',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['FRA'],
              logo_filename: 'cc_2003.jpg',
              start_date: '2003-06-18',
              end_date: '2003-06-29',
              color: '#0015de',
              team_count: 8,
              confed_count: 6,
              venue_count: 3,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Stade de France, Saint-Denis',
                filename: '640px-Finale_Coupe_de_France_2010-2011_(Lille_LOSC_vs_Paris_SG_PSG).jpg',
                text: 'The Stade de France hosted the final.',
              },
            ],
            final_standings: { champions: 'FRA', runners_up: 'CMR', third_place: ['TUR'], fourth_place: 'COL' },
            statistics: { total_matches: 16, total_goals: 37, attendance: 491700 },
            awards: {
              golden_boot: [{ name: 'Thierry Henry', team: 'FRA', goals: 4 }],
              silver_boot: [{ name: 'Tuncay', team: 'TUR', goals: 3, assists: 1 }],
              bronze_boot: [{ name: 'Shunsuke Nakamura', team: 'JPN', goals: 3, assists: 0, minutes: 170 }],
              golden_ball: [
                { name: 'Thierry Henry', team: 'FRA' },
                { name: 'Tuncay', team: 'TUR' },
                { name: 'Marc-Vivien Foé', team: 'CMR' },
              ],
              fair_play_team: ['JPN'],
            },
          },
        },
        {
          id: 'CONFEDC2001',
          data: {
            year: '2001',
            short_year: '2001',
            name: 'FIFA Confederations Cup Korea-Japan 2001',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['KOR', 'JPN'],
              logo_filename: 'cc_2001.jpg',
              start_date: '2001-05-30',
              end_date: '2001-06-10',
              color: '#e2952b',
              team_count: 8,
              confed_count: 6,
              venue_count: 6,
              city_count: 6,
            },
            hero_images: [
              {
                name: 'Niigata Stadium, Niigata',
                filename: '640px-Bigswan080628.jpeg',
                text: 'The Niigata Stadium hosted group B matches.',
              },
            ],
            final_standings: { champions: 'FRA', runners_up: 'JPN', third_place: ['AUS'], fourth_place: 'BRA' },
            statistics: { total_matches: 16, total_goals: 31, attendance: 557191 },
            awards: {
              golden_boot: [{ name: 'Robert Pires', team: 'FRA', goals: 2 }],
              silver_boot: [{ name: 'Éric Carrière', team: 'FRA', goals: 2 }],
              bronze_boot: [{ name: 'Hwang Sun-hong', team: 'KOR', goals: 2 }],
              golden_ball: [
                { name: 'Robert Pires', team: 'FRA' },
                { name: 'Patrick Vieira', team: 'FRA' },
                { name: 'Hidetoshi Nakata', team: 'JPN' },
              ],
              fair_play_team: ['JPN'],
            },
          },
        },
        {
          id: 'CONFEDC1999',
          data: {
            year: '1999',
            short_year: '1999',
            name: 'FIFA Confederations Cup Mexico 1999',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['MEX'],
              logo_filename: 'cc_1999.jpg',
              start_date: '1999-07-24',
              end_date: '1999-08-04',
              color: '#009865',
              team_count: 8,
              confed_count: 6,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Estadio Jalisco, Guadalajara',
                filename: '640px-Estadio_jalisco.jpg',
                text: 'The Estadio Jalisco hosted the semi-final Brazil vs Saudi Arabia.',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'BRA', third_place: ['USA'], fourth_place: 'KSA' },
            statistics: { total_matches: 16, total_goals: 55, attendance: 970000 },
            awards: {
              golden_boot: [{ name: 'Ronaldinho', team: 'BRA', goals: 6 }],
              silver_boot: [{ name: 'Cuauhtémoc Blanco', team: 'MEX', goals: 6 }],
              bronze_boot: [{ name: 'Marzouk Al-Otaibi', team: 'KSA', goals: 6 }],
              golden_ball: [
                { name: 'Ronaldinho', team: 'BRA' },
                { name: 'Cuauhtémoc Blanco', team: 'MEX' },
                { name: 'Marzouk Al-Otaibi', team: 'KSA' },
              ],
              fair_play_team: ['BRA'],
            },
          },
        },
        {
          id: 'CONFEDC1997',
          data: {
            year: '1997',
            short_year: '1997',
            name: 'FIFA Confederations Cup Saudi Arabia 1997',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['KSA'],
              logo_filename: 'cc_1997.png',
              start_date: '1997-12-12',
              end_date: '1997-12-21',
              color: '#177700',
              team_count: 8,
              confed_count: 6,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'King Fahd Stadium, Riyadh',
                filename: '640px-King_Fahd_Int._Stadium-_Opening_Arabian_Gulf_Cup_2014.jpg',
                text: 'The King Fahd Stadium hosted all the tournament matches.',
              },
            ],
            final_standings: { champions: 'BRA', runners_up: 'AUS', third_place: ['CZE'], fourth_place: 'URU' },
            statistics: { total_matches: 16, total_goals: 52, attendance: 333500 },
            awards: {
              golden_boot: [{ name: 'Romário', team: 'BRA', goals: 7 }],
              silver_boot: [{ name: 'Vladimír Šmicer', team: 'CZE', goals: 5 }],
              bronze_boot: [{ name: 'Ronaldo', team: 'BRA', goals: 4 }],
              golden_ball: [
                { name: 'Denílson', team: 'BRA' },
                { name: 'Romário', team: 'BRA' },
                { name: 'Vladimír Šmicer', team: 'CZE' },
              ],
              fair_play_team: ['RSA'],
            },
          },
        },
        {
          id: 'CONFEDC1995',
          data: {
            year: '1995',
            short_year: '1995',
            name: 'King Fahd Cup Saudi Arabia 1995',
            short_name: 'Saudi Arabia 1995',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'penalty'],
            details: {
              host: ['KSA'],
              logo_filename: 'Confederations_Cup.png',
              start_date: '1995-01-06',
              end_date: '1995-01-13',
              color: '#0e4676',
              team_count: 6,
              confed_count: 5,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'King Fahd Stadium, Riyadh',
                filename: '640px-King_Fahd_International_Stadium_(66723825).jpeg',
                text: 'The King Fahd Stadium hosted all the tournament matches.',
              },
            ],
            final_standings: { champions: 'DEN', runners_up: 'ARG', third_place: ['MEX'], fourth_place: 'NGA' },
            statistics: { total_matches: 8, total_goals: 19, attendance: 165000 },
            awards: {
              golden_boot: [{ name: 'Luis García', team: 'MEX', goals: 3 }],
              golden_ball: [{ name: 'Brian Laudrup', team: 'DEN' }],
            },
          },
        },
        {
          id: 'CONFEDC1992',
          data: {
            year: '1992',
            short_year: '1992',
            name: 'King Fahd Cup Saudi Arabia 1992',
            short_name: 'Saudi Arabia 1992',
            competition_id: 'CONFEDC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team', 'head2head', 'lot'],
            details: {
              host: ['KSA'],
              logo_filename: 'Confederations_Cup.png',
              start_date: '1992-10-15',
              end_date: '1992-10-20',
              color: '#9a7633',
              team_count: 4,
              confed_count: 4,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'King Fahd Stadium, Riyadh',
                filename: '640px-King_fahad_staduim.jpg',
                text: 'The King Fahd Stadium hosted all the tournament matches.',
              },
            ],
            final_standings: { champions: 'ARG', runners_up: 'KSA', third_place: ['USA'], fourth_place: 'CIV' },
            statistics: { total_matches: 4, total_goals: 18, attendance: 196500 },
            awards: {
              golden_boot: [
                { name: 'Gabriel Batistuta', team: 'ARG', goals: 2 },
                { name: 'Bruce Murray', team: 'USA', goals: 2 },
              ],
              golden_ball: [{ name: 'Fernando Redondo', team: 'ARG' }],
            },
          },
        },
      ],
    },
    {
      number: '100',
      rows: [
        {
          id: 'USOPEN2017',
          data: {
            name: '2017 US Open',
            tournament_type_id: '',
            start_date: '2017-08-28',
            end_date: '2017-09-10',
            active: false,
          },
        },
        {
          id: 'USOPEN2018',
          data: {
            name: '2018 US Open',
            tournament_type_id: '',
            start_date: '2018-08-27',
            end_date: '2018-09-09',
            active: false,
          },
        },
        {
          id: 'NFL2018',
          data: {
            name: 'National Football League 2018',
            tournament_type_id: 'NFL',
            start_date: '2018-08-03',
            end_date: '2019-02-04',
            active: false,
          },
        },
        {
          id: 'USOPEN2017MS',
          data: {
            name: "2017 US Open Men's Singles",
            tournament_type_id: 'ATP',
            start_date: '2017-08-28',
            end_date: '2017-09-10',
            active: false,
            logo_filename: 'usopen.svg',
            parent_tournament_id: 'USOPEN2017',
          },
        },
        {
          id: 'USOPEN2018MS',
          data: {
            name: "2018 US Open Men's Singles",
            tournament_type_id: 'ATP',
            start_date: '2018-08-27',
            end_date: '2018-09-09',
            active: false,
            logo_filename: 'usopen.svg',
            parent_tournament_id: 'USOPEN2018',
          },
        },
        {
          id: 'USOPEN2018WS',
          data: {
            name: "2018 US Open Women's Singles",
            tournament_type_id: 'WTA',
            start_date: '2018-08-27',
            end_date: '2018-09-09',
            active: false,
            logo_filename: 'usopen.svg',
            parent_tournament_id: 'USOPEN2018',
          },
        },
        {
          id: 'WOFT2016',
          data: {
            name: "Women's Olympic Football Tournament Rio 2016",
            tournament_type_id: 'WOFT',
            start_date: '2016-08-03',
            end_date: '2016-08-20',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: '2016.png',
            points_for_win: 3,
            parent_tournament_id: null,
          },
        },
        {
          id: '2017USOPEN',
          data: {
            name: '2017 US Open',
            tournament_type_id: '',
            start_date: '2017-08-28',
            end_date: '2017-09-10',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: '2017.png',
            points_for_win: 3,
            parent_tournament_id: null,
          },
        },
      ],
    },
  ],
}
