export const AppData = {
  collection: 'tournament',
  batches: [
    {
      number: '10',
      rows: [
        {
          id: 'AAC2015',
          data: {
            name: '2015 AFC Asian Cup Australia',
            tournament_type_id: 'AAC',
            start_date: '2015-01-09',
            end_date: '2015-01-31',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'aac_2015.png',
            points_for_win: 3,
          },
        },
        {
          id: 'AAC2011',
          data: {
            name: '2011 AFC Asian Cup Qatar',
            tournament_type_id: 'AAC',
            start_date: '2011-01-07',
            end_date: '2011-01-29',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'aac_2011.png',
            points_for_win: 3,
          },
        },
        {
          id: 'AAC2007',
          data: {
            name: '2007 AFC Asian Cup Indonesia-Malaysia-Thailand-Vietnam',
            tournament_type_id: 'AAC',
            start_date: '2007-07-07',
            end_date: '2007-07-29',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'aac_2007.png',
            points_for_win: 3,
          },
        },
        {
          id: 'AAC2004',
          data: {
            name: '2004 AFC Asian Cup China',
            tournament_type_id: 'AAC',
            start_date: '2004-07-17',
            end_date: '2004-08-07',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'aac_2004.png',
            points_for_win: 3,
          },
        },
        {
          id: 'AAC2000',
          data: {
            name: '2000 AFC Asian Cup Lebanon',
            tournament_type_id: 'AAC',
            start_date: '2000-10-12',
            end_date: '2000-10-29',
            active: false,
            third_place_ranking: true,
            head_to_head_tiebreaker: false,
            golden_goal_rule: true,
            logo_filename: 'aac_2000.png',
            points_for_win: 3,
          },
        },
        {
          id: 'AAC1996',
          data: {
            name: '1996 AFC Asian Cup United Arab Emirates',
            tournament_type_id: 'AAC',
            start_date: '1996-12-04',
            end_date: '1996-12-21',
            active: false,
            third_place_ranking: true,
            head_to_head_tiebreaker: false,
            golden_goal_rule: true,
            logo_filename: 'aac_1996.png',
            points_for_win: 3,
          },
        },
        {
          id: 'AAC1992',
          data: {
            name: '1992 AFC Asian Cup Japan',
            tournament_type_id: 'AAC',
            start_date: '1992-10-29',
            end_date: '1992-11-08',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1988',
          data: {
            name: '1988 AFC Asian Cup Qatar',
            tournament_type_id: 'AAC',
            start_date: '1988-12-02',
            end_date: '1988-12-18',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1984',
          data: {
            name: '1984 AFC Asian Cup Singapore',
            tournament_type_id: 'AAC',
            start_date: '1984-12-01',
            end_date: '1984-12-16',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1980',
          data: {
            name: '1980 AFC Asian Cup Kuwait',
            tournament_type_id: 'AAC',
            start_date: '1980-09-15',
            end_date: '1980-09-30',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1976',
          data: {
            name: '1976 AFC Asian Cup Iran',
            tournament_type_id: 'AAC',
            start_date: '1976-06-03',
            end_date: '1976-06-13',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1972',
          data: {
            name: '1972 AFC Asian Cup Thailand',
            tournament_type_id: 'AAC',
            start_date: '1972-05-07',
            end_date: '1972-05-19',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1968',
          data: {
            name: '1968 AFC Asian Cup Iran',
            tournament_type_id: 'AAC',
            start_date: '1968-05-10',
            end_date: '1968-05-19',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1964',
          data: {
            name: '1964 AFC Asian Cup Israel',
            tournament_type_id: 'AAC',
            start_date: '1964-05-26',
            end_date: '1964-06-03',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1960',
          data: {
            name: '1960 AFC Asian Cup Korea Republic',
            tournament_type_id: 'AAC',
            start_date: '1960-10-14',
            end_date: '1960-10-23',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC1956',
          data: {
            name: '1956 AFC Asian Cup Hong Kong',
            tournament_type_id: 'AAC',
            start_date: '1956-09-01',
            end_date: '1956-09-15',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'AFC.png',
            points_for_win: 2,
          },
        },
        {
          id: 'AAC2019',
          data: {
            name: '2019 AFC Asian Cup United Arab Emirates',
            tournament_type_id: 'AAC',
            start_date: '2019-01-05',
            end_date: '2019-02-01',
            active: true,
            third_place_ranking: true,
            head_to_head_tiebreaker: true,
            golden_goal_rule: false,
            logo_filename: 'aac_2019.png',
            points_for_win: 3,
          },
        },
      ],
    },
    {
      number: '11',
      rows: [
        {
          id: 'ONC2016',
          data: {
            name: '2016 OFC Nations Cup Papua New Guinea',
            tournament_type_id: 'ONC',
            start_date: '2016-05-28',
            end_date: '2016-06-11',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC2012',
          data: {
            name: '2012 OFC Nations Cup Solomon Islands',
            tournament_type_id: 'ONC',
            start_date: '2012-06-01',
            end_date: '2012-06-10',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC2008',
          data: {
            name: '2008 OFC Nations Cup',
            tournament_type_id: 'ONC',
            start_date: '2007-10-17',
            end_date: '2008-11-19',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC2004',
          data: {
            name: '2004 OFC Nations Cup Australia',
            tournament_type_id: 'ONC',
            start_date: '2004-05-29',
            end_date: '2004-10-12',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC2002',
          data: {
            name: '2002 OFC Nations Cup New Zealand',
            tournament_type_id: 'ONC',
            start_date: '2002-07-05',
            end_date: '2002-07-14',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC2000',
          data: {
            name: '2000 OFC Nations Cup Tahiti',
            tournament_type_id: 'ONC',
            start_date: '2000-06-19',
            end_date: '2000-06-28',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC1998',
          data: {
            name: '1998 OFC Nations Cup Australia',
            tournament_type_id: 'ONC',
            start_date: '1998-09-25',
            end_date: '1998-10-04',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC1996',
          data: {
            name: '1996 OFC Nations Cup',
            tournament_type_id: 'ONC',
            start_date: '1995-11-10',
            end_date: '1996-11-01',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'ONC1980',
          data: {
            name: '1980 OFC Nations Cup New Caledonia',
            tournament_type_id: 'ONC',
            start_date: '1980-02-24',
            end_date: '1980-03-01',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 2,
          },
        },
        {
          id: 'ONC1973',
          data: {
            name: '1973 OFC Nations Cup New Zealand',
            tournament_type_id: 'ONC',
            start_date: '1973-02-17',
            end_date: '1973-02-24',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'OFCcup.png',
            points_for_win: 2,
          },
        },
      ],
    },
    {
      number: '12',
      rows: [
        {
          id: 'CONFEDC2017',
          data: {
            name: '2017 FIFA Confederations Cup Russia',
            tournament_type_id: 'CONFEDC',
            start_date: '2017-06-17',
            end_date: '2017-07-02',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'cc_2017.png',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC2013',
          data: {
            name: '2013 FIFA Confederations Cup Brazil',
            tournament_type_id: 'CONFEDC',
            start_date: '2013-06-15',
            end_date: '2013-06-30',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'cc_2013.png',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC2009',
          data: {
            name: '2009 FIFA Confederations Cup South Africa',
            tournament_type_id: 'CONFEDC',
            start_date: '2009-06-14',
            end_date: '2009-06-28',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'cc_2009.png',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC2005',
          data: {
            name: '2005 FIFA Confederations Cup Germany',
            tournament_type_id: 'CONFEDC',
            start_date: '2005-06-15',
            end_date: '2005-06-29',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'cc_2005.jpg',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC2003',
          data: {
            name: '2003 FIFA Confederations Cup France',
            tournament_type_id: 'CONFEDC',
            start_date: '2003-06-18',
            end_date: '2003-06-29',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: true,
            logo_filename: 'cc_2003.jpg',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC2001',
          data: {
            name: '2001 FIFA Confederations Cup Korea-Japan',
            tournament_type_id: 'CONFEDC',
            start_date: '2001-05-30',
            end_date: '2001-06-10',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: true,
            logo_filename: 'cc_2001.jpg',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC1999',
          data: {
            name: '1999 FIFA Confederations Cup Mexico',
            tournament_type_id: 'CONFEDC',
            start_date: '1999-07-24',
            end_date: '1999-08-04',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: true,
            logo_filename: 'cc_1999.jpg',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC1997',
          data: {
            name: '1997 FIFA Confederations Cup Saudi Arabia',
            tournament_type_id: 'CONFEDC',
            start_date: '1997-12-12',
            end_date: '1997-12-21',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: true,
            logo_filename: 'cc_1997.png',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC1995',
          data: {
            name: '1995 King Fahd Cup Saudi Arabia',
            tournament_type_id: 'CONFEDC',
            start_date: '1995-01-06',
            end_date: '1995-01-13',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: true,
            logo_filename: 'Confederations_Cup.png',
            points_for_win: 3,
          },
        },
        {
          id: 'CONFEDC1992',
          data: {
            name: '1992 King Fahd Cup Saudi Arabia',
            tournament_type_id: 'CONFEDC',
            start_date: '1992-10-15',
            end_date: '1992-10-20',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: 'Confederations_Cup.png',
            points_for_win: 2,
          },
        },
      ],
    },
    {
      number: '13',
      rows: [
        {
          id: 'WC2018',
          data: {
            name: '2018 FIFA World Cup Russia',
            tournament_type_id: 'WC',
            start_date: '2018-06-14',
            end_date: '2018-07-15',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: '2018.png',
            points_for_win: 3,
            color: '#930c10',
            format:
              '{"name":"Russia 2018","stages":[{"name":"Group Phase","type":"roundrobin","groups":[{"name":"Group A","teams":[{"id":"URU"},{"id":"RUS"},{"id":"KSA"},{"id":"EGY"}],"matches":[{"home_team":"RUS","away_team":"KSA","home_score":"5","away_score":"0","date":"2018-06-14","time":"18:00","stadium":"Luzhniki Stadium","city":"Moscow"},{"home_team":"EGY","away_team":"URU","home_score":"0","away_score":"1","date":"2018-06-15","time":"17:00","stadium":"Ekaterinburg Arena","city":"Ekaterinburg"},{"home_team":"RUS","away_team":"EGY","home_score":"3","away_score":"1","date":"2018-06-19","time":"21:00","stadium":"Saint Petersburg Stadium","city":"St. Petersburg"},{"home_team":"URU","away_team":"KSA","home_score":"1","away_score":"0","date":"2018-06-20","time":"18:00","stadium":"Rostov Arena","city":"Rostov-On-Don"},{"home_team":"URU","away_team":"RUS","home_score":"3","away_score":"0","date":"2018-06-25","time":"18:00","stadium":"Samara Arena","city":"Samara"},{"home_team":"KSA","away_team":"EGY","home_score":"2","away_score":"1","date":"2018-06-25","time":"17:00","stadium":"Volgograd Arena","city":"Volgograd"}]},{"name":"Group B","teams":[{"id":"ESP"},{"id":"POR"},{"id":"IRN"},{"id":"MAR"}],"matches":[{"home_team":"MAR","away_team":"IRN","home_score":"0","away_score":"1","date":"2018-06-15","time":"18:00","stadium":"Saint Petersburg Stadium","city":"St. Petersburg"},{"home_team":"POR","away_team":"ESP","home_score":"3","away_score":"3","date":"2018-06-15","time":"21:00","stadium":"Fisht Stadium","city":"Sochi"},{"home_team":"POR","away_team":"MAR","home_score":"1","away_score":"0","date":"2018-06-20","time":"15:00","stadium":"Luzhniki Stadium","city":"Moscow"},{"home_team":"IRN","away_team":"ESP","home_score":"0","away_score":"1","date":"2018-06-20","time":"21:00","stadium":"Kazan Arena","city":"Kazan"},{"home_team":"ESP","away_team":"MAR","home_score":"2","away_score":"2","date":"2018-06-25","time":"20:00","stadium":"Kaliningrad Stadium","city":"Kaliningrad"},{"home_team":"IRN","away_team":"POR","home_score":"1","away_score":"1","date":"2018-06-25","time":"21:00","stadium":"Mordovia Arena","city":"Saransk"}]},{"name":"Group C","teams":[{"id":"FRA"},{"id":"DEN"},{"id":"PER"},{"id":"AUS"}],"matches":[{"home_team":"FRA","away_team":"AUS","home_score":"2","away_score":"1","date":"2018-06-16","time":"13:00","stadium":"Kazan Arena","city":"Kazan"},{"home_team":"PER","away_team":"DEN","home_score":"0","away_score":"1","date":"2018-06-16","time":"19:00","stadium":"Mordovia Arena","city":"Saransk"},{"home_team":"DEN","away_team":"AUS","home_score":"1","away_score":"1","date":"2018-06-21","time":"16:00","stadium":"Samara Arena","city":"Samara"},{"home_team":"FRA","away_team":"PER","home_score":"1","away_score":"0","date":"2018-06-21","time":"20:00","stadium":"Ekaterinburg Arena","city":"Ekaterinburg"},{"home_team":"AUS","away_team":"PER","home_score":"0","away_score":"2","date":"2018-06-26","time":"17:00","stadium":"Fisht Stadium","city":"Sochi"},{"home_team":"DEN","away_team":"FRA","home_score":"0","away_score":"0","date":"2018-06-26","time":"17:00","stadium":"Luzhniki Stadium","city":"Moscow"}]},{"name":"Group D","teams":[{"id":"CRO"},{"id":"ARG"},{"id":"NGA"},{"id":"ISL"}],"matches":[{"home_team":"ARG","away_team":"ISL","home_score":"1","away_score":"1","date":"2018-06-16","time":"16:00","stadium":"Spartak Stadium","city":"Moscow"},{"home_team":"CRO","away_team":"NGA","home_score":"2","away_score":"0","date":"2018-06-16","time":"21:00","stadium":"Kaliningrad Stadium","city":"Kaliningrad"},{"home_team":"ARG","away_team":"CRO","home_score":"0","away_score":"3","date":"2018-06-21","time":"21:00","stadium":"Nizhny Novgorod Stadium","city":"Nizhny Novgorod"},{"home_team":"NGA","away_team":"ISL","home_score":"2","away_score":"0","date":"2018-06-22","time":"18:00","stadium":"Volgograd Arena","city":"Volgograd"},{"home_team":"NGA","away_team":"ARG","home_score":"1","away_score":"2","date":"2018-06-26","time":"21:00","stadium":"Saint Petersburg Stadium","city":"St. Petersburg"},{"home_team":"ISL","away_team":"CRO","home_score":"1","away_score":"2","date":"2018-06-26","time":"21:00","stadium":"Rostov Arena","city":"Rostov-On-Don"}]},{"name":"Group E","teams":[{"id":"BRA"},{"id":"SUI"},{"id":"SRB"},{"id":"CRC"}],"matches":[{"home_team":"CRC","away_team":"SRB","home_score":"0","away_score":"1","date":"2018-06-17","time":"16:00","stadium":"Samara Arena","city":"Samara"},{"home_team":"BRA","away_team":"SUI","home_score":"1","away_score":"1","date":"2018-06-17","time":"21:00","stadium":"Rostov Arena","city":"Rostov-On-Don"},{"home_team":"BRA","away_team":"CRC","home_score":"2","away_score":"0","date":"2018-06-22","time":"15:00","stadium":"Saint Petersburg Stadium","city":"St. Petersburg"},{"home_team":"SRB","away_team":"SUI","home_score":"1","away_score":"2","date":"2018-06-22","time":"20:00","stadium":"Kaliningrad Stadium","city":"Kaliningrad"},{"home_team":"SRB","away_team":"BRA","home_score":"0","away_score":"2","date":"2018-06-27","time":"21:00","stadium":"Spartak Stadium","city":"Moscow"},{"home_team":"SUI","away_team":"CRC","home_score":"2","away_score":"2","date":"2018-06-27","time":"21:00","stadium":"Nizhny Novgorod Stadium","city":"Nizhny Novgorod"}]},{"name":"Group F","teams":[{"id":"SWE"},{"id":"MEX"},{"id":"KOR"},{"id":"GER"}],"matches":[{"home_team":"GER","away_team":"MEX","home_score":"0","away_score":"1","date":"2018-06-17","time":"18:00","stadium":"Luzhniki Stadium","city":"Moscow"},{"home_team":"SWE","away_team":"KOR","home_score":"1","away_score":"0","date":"2018-06-18","time":"15:00","stadium":"Nizhny Novgorod Stadium","city":"Nizhny Novgorod"},{"home_team":"KOR","away_team":"MEX","home_score":"1","away_score":"2","date":"2018-06-23","time":"18:00","stadium":"Rostov Arena","city":"Rostov-On-Don"},{"home_team":"GER","away_team":"SWE","home_score":"2","away_score":"1","date":"2018-06-23","time":"21:00","stadium":"Fisht Stadium","city":"Sochi"},{"home_team":"KOR","away_team":"GER","home_score":"2","away_score":"0","date":"2018-06-27","time":"17:00","stadium":"Kazan Arena","city":"Kazan"},{"home_team":"MEX","away_team":"SWE","home_score":"0","away_score":"3","date":"2018-06-27","time":"19:00","stadium":"Ekaterinburg Arena","city":"Ekaterinburg"}]},{"name":"Group G","teams":[{"id":"BEL"},{"id":"ENG"},{"id":"TUN"},{"id":"PAN"}],"matches":[{"home_team":"BEL","away_team":"PAN","home_score":"3","away_score":"0","date":"2018-06-18","time":"18:00","stadium":"Fisht Stadium","city":"Sochi"},{"home_team":"TUN","away_team":"ENG","home_score":"1","away_score":"2","date":"2018-06-18","time":"21:00","stadium":"Volgograd Arena","city":"Volgograd"},{"home_team":"BEL","away_team":"TUN","home_score":"5","away_score":"2","date":"2018-06-23","time":"15:00","stadium":"Spartak Stadium","city":"Moscow"},{"home_team":"ENG","away_team":"PAN","home_score":"6","away_score":"1","date":"2018-06-24","time":"15:00","stadium":"Nizhny Novgorod Stadium","city":"Nizhny Novgorod"},{"home_team":"PAN","away_team":"TUN","home_score":"1","away_score":"2","date":"2018-06-28","time":"21:00","stadium":"Mordovia Arena","city":"Saransk"},{"home_team":"ENG","away_team":"BEL","home_score":"0","away_score":"1","date":"2018-06-28","time":"20:00","stadium":"Kaliningrad Stadium","city":"Kaliningrad"}]},{"name":"Group H","teams":[{"id":"COL"},{"id":"JPN"},{"id":"SEN"},{"id":"POL"}],"matches":[{"home_team":"COL","away_team":"JPN","home_score":"1","away_score":"2","date":"2018-06-19","time":"15:00","stadium":"Mordovia Arena","city":"Saransk"},{"home_team":"POL","away_team":"SEN","home_score":"1","away_score":"2","date":"2018-06-19","time":"18:00","stadium":"Spartak Stadium","city":"Moscow"},{"home_team":"JPN","away_team":"SEN","home_score":"2","away_score":"2","date":"2018-06-24","time":"20:00","stadium":"Ekaterinburg Arena","city":"Ekaterinburg"},{"home_team":"POL","away_team":"COL","home_score":"0","away_score":"3","date":"2018-06-24","time":"21:00","stadium":"Kazan Arena","city":"Kazan"},{"home_team":"JPN","away_team":"POL","home_score":"0","away_score":"1","date":"2018-06-28","time":"17:00","stadium":"Volgograd Arena","city":"Volgograd"},{"home_team":"SEN","away_team":"COL","home_score":"0","away_score":"1","date":"2018-06-28","time":"18:00","stadium":"Samara Arena","city":"Samara"}]}]},{"name":"Knockout Phase","type":"knockout","rounds":[{"name":"Round of 16","matches":[{"home_team":"FRA","away_team":"ARG","home_score":"4","away_score":"3","date":"2018-06-30","time":"17:00","stadium":"Kazan Arena","city":"Kazan"},{"home_team":"URU","away_team":"POR","home_score":"2","away_score":"1","date":"2018-06-30","time":"21:00","stadium":"Fisht Stadium","city":"Sochi"},{"home_team":"ESP","away_team":"RUS","home_score":"1","away_score":"1","home_extra_score":"0","away_extra_score":"0","home_penalty_score":"3","away_penalty_score":"4","date":"2018-07-01","time":"17:00","stadium":"Luzhniki Stadium","city":"Moscow"},{"home_team":"CRO","away_team":"DEN","home_score":"1","away_score":"1","home_extra_score":"0","away_extra_score":"0","home_penalty_score":"3","away_penalty_score":"2","date":"2018-07-01","time":"21:00","stadium":"Nizhny Novgorod Stadium","city":"Nizhny Novgorod"},{"home_team":"BRA","away_team":"MEX","home_score":"2","away_score":"0","date":"2018-07-02","time":"18:00","stadium":"Samara Arena","city":"Samara"},{"home_team":"BEL","away_team":"JPN","home_score":"3","away_score":"2","date":"2018-07-02","time":"18:00","stadium":"Rostov Arena","city":"Rostov-On-Don"},{"home_team":"SWE","away_team":"SUI","home_score":"1","away_score":"0","date":"2018-07-03","time":"17:00","stadium":"Saint Petersburg Stadium","city":"St. Petersburg"},{"home_team":"COL","away_team":"ENG","home_score":"1","away_score":"1","home_extra_score":"0","away_extra_score":"0","home_penalty_score":"3","away_penalty_score":"4","date":"2018-07-03","time":"21:00","stadium":"Spartak Stadium","city":"Moscow"}]},{"name":"Quarterfinals","matches":[{"home_team":"URU","away_team":"FRA","home_score":"0","away_score":"2","date":"2018-07-06","time":"17:00","stadium":"Nizhny Novgorod Stadium","city":"Nizhny Novgorod"},{"home_team":"BRA","away_team":"BEL","home_score":"1","away_score":"2","date":"2018-07-06","time":"21:00","stadium":"Kazan Arena","city":"Kazan"},{"home_team":"SWE","away_team":"ENG","home_score":"0","away_score":"2","date":"2018-07-07","time":"18:00","stadium":"Samara Arena","city":"Samara"},{"home_team":"RUS","away_team":"CRO","home_score":"2","away_score":"2","home_extra_score":"0","away_extra_score":"0","home_penalty_score":"3","away_penalty_score":"4","date":"2018-07-07","time":"21:00","stadium":"Fisht Stadium","city":"Sochi"}]},{"name":"Semifinals","matches":[{"home_team":"FRA","away_team":"BEL","home_score":"1","away_score":"0","date":"2018-07-10","time":"21:00","stadium":"Saint Petersburg Stadium","city":"St. Petersburg"},{"home_team":"CRO","away_team":"END","home_score":"1","away_score":"1","home_extra_score":"1","away_extra_score":"0","date":"2018-07-11","time":"21:00","stadium":"Luzhniki Stadium","city":"Moscow"}]},{"name":"Third place","matches":[{"home_team":"BEL","away_team":"ENG","home_score":"2","away_score":"0","date":"2018-07-14","time":"17:00","stadium":"Saint Petersburg Stadium","city":"St. Petersburg"}]},{"name":"Final","matches":[{"home_team":"FRA","away_team":"CRO","home_score":"4","away_score":"2","date":"2018-07-15","time":"18:00","stadium":"Luzhniki Stadium","city":"Moscow"}]}]}]}',
          },
        },
      ],
    },
    {
      number: '100',
      rows: [
        {
          id: 'WOFT2016',
          data: {
            name: "Women's Olympic Football Tournament Rio 2016",
            tournament_type_id: 'WOFT',
            start_date: '2016-08-03',
            end_date: '2016-08-20',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: '2016.png',
            points_for_win: 3,
            parent_tournament_id: null,
          },
        },
        {
          id: '2017USOPEN',
          data: {
            name: '2017 US Open',
            tournament_type_id: '',
            start_date: '2017-08-28',
            end_date: '2017-09-10',
            active: false,
            third_place_ranking: false,
            head_to_head_tiebreaker: false,
            golden_goal_rule: false,
            logo_filename: '2017.png',
            points_for_win: 3,
            parent_tournament_id: null,
          },
        },
      ],
    },
  ],
}
