export const AppData = {
  collection: 'tournament',
  batches: [
    {
      number: '8',
      rows: [
        {
          id: 'GC2021',
          data: {
            year: '2021',
            short_year: '2021',
            name: 'Gold Cup 2021 United States',
            short_name: '2021 United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'fairplay', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: 'Concacaf_Gold_Cup_2021_480x329.png',
              start_date: '2021-07-10',
              end_date: '2021-08-01',
              color: '#d39534',
              team_count: 16,
              confed_count: 2,
              venue_count: 10,
              city_count: 9,
            },
            hero_images: [
              {
                name: 'Allegiant Stadium, Paradise',
                filename: '640px-Allegiantstadiumjune2020.jpg',
                text: 'The Allegiant Stadium in Paradise hosted the final United States vs Mexico.',
              },
            ],
            final_standings: { champions: 'USA', runners_up: 'MEX', semi_finalist1: 'CAN', semi_finalist2: 'QAT' },
            statistics: { total_matches: 31, total_goals: 89 },
            awards: {
              golden_boot: [{ name: 'Almoez Ali', team: 'QAT', goals: 4 }],
              golden_ball: [{ name: 'Héctor Herrera', team: 'MEX' }],
              best_young_player: [{ name: 'Tajon Buchanan', team: 'CAN' }],
              golden_glove: [{ name: 'Matt Turner', team: 'USA' }],
              fair_play_team: ['USA'],
            },
          },
        },
        {
          id: 'GC2019',
          data: {
            year: '2019',
            short_year: '2019',
            name: 'Gold Cup 2019 United States-Costa Rica-Jamaica',
            short_name: '2019 United States-Costa Rica-Jamaica',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2head', 'fairplay', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA', 'CRC', 'JAM'],
              logo_filename: '2019_CONCACAF_Gold_Cup_480x215.png',
              start_date: '2019-06-15',
              end_date: '2019-07-07',
              color: '#e6bf7a',
              team_count: 16,
              confed_count: 1,
              venue_count: 17,
              city_count: 16,
            },
            hero_images: [
              {
                name: 'Soldier Field, Chicago',
                filename: '640px-UsavsHonduras.jpeg',
                text: 'The Soldier Field in Chicago hosted the final.',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'USA', semi_finalist1: 'HAI', semi_finalist2: 'JAM' },
            statistics: { total_matches: 31, total_goals: 96, attendance: 1043168 },
            awards: {
              golden_boot: [{ name: 'Jonathan David', team: 'CAN', goals: 6 }],
              golden_ball: [{ name: 'Raúl Jiménez', team: 'MEX' }],
              best_young_player: [{ name: 'Christian Pulisic', team: 'USA' }],
              golden_glove: [{ name: 'Guillermo Ochoa', team: 'MEX' }],
              fair_play_team: ['USA'],
            },
          },
        },
        {
          id: 'GC2017',
          data: {
            year: '2017',
            short_year: '2017',
            name: 'Gold Cup 2017 United States',
            short_name: '2017 United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2headpoints', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: '2017_CONCACAF_Gold_Cup_480x217.png',
              start_date: '2017-07-07',
              end_date: '2017-07-26',
              color: '#eb1821',
              team_count: 12,
              confed_count: 1,
              venue_count: 14,
              city_count: 14,
            },
            hero_images: [
              {
                name: 'Opening game',
                filename: 'French_Guiana_on_the_Big_Stage_at_Long_Last.jpg',
                text: 'In Red Bull Arena, French Guiana is in action against Canada as French Guiana attempts a corner kick during a 2017 CONCACAF Gold Cup match on July 7, 2017. This match was not only the opening game of the 2017 CONCACAF Gold Cup, but it was also the first every match at a major international tournament for French Guiana.',
              },
            ],
            final_standings: { champions: 'USA', runners_up: 'JAM', semi_finalist1: 'CRC', semi_finalist2: 'MEX' },
            statistics: { total_matches: 25, total_goals: 55, attendance: 875667 },
            awards: {
              golden_boot: [
                { name: 'Alphonso Davies', team: 'CAN', goals: 3 },
                { name: 'Kévin Parsemain', team: 'MTQ-2019', goals: 3 },
                { name: 'Jordan Morris', team: 'USA', goals: 3 },
              ],
              golden_ball: [{ name: 'Michael Bradley', team: 'USA' }],
              best_young_player: [{ name: 'Alphonso Davies', team: 'CAN' }],
              golden_glove: [{ name: 'Andre Blake', team: 'JAM' }],
              fair_play_team: ['USA'],
            },
          },
        },
        {
          id: 'GC2015',
          data: {
            year: '2015',
            short_year: '2015',
            name: 'Gold Cup 2015 United States-Canada',
            short_name: 'United States-Canada',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2headpoints', 'lot'],
            details: {
              host: ['USA', 'CAN'],
              logo_filename: 'CONCACAF_Gold_Cup_2015_480x217.png',
              start_date: '2015-07-07',
              end_date: '2015-07-26',
              color: '#f72337',
              team_count: 12,
              confed_count: 1,
              venue_count: 14,
              city_count: 14,
            },
            hero_images: [
              {
                name: 'United States vs Cuba',
                filename: '640px-USMNT_players_lineup_vs_Cuba_2015_Gold_Cup_Baltimore.jpg',
                text: 'USMNT Gold Cup Baltimore',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'JAM', third_place: ['PAN'], fourth_place: 'USA' },
            statistics: { total_matches: 26, total_goals: 62, attendance: 1090396 },
            awards: {
              golden_boot: [{ name: 'Clint Dempsey', team: 'USA', goals: 7 }],
              golden_ball: [{ name: 'Andrés Guardado', team: 'MEX' }],
              best_young_player: [{ name: 'Jesús Manuel Corona', team: 'MEX' }],
              golden_glove: [{ name: 'Brad Guzan', team: 'USA' }],
              fair_play_team: ['JAM'],
            },
          },
        },
        {
          id: 'GC2013',
          data: {
            year: '2013',
            short_year: '2013',
            name: 'Gold Cup 2013 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team', 'head2headpoints', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: '2013_CONCACAF_Gold_Cup_480x212.png',
              start_date: '2013-07-07',
              end_date: '2013-07-28',
              color: '#0f246a',
              team_count: 12,
              confed_count: 1,
              venue_count: 13,
              city_count: 13,
            },
            hero_images: [
              {
                name: 'Final',
                filename: '640px-Gold_Cup_2013_final_in_Chicago_(cropped).jpeg',
                text: 'USA vs Panama, Gold Cup 2013 final at Soldier Field in Chicago, July 28, 2013',
              },
            ],
            final_standings: { champions: 'USA', runners_up: 'PAN', semi_finalist1: 'HON', semi_finalist2: 'MEX' },
            statistics: { total_matches: 25, total_goals: 67, attendance: 907208 },
            awards: {
              golden_boot: [
                { name: 'Gabriel Torres', team: 'PAN', goals: 5 },
                { name: 'Landon Donovan', team: 'USA', goals: 5 },
                { name: 'Chris Wondolowski', team: 'USA', goals: 5 },
              ],
              golden_ball: [{ name: 'Landon Donovan', team: 'USA' }],
              golden_glove: [{ name: 'Jaime Penedo', team: 'PAN' }],
              fair_play_team: ['PAN'],
            },
          },
        },
        {
          id: 'GC2011',
          data: {
            year: '2011',
            short_year: '2011',
            name: 'Gold Cup 2011 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: 'gc_2011.png',
              start_date: '2011-06-05',
              end_date: '2011-06-25',
              color: '#e6bf7a',
              team_count: 12,
              confed_count: 1,
              venue_count: 13,
              city_count: 13,
            },
            hero_images: [
              {
                name: 'RFK Stadium, Washington, D.C.',
                filename: '640px-Rfkstadium.png',
                text: 'The RFK Stadium hosted 2 quarter-finals.',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'USA', semi_finalist1: 'HON', semi_finalist2: 'PAN' },
            statistics: { total_matches: 25, total_goals: 80, attendance: 1140602 },
            awards: {
              golden_boot: [{ name: 'Javier Hernández', team: 'MEX', goals: 7 }],
              golden_ball: [{ name: 'Javier Hernández', team: 'MEX' }],
              golden_glove: [{ name: 'Noel Valladares', team: 'HON' }],
              fair_play_team: ['MEX'],
            },
          },
        },
        {
          id: 'GC2009',
          data: {
            year: '2009',
            short_year: '2009',
            name: 'Gold Cup 2009 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: '2009_CONCACAF_Gold_Cup_logo_480x218.png',
              start_date: '2009-07-03',
              end_date: '2009-07-26',
              color: '#eb1821',
              team_count: 12,
              confed_count: 1,
              venue_count: 13,
              city_count: 13,
            },
            hero_images: [
              {
                name: 'Semi-final',
                filename: '640px-MexicovsCostaRica.jpeg',
                text: 'Mexico vs Costa Rica',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'USA', semi_finalist1: 'CRC', semi_finalist2: 'HON' },
            statistics: { total_matches: 25, total_goals: 66, attendance: 860046 },
            awards: {
              golden_boot: [{ name: 'Miguel Sabah', team: 'MEX', goals: 4 }],
              golden_ball: [{ name: 'Giovani dos Santos', team: 'MEX' }],
              golden_glove: [{ name: 'Keylor Navas', team: 'CRC' }],
              fair_play_team: ['USA'],
            },
          },
        },
        {
          id: 'GC2007',
          data: {
            year: '2007',
            short_year: '2007',
            name: 'Gold Cup 2007 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: '2007_CONCACAF_Gold_Cup_logo_480x219.png',
              start_date: '2007-06-06',
              end_date: '2007-06-24',
              color: '#0f246a',
              team_count: 12,
              confed_count: 1,
              venue_count: 6,
              city_count: 6,
            },
            hero_images: [
              {
                name: 'The Home Depot Center, Carson',
                filename: '640px-HomeDepotCenter1.jpg',
                text: 'The Home Depot Center hosted group B matches.',
              },
            ],
            final_standings: { champions: 'USA', runners_up: 'MEX', semi_finalist1: 'CAN', semi_finalist2: 'GLP' },
            statistics: { total_matches: 25, total_goals: 64, attendance: 921464 },
            awards: {
              golden_boot: [{ name: 'Carlos Pavón', team: 'HON', goals: 5 }],
              golden_ball: [{ name: 'Julian de Guzman', team: 'CAN' }],
              golden_glove: [{ name: 'Franck Grandel', team: 'GLP' }],
              fair_play_team: ['HON'],
            },
          },
        },
        {
          id: 'GC2005',
          data: {
            year: '2005',
            short_year: '2005',
            name: 'Gold Cup 2005 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: '2005_CONCACAF_Gold_Cup_logo_480x221.png',
              start_date: '2005-07-06',
              end_date: '2005-07-24',
              color: '#e6bf7a',
              team_count: 12,
              confed_count: 3,
              venue_count: 7,
              city_count: 7,
            },
            hero_images: [
              {
                name: 'Giants Stadium, East Rutherford',
                filename: '640px-NY_Red_Bulls_vs_LA_Galaxy.jpg',
                text: 'The Giants Stadium hosted the final',
              },
            ],
            final_standings: { champions: 'USA', runners_up: 'PAN', semi_finalist1: 'COL', semi_finalist2: 'HON' },
            statistics: { total_matches: 25, total_goals: 73, attendance: 340018 },
            awards: {
              golden_boot: [
                { name: 'DaMarcus Beasley', team: 'USA', goals: 3 },
                { name: 'Landon Donovan', team: 'USA', goals: 3 },
                { name: 'Carlos Ruiz', team: 'GUA', goals: 3 },
                { name: 'Luis Tejada', team: 'PAN', goals: 3 },
                { name: 'Wilmer Velasquez', team: 'HON', goals: 3 },
              ],
              golden_ball: [{ name: 'Luis Tejada', team: 'PAN' }],
              golden_glove: [{ name: 'Jaime Penedo', team: 'PAN' }],
              fair_play_team: ['HON'],
            },
          },
        },
        {
          id: 'GC2003',
          data: {
            year: '2003',
            name: 'Gold Cup 2003 United States-Mexico',
            short_name: 'United States-Mexico',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['USA', 'MEX'],
              logo_filename: '2003_CONCACAF_Gold_Cup_logo_480x419.png',
              start_date: '2003-07-12',
              end_date: '2003-07-27',
              color: '#24a45f',
              team_count: 12,
              confed_count: 2,
              venue_count: 3,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Estadio Azteca, Mexico City',
                filename: '640px-Estadio_Azteca_07a.jpg',
                text: 'The Estadio Azteca hosted the final',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'BRA', third_place: ['USA'], fourth_place: 'CRC' },
            statistics: { total_matches: 20, total_goals: 50 },
            awards: {
              golden_boot: [
                { name: 'Walter Centeno', team: 'CRC', goals: 4 },
                { name: 'Landon Donovan', team: 'USA', goals: 4 },
              ],
              golden_ball: [{ name: 'Jesús Arellano', team: 'MEX' }],
              golden_glove: [{ name: 'Oswaldo Sánchez', team: 'MEX' }],
              fair_play_team: ['USA'],
            },
          },
        },
        {
          id: 'GC2002',
          data: {
            year: '2002',
            name: 'Gold Cup 2002 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'lot'],
            details: {
              host: ['USA'],
              logo_filename: 'gc_2002.png',
              start_date: '2002-01-18',
              end_date: '2002-02-02',
              color: '#eb1821',
              team_count: 12,
              confed_count: 3,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Rose Bowl, Pasadena',
                filename: '640px-Rose_Bowl,_panorama.jpg',
                text: 'The Rose Bowl hosted the final',
              },
            ],
            final_standings: { champions: 'USA', runners_up: 'CRC', third_place: ['CAN'], fourth_place: 'KOR' },
            statistics: { total_matches: 20, total_goals: 39 },
            awards: {
              golden_boot: [{ name: 'Brian McBride', team: 'USA', goals: 4 }],
              golden_ball: [{ name: 'Brian McBride', team: 'USA' }],
              golden_glove: [{ name: 'Lars Hirschfeld', team: 'CAN' }],
              fair_play_team: ['CRC'],
            },
          },
        },
        {
          id: 'GC2000',
          data: {
            year: '2000',
            name: 'Gold Cup 2000 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team', 'lot'],
            no_third_place: true,
            details: {
              host: ['USA'],
              logo_filename: 'gc_2000.png',
              start_date: '2000-02-12',
              end_date: '2000-02-27',
              color: '#0f246a',
              team_count: 12,
              confed_count: 3,
              venue_count: 3,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Qualcomm Stadium, San Diego',
                filename: '640px-Qualcomm_Stadium.jpg',
                text: 'The Qualcomm Stadium hosted the semi-final Colombia vs Peru.',
              },
            ],
            final_standings: { champions: 'CAN', runners_up: 'COL', semi_finalist1: 'PER', semi_finalist2: 'TRI' },
            statistics: { total_matches: 19, total_goals: 55, attendance: 695087 },
            awards: {
              golden_boot: [{ name: 'Carlo Corazzin', team: 'CAN', goals: 4 }],
              golden_ball: [{ name: 'Craig Forrest', team: 'CAN' }],
              best_young_player: [{ name: 'Richard Hastings', team: 'CAN' }],
              golden_glove: [{ name: 'Craig Forrest', team: 'CAN' }],
              fair_play_team: ['CAN'],
            },
          },
        },
        {
          id: 'GC1998',
          data: {
            year: '1998',
            name: 'Gold Cup 1998 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['USA'],
              logo_filename: 'gc_1998.png',
              start_date: '1998-02-01',
              end_date: '1998-02-15',
              color: '#e6bf7a',
              team_count: 10,
              confed_count: 2,
              venue_count: 3,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Los Angeles Memorial Coliseum, Los Angeles',
                filename: '640px-L.A._Memorial_Coliseum_Entrance.jpeg',
                text: 'The Los Angeles Memorial Coliseum hosted the final',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'USA', third_place: ['BRA'], fourth_place: 'JAM' },
            statistics: { total_matches: 16, total_goals: 44 },
            awards: {
              golden_boot: [
                { name: 'Paulo Wanchope', team: 'CRC', goals: 4 },
                { name: 'Luis Hernández', team: 'MEX', goals: 4 },
              ],
              golden_ball: [{ name: 'Kasey Keller', team: 'USA' }],
            },
          },
        },
        {
          id: 'GC1996',
          data: {
            year: '1996',
            name: 'Gold Cup 1996 United States',
            short_name: 'United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['USA'],
              logo_filename: 'gc_1996.png',
              start_date: '1996-01-10',
              end_date: '1996-01-21',
              color: '#eb1821',
              team_count: 9,
              confed_count: 2,
              venue_count: 3,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Anaheim Stadium, Anaheim',
                filename: '544px-Anaheim_Stadium_1986.jpg',
                text: 'The Anaheim Stadium hosted group C matches.',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'BRA', third_place: ['USA'], fourth_place: 'GUA' },
            statistics: { total_matches: 13, total_goals: 42, attendance: 487439 },
            awards: {
              golden_boot: [{ name: 'Eric Wynalda', team: 'USA', goals: 4 }],
              golden_ball: [{ name: 'Raúl Lara', team: 'MEX' }],
            },
          },
        },
        {
          id: 'GC1993',
          data: {
            year: '1993',
            name: 'Gold Cup 1993 United States-Mexico',
            short_name: 'United States-Mexico',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: true,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['USA', 'MEX'],
              logo_filename: 'gc_1993.jpg',
              start_date: '1993-07-10',
              end_date: '1993-07-25',
              color: '#24a45f',
              team_count: 8,
              confed_count: 1,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Cotton Bowl, Dallas',
                filename: '640px-Image_of_TX_OU_Red_River_Shootout_in_Cotton_Bowl_seen_from_fair_grounds_-_original.jpg',
                text: 'The Cotton Bowl hosted group A matches.',
              },
            ],
            final_standings: {
              champions: 'MEX',
              runners_up: 'USA',
              third_place: ['CRC', 'JAM'],
              third_place_text: 'Tied 1-1 at the end of extra time. Both teams shared the third place.',
            },
            statistics: { total_matches: 16, total_goals: 60, attendance: 709348 },
            awards: {
              golden_boot: [{ name: 'Zaguinho', team: 'MEX', goals: 11 }],
              golden_ball: [{ name: 'Ramón Ramírez', team: 'MEX' }],
            },
          },
        },
        {
          id: 'GC1991',
          data: {
            year: '1991',
            short_year: '1991',
            name: 'Gold Cup 1991 United States',
            short_name: '1991 United States',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['USA'],
              logo_filename: 'gc_1991.jpg',
              start_date: '1991-06-28',
              end_date: '1991-07-07',
              color: '#0f246a',
              team_count: 8,
              confed_count: 1,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Memorial Coliseum, Los Angeles',
                filename: '640px-11-11-06-LA-Coliseum-USC-UO.jpg',
                text: 'The Memorial Coliseum hosted the final.',
              },
            ],
            final_standings: { champions: 'USA', runners_up: 'HON', third_place: ['MEX'], fourth_place: 'CRC' },
            statistics: { total_matches: 16, total_goals: 50, attendance: 397124 },
            awards: {
              golden_boot: [{ name: 'Benjamín Galindo', team: 'MEX', goals: 4 }],
              golden_ball: [{ name: 'Tony Meola', team: 'USA' }],
            },
          },
        },
        {
          id: 'GC1989',
          data: {
            year: '1989',
            short_year: '1989',
            name: 'CONCACAF Championship 1989',
            short_name: '1989',
            era: 'CONCACAF Championship',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              logo_filename: 'Concacaf_logo.png',
              start_date: '1989-03-19',
              end_date: '1989-11-19',
              color: '#d5ba81',
              team_count: 5,
              confed_count: 1,
            },
            hero_images: [
              {
                name: 'National Stadium, Port of Spain',
                filename: '640px-HCStadium2013.jpg',
                text: 'National Stadium, Port of Spain, Trinidad and Tobago',
              },
            ],
            final_standings: { champions: 'CRC', runners_up: 'USA', third_place: ['TRI'], fourth_place: 'GUA' },
            statistics: { total_matches: 18, total_goals: 29 },
            awards: {
              golden_boot: [
                { name: 'Evaristo Coronado', team: 'CRC', goals: 2 },
                { name: 'Juan Arnoldo Cayasso', team: 'CRC', goals: 2 },
                { name: 'Leónidas Flores', team: 'CRC', goals: 2 },
                { name: 'Raúl Chacón', team: 'GUA', goals: 2 },
                { name: 'Julio Rodas', team: 'GUA', goals: 2 },
                { name: 'Leonson Lewis', team: 'TRI', goals: 2 },
                { name: 'Kerry Jamerson', team: 'TRI', goals: 2 },
                { name: 'Philibert Jones', team: 'TRI', goals: 2 },
              ],
            },
          },
        },
        {
          id: 'GC1985',
          data: {
            year: '1985',
            short_year: '1985',
            name: 'CONCACAF Championship 1985',
            short_name: '1985',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              logo_filename: 'Concacaf_logo.png',
              start_date: '1985-02-24',
              end_date: '1985-09-14',
              color: '#d5ba81',
              team_count: 9,
              confed_count: 1,
            },
            hero_images: [
              {
                name: 'Estadio Cuscatlán, San Salvador, El Salvador',
                filename: '640px-Monumental_Estadio_Cuscatlan.jpg',
                text: 'Estadio Cuscatlán, San Salvador, El Salvador',
              },
            ],
            final_standings: { champions: 'CAN', runners_up: 'HON', third_place: ['CRC'], fourth_place: 'SLV' },
            statistics: { total_matches: 24, total_goals: 54 },
            awards: {
              golden_boot: [{ name: 'Roberto Figueroa', team: 'HON', goals: 5 }],
            },
          },
        },
        {
          id: 'GC1981',
          data: {
            year: '1981',
            short_year: '1981',
            name: 'CONCACAF Championship 1981 Honduras',
            short_name: '1981 Honduras',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['HON'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1981-11-01',
              end_date: '1981-11-22',
              color: '#1d5f9a',
              team_count: 6,
              confed_count: 1,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Estadio Tiburcio Carías Andino, Tegucigalpa',
                filename: '640px-Estadio_Carias.jpg',
                text: 'The national stadium of Honduras in Tegucigalpa (Estadio Nacional de Tegucigalpa) also known as Estadio Tiburcio Carías Andino.',
              },
            ],
            final_standings: { champions: 'HON', runners_up: 'SLV', third_place: ['MEX'], fourth_place: 'CAN' },
            statistics: { total_matches: 15, total_goals: 28 },
            awards: {
              golden_boot: [{ name: 'Hugo Sánchez', team: 'MEX', goals: 3 }],
            },
          },
        },
        {
          id: 'GC1977',
          data: {
            year: '1977',
            short_year: '1977',
            name: 'CONCACAF Championship 1977 Mexico',
            short_name: '1977 Mexico',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['MEX'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1977-10-08',
              end_date: '1977-10-23',
              color: '#24a45f',
              team_count: 6,
              confed_count: 1,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Estadio Universitario, Monterrey',
                filename: '640px-Estadio_Universitario_UANL.jpg',
                text: 'Estadio Universitario, Monterrey',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'HAI-1964-1986', third_place: ['SLV'], fourth_place: 'CAN' },
            statistics: { total_matches: 15, total_goals: 55 },
            awards: {
              golden_boot: [{ name: 'Víctor Rangel', team: 'MEX', goals: 6 }],
            },
          },
        },
        {
          id: 'GC1973',
          data: {
            year: '1973',
            short_year: '1973',
            name: 'CONCACAF Championship 1973 Haiti',
            short_name: '1973 Haiti',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['HAI-1964-1986'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1973-11-29',
              end_date: '1973-12-18',
              color: '#01209f',
              team_count: 6,
              confed_count: 1,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Stade Sylvio Cator, Port-au-Prince',
                filename: '640px-Stade_Sylvio_Cator_after_earthquake_2010.jpg',
                text: 'The Stade Sylvio Cator hosted all of the tournament matches.',
              },
            ],
            final_standings: { champions: 'HAI-1964-1986', runners_up: 'TRI', third_place: ['MEX'], fourth_place: 'HON' },
            statistics: { total_matches: 15, total_goals: 43 },
            awards: {
              golden_boot: [{ name: 'Steve David', team: 'TRI', goals: 7 }],
            },
          },
        },
        {
          id: 'GC1971',
          data: {
            year: '1971',
            short_year: '1971',
            name: 'CONCACAF Championship 1971 Trinidad and Tobago',
            short_name: '1971 Trinidad and Tobago',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['TRI'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1971-11-20',
              end_date: '1971-12-05',
              color: '#fa2200',
              team_count: 6,
              confed_count: 1,
              venue_count: 4,
              city_count: 3,
            },
            hero_images: [
              {
                name: 'Arima Velodrome, Arima',
                filename: '640px-TnT_Arima_Velodrome_1.jpg',
                text: 'Arima Velodrome, Arima',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'HAI-1964-1986', third_place: ['CRC'], fourth_place: 'CUB' },
            statistics: { total_matches: 15, total_goals: 37 },
          },
        },
        {
          id: 'GC1969',
          data: {
            year: '1969',
            short_year: '1969',
            name: 'CONCACAF Championship 1969 Costa Rica',
            short_name: '1969 Costa Rica',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['CRC'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1969-11-23',
              end_date: '1969-12-07',
              color: '#2251a2',
              team_count: 6,
              confed_count: 1,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Estadio Nacional, San José, Costa Rica',
                filename: '640px-Estadio_nacional_costarica.jpg',
                text: 'Estadio Nacional, San José, Costa Rica',
              },
            ],
            final_standings: { champions: 'CRC', runners_up: 'GUA', third_place: ['ANT-1959-1986'], fourth_place: 'MEX' },
            statistics: { total_matches: 15, total_goals: 43 },
            awards: {
              golden_boot: [{ name: 'Victor Manuel Ruiz', team: 'CRC', goals: 4 }],
              silver_boot: [
                { name: 'Nelson Melgar', team: 'GUA', goals: 3 },
                { name: 'Marco Fión', team: 'GUA', goals: 3 },
              ],
            },
          },
        },
        {
          id: 'GC1967',
          data: {
            year: '1967',
            short_year: '1967',
            name: 'CONCACAF Championship 1967 Honduras',
            short_name: '1967 Honduras',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['HON'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1967-03-05',
              end_date: '1967-03-19',
              color: '#1d5f9a',
              team_count: 6,
              confed_count: 1,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Estadio Tiburcio Carías Andino, Tegucigalpa',
                filename: '640px-Estadio_Carias.jpg',
                text: 'The national stadium of Honduras in Tegucigalpa (Estadio Nacional de Tegucigalpa) also known as Estadio Tiburcio Carías Andino.',
              },
            ],
            final_standings: { champions: 'GUA', runners_up: 'MEX', third_place: ['HON'], fourth_place: 'TRI' },
            statistics: { total_matches: 15, total_goals: 35 },
            awards: {
              golden_boot: [
                { name: 'Luis Estrada', team: 'MEX', goals: 4 },
                { name: 'Manuel Recinos', team: 'GUA', goals: 4 },
              ],
            },
          },
        },
        {
          id: 'GC1965',
          data: {
            year: '1965',
            short_year: '1965',
            name: 'CONCACAF Championship 1965 Guatemala',
            short_name: '1965 Guatemala',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['GUA'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1965-03-28',
              end_date: '1965-04-11',
              color: '#5795de',
              team_count: 6,
              confed_count: 1,
            },
            hero_images: [
              {
                name: 'Estadio Mateo Flores, Guatemala City',
                filename: '640px-Estadio_Mateo_Flores_Guatemala.jpeg',
                text: 'Estadio Mateo Flores, Guatemala City',
              },
            ],
            final_standings: { champions: 'MEX', runners_up: 'GUA', third_place: ['CRC'], fourth_place: 'SLV' },
            statistics: { total_matches: 15, total_goals: 49 },
            awards: {
              golden_boot: [{ name: 'Ernesto Cisneros', team: 'MEX', goals: 5 }],
            },
          },
        },
        {
          id: 'GC1963',
          data: {
            year: '1963',
            short_year: '1963',
            name: 'CONCACAF Championship 1963 El Salvador',
            short_name: '1963 El Salvador',
            competition_id: 'GC',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['SLV'],
              logo_filename: 'Concacaf_logo.png',
              start_date: '1963-03-23',
              end_date: '1963-04-07',
              color: '#2470b4',
              team_count: 9,
              confed_count: 1,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Estadio Nacional Flor Blanca, San Salvador',
                filename: '640px-ESTADIO_Magico_Gonzales.jpeg',
                text: 'Estadio Nacional Flor Blanca, San Salvador',
              },
            ],
            final_standings: { champions: 'CRC', runners_up: 'SLV', third_place: ['ANT-1959-1986'], fourth_place: 'HON' },
            statistics: { total_matches: 22, total_goals: 76 },
            awards: {
              golden_boot: [{ name: 'Eduardo Hernández', team: 'SLV', goals: 6 }],
            },
          },
        },
      ],
    },
    {
      number: '9',
      rows: [
        {
          id: 'AFCON2019',
          data: {
            year: '2019',
            short_year: '2019',
            name: 'Africa Cup of Nations Egypt 2019',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'head2headreapply', 'goaldifferenceandgoalscored', 'lot'],
            details: {
              host: ['EGY'],
              logo_filename: '2019_Africa_Cup_of_Nations_logo_480x634.png',
              mascot_filename: '_Tut,_Africa_Cup_of_Nations_Egypt_2019_Mascot,_May_2019_.jpeg',
              start_date: '2019-06-21',
              end_date: '2019-07-19',
              color: '#ca0b0f',
              team_count: 24,
              venue_count: 6,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '806px-V3f2uf9o_algeria-win-afcon-afp_625x300_20_July_19.webp.png',
                text: 'Algeria',
              },
            ],
            final_standings: { champions: 'ALG', runners_up: 'SEN', third_place: ['NGA'], fourth_place: 'TUN' },
            statistics: { total_matches: 52, total_goals: 102, attendance: 943053 },
            awards: {
              golden_boot: [{ name: 'Odion Ighalo', team: 'NGA', goals: 5 }],
              golden_ball: [{ name: 'Ismaël Bennacer', team: 'ALG' }],
              best_young_player: [{ name: 'Krépin Diatta', team: 'SEN' }],
              golden_glove: [{ name: "Raïs M'Bolhi", team: 'ALG' }],
              fair_play_team: ['SEN'],
            },
          },
        },
        {
          id: 'AFCON2017',
          data: {
            year: '2017',
            short_year: '2017',
            name: 'Africa Cup of Nations Gabon 2017',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'head2headreapply', 'goaldifferenceandgoalscored', 'lot'],
            details: {
              host: ['GAB'],
              logo_filename: 'afcon_2017.png',
              mascot_filename: '12472337_1013610275372599_3491603779303180603_n.png',
              start_date: '2017-01-14',
              end_date: '2017-02-05',
              color: '#3775b8',
              team_count: 16,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '640px-Cameroon_celebrating_winning_2017_Africa_Cup_of_Nations_(cropped).jpg',
                text: 'Cameroon celebrating winning 2017 Africa Cup of Nation',
              },
            ],
            final_standings: { champions: 'CMR', runners_up: 'EGY', third_place: ['BFA'], fourth_place: 'GHA' },
            statistics: { total_matches: 32, total_goals: 66 },
            awards: {
              golden_boot: [{ name: 'Junior Kabananga', team: 'COD', goals: 3 }],
              golden_ball: [{ name: 'Christian Bassogog', team: 'CMR' }],
              fair_play_team: ['EGY'],
            },
          },
        },
        {
          id: 'AFCON2015',
          data: {
            year: '2015',
            short_year: '2015',
            name: 'Africa Cup of Nations Equatorial Guinea 2015',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'head2headreapply', 'goaldifferenceandgoalscored', 'lot'],
            details: {
              host: ['EQG'],
              logo_filename: 'afcon_2015.png',
              mascot_filename: '2021640_mascot_pnglarge_jpeg8f784e2506d7c8ba43738faf6eb50334.jpeg',
              start_date: '2015-01-17',
              end_date: '2015-02-08',
              color: '#2470b5',
              team_count: 16,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '640px-Acon_final_2015_(16331506630).jpg',
                text: 'Ivory Coast celebrating winning 2015 Africa Cup of Nation',
              },
            ],
            final_standings: { champions: 'CIV', runners_up: 'GHA', third_place: ['COD'], fourth_place: 'EQG' },
            statistics: { total_matches: 32, total_goals: 68, attendance: 617374 },
            awards: {
              golden_boot: [
                { name: 'André Ayew', team: 'GHA', goals: 3 },
                { name: 'Ahmed Akaïchi', team: 'TUN', goals: 3 },
                { name: 'Javier Balboa', team: 'EQG', goals: 3 },
                { name: 'Thievy Bifouma', team: 'CGO', goals: 3 },
                { name: 'Dieumerci Mbokani', team: 'COD', goals: 3 },
              ],
              golden_ball: [{ name: 'Christian Atsu', team: 'GHA' }],
              golden_glove: [{ name: 'Sylvain Gbohouo', team: 'CIV' }],
              fair_play_team: ['COD'],
            },
          },
        },
        {
          id: 'AFCON2013',
          data: {
            year: '2013',
            short_year: '2013',
            name: 'Africa Cup of Nations South Africa 2013',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'fairplay', 'lot'],
            details: {
              host: ['RSA'],
              logo_filename: 'afcon_2013.png',
              mascot_filename: '11750_401983089894620_2026646383_n.png',
              start_date: '2013-01-19',
              end_date: '2013-02-10',
              color: '#0d8a5f',
              team_count: 16,
              venue_count: 5,
              city_count: 5,
            },
            hero_images: [
              {
                name: 'Champions',
                filename: '640px-A_la_coupe_dAfrique_des_Nations.jpg',
                text: 'Nigeria celebrating winning 2013 Africa Cup of Nation',
              },
            ],
            final_standings: { champions: 'NGA', runners_up: 'BFA', third_place: ['MLI'], fourth_place: 'GHA' },
            statistics: { total_matches: 32, total_goals: 69, attendance: 729000 },
            awards: {
              golden_boot: [
                { name: 'Emmanuel Emenike', team: 'NGA', goals: 4 },
                { name: 'Mubarak Wakaso', team: 'GHA', goals: 4 },
              ],
              golden_ball: [{ name: 'Jonathan Pitroipa', team: 'BFA' }],
            },
          },
        },
        {
          id: 'AFCON2012',
          data: {
            year: '2012',
            short_year: '2012',
            name: 'Africa Cup of Nations Gabon-Equatorial Guinea 2012',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'fairplay', 'lot'],
            details: {
              host: ['GAB', 'EQG'],
              logo_filename: 'afcon_2012.png',
              mascot_filename: 'high_1297629038.jpg',
              start_date: '2012-01-21',
              end_date: '2012-02-12',
              color: '#3775b8',
              team_count: 16,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Estadio de Bata, Bata',
                filename: '640px-Estadio_de_Bata_(15896737884).jpg',
                text: 'The Estadio de Bata hosted the semi-final Zambia vs Ghana',
              },
            ],
            final_standings: { champions: 'ZAM', runners_up: 'CIV', third_place: ['MLI'], fourth_place: 'GHA' },
            statistics: { total_matches: 32, total_goals: 76, attendance: 456332 },
            awards: {
              golden_boot: [
                { name: 'Emmanuel Mayuka', team: 'ZAM', goals: 3 },
                { name: 'Manucho', team: 'ANG', goals: 3 },
                { name: 'Pierre-Emerick Aubameyang', team: 'GAB', goals: 3 },
                { name: 'Didier Drogba', team: 'CIV', goals: 3 },
                { name: 'Cheick Diabaté', team: 'MLI', goals: 3 },
                { name: 'Houssine Kharja', team: 'MAR', goals: 3 },
                { name: 'Christopher Katongo', team: 'ZAM', goals: 3 },
              ],
              golden_ball: [{ name: 'Christopher Katongo', team: 'ZAM' }],
              fair_play_team: ['CIV'],
            },
          },
        },
        {
          id: 'AFCON2010',
          data: {
            year: '2010',
            short_year: '2010',
            name: 'Africa Cup of Nations Angola 2010',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'fairplay', 'lot'],
            details: {
              host: ['ANG'],
              logo_filename: '2010_Africa_Cup_of_Nations_logo_480x650.png',
              mascot_filename: 'Palanquinha.svg',
              start_date: '2010-01-10',
              end_date: '2010-01-31',
              color: '#fa2200',
              team_count: 15,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Sign',
                filename: '640px-Sign_for_African_Nations_Cup.jpg',
                text: 'Countdown to the Africa Cup soccer tournament to be hosted in Angola at the end of the year.',
              },
            ],
            final_standings: { champions: 'EGY', runners_up: 'GHA', third_place: ['NGA'], fourth_place: 'ALG' },
            statistics: { total_matches: 29, total_goals: 71, attendance: 543500 },
            awards: {
              golden_boot: [{ name: 'Gedo', team: 'EGY', goals: 5 }],
              golden_ball: [{ name: 'Ahmed Hassan', team: 'EGY' }],
              golden_glove: [{ name: 'Essam El-Hadary', team: 'EGY' }],
            },
          },
        },
        {
          id: 'AFCON2008',
          data: {
            year: '2008',
            name: 'Africa Cup of Nations Ghana 2008',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'lot'],
            details: {
              host: ['GHA'],
              logo_filename: '2008_Africa_Cup_of_Nations_logo_480x770.png',
              start_date: '2008-01-20',
              end_date: '2008-02-10',
              color: '#237832',
              team_count: 16,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              { name: 'Tamale Stadium, Tamale', filename: 'Stadium_tamale2.jpg', text: 'The Tamale Stadium hosted the quarter-final Tunisia vs Cameroon.' },
            ],
            final_standings: { champions: 'EGY', runners_up: 'CMR', third_place: ['GHA'], fourth_place: 'CIV' },
            statistics: { total_matches: 32, total_goals: 99, attendance: 714000 },
            awards: {
              golden_boot: [{ name: "Samuel Eto'o", team: 'CMR', goals: 5 }],
              golden_ball: [{ name: 'Hosny Abd Rabo', team: 'EGY' }],
              golden_glove: [{ name: 'Essam El-Hadary', team: 'EGY' }],
            },
          },
        },
        {
          id: 'AFCON2006',
          data: {
            year: '2006',
            name: 'Africa Cup of Nations Egypt 2006',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'goaldifferenceandgoalscored', 'lot'],
            details: {
              host: ['EGY'],
              logo_filename: '2006_Africa_Cup_of_Nations_logo_480x776.png',
              mascot_filename: 'Croconile.jpg',
              start_date: '2006-01-20',
              end_date: '2006-02-10',
              color: '#ca0b0f',
              team_count: 16,
              venue_count: 6,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Cairo International Stadium, Cairo',
                filename: 'Crowd_in_Cairo_Stadium.jpg',
                text: 'The Cairo International Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'EGY', runners_up: 'CIV', third_place: ['NGA'], fourth_place: 'SEN' },
            statistics: { total_matches: 32, total_goals: 73, attendance: 714054 },
            awards: {
              golden_boot: [{ name: "Samuel Eto'o", team: 'CMR', goals: 5 }],
              golden_ball: [{ name: 'Ahmed Hassan', team: 'EGY' }],
            },
          },
        },
        {
          id: 'AFCON2004',
          data: {
            year: '2004',
            name: 'Africa Cup of Nations Tunisia 2004',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['points', 'head2head', 'head2headreapply', 'goaldifferenceandgoalscored', 'lot'],
            details: {
              host: ['TUN'],
              logo_filename: '2004_Africa_Cup_of_Nations_logo_480x1253.png',
              start_date: '2004-01-24',
              end_date: '2004-02-14',
              color: '#0089cc',
              team_count: 16,
              venue_count: 6,
              city_count: 6,
            },
            hero_images: [
              {
                name: 'Stade Olympique de Radès, Radès',
                filename: '640px-Tunisia_-_Netherlands_(Stade_de_Rades).jpg',
                text: 'The Stade Olympique de Radès hosted the final.',
              },
            ],
            final_standings: { champions: 'TUN', runners_up: 'MAR', third_place: ['NGA'], fourth_place: 'MLI' },
            statistics: { total_matches: 32, total_goals: 88, attendance: 553500 },
            awards: {
              golden_boot: [
                { name: 'Frédéric Kanouté', team: 'MLI', goals: 4 },
                { name: 'Patrick Mboma', team: 'CMR', goals: 4 },
                { name: 'Jay-Jay Okocha', team: 'NGA', goals: 4 },
                { name: 'Francileudo Santos', team: 'TUN', goals: 4 },
              ],
              golden_ball: [{ name: 'Jay-Jay Okocha', team: 'NGA' }],
            },
          },
        },
        {
          id: 'AFCON2002',
          data: {
            year: '2002',
            short_year: '2002',
            name: 'Africa Cup of Nations Mali 2002',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['MLI'],
              logo_filename: 'afcon_2002.png',
              start_date: '2002-01-19',
              end_date: '2002-02-10',
              color: '#29398c',
              team_count: 16,
              venue_count: 6,
              city_count: 5,
            },
            hero_images: [
              {
                name: 'Stade Modibo Kéïta, Bamako',
                filename: '640px-Stade_modibo_keita.jpg',
                text: 'The Stade Modibo Kéïta hosted the semi-final Nigeria vs Senegal.',
              },
            ],
            final_standings: { champions: 'CMR', runners_up: 'SEN', third_place: ['NGA'], fourth_place: 'MLI' },
            statistics: { total_matches: 32, total_goals: 48, attendance: 570000 },
            awards: {
              golden_boot: [
                { name: 'Julius Aghahowa', team: 'NGA', goals: 3 },
                { name: 'Patrick Mboma', team: 'CMR', goals: 3 },
                { name: 'Salomon Olembé', team: 'CMR', goals: 3 },
              ],
              golden_ball: [{ name: 'Rigobert Song', team: 'CMR' }],
            },
          },
        },
        {
          id: 'AFCON2000',
          data: {
            year: '2000',
            short_year: '2000',
            name: 'Africa Cup of Nations Ghana-Nigeria 2000',
            short_name: 'Ghana-Nigeria 2000',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['GHA', 'NGA'],
              logo_filename: 'afcon_2000.png',
              start_date: '2000-01-22',
              end_date: '2000-02-13',
              color: '#008040',
              team_count: 16,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Accra Sports Stadium, Accra, Ghana',
                filename: '40px-Ohene_Djan_stadium,_Accra.jpg',
                text: 'The Accra Sports Stadium hosted the semi-final Cameroon vs Tunisia.',
              },
            ],
            final_standings: { champions: 'CMR', runners_up: 'NGA', third_place: ['RSA'], fourth_place: 'TUN' },
            statistics: { total_matches: 32, total_goals: 73, attendance: 677500 },
            awards: {
              golden_boot: [{ name: 'Shaun Bartlett', team: 'RSA', goals: 5 }],
              golden_ball: [{ name: 'Lauren', team: 'CMR' }],
            },
          },
        },
        {
          id: 'AFCON1998',
          data: {
            year: '1998',
            short_year: '1998',
            name: 'Africa Cup of Nations Burkina Faso 1998',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['BFA'],
              logo_filename: 'afcon_1998.png',
              start_date: '1998-02-07',
              end_date: '1998-02-28',
              color: '#fa2200',
              team_count: 16,
              venue_count: 3,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Stade Municipal, Bobo-Dioulasso',
                filename: '640px-Stadiumbobodioulasso1.jpg',
                text: 'The Stade Municipal hosted the semi-final Burkina Faso vs Egypt.',
              },
            ],
            final_standings: { champions: 'EGY', runners_up: 'RSA', third_place: ['COD-1997-2003'], fourth_place: 'BFA' },
            statistics: { total_matches: 32, total_goals: 93, attendance: 412800 },
            awards: {
              golden_boot: [
                { name: 'Hossam Hassan', team: 'EGY', goals: 7 },
                { name: 'Benni McCarthy', team: 'RSA', goals: 7 },
              ],
              golden_ball: [{ name: 'Benni McCarthy', team: 'RSA' }],
            },
          },
        },
        {
          id: 'AFCON1996',
          data: {
            year: '1996',
            short_year: '1996',
            name: 'Africa Cup of Nations South Africa 1996',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 3,
            tiebreakers: ['team'],
            details: {
              host: ['RSA'],
              logo_filename: 'afcon_1996.jpg',
              start_date: '1996-01-13',
              end_date: '1996-02-03',
              color: '#178338',
              team_count: 15,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Kings Park Stadium, Durban',
                filename: '640px-Kings_Park_Stadium,_Durban.jpg',
                text: 'The Kings Park Stadium hosted the semi-final Zambia vs Tunisia.',
              },
            ],
            final_standings: { champions: 'RSA', runners_up: 'TUN', third_place: ['ZAM'], fourth_place: 'GHA' },
            statistics: { total_matches: 29, total_goals: 78, attendance: 640880 },
            awards: {
              golden_boot: [{ name: 'Kalusha Bwalya', team: 'ZAM', goals: 5 }],
              golden_ball: [{ name: 'Kalusha Bwalya', team: 'ZAM' }],
            },
          },
        },
        {
          id: 'AFCON1994',
          data: {
            year: '1994',
            short_year: '1994',
            name: 'Africa Cup of Nations Tunisia 1994',
            short_name: 'Tunisia 1994',
            active: false,
            golden_goal_rule: false,
            competition_id: 'AFCON',
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['TUN'],
              logo_filename: '1994_African_Cup_of_Nations_logo.jpg',
              start_date: '1994-03-26',
              end_date: '1994-04-10',
              color: '#fa2200',
              team_count: 12,
              venue_count: 3,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Stade El Menzah, Tunis',
                filename: '640px-Stade_Olympique_dEl_Menzah.jpg',
                text: 'The Stade El Menzah hosted the final.',
              },
            ],
            final_standings: { champions: 'NGA', runners_up: 'ZAM', third_place: ['CIV'], fourth_place: 'MLI' },
            statistics: { total_matches: 20, total_goals: 44, attendance: 273000 },
            awards: {
              golden_boot: [{ name: 'Rashidi Yekini', team: 'NGA', goals: 5 }],
              golden_ball: [{ name: 'Rashidi Yekini', team: 'NGA' }],
            },
          },
        },
        {
          id: 'AFCON1992',
          data: {
            year: '1992',
            short_year: '1992',
            name: 'Africa Cup of Nations Senegal 1992',
            short_name: 'Senegal 1992',
            active: false,
            golden_goal_rule: false,
            competition_id: 'AFCON',
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['SEN'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1992-01-12',
              end_date: '1992-01-26',
              color: '#24a45f',
              team_count: 12,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: "Stade de l'Amitié, Dakar",
                filename: '640px-Senegal_1_-_Cameroon_0_-_Stade_Leopold_Sedar_Senghor.jpg',
                text: "The Stade de l'Amitié hosted the final.",
              },
            ],
            final_standings: { champions: 'CIV', runners_up: 'GHA', third_place: ['NGA'], fourth_place: 'CMR' },
            statistics: { total_matches: 20, total_goals: 34 },
            awards: {
              golden_boot: [{ name: 'Rashidi Yekini', team: 'NGA', goals: 4 }],
              golden_ball: [{ name: 'Abedi Pele', team: 'GHA' }],
              golden_glove: [{ name: 'Alain Gouaméné', team: 'CIV' }],
            },
          },
        },
        {
          id: 'AFCON1990',
          data: {
            year: '1990',
            name: 'Africa Cup of Nations Algeria 1990',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['ALG'],
              logo_filename: 'afcon_1990.png',
              start_date: '1990-03-02',
              end_date: '1990-03-16',
              color: '#c80724',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Stade 19 Mai 1956, Annaba',
                filename: '640px-Stade_19_Mai_1956_(Annaba).jpg',
                text: 'The Stade 19 Mai 1956 hosted the semi-final Zambia vs Nigeria.',
              },
            ],
            final_standings: { champions: 'ALG', runners_up: 'NGA', third_place: ['ZAM'], fourth_place: 'SEN' },
            statistics: { total_matches: 16, total_goals: 30, attendance: 768000 },
            awards: {
              golden_boot: [{ name: 'Djamel Menad', team: 'ALG', goals: 4 }],
              golden_ball: [{ name: 'Rabah Madjer', team: 'ALG' }],
            },
          },
        },
        {
          id: 'AFCON1988',
          data: {
            year: '1988',
            short_year: '1988',
            name: 'Africa Cup of Nations Morocco 1988',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team', 'lot'],
            details: {
              host: ['MAR'],
              logo_filename: 'afcon_1988.png',
              start_date: '1988-03-13',
              end_date: '1988-03-27',
              color: '#f55535',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Stade Mohamed V, Casablanca',
                filename: '640px-Raja_de_Casablanca_vs_Mouloudia_dOujda,_November_02_2008-04.jpg',
                text: 'The Stade Mohamed V hosted the final.',
              },
            ],
            final_standings: { champions: 'CMR', runners_up: 'NGA', third_place: ['ALG'], fourth_place: 'MAR' },
            statistics: { total_matches: 16, total_goals: 23 },
            awards: {
              golden_boot: [
                { name: 'Lakhdar Belloumi', team: 'ALG', goals: 2 },
                { name: 'Roger Milla', team: 'CMR', goals: 2 },
                { name: 'Gamal Abdelhamid', team: 'EGY', goals: 2 },
                { name: 'Abdoulaye Traoré', team: 'CIV', goals: 2 },
              ],
              golden_ball: [{ name: 'Aziz Bouderbala', team: 'MAR' }],
              golden_glove: [{ name: 'Joseph-Antoine Bell', team: 'CMR' }],
            },
          },
        },
        {
          id: 'AFCON1986',
          data: {
            year: '1986',
            name: 'Africa Cup of Nations Egypt 1986',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['EGY'],
              logo_filename: 'CAN_1986_(logo).png',
              start_date: '1986-03-07',
              end_date: '1986-03-21',
              color: '#ca0b0f',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Cairo International Stadium, Cairo',
                filename: 'In_Cairo_Stadium.jpg',
                text: 'The Cairo International Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'EGY', runners_up: 'CMR', third_place: ['CIV'], fourth_place: 'MAR' },
            statistics: { total_matches: 16, total_goals: 31 },
            awards: {
              golden_boot: [{ name: 'Roger Milla', team: 'CMR', goals: 4 }],
              golden_ball: [{ name: 'Roger Milla', team: 'CMR' }],
            },
          },
        },
        {
          id: 'AFCON1984',
          data: {
            year: '1984',
            short_year: '1984',
            name: 'Africa Cup of Nations Ivory Coast 1984',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['CIV'],
              logo_filename: 'afcon_1984.png',
              start_date: '1984-03-04',
              end_date: '1984-03-18',
              color: '#e98611',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Stade Félix Houphouët-Boigny, Abidjan',
                filename: '640px-StadeFHB.jpg',
                text: 'The Stade Félix Houphouët-Boigny hosted the final.',
              },
            ],
            final_standings: { champions: 'CMR', runners_up: 'NGA', third_place: ['ALG'], fourth_place: 'EGY' },
            statistics: { total_matches: 16, total_goals: 39 },
            awards: {
              golden_boot: [{ name: 'Taher Abouzaid', team: 'EGY', goals: 4 }],
              golden_ball: [{ name: 'Théophile Abega', team: 'CMR' }],
              golden_glove: [{ name: 'Joseph-Antoine Bell', team: 'CMR' }],
            },
          },
        },
        {
          id: 'AFCON1982',
          data: {
            year: '1982',
            short_year: '1982',
            name: 'Africa Cup of Nations Libya 1982',
            short_name: 'Libya 1982',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['LBY-1977-2011'],
              logo_filename: 'afcon_1982.png',
              start_date: '1982-03-05',
              end_date: '1982-03-19',
              color: '#01004b',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: '11 June Stadium, Tripoli',
                filename: '11_June_Stadium_BenTaher.jpg',
                text: 'The 11 June Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'GHA', runners_up: 'LBY-1977-2011', third_place: ['ZAM'], fourth_place: 'ALG' },
            statistics: { total_matches: 16, total_goals: 32 },
            awards: {
              golden_boot: [{ name: 'George Alhassan', team: 'GHA', goals: 4 }],
              golden_ball: [{ name: 'Fawzi Al-Issawi', team: 'LBY-1977-2011' }],
            },
          },
        },
        {
          id: 'AFCON1980',
          data: {
            year: '1980',
            short_year: '1980',
            name: 'Africa Cup of Nations Nigeria 1980',
            short_name: 'Nigeria 1980',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['NGA'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1980-03-08',
              end_date: '1980-03-22',
              color: '#568629',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Sango, Ibadan, Nigeria',
                filename: '640px-Nigerias_Oyo_state,_Ibadan_has_beautiful_place_by_kingknx.jpg',
                text: 'Sango, Ibadan, Nigeria',
              },
            ],
            final_standings: { champions: 'NGA', runners_up: 'ALG', third_place: ['MAR'], fourth_place: 'EGY' },
            statistics: { total_matches: 16, total_goals: 33 },
            awards: {
              golden_boot: [
                { name: 'Khaled Labied', team: 'MAR', goals: 3 },
                { name: 'Segun Odegbami', team: 'NGA', goals: 3 },
              ],
              golden_ball: [{ name: 'Christian Chukwu', team: 'NGA' }],
            },
          },
        },
        {
          id: 'AFCON1978',
          data: {
            year: '1978',
            short_year: '1978',
            name: 'Africa Cup of Nations Ghana 1978',
            short_name: 'Ghana 1978',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['GHA'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1978-03-05',
              end_date: '1978-03-16',
              color: '#fa2200',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Baba Yara Stadium, Kumasi',
                filename: '640px-Kumasi924.jpeg',
                text: 'The Baba Yara Stadium hosted the semi-final Uganda vs Nigeria.',
              },
            ],
            final_standings: { champions: 'GHA', runners_up: 'UGA', third_place: ['NGA'], fourth_place: 'TUN' },
            statistics: { total_matches: 16, total_goals: 38 },
            awards: {
              golden_boot: [
                { name: 'Opoku Afriyie', team: 'GHA', goals: 3 },
                { name: 'Segun Odegbami', team: 'NGA', goals: 3 },
                { name: 'Phillip Omondi', team: 'UGA', goals: 3 },
              ],
              golden_ball: [{ name: 'Karim Abdul Razak', team: 'GHA' }],
            },
          },
        },
        {
          id: 'AFCON1976',
          data: {
            year: '1976',
            short_year: '1976',
            name: 'Africa Cup of Nations Ethiopia 1976',
            short_name: 'Ethiopia 1976',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['ETH-1975-1987'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1976-02-29',
              end_date: '1976-03-14',
              color: '#078930',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Addis Ababa Stadium, Addis Ababa',
                filename: 'Addis_Ababa_Stadium.jpg',
                text: 'The Addis Ababa Stadium hosted the final round.',
              },
            ],
            final_standings: { champions: 'MAR', runners_up: 'GUI', third_place: ['NGA'], fourth_place: 'EGY' },
            statistics: { total_matches: 18, total_goals: 54 },
            awards: {
              golden_boot: [{ name: 'Mamadou Aliou Keïta', team: 'GUI', goals: 4 }],
              golden_ball: [{ name: 'Ahmed Faras', team: 'MAR' }],
            },
          },
        },
        {
          id: 'AFCON1974',
          data: {
            year: '1974',
            short_year: '1974',
            name: 'Africa Cup of Nations Egypt 1974',
            short_name: 'Egypt 1974',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['EGY'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1974-03-01',
              end_date: '1974-03-14',
              color: '#ca0b0f',
              team_count: 8,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Cairo International Stadium, Cairo',
                filename: '640px-Cairo_International_Stadium.jpg',
                text: 'The Cairo International Stadium hosted the final.',
              },
            ],
            final_standings: { champions: 'ZAI', runners_up: 'ZAM', third_place: ['EGY'], fourth_place: 'CGO-1970-1991' },
            statistics: { total_matches: 17, total_goals: 54 },
            awards: {
              golden_boot: [{ name: 'Ndaye Mulamba', team: 'ZAI', goals: 9 }],
              golden_ball: [{ name: 'Ndaye Mulamba', team: 'ZAI' }],
            },
          },
        },
        {
          id: 'AFCON1972',
          data: {
            year: '1972',
            short_year: '1972',
            name: 'Africa Cup of Nations Cameroon 1972',
            short_name: 'Cameroon 1972',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['CMR-1961-1975'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1972-02-23',
              end_date: '1972-03-05',
              color: '#24a45f',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Stade Omnisports, Yaoundé',
                filename: '640px-Ahmadou_Ahidjo_stadium-2.jpg',
                text: 'The Stade Omnisports hosted the final.',
              },
            ],
            final_standings: { champions: 'CGO-1970-1991', runners_up: 'MLI', third_place: ['CMR-1961-1975'], fourth_place: 'ZAI' },
            statistics: { total_matches: 16, total_goals: 53 },
            awards: {
              golden_boot: [{ name: 'Fantamady Keita', team: 'MLI', goals: 5 }],
              golden_ball: [{ name: "François M'Pelé", team: 'CGO-1970-1991' }],
            },
          },
        },
        {
          id: 'AFCON1970',
          data: {
            year: '1970',
            short_year: '1970',
            name: 'Africa Cup of Nations Sudan 1970',
            short_name: 'Sudan 1970',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['SDN-1956-1970'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1970-02-06',
              end_date: '1970-02-16',
              color: '#fa2200',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Khartoum, Sudan',
                filename: 'Khartoumdowntown.jpg',
                text: 'Khartoum at night',
              },
            ],
            final_standings: { champions: 'SDN-1956-1970', runners_up: 'GHA', third_place: ['UAR'], fourth_place: 'CIV' },
            statistics: { total_matches: 16, total_goals: 51 },
            awards: {
              golden_boot: [{ name: 'Laurent Pokou', team: 'CIV', goals: 8 }],
              golden_ball: [{ name: 'Laurent Pokou', team: 'CIV' }],
            },
          },
        },
        {
          id: 'AFCON1968',
          data: {
            year: '1968',
            short_year: '1968',
            name: 'Africa Cup of Nations Ethiopia 1968',
            short_name: 'Ethiopia 1968',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['ETH-1941-1974'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1968-01-12',
              end_date: '1968-01-21',
              color: '#0e9061',
              team_count: 8,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Hailé Sélassié Stadium, Addis Ababa',
                filename: '640px-ET_Addis_asv2018-01_img02_Stadium.jpg',
                text: 'The Hailé Sélassié Stadium hosted the final',
              },
            ],
            final_standings: { champions: 'COD-1966-1971', runners_up: 'GHA', third_place: ['CIV'], fourth_place: 'ETH-1941-1974' },
            statistics: { total_matches: 16, total_goals: 52 },
            awards: {
              golden_boot: [{ name: 'Laurent Pokou', team: 'CIV', goals: 6 }],
              golden_ball: [{ name: 'Kazadi Mwamba', team: 'COD-1966-1971' }],
            },
          },
        },
        {
          id: 'AFCON1965',
          data: {
            year: '1965',
            short_year: '1965',
            name: 'Africa Cup of Nations Tunisia 1965',
            short_name: 'Tunisia 1965',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['pointslot'],
            details: {
              host: ['TUN'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1965-11-12',
              end_date: '1965-11-21',
              color: '#fa2200',
              team_count: 6,
              venue_count: 4,
              city_count: 4,
            },
            hero_images: [
              {
                name: 'Stade Chedli Zouiten, Tunis',
                filename: '637px-Tunis_-_Stade_Municipal_Geo_Andre.jpg',
                text: 'The Stade Chedli Zouite hosted the final',
              },
            ],
            final_standings: { champions: 'GHA-1964-1966', runners_up: 'TUN', third_place: ['CIV'], fourth_place: 'SEN' },
            statistics: { total_matches: 8, total_goals: 31 },
            awards: {
              golden_boot: [
                { name: 'Ben Acheampong', team: 'GHA-1964-1966', goals: 3 },
                { name: 'Osei Kofi', team: 'GHA-1964-1966', goals: 3 },
                { name: 'Eustache Manglé', team: 'CIV', goals: 3 },
              ],
              golden_ball: [{ name: 'Osei Kofi', team: 'GHA-1964-1966' }],
            },
          },
        },
        {
          id: 'AFCON1963',
          data: {
            year: '1963',
            short_year: '1963',
            name: 'Africa Cup of Nations Ghana 1963',
            short_name: 'Ghana 1963',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['GHA-1964-1966'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1963-11-24',
              end_date: '1963-12-01',
              color: '#fcd20f',
              team_count: 6,
              venue_count: 2,
              city_count: 2,
            },
            hero_images: [
              {
                name: 'Kumasi Sports Stadium, Kumasi',
                filename: '640px-Baba_Yara_Sports_Stadium_in_Kumasi.jpg',
                text: 'The Kumasi Sports Stadium hosted group B matches.',
              },
            ],
            final_standings: { champions: 'GHA-1964-1966', runners_up: 'SDN-1956-1970', third_place: ['UAR'], fourth_place: 'ETH-1941-1974' },
            statistics: { total_matches: 8, total_goals: 33 },
            awards: {
              golden_boot: [{ name: 'Hassan El-Shazly', team: 'UAR', goals: 6 }],
              golden_ball: [{ name: 'Hassan El-Shazly', team: 'UAR' }],
            },
          },
        },
        {
          id: 'AFCON1962',
          data: {
            year: '1962',
            short_year: '1962',
            name: 'Africa Cup of Nations Ethiopia 1962',
            short_name: 'Ethiopia 1962',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['ETH-1941-1974'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1962-01-14',
              end_date: '1962-01-21',
              color: '#0e9061',
              team_count: 4,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Addis Ababa, Ethiopia',
                filename: '640px-Holy_Trinity_Cathedral_Church.jpg',
                text: 'Addis Ababa, Ethiopia',
              },
            ],
            final_standings: { champions: 'ETH-1941-1974', runners_up: 'UAR', third_place: ['TUN'], fourth_place: 'UGA-1914-1962' },
            statistics: { total_matches: 4, total_goals: 18 },
            awards: {
              golden_boot: [
                { name: 'Badawi Abdel Fattah', team: 'UAR', goals: 3 },
                { name: 'Mengistu Worku', team: 'ETH-1941-1974', goals: 3 },
              ],
              golden_ball: [{ name: 'Mengistu Worku', team: 'ETH-1941-1974' }],
            },
          },
        },
        {
          id: 'AFCON1959',
          data: {
            year: '1959',
            short_year: '1959',
            name: 'Africa Cup of Nations United Arab Republic 1959',
            short_name: 'United Arab Republic 1959',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['UAR'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1959-05-22',
              end_date: '1959-05-29',
              color: '#ca0b0f',
              team_count: 3,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Prince Farouk Stadium, Cairo',
                filename: '471px-Mokhtar_El_tetsh_stadium.jpg',
                text: 'The Prince Farouk Stadium hosted all the matches.',
              },
            ],
            final_standings: { champions: 'UAR', runners_up: 'SDN-1956-1970', third_place: ['ETH-1941-1974'] },
            statistics: { total_matches: 3, total_goals: 8 },
            awards: {
              golden_boot: [{ name: 'Mahmoud El-Gohary', team: 'UAR', goals: 3 }],
              golden_ball: [{ name: 'Mahmoud El-Gohary', team: 'UAR' }],
            },
          },
        },
        {
          id: 'AFCON1957',
          data: {
            year: '1957',
            short_year: '1957',
            name: 'Africa Cup of Nations Sudan 1957',
            short_name: 'Sudan 1957',
            competition_id: 'AFCON',
            active: false,
            golden_goal_rule: false,
            points_for_win: 2,
            tiebreakers: ['team'],
            details: {
              host: ['SDN-1956-1970'],
              logo_filename: 'Africa_Cup_of_Nations.png',
              start_date: '1957-02-10',
              end_date: '1957-02-16',
              color: '#fa2200',
              team_count: 3,
              venue_count: 1,
              city_count: 1,
            },
            hero_images: [
              {
                name: 'Khartoum, Sudan',
                filename: '640px-University_of_Khartoum_001.jpeg',
                text: 'The University of Khartoum',
              },
            ],
            final_standings: { champions: 'EGY-1953-1958', runners_up: 'ETH-1941-1974', third_place: ['SDN-1956-1970'] },
            statistics: { total_matches: 2, total_goals: 7 },
            awards: {
              golden_boot: [{ name: 'Ad-Diba', team: 'EGY-1953-1958', goals: 5 }],
              golden_ball: [{ name: 'Ad-Diba', team: 'EGY-1953-1958' }],
            },
          },
        },
      ],
    },
  ],
}
