export const AppData = {
  collection: 'team',
  batches: [
    {
      number: '1',
      rows: [
        {
          id: 'SUI',
          data: {
            name: 'Switzerland',
            team_type_id: 'MNT',
            nation_id: 'SUI',
            parent_team_id: '',
            code: 'SUI',
          },
        },
      ],
    },
    {
      number: '2',
      rows: [
        {
          id: 'FRA',
          data: {
            name: 'France',
            team_type_id: 'MNT',
            nation_id: 'FRA',
            parent_team_id: '',
            code: 'FRA',
          },
        },
        {
          id: 'ITA',
          data: {
            name: 'Italy',
            team_type_id: 'MNT',
            nation_id: 'ITA',
            parent_team_id: '',
            code: 'ITA',
          },
        },
        {
          id: 'ARG',
          data: {
            name: 'Argentina',
            team_type_id: 'MNT',
            nation_id: 'ARG',
            parent_team_id: '',
            code: 'ARG',
          },
        },
        {
          id: 'USA_WNT',
          data: {
            name: 'United States',
            short_name: 'United States',
            team_type_id: 'WNT',
            nation_id: 'USA',
            parent_team_id: '',
            code: 'USA',
          },
        },
        {
          id: 'BRA_U23MNT',
          data: {
            name: 'Brazil',
            team_type_id: 'U23MNT',
            nation_id: 'BRA',
            parent_team_id: '',
            code: 'BRA',
          },
        },
        {
          id: 'CAN_U23WNT',
          data: {
            name: 'Canada',
            team_type_id: 'U23WNT',
            nation_id: 'CAN',
            parent_team_id: '',
            code: 'CAN',
          },
        },
        {
          id: 'POR',
          data: {
            name: 'Portugal',
            team_type_id: 'MNT',
            nation_id: 'POR',
            parent_team_id: '',
            code: 'POR',
          },
        },
        {
          id: 'USA',
          data: {
            name: 'United States',
            short_name: 'United States',
            team_type_id: 'MNT',
            nation_id: 'USA',
            parent_team_id: '',
            code: 'USA',
          },
        },
        {
          id: 'ALG',
          data: {
            name: 'Algeria',
            team_type_id: 'MNT',
            nation_id: 'ALG',
            parent_team_id: '',
            code: 'ALG',
          },
        },
        {
          id: 'QAT',
          data: {
            name: 'Qatar',
            team_type_id: 'MNT',
            nation_id: 'QAT',
            parent_team_id: '',
            code: 'QAT',
          },
        },
        {
          id: 'NZL',
          data: {
            name: 'New Zealand',
            team_type_id: 'MNT',
            nation_id: 'NZL',
            parent_team_id: '',
            code: 'NZL',
          },
        },
        {
          id: 'GER',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER',
            parent_team_id: '',
            successor: true,
            code: 'GER',
          },
        },
        {
          id: 'CRO',
          data: {
            name: 'Croatia',
            team_type_id: 'MNT',
            nation_id: 'CRO',
            parent_team_id: '',
            code: 'CRO',
          },
        },
        {
          id: 'BEL',
          data: {
            name: 'Belgium',
            team_type_id: 'MNT',
            nation_id: 'BEL',
            parent_team_id: '',
            code: 'BEL',
          },
        },
        {
          id: 'ENG',
          data: {
            name: 'England',
            team_type_id: 'MNT',
            nation_id: 'ENG',
            parent_team_id: '',
            code: 'ENG',
          },
        },
        {
          id: 'NED',
          data: {
            name: 'Netherlands',
            team_type_id: 'MNT',
            nation_id: 'NED',
            parent_team_id: '',
            code: 'NED',
          },
        },
        {
          id: 'TUR',
          data: {
            name: 'Turkey',
            team_type_id: 'MNT',
            nation_id: 'TUR',
            parent_team_id: '',
            code: 'TUR',
          },
        },
        {
          id: 'KOR',
          data: {
            name: 'Korea Republic',
            short_name: 'Korea Rep.',
            team_type_id: 'MNT',
            nation_id: 'KOR',
            parent_team_id: '',
            code: 'KOR',
          },
        },
        {
          id: 'SWE',
          data: {
            name: 'Sweden',
            team_type_id: 'MNT',
            nation_id: 'SWE',
            parent_team_id: '',
            code: 'SWE',
          },
        },
        {
          id: 'BUL',
          data: {
            name: 'Bulgaria',
            team_type_id: 'MNT',
            nation_id: 'BUL',
            parent_team_id: '',
            code: 'BUL',
          },
        },
        {
          id: 'GER-1949-1990',
          data: {
            name: 'Germany FR',
            short_name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER-1949-1990',
            parent_team_id: 'GER',
            code: 'GER',
          },
        },
        {
          id: 'POL',
          data: {
            name: 'Poland',
            team_type_id: 'MNT',
            nation_id: 'POL',
            parent_team_id: '',
            code: 'POL',
          },
        },
        {
          id: 'URS',
          data: {
            name: 'Soviet Union',
            short_name: 'Soviet Union',
            team_type_id: 'MNT',
            nation_id: 'URS',
            parent_team_id: 'RUS',
            code: 'URS',
          },
        },
        {
          id: 'TCH',
          data: {
            name: 'Czechoslovakia',
            team_type_id: 'MNT',
            nation_id: 'TCH',
            parent_team_id: 'CZE',
            code: 'TCH',
          },
        },
        {
          id: 'CHI',
          data: {
            name: 'Chile',
            team_type_id: 'MNT',
            nation_id: 'CHI',
            parent_team_id: '',
            code: 'CHI',
          },
        },
        {
          id: 'YUG-1945-1963',
          data: {
            name: 'Yugoslavia',
            short_name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1945-1963',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'HUN-1949-1956',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN-1949-1956',
            parent_team_id: 'HUN',
            code: 'HUN',
          },
        },
        {
          id: 'AUT',
          data: {
            name: 'Austria',
            team_type_id: 'MNT',
            nation_id: 'AUT',
            parent_team_id: '',
            code: 'AUT',
          },
        },
        {
          id: 'ESP-1945-1977',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP-1945-1977',
            parent_team_id: 'ESP',
            code: 'ESP',
          },
        },
        {
          id: 'ITA-1861-1946',
          data: {
            name: 'Italy',
            team_type_id: 'MNT',
            nation_id: 'ITA-1861-1946',
            parent_team_id: 'ITA',
            code: 'ITA',
          },
        },
        {
          id: 'HUN-1919-1946',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN-1919-1946',
            parent_team_id: 'HUN',
            code: 'HUN',
          },
        },
        {
          id: 'GER-1933-1935',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER-1933-1935',
            parent_team_id: 'GER',
            code: 'GER',
          },
        },
        {
          id: 'YUG-1929-1943',
          data: {
            name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1929-1943',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'BRA',
          data: {
            name: 'Brazil',
            team_type_id: 'MNT',
            nation_id: 'BRA',
            parent_team_id: '',
            code: 'BRA',
          },
        },
        {
          id: 'ESP',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP',
            parent_team_id: '',
            code: 'ESP',
          },
        },
        {
          id: 'URU',
          data: {
            name: 'Uruguay',
            team_type_id: 'MNT',
            nation_id: 'URU',
            parent_team_id: '',
            code: 'URU',
          },
        },
        {
          id: 'MEX',
          data: {
            name: 'Mexico',
            team_type_id: 'MNT',
            nation_id: 'MEX',
            parent_team_id: '',
            code: 'MEX',
          },
        },
        {
          id: 'EGY',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY',
            parent_team_id: '',
            successor: true,
            code: 'EGY',
          },
        },
        {
          id: 'JPN',
          data: {
            name: 'Japan',
            team_type_id: 'MNT',
            nation_id: 'JPN',
            parent_team_id: '',
            code: 'JPN',
          },
        },
        {
          id: 'HUN_U23MNT',
          data: {
            name: 'Hungary',
            team_type_id: 'U23MNT',
            nation_id: 'HUN',
            parent_team_id: '',
            code: 'HUN',
          },
        },
        {
          id: 'GBR_U23MNT',
          data: {
            name: 'Great Britain',
            short_name: 'Great Britain',
            team_type_id: 'U23MNT',
            nation_id: 'GBR',
            parent_team_id: '',
            code: 'GBR',
          },
        },
        {
          id: 'USA_U23WNT',
          data: {
            name: 'United States',
            short_name: 'United States',
            team_type_id: 'U23WNT',
            nation_id: 'USA',
            parent_team_id: '',
            code: 'USA',
          },
        },
        {
          id: 'PAR',
          data: {
            name: 'Paraguay',
            team_type_id: 'MNT',
            nation_id: 'PAR',
            parent_team_id: '',
            code: 'PAR',
          },
        },
        {
          id: 'VEN',
          data: {
            name: 'Venezuela',
            team_type_id: 'MNT',
            nation_id: 'VEN',
            parent_team_id: '',
            code: 'VEN',
          },
        },
        {
          id: 'BOL',
          data: {
            name: 'Bolivia',
            team_type_id: 'MNT',
            nation_id: 'BOL',
            parent_team_id: '',
            code: 'BOL',
          },
        },
        {
          id: 'ECU',
          data: {
            name: 'Ecuador',
            team_type_id: 'MNT',
            nation_id: 'ECU',
            parent_team_id: '',
            code: 'ECU',
          },
        },
        {
          id: 'NED_WNT',
          data: {
            name: 'Netherlands',
            team_type_id: 'WNT',
            nation_id: 'NED',
            parent_team_id: '',
            code: 'NED',
          },
        },
        {
          id: 'SWE_WNT',
          data: {
            name: 'Sweden',
            team_type_id: 'WNT',
            nation_id: 'SWE',
            parent_team_id: '',
            code: 'SWE',
          },
        },
        {
          id: 'ENG_WNT',
          data: {
            name: 'England',
            team_type_id: 'WNT',
            nation_id: 'ENG',
            parent_team_id: '',
            code: 'ENG',
          },
        },
        {
          id: 'JPN_WNT',
          data: {
            name: 'Japan',
            team_type_id: 'WNT',
            nation_id: 'JPN',
            parent_team_id: '',
            code: 'JPN',
          },
        },
        {
          id: 'GER_WNT',
          data: {
            name: 'Germany',
            team_type_id: 'WNT',
            nation_id: 'GER',
            parent_team_id: '',
            code: 'GER',
          },
        },
        {
          id: 'FRA_WNT',
          data: {
            name: 'France',
            team_type_id: 'WNT',
            nation_id: 'FRA',
            parent_team_id: '',
            code: 'FRA',
          },
        },
        {
          id: 'BRA_WNT',
          data: {
            name: 'Brazil',
            team_type_id: 'WNT',
            nation_id: 'BRA',
            parent_team_id: '',
            code: 'BRA',
          },
        },
        {
          id: 'NOR_WNT',
          data: {
            name: 'Norway',
            team_type_id: 'WNT',
            nation_id: 'NOR',
            parent_team_id: '',
            code: 'NOR',
          },
        },
        {
          id: 'CAN_WNT',
          data: {
            name: 'Canada',
            team_type_id: 'WNT',
            nation_id: 'CAN',
            parent_team_id: '',
            code: 'CAN',
          },
        },
        {
          id: 'CHN_WNT',
          data: {
            name: 'China PR',
            team_type_id: 'WNT',
            nation_id: 'CHN',
            parent_team_id: '',
            code: 'CHN',
          },
        },
        {
          id: 'ESP_U23MNT',
          data: {
            name: 'Spain',
            team_type_id: 'U23MNT',
            nation_id: 'ESP',
            parent_team_id: '',
            code: 'ESP',
          },
        },
        {
          id: 'MEX_U23MNT',
          data: {
            name: 'Mexico',
            team_type_id: 'U23MNT',
            nation_id: 'MEX',
            parent_team_id: '',
            code: 'MEX',
          },
        },
        {
          id: 'JPN_U23MNT',
          data: {
            name: 'Japan',
            team_type_id: 'U23MNT',
            nation_id: 'JPN',
            parent_team_id: '',
            code: 'JPN',
          },
        },
        {
          id: 'GER_U23MNT',
          data: {
            name: 'Germany',
            team_type_id: 'U23MNT',
            nation_id: 'GER',
            parent_team_id: '',
            code: 'GER',
          },
        },
        {
          id: 'NGA_U23MNT',
          data: {
            name: 'Nigeria',
            team_type_id: 'U23MNT',
            nation_id: 'NGA',
            parent_team_id: '',
            code: 'NGA',
          },
        },
        {
          id: 'HON_U23MNT',
          data: {
            name: 'Honduras',
            team_type_id: 'U23MNT',
            nation_id: 'HON',
            parent_team_id: '',
            code: 'HON',
          },
        },
        {
          id: 'KOR_U23MNT',
          data: {
            name: 'Korea Republic',
            short_name: 'Korea Rep.',
            team_type_id: 'U23MNT',
            nation_id: 'KOR',
            parent_team_id: '',
            code: 'KOR',
          },
        },
        {
          id: 'ARG_U23MNT',
          data: {
            name: 'Argentina',
            team_type_id: 'U23MNT',
            nation_id: 'ARG',
            parent_team_id: '',
            code: 'ARG',
          },
        },
        {
          id: 'BEL_U23MNT',
          data: {
            name: 'Belgium',
            team_type_id: 'U23MNT',
            nation_id: 'BEL',
            parent_team_id: '',
            code: 'BEL',
          },
        },
        {
          id: 'PAR_U23MNT',
          data: {
            name: 'Paraguay',
            team_type_id: 'U23MNT',
            nation_id: 'PAR',
            parent_team_id: '',
            code: 'PAR',
          },
        },
        {
          id: 'ITA_U23MNT',
          data: {
            name: 'Italy',
            team_type_id: 'U23MNT',
            nation_id: 'ITA',
            parent_team_id: '',
            code: 'ITA',
          },
        },
        {
          id: 'IRQ-2004-2008_U23MNT',
          data: {
            name: 'Iraq',
            team_type_id: 'U23MNT',
            nation_id: 'IRQ-2004-2008',
            parent_team_id: 'IRQ_U23MNT',
            code: 'IRQ',
          },
        },
        {
          id: 'CMR_U23MNT',
          data: {
            name: 'Cameroon',
            team_type_id: 'U23MNT',
            nation_id: 'CMR',
            parent_team_id: '',
            code: 'CMR',
          },
        },
        {
          id: 'CHI_U23MNT',
          data: {
            name: 'Chile',
            team_type_id: 'U23MNT',
            nation_id: 'CHI',
            parent_team_id: '',
            code: 'CHI',
          },
        },
        {
          id: 'USA_U23MNT',
          data: {
            name: 'United States',
            short_name: 'United States',
            team_type_id: 'U23MNT',
            nation_id: 'USA',
            parent_team_id: '',
            code: 'USA',
          },
        },
        {
          id: 'POR_U23MNT',
          data: {
            name: 'Portugal',
            team_type_id: 'U23MNT',
            nation_id: 'POR',
            parent_team_id: '',
            code: 'POR',
          },
        },
        {
          id: 'POL_U23MNT',
          data: {
            name: 'Poland',
            team_type_id: 'U23MNT',
            nation_id: 'POL',
            parent_team_id: '',
            code: 'POL',
          },
        },
        {
          id: 'GHA_U23MNT',
          data: {
            name: 'Ghana',
            team_type_id: 'U23MNT',
            nation_id: 'GHA',
            parent_team_id: '',
            code: 'GHA',
          },
        },
        {
          id: 'AUS_U23MNT',
          data: {
            name: 'Australia',
            team_type_id: 'U23MNT',
            nation_id: 'AUS',
            parent_team_id: '',
            code: 'AUS',
          },
        },
        {
          id: 'URS_U23MNT',
          data: {
            name: 'Soviet Union',
            short_name: 'Soviet Union',
            team_type_id: 'U23MNT',
            nation_id: 'URS',
            parent_team_id: 'RUS_U23MNT',
            code: 'URS',
          },
        },
        {
          id: 'GER-1949-1990_U23MNT',
          data: {
            name: 'Germany FR',
            short_name: 'Germany',
            team_type_id: 'U23MNT',
            nation_id: 'GER-1949-1990',
            parent_team_id: 'GER_U23MNT',
            code: 'GER',
          },
        },
        {
          id: 'FRA_U23MNT',
          data: {
            name: 'France',
            team_type_id: 'U23MNT',
            nation_id: 'FRA',
            parent_team_id: '',
            code: 'FRA',
          },
        },
        {
          id: 'YUG-1963-1992_U23MNT',
          data: {
            name: 'Yugoslavia',
            team_type_id: 'U23MNT',
            nation_id: 'YUG-1963-1992',
            parent_team_id: 'SRB_U23MNT',
            code: 'YUG',
          },
        },
        {
          id: 'TCH_U23MNT',
          data: {
            name: 'Czechoslovakia',
            short_name: 'Czechoslovakia',
            team_type_id: 'U23MNT',
            nation_id: 'TCH',
            parent_team_id: 'CZE_U23MNT',
            code: 'TCH',
          },
        },
        {
          id: 'GDR_U23MNT',
          data: {
            name: 'Germany DR',
            short_name: 'Germany DR',
            team_type_id: 'U23MNT',
            nation_id: 'GDR',
            parent_team_id: '',
            code: 'GDR',
          },
        },
        {
          id: 'BUL-1967-1971_U23MNT',
          data: {
            name: 'Bulgaria',
            team_type_id: 'U23MNT',
            nation_id: 'BUL-1967-1971',
            parent_team_id: 'BUL_U23MNT',
            code: 'BUL',
          },
        },
        {
          id: 'EGY-1958-1971_U23MNT',
          data: {
            name: 'United Arab Republic',
            short_name: 'United Arab Republic',
            team_type_id: 'U23MNT',
            nation_id: 'UAR',
            parent_team_id: 'EGY_U23MNT',
            code: 'UAR',
          },
        },
        {
          id: 'YUG-1945-1963_U23MNT',
          data: {
            name: 'Yugoslavia',
            team_type_id: 'U23MNT',
            nation_id: 'YUG-1945-1963',
            parent_team_id: 'SRB_U23MNT',
            code: 'YUG',
          },
        },
        {
          id: 'DEN_U23MNT',
          data: {
            name: 'Denmark',
            team_type_id: 'U23MNT',
            nation_id: 'DEN',
            parent_team_id: '',
            code: 'DEN',
          },
        },
        {
          id: 'BUL-1948-1967_U23MNT',
          data: {
            name: 'Bulgaria',
            team_type_id: 'U23MNT',
            nation_id: 'BUL-1948-1967',
            parent_team_id: 'BUL_U23MNT',
            code: 'BUL',
          },
        },
        {
          id: 'IND_U23MNT',
          data: {
            name: 'India',
            team_type_id: 'U23MNT',
            nation_id: 'IND',
            parent_team_id: '',
            code: 'IND',
          },
        },
        {
          id: 'HUN-1949-1956_U23MNT',
          data: {
            name: 'Hungary',
            team_type_id: 'U23MNT',
            nation_id: 'HUN-1949-1956',
            parent_team_id: 'HUN_U23MNT',
            code: 'HUN',
          },
        },
        {
          id: 'SWE_U23MNT',
          data: {
            name: 'Sweden',
            team_type_id: 'U23MNT',
            nation_id: 'SWE',
            parent_team_id: '',
            code: 'SWE',
          },
        },
        {
          id: 'ITA-1861-1946_U23MNT',
          data: {
            name: 'Italy',
            team_type_id: 'U23MNT',
            nation_id: 'ITA-1861-1946',
            parent_team_id: 'ITA_U23MNT',
            code: 'ITA',
          },
        },
        {
          id: 'AUT_U23MNT',
          data: {
            name: 'Austria',
            team_type_id: 'U23MNT',
            nation_id: 'AUT',
            parent_team_id: '',
            code: 'AUT',
          },
        },
        {
          id: 'NOR_U23MNT',
          data: {
            name: 'Norway',
            team_type_id: 'U23MNT',
            nation_id: 'NOR',
            parent_team_id: '',
            code: 'NOR',
          },
        },
        {
          id: 'URU_U23MNT',
          data: {
            name: 'Uruguay',
            team_type_id: 'U23MNT',
            nation_id: 'URU',
            parent_team_id: '',
            code: 'URU',
          },
        },
        {
          id: 'EGY-1922-1953_U23MNT',
          data: {
            name: 'Egypt',
            team_type_id: 'U23MNT',
            nation_id: 'EGY-1922-1953',
            parent_team_id: 'EGY_U23MNT',
            code: 'EGY',
          },
        },
        {
          id: 'SUI_U23MNT',
          data: {
            name: 'Switzerland',
            team_type_id: 'U23MNT',
            nation_id: 'SUI',
            parent_team_id: '',
            code: 'SUI',
          },
        },
        {
          id: 'NED_U23MNT',
          data: {
            name: 'Netherlands',
            team_type_id: 'U23MNT',
            nation_id: 'NED',
            parent_team_id: '',
            code: 'NED',
          },
        },
        {
          id: 'ESP-1875-1931_U23MNT',
          data: {
            name: 'Spain',
            team_type_id: 'U23MNT',
            nation_id: 'ESP-1875-1931',
            parent_team_id: 'ESP_U23MNT',
            code: 'ESP',
          },
        },
        {
          id: 'FIN-1809-1917_U23MNT',
          data: {
            name: 'Finland',
            team_type_id: 'U23MNT',
            nation_id: 'FIN-1809-1917',
            parent_team_id: 'FIN_U23MNT',
            code: 'FIN',
          },
        },
        {
          id: 'SWE_U23WNT',
          data: {
            name: 'Sweden',
            team_type_id: 'U23WNT',
            nation_id: 'SWE',
            parent_team_id: '',
            code: 'SWE',
          },
        },
        {
          id: 'AUS_U23WNT',
          data: {
            name: 'Australia',
            team_type_id: 'U23WNT',
            nation_id: 'AUS',
            parent_team_id: '',
            code: 'AUS',
          },
        },
        {
          id: 'GER_U23WNT',
          data: {
            name: 'Germany',
            team_type_id: 'U23WNT',
            nation_id: 'GER',
            parent_team_id: '',
            code: 'GER',
          },
        },
        {
          id: 'BRA_U23WNT',
          data: {
            name: 'Brazil',
            team_type_id: 'U23WNT',
            nation_id: 'BRA',
            parent_team_id: '',
            code: 'BRA',
          },
        },
        {
          id: 'JPN_U23WNT',
          data: {
            name: 'Japan',
            team_type_id: 'U23WNT',
            nation_id: 'JPN',
            parent_team_id: '',
            code: 'JPN',
          },
        },
        {
          id: 'FRA_U23WNT',
          data: {
            name: 'France',
            team_type_id: 'U23WNT',
            nation_id: 'FRA',
            parent_team_id: '',
            code: 'FRA',
          },
        },
        {
          id: 'NOR_U23WNT',
          data: {
            name: 'Norway',
            team_type_id: 'U23WNT',
            nation_id: 'NOR',
            parent_team_id: '',
            code: 'NOR',
          },
        },
        {
          id: 'CHN_U23WNT',
          data: {
            name: 'China PR',
            team_type_id: 'U23WNT',
            nation_id: 'CHN',
            parent_team_id: '',
            code: 'CHN',
          },
        },
        {
          id: 'RSA',
          data: {
            name: 'South Africa',
            short_name: 'SouthAfrica',
            team_type_id: 'MNT',
            nation_id: 'RSA',
            parent_team_id: '',
            code: 'RSA',
          },
        },
        {
          id: 'CMR',
          data: {
            name: 'Cameroon',
            team_type_id: 'MNT',
            nation_id: 'CMR',
            parent_team_id: '',
            code: 'CMR',
          },
        },
        {
          id: 'AUS',
          data: {
            name: 'Australia',
            team_type_id: 'MNT',
            nation_id: 'AUS',
            parent_team_id: '',
            code: 'AUS',
          },
        },
        {
          id: 'KSA',
          data: {
            name: 'Saudi Arabia',
            short_name: 'SaudiArabia',
            team_type_id: 'MNT',
            nation_id: 'KSA',
            parent_team_id: '',
            code: 'KSA',
          },
        },
        {
          id: 'CZE',
          data: {
            name: 'Czech Republic',
            short_name: 'Czech Rep.',
            team_type_id: 'MNT',
            nation_id: 'CZE',
            parent_team_id: '',
            successor: true,
            code: 'CZE',
          },
        },
        {
          id: 'DEN',
          data: {
            name: 'Denmark',
            team_type_id: 'MNT',
            nation_id: 'DEN',
            parent_team_id: '',
            code: 'DEN',
          },
        },
        {
          id: 'NGA',
          data: {
            name: 'Nigeria',
            team_type_id: 'MNT',
            nation_id: 'NGA',
            parent_team_id: '',
            code: 'NGA',
          },
        },
        {
          id: 'CIV',
          data: {
            name: 'Ivory Coast',
            team_type_id: 'MNT',
            nation_id: 'CIV',
            parent_team_id: '',
            code: 'CIV',
          },
        },
        {
          id: 'IRN',
          data: {
            name: 'IR Iran',
            team_type_id: 'MNT',
            nation_id: 'IRN',
            parent_team_id: '',
            code: 'IRN',
          },
        },
        {
          id: 'UAE',
          data: {
            name: 'United Arab Emirates',
            short_name: 'UAE',
            team_type_id: 'MNT',
            nation_id: 'UAE',
            parent_team_id: '',
            code: 'UAE',
          },
        },
        {
          id: 'IRQ',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ',
            parent_team_id: '',
            code: 'IRQ',
          },
        },
        {
          id: 'UZB',
          data: {
            name: 'Uzbekistan',
            team_type_id: 'MNT',
            nation_id: 'UZB',
            parent_team_id: '',
            code: 'UZB',
          },
        },
        {
          id: 'IRQ-2004-2008',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ-2004-2008',
            parent_team_id: 'IRQ',
            code: 'IRQ',
          },
        },
        {
          id: 'CHN',
          data: {
            name: 'China PR',
            team_type_id: 'MNT',
            nation_id: 'CHN',
            parent_team_id: '',
            code: 'CHN',
          },
        },
        {
          id: 'BHR',
          data: {
            name: 'Bahrain',
            team_type_id: 'MNT',
            nation_id: 'BHR',
            parent_team_id: '',
            code: 'BHR',
          },
        },
        {
          id: 'KUW',
          data: {
            name: 'Kuwait',
            team_type_id: 'MNT',
            nation_id: 'KUW',
            parent_team_id: '',
            code: 'KUW',
          },
        },
        {
          id: 'PRK',
          data: {
            name: 'Korea DPR',
            team_type_id: 'MNT',
            nation_id: 'PRK',
            parent_team_id: '',
            code: 'PRK',
          },
        },
        {
          id: 'IRN-1964-1980',
          data: {
            name: 'Iran',
            team_type_id: 'MNT',
            nation_id: 'IRN-1964-1980',
            parent_team_id: 'IRN',
            code: 'IRN',
          },
        },
        {
          id: 'IRQ-1963-1991',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ-1963-1991',
            parent_team_id: 'IRQ',
            code: 'IRQ',
          },
        },
        {
          id: 'THA',
          data: {
            name: 'Thailand',
            team_type_id: 'MNT',
            nation_id: 'THA',
            parent_team_id: '',
            code: 'THA',
          },
        },
        {
          id: 'CAM-1970-1975',
          data: {
            name: 'Khmer Republic',
            short_name: 'Khmer Rep.',
            team_type_id: 'MNT',
            nation_id: 'CAM-1970-1975',
            parent_team_id: 'CAM',
            code: 'CAM',
          },
        },
        {
          id: 'BUR-1948-1974',
          data: {
            name: 'Burma',
            team_type_id: 'MNT',
            nation_id: 'BUR-1948-1974',
            parent_team_id: 'MYA',
            code: 'BUR',
          },
        },
        {
          id: 'ISR',
          data: {
            name: 'Israel',
            team_type_id: 'MNT',
            nation_id: 'ISR',
            parent_team_id: '',
            code: 'ISR',
          },
        },
        {
          id: 'TPE-1960-1979',
          data: {
            name: 'Republic of China',
            short_name: 'Rep. China',
            team_type_id: 'MNT',
            nation_id: 'TPE-1960-1979',
            parent_team_id: 'TPE',
            code: 'TPE',
          },
        },
        {
          id: 'IND',
          data: {
            name: 'India',
            team_type_id: 'MNT',
            nation_id: 'IND',
            parent_team_id: '',
            code: 'IND',
          },
        },
        {
          id: 'HKG-1959-1997',
          data: {
            name: 'Hong Kong',
            team_type_id: 'MNT',
            nation_id: 'HKG-1959-1997',
            parent_team_id: 'HKG',
            code: 'HKG',
          },
        },
        {
          id: 'VSO',
          data: {
            name: 'South Vietnam',
            short_name: 'S. Vietnam',
            team_type_id: 'MNT',
            nation_id: 'VSO',
            parent_team_id: 'VIE',
            code: 'VSO',
          },
        },
        {
          id: 'HKG-1955-1959',
          data: {
            name: 'Hong Kong',
            team_type_id: 'MNT',
            nation_id: 'HKG-1955-1959',
            parent_team_id: 'HKG',
            code: 'HKG',
          },
        },
        {
          id: 'SEN',
          data: {
            name: 'Senegal',
            team_type_id: 'MNT',
            nation_id: 'SEN',
            parent_team_id: '',
            code: 'SEN',
          },
        },
        {
          id: 'TUN',
          data: {
            name: 'Tunisia',
            team_type_id: 'MNT',
            nation_id: 'TUN',
            parent_team_id: '',
            code: 'TUN',
          },
        },
        {
          id: 'BFA',
          data: {
            name: 'Burkina Faso',
            short_name: 'BurkinaFaso',
            team_type_id: 'MNT',
            nation_id: 'BFA',
            parent_team_id: '',
            successor: true,
            code: 'BFA',
          },
        },
        {
          id: 'GHA',
          data: {
            name: 'Ghana',
            team_type_id: 'MNT',
            nation_id: 'GHA',
            parent_team_id: '',
            code: 'GHA',
          },
        },
        {
          id: 'COD',
          data: {
            name: 'Congo DR',
            team_type_id: 'MNT',
            nation_id: 'COD',
            parent_team_id: '',
            successor: true,
            code: 'COD',
          },
        },
        {
          id: 'EQG',
          data: {
            name: 'Equatorial Guinea',
            short_name: 'Equ Guinea',
            team_type_id: 'MNT',
            nation_id: 'EQG',
            parent_team_id: '',
            code: 'EQG',
          },
        },
        {
          id: 'MLI',
          data: {
            name: 'Mali',
            team_type_id: 'MNT',
            nation_id: 'MLI',
            parent_team_id: '',
            code: 'MLI',
          },
        },
        {
          id: 'ZAM',
          data: {
            name: 'Zambia',
            team_type_id: 'MNT',
            nation_id: 'ZAM',
            parent_team_id: '',
            code: 'ZAM',
          },
        },
        {
          id: 'MAR',
          data: {
            name: 'Morocco',
            team_type_id: 'MNT',
            nation_id: 'MAR',
            parent_team_id: '',
            code: 'MAR',
          },
        },
        {
          id: 'COD-1997-2003',
          data: {
            name: 'Congo DR',
            team_type_id: 'MNT',
            nation_id: 'COD-1997-2003',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'LBY-1977-2011',
          data: {
            name: 'Libya',
            team_type_id: 'MNT',
            nation_id: 'LBY-1977-2011',
            parent_team_id: 'LBY',
            code: 'LBY',
          },
        },
        {
          id: 'UGA',
          data: {
            name: 'Uganda',
            team_type_id: 'MNT',
            nation_id: 'UGA',
            parent_team_id: '',
            code: 'UGA',
          },
        },
        {
          id: 'GUI',
          data: {
            name: 'Guinea',
            team_type_id: 'MNT',
            nation_id: 'GUI',
            code: 'GUI',
          },
        },
        {
          id: 'ZAI',
          data: {
            name: 'Zaire',
            team_type_id: 'MNT',
            nation_id: 'COD-1971-1997',
            parent_team_id: 'COD',
            code: 'ZAI',
          },
        },
        {
          id: 'CGO-1970-1991',
          data: {
            name: 'Congo',
            team_type_id: 'MNT',
            nation_id: 'CGO-1970-1991',
            parent_team_id: 'CGO',
            code: 'CGO',
          },
        },
        {
          id: 'CMR-1961-1975',
          data: {
            name: 'Cameroon',
            team_type_id: 'MNT',
            nation_id: 'CMR-1961-1975',
            parent_team_id: 'CMR',
            code: 'CMR',
          },
        },
        {
          id: 'SDN-1956-1970',
          data: {
            name: 'Sudan',
            team_type_id: 'MNT',
            nation_id: 'SDN-1956-1970',
            parent_team_id: 'SDN',
            code: 'SDN',
          },
        },
        {
          id: 'UAR',
          data: {
            name: 'United Arab Republic',
            short_name: 'United Arab Republic',
            team_type_id: 'MNT',
            nation_id: 'UAR',
            parent_team_id: 'EGY',
            code: 'UAR',
          },
        },
        {
          id: 'COD-1966-1971',
          data: {
            name: 'Congo-Kinshasa',
            short_name: 'CongoKinsh',
            team_type_id: 'MNT',
            nation_id: 'COD-1966-1971',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'ETH-1941-1974',
          data: {
            name: 'Ethiopia',
            team_type_id: 'MNT',
            nation_id: 'ETH-1941-1974',
            parent_team_id: 'ETH',
            code: 'ETH',
          },
        },
        {
          id: 'GHA-1964-1966',
          data: {
            name: 'Ghana',
            team_type_id: 'MNT',
            nation_id: 'GHA-1964-1966',
            parent_team_id: 'GHA',
            code: 'GHA',
          },
        },
        {
          id: 'UGA-1914-1962',
          data: {
            name: 'Uganda',
            team_type_id: 'MNT',
            nation_id: 'UGA-1914-1962',
            parent_team_id: 'UGA',
            code: 'UGA',
          },
        },
        {
          id: 'EGY-1953-1958',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY-1953-1958',
            parent_team_id: 'EGY',
            code: 'EGY',
          },
        },
        {
          id: 'PNG',
          data: {
            name: 'Papua New Guinea',
            short_name: 'PapuaNGuinea',
            team_type_id: 'MNT',
            nation_id: 'PNG',
            parent_team_id: '',
            code: 'PNG',
          },
        },
        {
          id: 'NCL',
          data: {
            name: 'New Caledonia',
            short_name: 'NewCaledonia',
            team_type_id: 'MNT',
            nation_id: 'NCL',
            parent_team_id: '',
            code: 'NCL',
          },
        },
        {
          id: 'SOL',
          data: {
            name: 'Solomon Islands',
            short_name: 'SolomonIslands',
            team_type_id: 'MNT',
            nation_id: 'SOL',
            parent_team_id: '',
            code: 'SOL',
          },
        },
        {
          id: 'TAH',
          data: {
            name: 'Tahiti',
            team_type_id: 'MNT',
            nation_id: 'TAH',
            parent_team_id: '',
            code: 'TAH',
          },
        },
        {
          id: 'NCL-1973-2008',
          data: {
            name: 'New Caledonia',
            short_name: 'NewCaledonia',
            team_type_id: 'MNT',
            nation_id: 'NCL-1973-2008',
            parent_team_id: 'NCL',
            code: 'NCL',
          },
        },
        {
          id: 'FIJ',
          data: {
            name: 'Fiji',
            team_type_id: 'MNT',
            nation_id: 'FIJ',
            parent_team_id: '',
            code: 'FIJ',
          },
        },
        {
          id: 'VAN',
          data: {
            name: 'Vanuatu',
            team_type_id: 'MNT',
            nation_id: 'VAN',
            parent_team_id: '',
            code: 'VAN',
          },
        },
        {
          id: 'TAH-1794-1984',
          data: {
            name: 'Tahiti',
            team_type_id: 'MNT',
            nation_id: 'TAH-1794-1984',
            parent_team_id: 'TAH',
            code: 'TAH',
          },
        },
        {
          id: 'VAN-1953-1980',
          data: {
            name: 'New Hebrides',
            team_type_id: 'MNT',
            nation_id: 'VAN-1953-1980',
            parent_team_id: 'VAN',
            code: 'VAN',
          },
        },
        {
          id: 'WAL',
          data: {
            name: 'Wales',
            team_type_id: 'MNT',
            nation_id: 'WAL',
            parent_team_id: '',
            code: 'WAL',
          },
        },
        {
          id: 'RUS',
          data: {
            name: 'Russia',
            team_type_id: 'MNT',
            nation_id: 'RUS',
            parent_team_id: '',
            successor: true,
            code: 'RUS',
          },
        },
        {
          id: 'GRE',
          data: {
            name: 'Greece',
            team_type_id: 'MNT',
            nation_id: 'GRE',
            parent_team_id: '',
            code: 'GRE',
          },
        },
        {
          id: 'YUG-1963-1992',
          data: {
            name: 'Yugoslavia',
            short_name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1963-1992',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'HUN',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN',
            parent_team_id: '',
            code: 'HUN',
          },
        },
      ],
    },
  ],
}
