export const AppData = {
  collection: 'team',
  batches: [
    {
      number: '1',
      rows: [
        {
          id: 'AFG',
          data: {
            name: 'Afghanistan',
            team_type_id: 'MNT',
            nation_id: 'AFG',
            parent_team_id: '',
            code: 'AFG',
          },
        },
      ],
    },
    {
      number: '2',
      rows: [
        {
          id: 'AFG',
          data: {
            name: 'Afghanistan',
            team_type_id: 'MNT',
            nation_id: 'AFG',
            parent_team_id: '',
            code: 'AFG',
          },
        },
        {
          id: 'ALB',
          data: {
            name: 'Albania',
            team_type_id: 'MNT',
            nation_id: 'ALB',
            parent_team_id: '',
            code: 'ALB',
          },
        },
        {
          id: 'ALG',
          data: {
            name: 'Algeria',
            team_type_id: 'MNT',
            nation_id: 'ALG',
            parent_team_id: '',
            code: 'ALG',
          },
        },
        {
          id: 'ASA',
          data: {
            name: 'American Samoa',
            team_type_id: 'MNT',
            nation_id: 'ASA',
            parent_team_id: '',
            code: 'ASA',
          },
        },
        {
          id: 'AND',
          data: {
            name: 'Andorra',
            team_type_id: 'MNT',
            nation_id: 'AND',
            parent_team_id: '',
            code: 'AND',
          },
        },
        {
          id: 'ANG',
          data: {
            name: 'Angola',
            team_type_id: 'MNT',
            nation_id: 'ANG',
            parent_team_id: '',
            code: 'ANG',
          },
        },
        {
          id: 'AIA',
          data: {
            name: 'Anguilla',
            team_type_id: 'MNT',
            nation_id: 'AIA',
            parent_team_id: '',
            code: 'AIA',
          },
        },
        {
          id: 'ATG',
          data: {
            name: 'Antigua and Barbuda',
            team_type_id: 'MNT',
            nation_id: 'ATG',
            parent_team_id: '',
            code: 'ATG',
          },
        },
        {
          id: 'ARG',
          data: {
            name: 'Argentina',
            team_type_id: 'MNT',
            nation_id: 'ARG',
            parent_team_id: '',
            code: 'ARG',
          },
        },
        {
          id: 'ARM',
          data: {
            name: 'Armenia',
            team_type_id: 'MNT',
            nation_id: 'ARM',
            parent_team_id: '',
            code: 'ARM',
          },
        },
        {
          id: 'AUS',
          data: {
            name: 'Australia',
            team_type_id: 'MNT',
            nation_id: 'AUS',
            parent_team_id: '',
            code: 'AUS',
          },
        },
        {
          id: 'AUT',
          data: {
            name: 'Austria',
            team_type_id: 'MNT',
            nation_id: 'AUT',
            parent_team_id: '',
            code: 'AUT',
          },
        },
        {
          id: 'AZE',
          data: {
            name: 'Azerbaijan',
            team_type_id: 'MNT',
            nation_id: 'AZE',
            parent_team_id: '',
            code: 'AZE',
          },
        },
        {
          id: 'BAH',
          data: {
            name: 'Bahamas',
            team_type_id: 'MNT',
            nation_id: 'BAH',
            parent_team_id: '',
            code: 'BAH',
          },
        },
        {
          id: 'BHR',
          data: {
            name: 'Bahrain',
            team_type_id: 'MNT',
            nation_id: 'BHR',
            parent_team_id: '',
            code: 'BHR',
          },
        },
        {
          id: 'BAN',
          data: {
            name: 'Bangladesh',
            team_type_id: 'MNT',
            nation_id: 'BAN',
            parent_team_id: '',
            code: 'BAN',
          },
        },
        {
          id: 'BRB',
          data: {
            name: 'Barbados',
            team_type_id: 'MNT',
            nation_id: 'BRB',
            parent_team_id: '',
            code: 'BRB',
          },
        },
        {
          id: 'BLR',
          data: {
            name: 'Belarus',
            team_type_id: 'MNT',
            nation_id: 'BLR',
            parent_team_id: '',
            code: 'BLR',
          },
        },
        {
          id: 'BEL',
          data: {
            name: 'Belgium',
            team_type_id: 'MNT',
            nation_id: 'BEL',
            parent_team_id: '',
            code: 'BEL',
          },
        },
        {
          id: 'BLZ',
          data: {
            name: 'Belize',
            team_type_id: 'MNT',
            nation_id: 'BLZ',
            parent_team_id: '',
            code: 'BLZ',
          },
        },
        {
          id: 'BEN',
          data: {
            name: 'Benin',
            team_type_id: 'MNT',
            nation_id: 'BEN',
            parent_team_id: '',
            code: 'BEN',
          },
        },
        {
          id: 'BER',
          data: {
            name: 'Bermuda',
            team_type_id: 'MNT',
            nation_id: 'BER',
            parent_team_id: '',
            code: 'BER',
          },
        },
        {
          id: 'BHU',
          data: {
            name: 'Bhutan',
            team_type_id: 'MNT',
            nation_id: 'BHU',
            parent_team_id: '',
            code: 'BHU',
          },
        },
        {
          id: 'BOL',
          data: {
            name: 'Bolivia',
            team_type_id: 'MNT',
            nation_id: 'BOL',
            parent_team_id: '',
            code: 'BOL',
          },
        },
        {
          id: 'BOE',
          data: {
            name: 'Bonaire',
            team_type_id: 'MNT',
            nation_id: 'BOE',
            parent_team_id: '',
            code: 'BOE',
          },
        },
        {
          id: 'BIH',
          data: {
            name: 'Bosnia and Herzegovina',
            team_type_id: 'MNT',
            nation_id: 'BIH',
            parent_team_id: '',
            code: 'BIH',
          },
        },
        {
          id: 'BOT',
          data: {
            name: 'Botswana',
            team_type_id: 'MNT',
            nation_id: 'BOT',
            parent_team_id: '',
            code: 'BOT',
          },
        },
        {
          id: 'BRA',
          data: {
            name: 'Brazil',
            team_type_id: 'MNT',
            nation_id: 'BRA',
            parent_team_id: '',
            code: 'BRA',
          },
        },
        {
          id: 'VGB',
          data: {
            name: 'British Virgin Islands',
            team_type_id: 'MNT',
            nation_id: 'VGB',
            parent_team_id: '',
            code: 'VGB',
          },
        },
        {
          id: 'BRU',
          data: {
            name: 'Brunei Darussalam',
            team_type_id: 'MNT',
            nation_id: 'BRU',
            parent_team_id: '',
            code: 'BRU',
          },
        },
        {
          id: 'BUL',
          data: {
            name: 'Bulgaria',
            team_type_id: 'MNT',
            nation_id: 'BUL',
            parent_team_id: '',
            code: 'BUL',
          },
        },
        {
          id: 'BUL-1971-1990',
          data: {
            name: 'Bulgaria',
            team_type_id: 'MNT',
            nation_id: 'BUL-1971-1990',
            parent_team_id: 'BUL',
            code: 'BUL',
          },
        },
        {
          id: 'BUL-1967-1971',
          data: {
            name: 'Bulgaria',
            team_type_id: 'MNT',
            nation_id: 'BUL-1967-1971',
            parent_team_id: 'BUL',
            code: 'BUL',
          },
        },
        {
          id: 'BUL-1948-1967',
          data: {
            name: 'Bulgaria',
            team_type_id: 'MNT',
            nation_id: 'BUL-1948-1967',
            parent_team_id: 'BUL',
            code: 'BUL',
          },
        },
        {
          id: 'BFA',
          data: {
            name: 'Burkina Faso',
            short_name: 'BurkinaFaso',
            team_type_id: 'MNT',
            nation_id: 'BFA',
            parent_team_id: '',
            successor: true,
            code: 'BFA',
          },
        },
        {
          id: 'UPV',
          data: {
            name: 'Upper Volta',
            team_type_id: 'MNT',
            nation_id: 'UPV',
            parent_team_id: 'BFA',
            code: 'UPV',
          },
        },
        {
          id: 'BDI',
          data: {
            name: 'Burundi',
            team_type_id: 'MNT',
            nation_id: 'BDI',
            parent_team_id: '',
            code: 'BDI',
          },
        },
        {
          id: 'CAM',
          data: {
            name: 'Cambodia',
            team_type_id: 'MNT',
            nation_id: 'CAM',
            parent_team_id: '',
            code: 'CAM',
          },
        },
        {
          id: 'CAM-1970-1975',
          data: {
            name: 'Khmer Republic',
            short_name: 'Khmer Rep.',
            team_type_id: 'MNT',
            nation_id: 'CAM-1970-1975',
            parent_team_id: 'CAM',
            code: 'CAM',
          },
        },
        {
          id: 'CMR',
          data: {
            name: 'Cameroon',
            team_type_id: 'MNT',
            nation_id: 'CMR',
            parent_team_id: '',
            code: 'CMR',
          },
        },
        {
          id: 'CMR-1961-1975',
          data: {
            name: 'Cameroon',
            team_type_id: 'MNT',
            nation_id: 'CMR-1961-1975',
            parent_team_id: 'CMR',
            code: 'CMR',
          },
        },
        {
          id: 'CAN',
          data: {
            name: 'Canada',
            team_type_id: 'MNT',
            nation_id: 'CAN',
            parent_team_id: '',
            code: 'CAN',
          },
        },
        {
          id: 'CPV',
          data: {
            name: 'Cape Verde',
            team_type_id: 'MNT',
            nation_id: 'CPV',
            parent_team_id: '',
            code: 'CPV',
          },
        },
        {
          id: 'CAY',
          data: {
            name: 'Cayman Islands',
            team_type_id: 'MNT',
            nation_id: 'CAY',
            parent_team_id: '',
            code: 'CAY',
          },
        },
        {
          id: 'CTA',
          data: {
            name: 'Central African Republic',
            team_type_id: 'MNT',
            nation_id: 'CTA',
            parent_team_id: '',
            code: 'CTA',
          },
        },
        {
          id: 'CHA',
          data: {
            name: 'Chad',
            team_type_id: 'MNT',
            nation_id: 'CHA',
            parent_team_id: '',
            code: 'CHA',
          },
        },
        {
          id: 'CHI',
          data: {
            name: 'Chile',
            team_type_id: 'MNT',
            nation_id: 'CHI',
            parent_team_id: '',
            code: 'CHI',
          },
        },
        {
          id: 'CHN',
          data: {
            name: 'China PR',
            team_type_id: 'MNT',
            nation_id: 'CHN',
            parent_team_id: '',
            code: 'CHN',
          },
        },
        {
          id: 'TPE',
          data: {
            name: 'Chinese Taipei',
            team_type_id: 'MNT',
            nation_id: 'TPE',
            parent_team_id: '',
            code: 'TPE',
          },
        },
        {
          id: 'TPE-1960-1979',
          data: {
            name: 'Republic of China',
            short_name: 'Rep. China',
            team_type_id: 'MNT',
            nation_id: 'TPE-1960-1979',
            parent_team_id: 'TPE',
            code: 'TPE',
          },
        },
        {
          id: 'COL',
          data: {
            name: 'Colombia',
            team_type_id: 'MNT',
            nation_id: 'COL',
            parent_team_id: '',
            code: 'COL',
          },
        },
        {
          id: 'COM',
          data: {
            name: 'Comoros',
            team_type_id: 'MNT',
            nation_id: 'COM',
            parent_team_id: '',
            code: 'COM',
          },
        },
        {
          id: 'CGO',
          data: {
            name: 'Congo',
            team_type_id: 'MNT',
            nation_id: 'CGO',
            parent_team_id: '',
            code: 'CGO',
          },
        },
        {
          id: 'CGO-1970-1991',
          data: {
            name: 'Congo',
            team_type_id: 'MNT',
            nation_id: 'CGO-1970-1991',
            parent_team_id: 'CGO',
            code: 'CGO',
          },
        },
        {
          id: 'CGO-1959-1970',
          data: {
            name: 'Congo-Brazzaville',
            team_type_id: 'MNT',
            nation_id: 'CGO-1959-1970',
            parent_team_id: 'CGO',
            code: 'CGO',
          },
        },
        {
          id: 'COD',
          data: {
            name: 'Congo DR',
            team_type_id: 'MNT',
            nation_id: 'COD',
            parent_team_id: '',
            successor: true,
            code: 'COD',
          },
        },
        {
          id: 'COD-2003-2006',
          data: {
            name: 'Congo DR',
            team_type_id: 'MNT',
            nation_id: 'COD-2003-2006',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'COD-1997-2003',
          data: {
            name: 'Congo DR',
            team_type_id: 'MNT',
            nation_id: 'COD-1997-2003',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'ZAI',
          data: {
            name: 'Zaire',
            team_type_id: 'MNT',
            nation_id: 'ZAI',
            parent_team_id: 'COD',
            code: 'ZAI',
          },
        },
        {
          id: 'COD-1966-1971',
          data: {
            name: 'Congo-Kinshasa',
            short_name: 'CongoKinsh',
            team_type_id: 'MNT',
            nation_id: 'COD-1966-1971',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'COD-1964-1966',
          data: {
            name: 'Congo-Léopoldville',
            team_type_id: 'MNT',
            nation_id: 'COD-1964-1966',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'COK',
          data: {
            name: 'Cook Islands',
            team_type_id: 'MNT',
            nation_id: 'COK',
            parent_team_id: '',
            code: 'COK',
          },
        },
        {
          id: 'CRC',
          data: {
            name: 'Costa Rica',
            team_type_id: 'MNT',
            nation_id: 'CRC',
            parent_team_id: '',
            code: 'CRC',
          },
        },
        {
          id: 'CRO',
          data: {
            name: 'Croatia',
            team_type_id: 'MNT',
            nation_id: 'CRO',
            parent_team_id: '',
            code: 'CRO',
          },
        },
        {
          id: 'CUB',
          data: {
            name: 'Cuba',
            team_type_id: 'MNT',
            nation_id: 'CUB',
            parent_team_id: '',
            code: 'CUB',
          },
        },
        {
          id: 'CUW',
          data: {
            name: 'Curaçao',
            team_type_id: 'MNT',
            nation_id: 'CUW',
            parent_team_id: '',
            successor: true,
            code: 'CUW',
          },
        },
        {
          id: 'ANT',
          data: {
            name: 'Netherlands Antilles',
            team_type_id: 'MNT',
            nation_id: 'ANT',
            parent_team_id: 'CUW',
            code: 'ANT',
          },
        },
        {
          id: 'ANT-1959-1986',
          data: {
            name: 'Netherlands Antilles',
            team_type_id: 'MNT',
            nation_id: 'ANT-1959-1986',
            parent_team_id: 'CUW',
            code: 'ANT',
          },
        },
        {
          id: 'CYP',
          data: {
            name: 'Cyprus',
            team_type_id: 'MNT',
            nation_id: 'CYP',
            parent_team_id: '',
            code: 'CYP',
          },
        },
        {
          id: 'CZE',
          data: {
            name: 'Czech Republic',
            short_name: 'Czech Rep.',
            team_type_id: 'MNT',
            nation_id: 'CZE',
            parent_team_id: '',
            successor: true,
            code: 'CZE',
          },
        },
        {
          id: 'TCH',
          data: {
            name: 'Czechoslovakia',
            team_type_id: 'MNT',
            nation_id: 'TCH',
            parent_team_id: 'CZE',
            code: 'TCH',
          },
        },
        {
          id: 'DEN',
          data: {
            name: 'Denmark',
            team_type_id: 'MNT',
            nation_id: 'DEN',
            parent_team_id: '',
            code: 'DEN',
          },
        },
        {
          id: 'DJI',
          data: {
            name: 'Djibouti',
            team_type_id: 'MNT',
            nation_id: 'DJI',
            parent_team_id: '',
            code: 'DJI',
          },
        },
        {
          id: 'DMA',
          data: {
            name: 'Dominica',
            team_type_id: 'MNT',
            nation_id: 'DMA',
            parent_team_id: '',
            code: 'DMA',
          },
        },
        {
          id: 'DOM',
          data: {
            name: 'Dominican Republic',
            team_type_id: 'MNT',
            nation_id: 'DOM',
            parent_team_id: '',
            code: 'DOM',
          },
        },
        {
          id: 'GDR',
          data: {
            name: 'Germany DR',
            team_type_id: 'MNT',
            nation_id: 'GDR',
            parent_team_id: '',
            code: 'GDR',
          },
        },
        {
          id: 'ECU',
          data: {
            name: 'Ecuador',
            team_type_id: 'MNT',
            nation_id: 'ECU',
            parent_team_id: '',
            code: 'ECU',
          },
        },
        {
          id: 'EGY',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY',
            parent_team_id: '',
            successor: true,
            code: 'EGY',
          },
        },
        {
          id: 'UAR',
          data: {
            name: 'United Arab Republic',
            short_name: 'United Arab Republic',
            team_type_id: 'MNT',
            nation_id: 'UAR',
            parent_team_id: 'EGY',
            code: 'UAR',
          },
        },
        {
          id: 'EGY-1953-1958',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY-1953-1958',
            parent_team_id: 'EGY',
            code: 'EGY',
          },
        },
        {
          id: 'EGY-1922-1953',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY-1922-1953',
            parent_team_id: 'EGY',
            code: 'EGY',
          },
        },
        {
          id: 'SLV',
          data: {
            name: 'El Salvador',
            team_type_id: 'MNT',
            nation_id: 'SLV',
            parent_team_id: '',
            code: 'SLV',
          },
        },
        {
          id: 'ENG',
          data: {
            name: 'England',
            team_type_id: 'MNT',
            nation_id: 'ENG',
            parent_team_id: '',
            code: 'ENG',
          },
        },
        {
          id: 'EQG',
          data: {
            name: 'Equatorial Guinea',
            short_name: 'Equ Guinea',
            team_type_id: 'MNT',
            nation_id: 'EQG',
            parent_team_id: '',
            code: 'EQG',
          },
        },
        {
          id: 'ERI',
          data: {
            name: 'Eritrea',
            team_type_id: 'MNT',
            nation_id: 'ERI',
            parent_team_id: '',
            code: 'ERI',
          },
        },
        {
          id: 'EST',
          data: {
            name: 'Estonia',
            team_type_id: 'MNT',
            nation_id: 'EST',
            parent_team_id: '',
            code: 'EST',
          },
        },
        {
          id: 'SWZ',
          data: {
            name: 'Eswatini',
            team_type_id: 'MNT',
            nation_id: 'SWZ',
            parent_team_id: '',
            code: 'SZW',
          },
        },
        {
          id: 'ETH',
          data: {
            name: 'Ethiopia',
            team_type_id: 'MNT',
            nation_id: 'ETH',
            parent_team_id: '',
            code: 'ETH',
          },
        },
        {
          id: 'ETH-1975-1987',
          data: {
            name: 'Ethiopia',
            team_type_id: 'MNT',
            nation_id: 'ETH-1975-1987',
            parent_team_id: 'ETH',
            code: 'ETH',
          },
        },
        {
          id: 'ETH-1941-1974',
          data: {
            name: 'Ethiopia',
            team_type_id: 'MNT',
            nation_id: 'ETH-1941-1974',
            parent_team_id: 'ETH',
            code: 'ETH',
          },
        },
        {
          id: 'FRO',
          data: {
            name: 'Faroe Islands',
            team_type_id: 'MNT',
            nation_id: 'FRO',
            parent_team_id: '',
            code: 'FRO',
          },
        },
        {
          id: 'FIJ',
          data: {
            name: 'Fiji',
            team_type_id: 'MNT',
            nation_id: 'FIJ',
            parent_team_id: '',
            code: 'FIJ',
          },
        },
        {
          id: 'FIN',
          data: {
            name: 'Finland',
            team_type_id: 'MNT',
            nation_id: 'FIN',
            parent_team_id: '',
            code: 'FIN',
          },
        },
        {
          id: 'FRA',
          data: {
            name: 'France',
            team_type_id: 'MNT',
            nation_id: 'FRA',
            parent_team_id: '',
            code: 'FRA',
          },
        },
        {
          id: 'GUF',
          data: {
            name: 'French Guiana',
            team_type_id: 'MNT',
            nation_id: 'GUF',
            parent_team_id: '',
            code: 'GUF',
          },
        },
        {
          id: 'GAB',
          data: {
            name: 'Gabon',
            team_type_id: 'MNT',
            nation_id: 'GAB',
            parent_team_id: '',
            code: 'GAB',
          },
        },
        {
          id: 'GAM',
          data: {
            name: 'Gambia',
            team_type_id: 'MNT',
            nation_id: 'GAM',
            parent_team_id: '',
            code: 'GAM',
          },
        },
        {
          id: 'GEO',
          data: {
            name: 'Georgia',
            team_type_id: 'MNT',
            nation_id: 'GEO',
            parent_team_id: '',
            code: 'GEO',
          },
        },
        {
          id: 'GER',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER',
            parent_team_id: '',
            successor: true,
            code: 'GER',
          },
        },
        {
          id: 'GER-1949-1990',
          data: {
            name: 'Germany FR',
            short_name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER-1949-1990',
            parent_team_id: 'GER',
            code: 'GER',
          },
        },
        {
          id: 'GER-1935-1945',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER-1935-1945',
            parent_team_id: 'GER',
            code: 'GER',
          },
        },
        {
          id: 'GER-1933-1935',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER-1933-1935',
            parent_team_id: 'GER',
            code: 'GER',
          },
        },
        {
          id: 'GHA',
          data: {
            name: 'Ghana',
            team_type_id: 'MNT',
            nation_id: 'GHA',
            parent_team_id: '',
            code: 'GHA',
          },
        },
        {
          id: 'GHA-1964-1966',
          data: {
            name: 'Ghana',
            team_type_id: 'MNT',
            nation_id: 'GHA-1964-1966',
            parent_team_id: 'GHA',
            code: 'GHA',
          },
        },
        {
          id: 'GIB',
          data: {
            name: 'Gibraltar',
            team_type_id: 'MNT',
            nation_id: 'GIB',
            parent_team_id: '',
            code: 'GIB',
          },
        },
        {
          id: 'GRE',
          data: {
            name: 'Greece',
            team_type_id: 'MNT',
            nation_id: 'GRE',
            parent_team_id: '',
            code: 'GRE',
          },
        },
        {
          id: 'GRN',
          data: {
            name: 'Grenada',
            team_type_id: 'MNT',
            nation_id: 'GRN',
            parent_team_id: '',
            code: 'GRN',
          },
        },
        {
          id: 'GLP',
          data: {
            name: 'Guadeloupe',
            team_type_id: 'MNT',
            nation_id: 'GLP',
            parent_team_id: '',
            code: 'GLP',
          },
        },
        {
          id: 'GUM',
          data: {
            name: 'Guam',
            team_type_id: 'MNT',
            nation_id: 'GUM',
            parent_team_id: '',
            code: 'GUM',
          },
        },
        {
          id: 'GUA',
          data: {
            name: 'Guatemala',
            team_type_id: 'MNT',
            nation_id: 'GUA',
            parent_team_id: '',
            code: 'GUA',
          },
        },
        {
          id: 'GUI',
          data: {
            name: 'Guinea',
            team_type_id: 'MNT',
            nation_id: 'GUI',
            parent_team_id: '',
            code: 'GUI',
          },
        },
        {
          id: 'GNB',
          data: {
            name: 'Guinea-Bissau',
            team_type_id: 'MNT',
            nation_id: 'GNB',
            parent_team_id: '',
            code: 'GNB',
          },
        },
        {
          id: 'GUY',
          data: {
            name: 'Guyana',
            team_type_id: 'MNT',
            nation_id: 'GUY',
            parent_team_id: '',
            code: 'GUY',
          },
        },
        {
          id: 'HAI',
          data: {
            name: 'Haiti',
            team_type_id: 'MNT',
            nation_id: 'HAI',
            parent_team_id: '',
            code: 'HAI',
          },
        },
        {
          id: 'HAI-1964-1986',
          data: {
            name: 'Haiti',
            team_type_id: 'MNT',
            nation_id: 'HAI-1964-1986',
            parent_team_id: 'HAI',
            code: 'HAI',
          },
        },
        {
          id: 'HON',
          data: {
            name: 'Honduras',
            team_type_id: 'MNT',
            nation_id: 'HON',
            parent_team_id: '',
            code: 'HON',
          },
        },
        {
          id: 'HKG',
          data: {
            name: 'Hong Kong',
            team_type_id: 'MNT',
            nation_id: 'HKG',
            parent_team_id: '',
            code: 'HKG',
          },
        },
        {
          id: 'HKG-1959-1997',
          data: {
            name: 'Hong Kong',
            team_type_id: 'MNT',
            nation_id: 'HKG-1959-1997',
            parent_team_id: 'HKG',
            code: 'HKG',
          },
        },
        {
          id: 'HKG-1955-1959',
          data: {
            name: 'Hong Kong',
            team_type_id: 'MNT',
            nation_id: 'HKG-1955-1959',
            parent_team_id: 'HKG',
            code: 'HKG',
          },
        },
        {
          id: 'HUN',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN',
            parent_team_id: '',
            code: 'HUN',
          },
        },
        {
          id: 'HUN-1949-1956',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN-1949-1956',
            parent_team_id: 'HUN',
            code: 'HUN',
          },
        },
        {
          id: 'HUN-1919-1946',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN-1919-1946',
            parent_team_id: 'HUN',
            code: 'HUN',
          },
        },
        {
          id: 'ISL',
          data: {
            name: 'Iceland',
            team_type_id: 'MNT',
            nation_id: 'ISL',
            parent_team_id: '',
            code: 'ISL',
          },
        },
        {
          id: 'IND',
          data: {
            name: 'India',
            team_type_id: 'MNT',
            nation_id: 'IND',
            parent_team_id: '',
            code: 'IND',
          },
        },
        {
          id: 'IDN',
          data: {
            name: 'Indonesia',
            team_type_id: 'MNT',
            nation_id: 'IDN',
            parent_team_id: '',
            successor: true,
            code: 'IDN',
          },
        },
        {
          id: 'INH',
          data: {
            name: 'Dutch East Indies',
            team_type_id: 'MNT',
            nation_id: 'INH',
            parent_team_id: 'IDN',
            code: 'INH',
          },
        },
        {
          id: 'IRN',
          data: {
            name: 'IR Iran',
            team_type_id: 'MNT',
            nation_id: 'IRN',
            parent_team_id: '',
            code: 'IRN',
          },
        },
        {
          id: 'IRN-1964-1980',
          data: {
            name: 'Iran',
            team_type_id: 'MNT',
            nation_id: 'IRN-1964-1980',
            parent_team_id: 'IRN',
            code: 'IRN',
          },
        },
        {
          id: 'IRQ',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ',
            parent_team_id: '',
            code: 'IRQ',
          },
        },
        {
          id: 'IRQ-2004-2008',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ-2004-2008',
            parent_team_id: 'IRQ',
            code: 'IRQ',
          },
        },
        {
          id: 'IRQ-1991-2004',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ-1991-2004',
            parent_team_id: 'IRQ',
            code: 'IRQ',
          },
        },
        {
          id: 'IRQ-1963-1991',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ-1963-1991',
            parent_team_id: 'IRQ',
            code: 'IRQ',
          },
        },
        {
          id: 'ISR',
          data: {
            name: 'Israel',
            team_type_id: 'MNT',
            nation_id: 'ISR',
            parent_team_id: '',
            code: 'ISR',
          },
        },
        {
          id: 'ITA',
          data: {
            name: 'Italy',
            team_type_id: 'MNT',
            nation_id: 'ITA',
            parent_team_id: '',
            code: 'ITA',
          },
        },
        {
          id: 'ITA-1861-1946',
          data: {
            name: 'Italy',
            team_type_id: 'MNT',
            nation_id: 'ITA-1861-1946',
            parent_team_id: 'ITA',
            code: 'ITA',
          },
        },
        {
          id: 'CIV',
          data: {
            name: 'Ivory Coast',
            team_type_id: 'MNT',
            nation_id: 'CIV',
            parent_team_id: '',
            code: 'CIV',
          },
        },
        {
          id: 'JAM',
          data: {
            name: 'Jamaica',
            team_type_id: 'MNT',
            nation_id: 'JAM',
            parent_team_id: '',
            code: 'JAM',
          },
        },
        {
          id: 'JPN',
          data: {
            name: 'Japan',
            team_type_id: 'MNT',
            nation_id: 'JPN',
            parent_team_id: '',
            code: 'JPN',
          },
        },
        {
          id: 'JOR',
          data: {
            name: 'Jordan',
            team_type_id: 'MNT',
            nation_id: 'JOR',
            parent_team_id: '',
            code: 'JOR',
          },
        },
        {
          id: 'KAZ',
          data: {
            name: 'Kazakhstan',
            team_type_id: 'MNT',
            nation_id: 'KAZ',
            parent_team_id: '',
            code: 'KAZ',
          },
        },
        {
          id: 'KEN',
          data: {
            name: 'Kenya',
            team_type_id: 'MNT',
            nation_id: 'KEN',
            parent_team_id: '',
            code: 'KEN',
          },
        },
        {
          id: 'PRK',
          data: {
            name: 'Korea DPR',
            team_type_id: 'MNT',
            nation_id: 'PRK',
            parent_team_id: '',
            code: 'PRK',
          },
        },
        {
          id: 'KOR',
          data: {
            name: 'Korea Republic',
            short_name: 'Korea Rep.',
            team_type_id: 'MNT',
            nation_id: 'KOR',
            parent_team_id: '',
            code: 'KOR',
          },
        },
        {
          id: 'KVX',
          data: {
            name: 'Kosovo',
            team_type_id: 'MNT',
            nation_id: 'KVX',
            parent_team_id: '',
            code: 'KVX',
          },
        },
        {
          id: 'KUW',
          data: {
            name: 'Kuwait',
            team_type_id: 'MNT',
            nation_id: 'KUW',
            parent_team_id: '',
            code: 'KUW',
          },
        },
        {
          id: 'KGZ',
          data: {
            name: 'Kyrgyz Republic',
            short_name: 'Kyrgyzstan',
            team_type_id: 'MNT',
            nation_id: 'KGZ',
            parent_team_id: '',
            code: 'KGZ',
          },
        },
        {
          id: 'LAO',
          data: {
            name: 'Laos',
            team_type_id: 'MNT',
            nation_id: 'LAO',
            parent_team_id: '',
            code: 'LAO',
          },
        },
        {
          id: 'LVA',
          data: {
            name: 'Latvia',
            team_type_id: 'MNT',
            nation_id: 'LVA',
            parent_team_id: '',
            code: 'LVA',
          },
        },
        {
          id: 'LBN',
          data: {
            name: 'Lebanon',
            team_type_id: 'MNT',
            nation_id: 'LBN',
            parent_team_id: '',
            code: 'LBN',
          },
        },
        {
          id: 'LES',
          data: {
            name: 'Lesotho',
            team_type_id: 'MNT',
            nation_id: 'LES',
            parent_team_id: '',
            code: 'LES',
          },
        },
        {
          id: 'LBR',
          data: {
            name: 'Liberia',
            team_type_id: 'MNT',
            nation_id: 'LBR',
            parent_team_id: '',
            code: 'LBR',
          },
        },
        {
          id: 'LBY',
          data: {
            name: 'Libya',
            team_type_id: 'MNT',
            nation_id: 'LBY',
            parent_team_id: '',
            code: 'LBY',
          },
        },
        {
          id: 'LBY-1977-2011',
          data: {
            name: 'Libya',
            team_type_id: 'MNT',
            nation_id: 'LBY-1977-2011',
            parent_team_id: 'LBY',
            code: 'LBY',
          },
        },
        {
          id: 'LIE',
          data: {
            name: 'Liechtenstein',
            team_type_id: 'MNT',
            nation_id: 'LIE',
            parent_team_id: '',
            code: 'LIE',
          },
        },
        {
          id: 'LTU',
          data: {
            name: 'Lithuania',
            team_type_id: 'MNT',
            nation_id: 'LTU',
            parent_team_id: '',
            code: 'LTU',
          },
        },
        {
          id: 'LUX',
          data: {
            name: 'Luxembourg',
            team_type_id: 'MNT',
            nation_id: 'LUX',
            parent_team_id: '',
            code: 'LUX',
          },
        },
        {
          id: 'MAC',
          data: {
            name: 'Macau',
            team_type_id: 'MNT',
            nation_id: 'MAC',
            parent_team_id: '',
            code: 'MAC',
          },
        },
        {
          id: 'MAD',
          data: {
            name: 'Madagascar',
            team_type_id: 'MNT',
            nation_id: 'MAD',
            parent_team_id: '',
            code: 'MAD',
          },
        },
        {
          id: 'MWI',
          data: {
            name: 'Malawi',
            team_type_id: 'MNT',
            nation_id: 'MWI',
            parent_team_id: '',
            code: 'MWI',
          },
        },
        {
          id: 'MAS',
          data: {
            name: 'Malaysia',
            team_type_id: 'MNT',
            nation_id: 'MAS',
            parent_team_id: '',
            code: 'MAS',
          },
        },
        {
          id: 'MDV',
          data: {
            name: 'Maldives',
            team_type_id: 'MNT',
            nation_id: 'MDV',
            parent_team_id: '',
            code: 'MDV',
          },
        },
        {
          id: 'MLI',
          data: {
            name: 'Mali',
            team_type_id: 'MNT',
            nation_id: 'MLI',
            parent_team_id: '',
            code: 'MLI',
          },
        },
        {
          id: 'MLT',
          data: {
            name: 'Malta',
            team_type_id: 'MNT',
            nation_id: 'MLT',
            parent_team_id: '',
            code: 'MLT',
          },
        },
        {
          id: 'MTQ',
          data: {
            name: 'Martinique',
            team_type_id: 'MNT',
            nation_id: 'MTQ',
            parent_team_id: '',
            code: 'MTQ',
          },
        },
        {
          id: 'MTQ-2019',
          data: {
            name: 'Martinique',
            team_type_id: 'MNT',
            nation_id: 'MTQ-2019',
            parent_team_id: 'MTQ',
            code: 'MTQ',
          },
        },
        {
          id: 'MTN',
          data: {
            name: 'Mauritania',
            team_type_id: 'MNT',
            nation_id: 'MTN',
            parent_team_id: '',
            code: 'MTN',
          },
        },
        {
          id: 'MRI',
          data: {
            name: 'Mauritius',
            team_type_id: 'MNT',
            nation_id: 'MRI',
            parent_team_id: '',
            code: 'MRI',
          },
        },
        {
          id: 'MEX',
          data: {
            name: 'Mexico',
            team_type_id: 'MNT',
            nation_id: 'MEX',
            parent_team_id: '',
            code: 'MEX',
          },
        },
        {
          id: 'MEX-1916-1934',
          data: {
            name: 'Mexico',
            team_type_id: 'MNT',
            nation_id: 'MEX-1916-1934',
            parent_team_id: 'MEX',
            code: 'MEX',
          },
        },
        {
          id: 'MDA',
          data: {
            name: 'Moldova',
            team_type_id: 'MNT',
            nation_id: 'MDA',
            parent_team_id: '',
            code: 'MDA',
          },
        },
        {
          id: 'MNG',
          data: {
            name: 'Mongolia',
            team_type_id: 'MNT',
            nation_id: 'MNG',
            parent_team_id: '',
            code: 'MNG',
          },
        },
        {
          id: 'MNE',
          data: {
            name: 'Montenegro',
            team_type_id: 'MNT',
            nation_id: 'MNE',
            parent_team_id: '',
            code: 'MNE',
          },
        },
        {
          id: 'MSR',
          data: {
            name: 'Montserrat',
            team_type_id: 'MNT',
            nation_id: 'MSR',
            parent_team_id: '',
            code: 'MSR',
          },
        },
        {
          id: 'MAR',
          data: {
            name: 'Morocco',
            team_type_id: 'MNT',
            nation_id: 'MAR',
            parent_team_id: '',
            code: 'MAR',
          },
        },
        {
          id: 'MOZ',
          data: {
            name: 'Mozambique',
            team_type_id: 'MNT',
            nation_id: 'MOZ',
            parent_team_id: '',
            code: 'MOZR',
          },
        },
        {
          id: 'MYA',
          data: {
            name: 'Myanmar',
            team_type_id: 'MNT',
            nation_id: 'MYA',
            parent_team_id: '',
            code: 'MYA',
          },
        },
        {
          id: 'BUR-1948-1974',
          data: {
            name: 'Burma',
            team_type_id: 'MNT',
            nation_id: 'BUR-1948-1974',
            parent_team_id: 'MYA',
            code: 'BUR',
          },
        },
        {
          id: 'NAM',
          data: {
            name: 'Namibia',
            team_type_id: 'MNT',
            nation_id: 'NAM',
            parent_team_id: '',
            code: 'NAM',
          },
        },
        {
          id: 'NEP',
          data: {
            name: 'Nepal',
            team_type_id: 'MNT',
            nation_id: 'NEP',
            parent_team_id: '',
            code: 'NEP',
          },
        },
        {
          id: 'NED',
          data: {
            name: 'Netherlands',
            team_type_id: 'MNT',
            nation_id: 'NED',
            parent_team_id: '',
            code: 'NED',
          },
        },
        {
          id: 'NCL',
          data: {
            name: 'New Caledonia',
            short_name: 'NewCaledonia',
            team_type_id: 'MNT',
            nation_id: 'NCL',
            parent_team_id: '',
            code: 'NCL',
          },
        },
        {
          id: 'NCL-1973-2008',
          data: {
            name: 'New Caledonia',
            short_name: 'NewCaledonia',
            team_type_id: 'MNT',
            nation_id: 'NCL-1973-2008',
            parent_team_id: 'NCL',
            code: 'NCL',
          },
        },
        {
          id: 'NZL',
          data: {
            name: 'New Zealand',
            team_type_id: 'MNT',
            nation_id: 'NZL',
            parent_team_id: '',
            code: 'NZL',
          },
        },
        {
          id: 'NCA',
          data: {
            name: 'Nicaragua',
            team_type_id: 'MNT',
            nation_id: 'NCA',
            parent_team_id: '',
            code: 'NCA',
          },
        },
        {
          id: 'NIG',
          data: {
            name: 'Niger',
            team_type_id: 'MNT',
            nation_id: 'NIG',
            parent_team_id: '',
            code: 'NIG',
          },
        },
        {
          id: 'NGA',
          data: {
            name: 'Nigeria',
            team_type_id: 'MNT',
            nation_id: 'NGA',
            parent_team_id: '',
            code: 'NGA',
          },
        },
        {
          id: 'MKD',
          data: {
            name: 'North Macedonia',
            team_type_id: 'MNT',
            nation_id: 'MKD',
            parent_team_id: '',
            code: 'MKD',
          },
        },
        {
          id: 'MKD-2019',
          data: {
            name: 'Macedonia',
            team_type_id: 'MNT',
            nation_id: 'MKD-2019',
            parent_team_id: 'MKD',
            code: 'MKD',
          },
        },
        {
          id: 'NIR',
          data: {
            name: 'Northern Ireland',
            team_type_id: 'MNT',
            nation_id: 'NIR',
            parent_team_id: '',
            code: 'NIR',
          },
        },
        {
          id: 'NOR',
          data: {
            name: 'Norway',
            team_type_id: 'MNT',
            nation_id: 'NOR',
            parent_team_id: '',
            code: 'NOR',
          },
        },
        {
          id: 'OMA',
          data: {
            name: 'Oman',
            team_type_id: 'MNT',
            nation_id: 'OMA',
            parent_team_id: '',
            code: 'OMA',
          },
        },
        {
          id: 'PAK',
          data: {
            name: 'Pakistan',
            team_type_id: 'MNT',
            nation_id: 'PAK',
            parent_team_id: '',
            code: 'PAK',
          },
        },
        {
          id: 'PLE',
          data: {
            name: 'Palestine',
            team_type_id: 'MNT',
            nation_id: 'PLE',
            parent_team_id: '',
            code: 'PLE',
          },
        },
        {
          id: 'PAN',
          data: {
            name: 'Panama',
            team_type_id: 'MNT',
            nation_id: 'PAN',
            parent_team_id: '',
            code: 'PAN',
          },
        },
        {
          id: 'PNG',
          data: {
            name: 'Papua New Guinea',
            short_name: 'PapuaNGuinea',
            team_type_id: 'MNT',
            nation_id: 'PNG',
            parent_team_id: '',
            code: 'PNG',
          },
        },
        {
          id: 'PAR',
          data: {
            name: 'Paraguay',
            team_type_id: 'MNT',
            nation_id: 'PAR',
            parent_team_id: '',
            code: 'PAR',
          },
        },
        {
          id: 'PER',
          data: {
            name: 'Peru',
            team_type_id: 'MNT',
            nation_id: 'PER',
            parent_team_id: '',
            code: 'PER',
          },
        },
        {
          id: 'PHI',
          data: {
            name: 'Philippines',
            team_type_id: 'MNT',
            nation_id: 'PHI',
            parent_team_id: '',
            code: 'PHI',
          },
        },
        {
          id: 'POL',
          data: {
            name: 'Poland',
            team_type_id: 'MNT',
            nation_id: 'POL',
            parent_team_id: '',
            code: 'POL',
          },
        },
        {
          id: 'POR',
          data: {
            name: 'Portugal',
            team_type_id: 'MNT',
            nation_id: 'POR',
            parent_team_id: '',
            code: 'POR',
          },
        },
        {
          id: 'PUR',
          data: {
            name: 'Puerto Rico',
            team_type_id: 'MNT',
            nation_id: 'PUR',
            parent_team_id: '',
            code: 'PUR',
          },
        },
        {
          id: 'QAT',
          data: {
            name: 'Qatar',
            team_type_id: 'MNT',
            nation_id: 'QAT',
            parent_team_id: '',
            code: 'QAT',
          },
        },
        {
          id: 'IRL',
          data: {
            name: 'Republic of Ireland',
            short_name: 'Rep. Ireland',
            team_type_id: 'MNT',
            nation_id: 'IRL',
            parent_team_id: '',
            code: 'IRL',
          },
        },
        {
          id: 'ROU',
          data: {
            name: 'Romania',
            team_type_id: 'MNT',
            nation_id: 'ROU',
            parent_team_id: '',
            code: 'ROU',
          },
        },
        {
          id: 'ROU-1965-1989',
          data: {
            name: 'Romania',
            team_type_id: 'MNT',
            nation_id: 'ROU-1965-1989',
            parent_team_id: 'ROU',
            code: 'ROU',
          },
        },
        {
          id: 'RUS',
          data: {
            name: 'Russia',
            team_type_id: 'MNT',
            nation_id: 'RUS',
            parent_team_id: '',
            successor: true,
            code: 'RUS',
          },
        },
        {
          id: 'CIS',
          data: {
            name: 'CIS',
            team_type_id: 'MNT',
            nation_id: 'CIS',
            parent_team_id: 'RUS',
            code: 'CIS',
          },
        },
        {
          id: 'URS',
          data: {
            name: 'Soviet Union',
            short_name: 'Soviet Union',
            team_type_id: 'MNT',
            nation_id: 'URS',
            parent_team_id: 'RUS',
            code: 'URS',
          },
        },
        {
          id: 'RWA',
          data: {
            name: 'Rwanda',
            team_type_id: 'MNT',
            nation_id: 'RWA',
            parent_team_id: '',
            code: 'RWA',
          },
        },
        {
          id: 'SAM',
          data: {
            name: 'Samoa',
            team_type_id: 'MNT',
            nation_id: 'SAM',
            parent_team_id: '',
            code: 'SAM',
          },
        },
        {
          id: 'SMR',
          data: {
            name: 'San Marino',
            team_type_id: 'MNT',
            nation_id: 'SMR',
            parent_team_id: '',
            code: 'SMR',
          },
        },
        {
          id: 'STP',
          data: {
            name: 'São Tomé and Príncipe',
            team_type_id: 'MNT',
            nation_id: 'STP',
            parent_team_id: '',
            code: 'STP',
          },
        },
        {
          id: 'KSA',
          data: {
            name: 'Saudi Arabia',
            short_name: 'SaudiArabia',
            team_type_id: 'MNT',
            nation_id: 'KSA',
            parent_team_id: '',
            code: 'KSA',
          },
        },
        {
          id: 'SCO',
          data: {
            name: 'Scotland',
            team_type_id: 'MNT',
            nation_id: 'SCO',
            parent_team_id: '',
            code: 'SCO',
          },
        },
        {
          id: 'SEN',
          data: {
            name: 'Senegal',
            team_type_id: 'MNT',
            nation_id: 'SEN',
            parent_team_id: '',
            code: 'SEN',
          },
        },
        {
          id: 'SRB',
          data: {
            name: 'Serbia',
            team_type_id: 'MNT',
            nation_id: 'SRB',
            parent_team_id: '',
            successor: true,
            code: 'SRB',
          },
        },
        {
          id: 'SRB-2003-2006',
          data: {
            name: 'Serbia and Montenegro',
            team_type_id: 'MNT',
            nation_id: 'SRB-2003-2006',
            parent_team_id: 'SRB',
            code: 'SRB',
          },
        },
        {
          id: 'YUG-1992-2003',
          data: {
            name: 'FR Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1992-2003',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'YUG-1963-1992',
          data: {
            name: 'Yugoslavia',
            short_name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1963-1992',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'YUG-1945-1963',
          data: {
            name: 'Yugoslavia',
            short_name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1945-1963',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'YUG-1929-1943',
          data: {
            name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1929-1943',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'SEY',
          data: {
            name: 'Seychelles',
            team_type_id: 'MNT',
            nation_id: 'SEY',
            parent_team_id: '',
            code: 'SEY',
          },
        },
        {
          id: 'SLE',
          data: {
            name: 'Sierra Leone',
            team_type_id: 'MNT',
            nation_id: 'SLE',
            parent_team_id: '',
            code: 'SLE',
          },
        },
        {
          id: 'SIN',
          data: {
            name: 'Singapore',
            team_type_id: 'MNT',
            nation_id: 'SIN',
            parent_team_id: '',
            code: 'SIN',
          },
        },
        {
          id: 'SVK',
          data: {
            name: 'Slovakia',
            team_type_id: 'MNT',
            nation_id: 'SVK',
            parent_team_id: '',
            code: 'SVK',
          },
        },
        {
          id: 'SVN',
          data: {
            name: 'Slovenia',
            team_type_id: 'MNT',
            nation_id: 'SVN',
            parent_team_id: '',
            code: 'SVN',
          },
        },
        {
          id: 'SOL',
          data: {
            name: 'Solomon Islands',
            short_name: 'SolomonIslands',
            team_type_id: 'MNT',
            nation_id: 'SOL',
            parent_team_id: '',
            code: 'SOL',
          },
        },
        {
          id: 'SOM',
          data: {
            name: 'Somalia',
            team_type_id: 'MNT',
            nation_id: 'SOM',
            parent_team_id: '',
            code: 'SOM',
          },
        },
        {
          id: 'RSA',
          data: {
            name: 'South Africa',
            short_name: 'SouthAfrica',
            team_type_id: 'MNT',
            nation_id: 'RSA',
            parent_team_id: '',
            code: 'RSA',
          },
        },
        {
          id: 'RSA-1928-1994',
          data: {
            name: 'South Africa',
            short_name: 'SouthAfrica',
            team_type_id: 'MNT',
            nation_id: 'RSA-1928-1994',
            parent_team_id: 'RSA',
            code: 'RSA',
          },
        },
        {
          id: 'SSD',
          data: {
            name: 'South Sudan',
            team_type_id: 'MNT',
            nation_id: 'SSD',
            parent_team_id: '',
            code: 'SSD',
          },
        },
        {
          id: 'YMD',
          data: {
            name: 'South Yemen',
            team_type_id: 'MNT',
            nation_id: 'YMD',
            parent_team_id: '',
            code: 'YMD',
          },
        },
        {
          id: 'ESP',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP',
            parent_team_id: '',
            code: 'ESP',
          },
        },
        {
          id: 'ESP-1977-1981',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP-1977-1981',
            parent_team_id: 'ESP',
            code: 'ESP',
          },
        },
        {
          id: 'ESP-1945-1977',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP-1945-1977',
            parent_team_id: 'ESP',
            code: 'ESP',
          },
        },
        {
          id: 'ESP-1931-1936',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP-1931-1936',
            parent_team_id: 'ESP',
            code: 'ESP',
          },
        },
        {
          id: 'SRI',
          data: {
            name: 'Sri Lanka',
            team_type_id: 'MNT',
            nation_id: 'SRI',
            parent_team_id: '',
            code: 'SRI',
          },
        },
        {
          id: 'SKN',
          data: {
            name: 'St. Kitts and Nevis',
            team_type_id: 'MNT',
            nation_id: 'SKN',
            parent_team_id: '',
            code: 'SKN',
          },
        },
        {
          id: 'LCA',
          data: {
            name: 'St. Lucia',
            team_type_id: 'MNT',
            nation_id: 'LCA',
            parent_team_id: '',
            code: 'LCA',
          },
        },
        {
          id: 'VIN',
          data: {
            name: 'Saint Vincent and the Grenadines',
            team_type_id: 'MNT',
            nation_id: 'VIN',
            parent_team_id: '',
            code: 'VIN',
          },
        },
        {
          id: 'SDN',
          data: {
            name: 'Sudan',
            team_type_id: 'MNT',
            nation_id: 'SDN',
            parent_team_id: '',
            code: 'SDN',
          },
        },
        {
          id: 'SDN-1956-1970',
          data: {
            name: 'Sudan',
            team_type_id: 'MNT',
            nation_id: 'SDN-1956-1970',
            parent_team_id: 'SDN',
            code: 'SDN',
          },
        },
        {
          id: 'SUR',
          data: {
            name: 'Suriname',
            team_type_id: 'MNT',
            nation_id: 'SUR',
            parent_team_id: '',
            code: 'SUR',
          },
        },
        {
          id: 'SWE',
          data: {
            name: 'Sweden',
            team_type_id: 'MNT',
            nation_id: 'SWE',
            parent_team_id: '',
            code: 'SWE',
          },
        },
        {
          id: 'SUI',
          data: {
            name: 'Switzerland',
            team_type_id: 'MNT',
            nation_id: 'SUI',
            parent_team_id: '',
            code: 'SUI',
          },
        },
        {
          id: 'SYR',
          data: {
            name: 'Syria',
            team_type_id: 'MNT',
            nation_id: 'SYR',
            parent_team_id: '',
            code: 'SYR',
          },
        },
        {
          id: 'TAH',
          data: {
            name: 'Tahiti',
            team_type_id: 'MNT',
            nation_id: 'TAH',
            parent_team_id: '',
            code: 'TAH',
          },
        },
        {
          id: 'TAH-1794-1984',
          data: {
            name: 'Tahiti',
            team_type_id: 'MNT',
            nation_id: 'TAH-1794-1984',
            parent_team_id: 'TAH',
            code: 'TAH',
          },
        },
        {
          id: 'TJK',
          data: {
            name: 'Tajikistan',
            team_type_id: 'MNT',
            nation_id: 'TJK',
            parent_team_id: '',
            code: 'TJK',
          },
        },
        {
          id: 'TAN',
          data: {
            name: 'Tanzania',
            team_type_id: 'MNT',
            nation_id: 'TAN',
            parent_team_id: '',
            code: 'TAN',
          },
        },
        {
          id: 'THA',
          data: {
            name: 'Thailand',
            team_type_id: 'MNT',
            nation_id: 'THA',
            parent_team_id: '',
            code: 'THA',
          },
        },
        {
          id: 'TLS',
          data: {
            name: 'Timor-Leste',
            team_type_id: 'MNT',
            nation_id: 'TLS',
            parent_team_id: '',
            code: 'TLS',
          },
        },
        {
          id: 'TOG',
          data: {
            name: 'Togo',
            team_type_id: 'MNT',
            nation_id: 'TOG',
            parent_team_id: '',
            code: 'TOG',
          },
        },
        {
          id: 'TGA',
          data: {
            name: 'Tonga',
            team_type_id: 'MNT',
            nation_id: 'TGA',
            parent_team_id: '',
            code: 'TGA',
          },
        },
        {
          id: 'TRI',
          data: {
            name: 'Trinidad and Tobago',
            short_name: 'Trinidad & Tobago',
            team_type_id: 'MNT',
            nation_id: 'TRI',
            parent_team_id: '',
            code: 'TRI',
          },
        },
        {
          id: 'TUN',
          data: {
            name: 'Tunisia',
            team_type_id: 'MNT',
            nation_id: 'TUN',
            parent_team_id: '',
            code: 'TUN',
          },
        },
        {
          id: 'TUR',
          data: {
            name: 'Turkey',
            team_type_id: 'MNT',
            nation_id: 'TUR',
            parent_team_id: '',
            code: 'TUR',
          },
        },
        {
          id: 'TKM',
          data: {
            name: 'Turkmenistan',
            team_type_id: 'MNT',
            nation_id: 'TKM',
            parent_team_id: '',
            code: 'TKM',
          },
        },
        {
          id: 'TCA',
          data: {
            name: 'Turks and Caicos Islands',
            team_type_id: 'MNT',
            nation_id: 'TCA',
            parent_team_id: '',
            code: 'TCA',
          },
        },
        {
          id: 'TUV',
          data: {
            name: 'Tuvalu',
            team_type_id: 'MNT',
            nation_id: 'TUV',
            parent_team_id: '',
            code: 'TUV',
          },
        },
        {
          id: 'UGA',
          data: {
            name: 'Uganda',
            team_type_id: 'MNT',
            nation_id: 'UGA',
            parent_team_id: '',
            code: 'UGA',
          },
        },
        {
          id: 'UGA-1914-1962',
          data: {
            name: 'Uganda',
            team_type_id: 'MNT',
            nation_id: 'UGA-1914-1962',
            parent_team_id: 'UGA',
            code: 'UGA',
          },
        },
        {
          id: 'UKR',
          data: {
            name: 'Ukraine',
            team_type_id: 'MNT',
            nation_id: 'UKR',
            parent_team_id: '',
            code: 'UKR',
          },
        },
        {
          id: 'UAE',
          data: {
            name: 'United Arab Emirates',
            short_name: 'UAE',
            team_type_id: 'MNT',
            nation_id: 'UAE',
            parent_team_id: '',
            code: 'UAE',
          },
        },
        {
          id: 'URU',
          data: {
            name: 'Uruguay',
            team_type_id: 'MNT',
            nation_id: 'URU',
            parent_team_id: '',
            code: 'URU',
          },
        },
        {
          id: 'VIR',
          data: {
            name: 'US Virgin Islands',
            team_type_id: 'MNT',
            nation_id: 'VIR',
            parent_team_id: '',
            code: 'VIR',
          },
        },
        {
          id: 'USA',
          data: {
            name: 'United States',
            short_name: 'United States',
            team_type_id: 'MNT',
            nation_id: 'USA',
            parent_team_id: '',
            code: 'USA',
          },
        },
        {
          id: 'UZB',
          data: {
            name: 'Uzbekistan',
            team_type_id: 'MNT',
            nation_id: 'UZB',
            parent_team_id: '',
            code: 'UZB',
          },
        },
        {
          id: 'VAN',
          data: {
            name: 'Vanuatu',
            team_type_id: 'MNT',
            nation_id: 'VAN',
            parent_team_id: '',
            code: 'VAN',
          },
        },
        {
          id: 'VAN-1980',
          data: {
            name: 'New Hebrides',
            team_type_id: 'MNT',
            nation_id: 'VAN-1980',
            parent_team_id: 'VAN',
            code: 'VAN',
          },
        },
        {
          id: 'VAN-1953-1980',
          data: {
            name: 'New Hebrides',
            team_type_id: 'MNT',
            nation_id: 'VAN-1953-1980',
            parent_team_id: 'VAN',
            code: 'VAN',
          },
        },
        {
          id: 'VEN',
          data: {
            name: 'Venezuela',
            team_type_id: 'MNT',
            nation_id: 'VEN',
            parent_team_id: '',
            code: 'VEN',
          },
        },
        {
          id: 'VEN-1954-2006',
          data: {
            name: 'Venezuela',
            team_type_id: 'MNT',
            nation_id: 'VEN-1954-2006',
            parent_team_id: 'VEN',
            code: 'VEN',
          },
        },
        {
          id: 'VEN-1930-1954',
          data: {
            name: 'Venezuela',
            team_type_id: 'MNT',
            nation_id: 'VEN-1930-1954',
            parent_team_id: 'VEN',
            code: 'VEN',
          },
        },
        {
          id: 'VIE',
          data: {
            name: 'Vietnam',
            team_type_id: 'MNT',
            nation_id: 'VIE',
            parent_team_id: '',
            code: 'VIE',
          },
        },
        {
          id: 'VSO',
          data: {
            name: 'South Vietnam',
            short_name: 'S. Vietnam',
            team_type_id: 'MNT',
            nation_id: 'VSO',
            parent_team_id: 'VIE',
            code: 'VSO',
          },
        },
        {
          id: 'WAL',
          data: {
            name: 'Wales',
            team_type_id: 'MNT',
            nation_id: 'WAL',
            parent_team_id: '',
            code: 'WAL',
          },
        },
        {
          id: 'WAL-1953-1959',
          data: {
            name: 'Wales',
            team_type_id: 'MNT',
            nation_id: 'WAL-1953-1959',
            parent_team_id: 'WAL',
            code: 'WAL',
          },
        },
        {
          id: 'YEM',
          data: {
            name: 'Yemen',
            team_type_id: 'MNT',
            nation_id: 'YEM',
            parent_team_id: '',
            code: 'YEM',
          },
        },
        {
          id: 'ZAM',
          data: {
            name: 'Zambia',
            team_type_id: 'MNT',
            nation_id: 'ZAM',
            parent_team_id: '',
            code: 'ZAM',
          },
        },
        {
          id: 'ZIM',
          data: {
            name: 'Zimbabwe',
            team_type_id: 'MNT',
            nation_id: 'ZIM',
            parent_team_id: '',
            code: 'ZIM',
          },
        },
      ],
    },
  ],
}
