export const AppData = {
  collection: 'team',
  batches: [
    {
      number: '7',
      rows: [
        {
          id: 'DOR',
          data: {
            name: 'Borussia Dortmund',
            short_name: 'Borus.Dortmund',
            team_type_id: 'CLUB',
            nation_id: 'GER',
            parent_team_id: '',
            club_code: 'DOR',
            logo_filename: 'Borussia_Dortmund_logo_640x640.png',
            official_name: 'Borussia Dortmund',
          },
        },
        {
          id: 'LIL',
          data: {
            name: 'Lille OSC',
            team_type_id: 'CLUB',
            nation_id: 'FRA',
            parent_team_id: '',
            club_code: 'LIL',
            logo_filename: 'Lille_OSC_2018_logo_673x640.png',
            official_name: 'Lille Olympique Sporting Club',
          },
        },
        {
          id: 'SLB',
          data: {
            name: 'Benfica',
            team_type_id: 'CLUB',
            nation_id: 'POR',
            parent_team_id: '',
            club_code: 'SLB',
            logo_filename: 'SL_Benfica_logo_647x640.png',
            official_name: 'SL Benfica',
          },
        },
      ],
    },
    {
      number: '8',
      rows: [
        {
          id: 'CHE',
          data: {
            name: 'Chelsea',
            team_type_id: 'CLUB',
            nation_id: 'ENG',
            parent_team_id: '',
            club_code: 'CHE',
            logo_filename: 'Chelsea_FC_640x640.png',
            official_name: 'Chelsea FC',
          },
        },
        {
          id: 'VIL',
          data: {
            name: 'Villarreal',
            team_type_id: 'CLUB',
            nation_id: 'ESP',
            parent_team_id: '',
            club_code: 'VIL',
            logo_filename: 'Villarreal_CF_logo_514x640.png',
            official_name: 'Villarreal CF',
          },
        },
        {
          id: 'SEV',
          data: {
            name: 'Sevilla',
            team_type_id: 'CLUB',
            nation_id: 'ESP',
            parent_team_id: '',
            club_code: 'SEV',
            logo_filename: 'Sevilla_FC_logo_526x640.png',
            official_name: 'Sevilla FC',
          },
        },
        {
          id: 'RMA',
          data: {
            name: 'Real Madrid',
            team_type_id: 'CLUB',
            nation_id: 'ESP',
            parent_team_id: '',
            club_code: 'RMA',
            logo_filename: 'Real_Madrid_CF_478x640.png',
            official_name: 'Real Madrid CF',
          },
        },
        {
          id: 'MCI',
          data: {
            name: 'Manchester City',
            team_type_id: 'CLUB',
            nation_id: 'ENG',
            parent_team_id: '',
            club_code: 'MCI',
            logo_filename: 'Manchester_City_FC_badge_640x640.png',
            official_name: 'Manchester City FC',
          },
        },
        {
          id: 'PSG',
          data: {
            name: 'Paris Saint-Germain',
            short_name: 'Paris St-Ger',
            team_type_id: 'CLUB',
            nation_id: 'FRA',
            parent_team_id: '',
            club_code: 'PSG',
            logo_filename: 'Paris_Saint-Germain_F.C._640x640.png',
            official_name: 'Paris Saint-Germain',
          },
        },
        {
          id: 'BAY',
          data: {
            name: 'Bayern Munich',
            short_name: 'BayernMunich',
            team_type_id: 'CLUB',
            nation_id: 'GER',
            parent_team_id: '',
            club_code: 'BAY',
            logo_filename: 'FC_Bayern_Munchen_logo_(2017)_640x640.png',
            official_name: 'FC Bayern München',
          },
        },
        {
          id: 'LYO',
          data: {
            name: 'Lyon',
            team_type_id: 'CLUB',
            nation_id: 'FRA',
            parent_team_id: '',
            club_code: 'LYO',
            logo_filename: 'Olympique_Lyonnais_552x640.png',
            official_name: 'Olympique Lyonnais',
          },
        },
        {
          id: 'RBL',
          data: {
            name: 'RB Leipzig',
            team_type_id: 'CLUB',
            nation_id: 'GER',
            parent_team_id: '',
            club_code: 'RBL',
            logo_filename: 'RB_Leipzig_2014_logo_973x640.png',
            official_name: 'RB Leipzig',
          },
        },
        {
          id: 'LIV',
          data: {
            name: 'Liverpool',
            team_type_id: 'CLUB',
            nation_id: 'ENG',
            parent_team_id: '',
            club_code: 'LIV',
            logo_filename: 'Liverpool_FC_469x640.png',
            official_name: 'Liverpool FC',
          },
        },
        {
          id: 'TOT',
          data: {
            name: 'Tottenham Hotspur',
            short_name: 'Tottenham',
            team_type_id: 'CLUB',
            nation_id: 'ENG',
            parent_team_id: '',
            club_code: 'TOT',
            logo_filename: 'Tottenham_Hotspur_311x640.png',
            official_name: 'Tottenham Hotspur FC',
          },
        },
        {
          id: 'AJA',
          data: {
            name: 'Ajax Amsterdam',
            short_name: 'Ajax',
            team_type_id: 'CLUB',
            nation_id: 'NED',
            parent_team_id: '',
            club_code: 'AJA',
            logo_filename: 'Ajax_Amsterdam_636x640.png',
            official_name: 'AFC Ajax',
          },
        },
        {
          id: 'FCB',
          data: {
            name: 'Barcelona',
            team_type_id: 'CLUB',
            nation_id: 'ESP',
            parent_team_id: '',
            club_code: 'FCB',
            logo_filename: 'FC_Barcelona_(crest)_592x600.png',
            official_name: 'FC Barcelona',
          },
        },
        {
          id: 'MUN',
          data: {
            name: 'Manchester United',
            short_name: 'Man Utd',
            team_type_id: 'CLUB',
            nation_id: 'ENG',
            parent_team_id: '',
            club_code: 'MUN',
            logo_filename: 'Manchester_United_FC_crest_632x640.png',
            official_name: 'Manchester United FC',
          },
        },
        {
          id: 'ARS',
          data: {
            name: 'Arsenal',
            team_type_id: 'CLUB',
            nation_id: 'ENG',
            parent_team_id: '',
            club_code: 'ARS',
            logo_filename: 'Arsenal_FC_545x640.png',
            official_name: 'Arsenal FC',
          },
        },
        {
          id: 'ROM',
          data: {
            name: 'AS Roma',
            team_type_id: 'CLUB',
            nation_id: 'ITA',
            parent_team_id: '',
            club_code: 'ROM',
            logo_filename: 'AS_Roma_logo_(2017)_494x640.png',
            official_name: 'AS Roma',
          },
        },
        {
          id: 'INT',
          data: {
            name: 'Inter Milan',
            team_type_id: 'CLUB',
            nation_id: 'ITA',
            parent_team_id: '',
            club_code: 'INT',
            logo_filename: 'FC_Internazionale_Milano_2021_640x640.png',
            official_name: 'FC Internazionale Milano',
          },
        },
        {
          id: 'SHK',
          data: {
            name: 'Shakhtar Donetsk',
            short_name: 'Shakhtar',
            team_type_id: 'CLUB',
            nation_id: 'UKR',
            parent_team_id: '',
            club_code: 'SHK',
            logo_filename: 'FC_Shakhtar_Donetsk_358x562.png',
            official_name: 'FC Shakhtar Donetsk',
          },
        },
        {
          id: 'SGE',
          data: {
            name: 'Eintracht Frankfurt',
            short_name: 'Eintracht F',
            team_type_id: 'CLUB',
            nation_id: 'GER',
            parent_team_id: '',
            club_code: 'SGE',
            logo_filename: 'Eintracht_Frankfurt_Logo_640x640.png',
            official_name: 'Eintracht Frankfurt e.V.',
          },
        },
        {
          id: 'VAL',
          data: {
            name: 'Valencia',
            team_type_id: 'CLUB',
            nation_id: 'ESP',
            parent_team_id: '',
            club_code: 'VAL',
            logo_filename: 'Valenciacf_508x640.png',
            official_name: 'Valencia CF',
          },
        },
        {
          id: 'SLI',
          data: {
            name: 'Sporting Lisbon',
            short_name: 'Sporting Li.',
            team_type_id: 'CLUB',
            nation_id: 'POR',
            parent_team_id: '',
            club_code: 'SLI',
            logo_filename: 'Sporting_Clube_de_Portugal_(Logo)_477x640.png',
            official_name: 'Sporting Clube de Portugal',
          },
        },
      ],
    },
  ],
}
