export const AppData = {
  collection: 'team',
  batches: [
    {
      number: '5',
      rows: [
        {
          id: 'BRA',
          data: {
            name: 'Brazil',
            team_type_id: 'MNT',
            nation_id: 'BRA',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'GER',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'ARG',
          data: {
            name: 'Argentina',
            team_type_id: 'MNT',
            nation_id: 'ARG',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'POR',
          data: {
            name: 'Portugal',
            team_type_id: 'MNT',
            nation_id: 'POR',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'BEL',
          data: {
            name: 'Belgium',
            team_type_id: 'MNT',
            nation_id: 'BEL',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'ESP',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'POL',
          data: {
            name: 'Poland',
            team_type_id: 'MNT',
            nation_id: 'POL',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'EGY',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'MAR',
          data: {
            name: 'Morocco',
            team_type_id: 'MNT',
            nation_id: 'MAR',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'NGA',
          data: {
            name: 'Nigeria',
            team_type_id: 'MNT',
            nation_id: 'NGA',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'SEN',
          data: {
            name: 'Senegal',
            team_type_id: 'MNT',
            nation_id: 'SEN',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'TUN',
          data: {
            name: 'Tunisia',
            team_type_id: 'MNT',
            nation_id: 'TUN',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'AUS',
          data: {
            name: 'Australia',
            team_type_id: 'MNT',
            nation_id: 'AUS',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'IRN',
          data: {
            name: 'Iran',
            team_type_id: 'MNT',
            nation_id: 'IRN',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'JPN',
          data: {
            name: 'Japan',
            team_type_id: 'MNT',
            nation_id: 'JPN',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'KOR',
          data: {
            name: 'Korea Republic',
            team_type_id: 'MNT',
            nation_id: 'KOR',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'KSA',
          data: {
            name: 'Saudi Arabia',
            team_type_id: 'MNT',
            nation_id: 'KSA',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'CRO',
          data: {
            name: 'Croatia',
            team_type_id: 'MNT',
            nation_id: 'CRO',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'DEN',
          data: {
            name: 'Denmark',
            team_type_id: 'MNT',
            nation_id: 'DEN',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'ENG',
          data: {
            name: 'England',
            team_type_id: 'MNT',
            nation_id: 'ENG',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'FRA',
          data: {
            name: 'France',
            team_type_id: 'MNT',
            nation_id: 'FRA',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'ISL',
          data: {
            name: 'Iceland',
            team_type_id: 'MNT',
            nation_id: 'ISL',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'RUS',
          data: {
            name: 'Russia',
            team_type_id: 'MNT',
            nation_id: 'RUS',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'SRB',
          data: {
            name: 'Serbia',
            team_type_id: 'MNT',
            nation_id: 'SRB',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'SWE',
          data: {
            name: 'Sweden',
            team_type_id: 'MNT',
            nation_id: 'SWE',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'SUI',
          data: {
            name: 'Switzerland',
            team_type_id: 'MNT',
            nation_id: 'SUI',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'CRC',
          data: {
            name: 'Costa Rica',
            team_type_id: 'MNT',
            nation_id: 'CRC',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'MEX',
          data: {
            name: 'Mexico',
            team_type_id: 'MNT',
            nation_id: 'MEX',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'PAN',
          data: {
            name: 'Panama',
            team_type_id: 'MNT',
            nation_id: 'PAN',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'COL',
          data: {
            name: 'Colombia',
            team_type_id: 'MNT',
            nation_id: 'COL',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'PER',
          data: {
            name: 'Peru',
            team_type_id: 'MNT',
            nation_id: 'PER',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
        {
          id: 'URU',
          data: {
            name: 'Uruguay',
            team_type_id: 'MNT',
            nation_id: 'URU',
            parent_team_id: '',
            club_code: '',
            official_name: '',
          },
        },
      ],
    },
  ],
}
