export const AppData = {
  collection: 'team',
  batches: [
    {
      number: '1',
      rows: [
        {
          id: 'SIN',
          data: {
            name: 'Singapore',
            team_type_id: 'MNT',
            nation_id: 'SIN',
            parent_team_id: '',
            code: 'SIN',
          },
        },
      ],
    },
    {
      number: '2',
      rows: [
        {
          id: 'FRA',
          data: {
            name: 'France',
            team_type_id: 'MNT',
            nation_id: 'FRA',
            parent_team_id: '',
            code: 'FRA',
          },
        },
        {
          id: 'ITA',
          data: {
            name: 'Italy',
            team_type_id: 'MNT',
            nation_id: 'ITA',
            parent_team_id: '',
            code: 'ITA',
          },
        },
        {
          id: 'ARG',
          data: {
            name: 'Argentina',
            team_type_id: 'MNT',
            nation_id: 'ARG',
            parent_team_id: '',
            code: 'ARG',
          },
        },
        {
          id: 'POR',
          data: {
            name: 'Portugal',
            team_type_id: 'MNT',
            nation_id: 'POR',
            parent_team_id: '',
            code: 'POR',
          },
        },
        {
          id: 'USA',
          data: {
            name: 'United States',
            short_name: 'United States',
            team_type_id: 'MNT',
            nation_id: 'USA',
            parent_team_id: '',
            code: 'USA',
          },
        },
        {
          id: 'ALG',
          data: {
            name: 'Algeria',
            team_type_id: 'MNT',
            nation_id: 'ALG',
            parent_team_id: '',
            code: 'ALG',
          },
        },
        {
          id: 'QAT',
          data: {
            name: 'Qatar',
            team_type_id: 'MNT',
            nation_id: 'QAT',
            parent_team_id: '',
            code: 'QAT',
          },
        },
        {
          id: 'NZL',
          data: {
            name: 'New Zealand',
            team_type_id: 'MNT',
            nation_id: 'NZL',
            parent_team_id: '',
            code: 'NZL',
          },
        },
        {
          id: 'GER',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER',
            parent_team_id: '',
            successor: true,
            code: 'GER',
          },
        },
        {
          id: 'CRO',
          data: {
            name: 'Croatia',
            team_type_id: 'MNT',
            nation_id: 'CRO',
            parent_team_id: '',
            code: 'CRO',
          },
        },
        {
          id: 'BEL',
          data: {
            name: 'Belgium',
            team_type_id: 'MNT',
            nation_id: 'BEL',
            parent_team_id: '',
            code: 'BEL',
          },
        },
        {
          id: 'ENG',
          data: {
            name: 'England',
            team_type_id: 'MNT',
            nation_id: 'ENG',
            parent_team_id: '',
            code: 'ENG',
          },
        },
        {
          id: 'NED',
          data: {
            name: 'Netherlands',
            team_type_id: 'MNT',
            nation_id: 'NED',
            parent_team_id: '',
            code: 'NED',
          },
        },
        {
          id: 'TUR',
          data: {
            name: 'Turkey',
            team_type_id: 'MNT',
            nation_id: 'TUR',
            parent_team_id: '',
            code: 'TUR',
          },
        },
        {
          id: 'KOR',
          data: {
            name: 'Korea Republic',
            short_name: 'Korea Rep.',
            team_type_id: 'MNT',
            nation_id: 'KOR',
            parent_team_id: '',
            code: 'KOR',
          },
        },
        {
          id: 'SWE',
          data: {
            name: 'Sweden',
            team_type_id: 'MNT',
            nation_id: 'SWE',
            parent_team_id: '',
            code: 'SWE',
          },
        },
        {
          id: 'BUL',
          data: {
            name: 'Bulgaria',
            team_type_id: 'MNT',
            nation_id: 'BUL',
            parent_team_id: '',
            code: 'BUL',
          },
        },
        {
          id: 'GER-1949-1990',
          data: {
            name: 'Germany FR',
            short_name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER-1949-1990',
            parent_team_id: 'GER',
            code: 'GER',
          },
        },
        {
          id: 'POL',
          data: {
            name: 'Poland',
            team_type_id: 'MNT',
            nation_id: 'POL',
            parent_team_id: '',
            code: 'POL',
          },
        },
        {
          id: 'URS',
          data: {
            name: 'Soviet Union',
            short_name: 'Soviet Union',
            team_type_id: 'MNT',
            nation_id: 'URS',
            parent_team_id: 'RUS',
            code: 'URS',
          },
        },
        {
          id: 'TCH',
          data: {
            name: 'Czechoslovakia',
            team_type_id: 'MNT',
            nation_id: 'TCH',
            parent_team_id: 'CZE',
            code: 'TCH',
          },
        },
        {
          id: 'CHI',
          data: {
            name: 'Chile',
            team_type_id: 'MNT',
            nation_id: 'CHI',
            parent_team_id: '',
            code: 'CHI',
          },
        },
        {
          id: 'YUG-1945-1963',
          data: {
            name: 'Yugoslavia',
            short_name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1945-1963',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'HUN-1949-1956',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN-1949-1956',
            parent_team_id: 'HUN',
            code: 'HUN',
          },
        },
        {
          id: 'AUT',
          data: {
            name: 'Austria',
            team_type_id: 'MNT',
            nation_id: 'AUT',
            parent_team_id: '',
            code: 'AUT',
          },
        },
        {
          id: 'ESP-1945-1977',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP-1945-1977',
            parent_team_id: 'ESP',
            code: 'ESP',
          },
        },
        {
          id: 'ITA-1861-1946',
          data: {
            name: 'Italy',
            team_type_id: 'MNT',
            nation_id: 'ITA-1861-1946',
            parent_team_id: 'ITA',
            code: 'ITA',
          },
        },
        {
          id: 'HUN-1919-1946',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN-1919-1946',
            parent_team_id: 'HUN',
            code: 'HUN',
          },
        },
        {
          id: 'GER-1933-1935',
          data: {
            name: 'Germany',
            team_type_id: 'MNT',
            nation_id: 'GER-1933-1935',
            parent_team_id: 'GER',
            code: 'GER',
          },
        },
        {
          id: 'YUG-1929-1943',
          data: {
            name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1929-1943',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'BRA',
          data: {
            name: 'Brazil',
            team_type_id: 'MNT',
            nation_id: 'BRA',
            parent_team_id: '',
            code: 'BRA',
          },
        },
        {
          id: 'ESP',
          data: {
            name: 'Spain',
            team_type_id: 'MNT',
            nation_id: 'ESP',
            parent_team_id: '',
            code: 'ESP',
          },
        },
        {
          id: 'URU',
          data: {
            name: 'Uruguay',
            team_type_id: 'MNT',
            nation_id: 'URU',
            parent_team_id: '',
            code: 'URU',
          },
        },
        {
          id: 'MEX',
          data: {
            name: 'Mexico',
            team_type_id: 'MNT',
            nation_id: 'MEX',
            parent_team_id: '',
            code: 'MEX',
          },
        },
        {
          id: 'EGY',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY',
            parent_team_id: '',
            successor: true,
            code: 'EGY',
          },
        },
        {
          id: 'JPN',
          data: {
            name: 'Japan',
            team_type_id: 'MNT',
            nation_id: 'JPN',
            parent_team_id: '',
            code: 'JPN',
          },
        },
        {
          id: 'PAR',
          data: {
            name: 'Paraguay',
            team_type_id: 'MNT',
            nation_id: 'PAR',
            parent_team_id: '',
            code: 'PAR',
          },
        },
        {
          id: 'VEN',
          data: {
            name: 'Venezuela',
            team_type_id: 'MNT',
            nation_id: 'VEN',
            parent_team_id: '',
            code: 'VEN',
          },
        },
        {
          id: 'BOL',
          data: {
            name: 'Bolivia',
            team_type_id: 'MNT',
            nation_id: 'BOL',
            parent_team_id: '',
            code: 'BOL',
          },
        },
        {
          id: 'ECU',
          data: {
            name: 'Ecuador',
            team_type_id: 'MNT',
            nation_id: 'ECU',
            parent_team_id: '',
            code: 'ECU',
          },
        },
        {
          id: 'RSA',
          data: {
            name: 'South Africa',
            short_name: 'SouthAfrica',
            team_type_id: 'MNT',
            nation_id: 'RSA',
            parent_team_id: '',
            code: 'RSA',
          },
        },
        {
          id: 'CMR',
          data: {
            name: 'Cameroon',
            team_type_id: 'MNT',
            nation_id: 'CMR',
            parent_team_id: '',
            code: 'CMR',
          },
        },
        {
          id: 'AUS',
          data: {
            name: 'Australia',
            team_type_id: 'MNT',
            nation_id: 'AUS',
            parent_team_id: '',
            code: 'AUS',
          },
        },
        {
          id: 'KSA',
          data: {
            name: 'Saudi Arabia',
            short_name: 'SaudiArabia',
            team_type_id: 'MNT',
            nation_id: 'KSA',
            parent_team_id: '',
            code: 'KSA',
          },
        },
        {
          id: 'CZE',
          data: {
            name: 'Czech Republic',
            short_name: 'Czech Rep.',
            team_type_id: 'MNT',
            nation_id: 'CZE',
            parent_team_id: '',
            successor: true,
            code: 'CZE',
          },
        },
        {
          id: 'DEN',
          data: {
            name: 'Denmark',
            team_type_id: 'MNT',
            nation_id: 'DEN',
            parent_team_id: '',
            code: 'DEN',
          },
        },
        {
          id: 'NGA',
          data: {
            name: 'Nigeria',
            team_type_id: 'MNT',
            nation_id: 'NGA',
            parent_team_id: '',
            code: 'NGA',
          },
        },
        {
          id: 'CIV',
          data: {
            name: 'Ivory Coast',
            team_type_id: 'MNT',
            nation_id: 'CIV',
            parent_team_id: '',
            code: 'CIV',
          },
        },
        {
          id: 'IRN',
          data: {
            name: 'IR Iran',
            team_type_id: 'MNT',
            nation_id: 'IRN',
            parent_team_id: '',
            code: 'IRN',
          },
        },
        {
          id: 'UAE',
          data: {
            name: 'United Arab Emirates',
            short_name: 'UAE',
            team_type_id: 'MNT',
            nation_id: 'UAE',
            parent_team_id: '',
            code: 'UAE',
          },
        },
        {
          id: 'IRQ',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ',
            parent_team_id: '',
            code: 'IRQ',
          },
        },
        {
          id: 'UZB',
          data: {
            name: 'Uzbekistan',
            team_type_id: 'MNT',
            nation_id: 'UZB',
            parent_team_id: '',
            code: 'UZB',
          },
        },
        {
          id: 'IRQ-2004-2008',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ-2004-2008',
            parent_team_id: 'IRQ',
            code: 'IRQ',
          },
        },
        {
          id: 'CHN',
          data: {
            name: 'China PR',
            team_type_id: 'MNT',
            nation_id: 'CHN',
            parent_team_id: '',
            code: 'CHN',
          },
        },
        {
          id: 'BHR',
          data: {
            name: 'Bahrain',
            team_type_id: 'MNT',
            nation_id: 'BHR',
            parent_team_id: '',
            code: 'BHR',
          },
        },
        {
          id: 'KUW',
          data: {
            name: 'Kuwait',
            team_type_id: 'MNT',
            nation_id: 'KUW',
            parent_team_id: '',
            code: 'KUW',
          },
        },
        {
          id: 'PRK',
          data: {
            name: 'Korea DPR',
            team_type_id: 'MNT',
            nation_id: 'PRK',
            parent_team_id: '',
            code: 'PRK',
          },
        },
        {
          id: 'IRN-1964-1980',
          data: {
            name: 'Iran',
            team_type_id: 'MNT',
            nation_id: 'IRN-1964-1980',
            parent_team_id: 'IRN',
            code: 'IRN',
          },
        },
        {
          id: 'IRQ-1963-1991',
          data: {
            name: 'Iraq',
            team_type_id: 'MNT',
            nation_id: 'IRQ-1963-1991',
            parent_team_id: 'IRQ',
            code: 'IRQ',
          },
        },
        {
          id: 'THA',
          data: {
            name: 'Thailand',
            team_type_id: 'MNT',
            nation_id: 'THA',
            parent_team_id: '',
            code: 'THA',
          },
        },
        {
          id: 'CAM-1970-1975',
          data: {
            name: 'Khmer Republic',
            short_name: 'Khmer Rep.',
            team_type_id: 'MNT',
            nation_id: 'CAM-1970-1975',
            parent_team_id: 'CAM',
            code: 'CAM',
          },
        },
        {
          id: 'BUR-1948-1974',
          data: {
            name: 'Burma',
            team_type_id: 'MNT',
            nation_id: 'BUR-1948-1974',
            parent_team_id: 'MYA',
            code: 'BUR',
          },
        },
        {
          id: 'ISR',
          data: {
            name: 'Israel',
            team_type_id: 'MNT',
            nation_id: 'ISR',
            parent_team_id: '',
            code: 'ISR',
          },
        },
        {
          id: 'TPE-1960-1979',
          data: {
            name: 'Republic of China',
            short_name: 'Rep. China',
            team_type_id: 'MNT',
            nation_id: 'TPE-1960-1979',
            parent_team_id: 'TPE',
            code: 'TPE',
          },
        },
        {
          id: 'IND',
          data: {
            name: 'India',
            team_type_id: 'MNT',
            nation_id: 'IND',
            parent_team_id: '',
            code: 'IND',
          },
        },
        {
          id: 'HKG-1959-1997',
          data: {
            name: 'Hong Kong',
            team_type_id: 'MNT',
            nation_id: 'HKG-1959-1997',
            parent_team_id: 'HKG',
            code: 'HKG',
          },
        },
        {
          id: 'VSO',
          data: {
            name: 'South Vietnam',
            short_name: 'S. Vietnam',
            team_type_id: 'MNT',
            nation_id: 'VSO',
            parent_team_id: 'VIE',
            code: 'VSO',
          },
        },
        {
          id: 'HKG-1955-1959',
          data: {
            name: 'Hong Kong',
            team_type_id: 'MNT',
            nation_id: 'HKG-1955-1959',
            parent_team_id: 'HKG',
            code: 'HKG',
          },
        },
        {
          id: 'SEN',
          data: {
            name: 'Senegal',
            team_type_id: 'MNT',
            nation_id: 'SEN',
            parent_team_id: '',
            code: 'SEN',
          },
        },
        {
          id: 'TUN',
          data: {
            name: 'Tunisia',
            team_type_id: 'MNT',
            nation_id: 'TUN',
            parent_team_id: '',
            code: 'TUN',
          },
        },
        {
          id: 'BFA',
          data: {
            name: 'Burkina Faso',
            short_name: 'BurkinaFaso',
            team_type_id: 'MNT',
            nation_id: 'BFA',
            parent_team_id: '',
            successor: true,
            code: 'BFA',
          },
        },
        {
          id: 'GHA',
          data: {
            name: 'Ghana',
            team_type_id: 'MNT',
            nation_id: 'GHA',
            parent_team_id: '',
            code: 'GHA',
          },
        },
        {
          id: 'COD',
          data: {
            name: 'Congo DR',
            team_type_id: 'MNT',
            nation_id: 'COD',
            parent_team_id: '',
            successor: true,
            code: 'COD',
          },
        },
        {
          id: 'EQG',
          data: {
            name: 'Equatorial Guinea',
            short_name: 'Equ Guinea',
            team_type_id: 'MNT',
            nation_id: 'EQG',
            parent_team_id: '',
            code: 'EQG',
          },
        },
        {
          id: 'MLI',
          data: {
            name: 'Mali',
            team_type_id: 'MNT',
            nation_id: 'MLI',
            parent_team_id: '',
            code: 'MLI',
          },
        },
        {
          id: 'ZAM',
          data: {
            name: 'Zambia',
            team_type_id: 'MNT',
            nation_id: 'ZAM',
            parent_team_id: '',
            code: 'ZAM',
          },
        },
        {
          id: 'MAR',
          data: {
            name: 'Morocco',
            team_type_id: 'MNT',
            nation_id: 'MAR',
            parent_team_id: '',
            code: 'MAR',
          },
        },
        {
          id: 'COD-1997-2003',
          data: {
            name: 'Congo DR',
            team_type_id: 'MNT',
            nation_id: 'COD-1997-2003',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'LBY-1977-2011',
          data: {
            name: 'Libya',
            team_type_id: 'MNT',
            nation_id: 'LBY-1977-2011',
            parent_team_id: 'LBY',
            code: 'LBY',
          },
        },
        {
          id: 'UGA',
          data: {
            name: 'Uganda',
            team_type_id: 'MNT',
            nation_id: 'UGA',
            parent_team_id: '',
            code: 'UGA',
          },
        },
        {
          id: 'GUI',
          data: {
            name: 'Guinea',
            team_type_id: 'MNT',
            nation_id: 'GUI',
            code: 'GUI',
          },
        },
        {
          id: 'ZAI',
          data: {
            name: 'Zaire',
            team_type_id: 'MNT',
            nation_id: 'COD-1971-1997',
            parent_team_id: 'COD',
            code: 'ZAI',
          },
        },
        {
          id: 'CGO-1970-1991',
          data: {
            name: 'Congo',
            team_type_id: 'MNT',
            nation_id: 'CGO-1970-1991',
            parent_team_id: 'CGO',
            code: 'CGO',
          },
        },
        {
          id: 'CMR-1961-1975',
          data: {
            name: 'Cameroon',
            team_type_id: 'MNT',
            nation_id: 'CMR-1961-1975',
            parent_team_id: 'CMR',
            code: 'CMR',
          },
        },
        {
          id: 'SDN-1956-1970',
          data: {
            name: 'Sudan',
            team_type_id: 'MNT',
            nation_id: 'SDN-1956-1970',
            parent_team_id: 'SDN',
            code: 'SDN',
          },
        },
        {
          id: 'UAR',
          data: {
            name: 'United Arab Republic',
            short_name: 'United Arab Republic',
            team_type_id: 'MNT',
            nation_id: 'UAR',
            parent_team_id: 'EGY',
            code: 'UAR',
          },
        },
        {
          id: 'COD-1966-1971',
          data: {
            name: 'Congo-Kinshasa',
            short_name: 'CongoKinsh',
            team_type_id: 'MNT',
            nation_id: 'COD-1966-1971',
            parent_team_id: 'COD',
            code: 'COD',
          },
        },
        {
          id: 'ETH-1941-1974',
          data: {
            name: 'Ethiopia',
            team_type_id: 'MNT',
            nation_id: 'ETH-1941-1974',
            parent_team_id: 'ETH',
            code: 'ETH',
          },
        },
        {
          id: 'GHA-1964-1966',
          data: {
            name: 'Ghana',
            team_type_id: 'MNT',
            nation_id: 'GHA-1964-1966',
            parent_team_id: 'GHA',
            code: 'GHA',
          },
        },
        {
          id: 'UGA-1914-1962',
          data: {
            name: 'Uganda',
            team_type_id: 'MNT',
            nation_id: 'UGA-1914-1962',
            parent_team_id: 'UGA',
            code: 'UGA',
          },
        },
        {
          id: 'EGY-1953-1958',
          data: {
            name: 'Egypt',
            team_type_id: 'MNT',
            nation_id: 'EGY-1953-1958',
            parent_team_id: 'EGY',
            code: 'EGY',
          },
        },
        {
          id: 'PNG',
          data: {
            name: 'Papua New Guinea',
            short_name: 'PapuaNGuinea',
            team_type_id: 'MNT',
            nation_id: 'PNG',
            parent_team_id: '',
            code: 'PNG',
          },
        },
        {
          id: 'NCL',
          data: {
            name: 'New Caledonia',
            short_name: 'NewCaledonia',
            team_type_id: 'MNT',
            nation_id: 'NCL',
            parent_team_id: '',
            code: 'NCL',
          },
        },
        {
          id: 'SOL',
          data: {
            name: 'Solomon Islands',
            short_name: 'SolomonIslands',
            team_type_id: 'MNT',
            nation_id: 'SOL',
            parent_team_id: '',
            code: 'SOL',
          },
        },
        {
          id: 'TAH',
          data: {
            name: 'Tahiti',
            team_type_id: 'MNT',
            nation_id: 'TAH',
            parent_team_id: '',
            code: 'TAH',
          },
        },
        {
          id: 'NCL-1973-2008',
          data: {
            name: 'New Caledonia',
            short_name: 'NewCaledonia',
            team_type_id: 'MNT',
            nation_id: 'NCL-1973-2008',
            parent_team_id: 'NCL',
            code: 'NCL',
          },
        },
        {
          id: 'FIJ',
          data: {
            name: 'Fiji',
            team_type_id: 'MNT',
            nation_id: 'FIJ',
            parent_team_id: '',
            code: 'FIJ',
          },
        },
        {
          id: 'VAN',
          data: {
            name: 'Vanuatu',
            team_type_id: 'MNT',
            nation_id: 'VAN',
            parent_team_id: '',
            code: 'VAN',
          },
        },
        {
          id: 'TAH-1794-1984',
          data: {
            name: 'Tahiti',
            team_type_id: 'MNT',
            nation_id: 'TAH-1794-1984',
            parent_team_id: 'TAH',
            code: 'TAH',
          },
        },
        {
          id: 'VAN-1953-1980',
          data: {
            name: 'New Hebrides',
            team_type_id: 'MNT',
            nation_id: 'VAN-1953-1980',
            parent_team_id: 'VAN',
            code: 'VAN',
          },
        },
        {
          id: 'WAL',
          data: {
            name: 'Wales',
            team_type_id: 'MNT',
            nation_id: 'WAL',
            parent_team_id: '',
            code: 'WAL',
          },
        },
        {
          id: 'RUS',
          data: {
            name: 'Russia',
            team_type_id: 'MNT',
            nation_id: 'RUS',
            parent_team_id: '',
            successor: true,
            code: 'RUS',
          },
        },
        {
          id: 'GRE',
          data: {
            name: 'Greece',
            team_type_id: 'MNT',
            nation_id: 'GRE',
            parent_team_id: '',
            code: 'GRE',
          },
        },
        {
          id: 'YUG-1963-1992',
          data: {
            name: 'Yugoslavia',
            short_name: 'Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1963-1992',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'HUN',
          data: {
            name: 'Hungary',
            team_type_id: 'MNT',
            nation_id: 'HUN',
            parent_team_id: '',
            code: 'HUN',
          },
        },
        {
          id: 'SUI',
          data: {
            name: 'Switzerland',
            team_type_id: 'MNT',
            nation_id: 'SUI',
            parent_team_id: '',
            code: 'SUI',
          },
        },
        {
          id: 'CAN',
          data: {
            name: 'Canada',
            team_type_id: 'MNT',
            nation_id: 'CAN',
            parent_team_id: '',
            code: 'CAN',
          },
        },
        {
          id: 'HAI',
          data: {
            name: 'Haiti',
            team_type_id: 'MNT',
            nation_id: 'HAI',
            parent_team_id: '',
            code: 'HAI',
          },
        },
        {
          id: 'JAM',
          data: {
            name: 'Jamaica',
            team_type_id: 'MNT',
            nation_id: 'JAM',
            parent_team_id: '',
            code: 'JAM',
          },
        },
        {
          id: 'CRC',
          data: {
            name: 'Costa Rica',
            team_type_id: 'MNT',
            nation_id: 'CRC',
            parent_team_id: '',
            code: 'CRC',
          },
        },
        {
          id: 'PAN',
          data: {
            name: 'Panama',
            team_type_id: 'MNT',
            nation_id: 'PAN',
            parent_team_id: '',
            code: 'PAN',
          },
        },
        {
          id: 'HON',
          data: {
            name: 'Honduras',
            team_type_id: 'MNT',
            nation_id: 'HON',
            parent_team_id: '',
            code: 'HON',
          },
        },
        {
          id: 'GLP',
          data: {
            name: 'Guadeloupe',
            team_type_id: 'MNT',
            nation_id: 'GLP',
            parent_team_id: '',
            code: 'GLP',
          },
        },
        {
          id: 'COL',
          data: {
            name: 'Colombia',
            team_type_id: 'MNT',
            nation_id: 'COL',
            parent_team_id: '',
            code: 'COL',
          },
        },
        {
          id: 'PER',
          data: {
            name: 'Peru',
            team_type_id: 'MNT',
            nation_id: 'PER',
            parent_team_id: '',
            code: 'PER',
          },
        },
        {
          id: 'TRI',
          data: {
            name: 'Trinidad and Tobago',
            short_name: 'Trinidad & Tobago',
            team_type_id: 'MNT',
            nation_id: 'TRI',
            parent_team_id: '',
            code: 'TRI',
          },
        },
        {
          id: 'GUA',
          data: {
            name: 'Guatemala',
            team_type_id: 'MNT',
            nation_id: 'GUA',
            parent_team_id: '',
            code: 'GUA',
          },
        },
        {
          id: 'SLV',
          data: {
            name: 'El Salvador',
            team_type_id: 'MNT',
            nation_id: 'SLV',
            parent_team_id: '',
            code: 'SLV',
          },
        },
        {
          id: 'HAI-1964-1986',
          data: {
            name: 'Haiti',
            team_type_id: 'MNT',
            nation_id: 'HAI-1964-1986',
            parent_team_id: 'HAI',
            code: 'HAI',
          },
        },
        {
          id: 'CUB',
          data: {
            name: 'Cuba',
            team_type_id: 'MNT',
            nation_id: 'CUB',
            parent_team_id: '',
            code: 'CUB',
          },
        },
        {
          id: 'ANT-1959-1986',
          data: {
            name: 'Netherlands Antilles',
            team_type_id: 'MNT',
            nation_id: 'ANT-1959-1986',
            parent_team_id: 'CUW',
            code: 'ANT',
          },
        },
        {
          id: 'AZE',
          data: {
            name: 'Azerbaijan',
            team_type_id: 'MNT',
            nation_id: 'AZE',
            parent_team_id: '',
            code: 'AZE',
          },
        },
        {
          id: 'ROU',
          data: {
            name: 'Romania',
            team_type_id: 'MNT',
            nation_id: 'ROU',
            parent_team_id: '',
            code: 'ROU',
          },
        },
        {
          id: 'SCO',
          data: {
            name: 'Scotland',
            team_type_id: 'MNT',
            nation_id: 'SCO',
            parent_team_id: '',
            code: 'SCO',
          },
        },
        {
          id: 'NOR',
          data: {
            name: 'Norway',
            team_type_id: 'MNT',
            nation_id: 'NOR',
            parent_team_id: '',
            code: 'NOR',
          },
        },
        {
          id: 'UKR',
          data: {
            name: 'Ukraine',
            team_type_id: 'MNT',
            nation_id: 'UKR',
            parent_team_id: '',
            code: 'UKR',
          },
        },
        {
          id: 'YUG-1992-2003',
          data: {
            name: 'FR Yugoslavia',
            team_type_id: 'MNT',
            nation_id: 'YUG-1992-2003',
            parent_team_id: 'SRB',
            code: 'YUG',
          },
        },
        {
          id: 'VEN-1954-2006',
          data: {
            name: 'Venezuela',
            team_type_id: 'MNT',
            nation_id: 'VEN-1954-2006',
            parent_team_id: 'VEN',
            code: 'VEN',
          },
        },
        {
          id: 'SRB',
          data: {
            name: 'Serbia',
            team_type_id: 'MNT',
            nation_id: 'SRB',
            parent_team_id: '',
            successor: true,
            code: 'SRB',
          },
        },
        {
          id: 'MTQ-2019',
          data: {
            name: 'Martinique',
            team_type_id: 'MNT',
            nation_id: 'MTQ-2019',
            parent_team_id: 'MTQ',
            code: 'MTQ',
          },
        },
        {
          id: 'GAB',
          data: {
            name: 'Gabon',
            team_type_id: 'MNT',
            nation_id: 'GAB',
            parent_team_id: '',
            code: 'GAB',
          },
        },
        {
          id: 'CGO',
          data: {
            name: 'Congo',
            team_type_id: 'MNT',
            nation_id: 'CGO',
            parent_team_id: '',
            code: 'CGO',
          },
        },
        {
          id: 'ANG',
          data: {
            name: 'Angola',
            team_type_id: 'MNT',
            nation_id: 'ANG',
            parent_team_id: '',
            code: 'ANG',
          },
        },
        {
          id: 'ETH',
          data: {
            name: 'Ethiopia',
            team_type_id: 'MNT',
            nation_id: 'ETH',
            parent_team_id: '',
            code: 'ETH',
          },
        },
        {
          id: 'ETH-1975-1987',
          data: {
            name: 'Ethiopia',
            team_type_id: 'MNT',
            nation_id: 'ETH-1975-1987',
            parent_team_id: 'ETH',
            code: 'ETH',
          },
        },
        {
          id: 'IDN',
          data: {
            name: 'Indonesia',
            team_type_id: 'MNT',
            nation_id: 'IDN',
            parent_team_id: '',
            successor: true,
            code: 'IDN',
          },
        },
        {
          id: 'MAS',
          data: {
            name: 'Malaysia',
            team_type_id: 'MNT',
            nation_id: 'MAS',
            parent_team_id: '',
            code: 'MAS',
          },
        },
        {
          id: 'VIE',
          data: {
            name: 'Vietnam',
            team_type_id: 'MNT',
            nation_id: 'VIE',
            parent_team_id: '',
            code: 'VIE',
          },
        },
      ],
    },
  ],
}
